### PR TITLE
dependencies.tsv: fix charm.v5 commit

### PR DESCRIPTION
**Pull request by axw**
Was using a commit not in the charm.v5 branch
previously, so when I updated it last some
fixes were lost. I cherry-picked the fixes
into v5.

Fixes https://bugs.launchpad.net/juju-core/+bug/1450919

(Review request: http://reviews.vapour.ws/r/1575/)

### CODE REVIEW

**Comment by axw** [comment]
$$__fixes-1450919__$$

**Comment by bz2** [comment]
Build failed: github outage

**Comment by bz2** [comment]
$$merge$$

**Comment by bz2** [comment]
# github.com/juju/juju/worker/uniter/hook
worker/uniter/hook/hook.go:54: undefined: hooks.StorageDetached

The companion renaming hasn't been forward ported to master yet.

**Comment by axw** [comment]
I'll leave this for now. Ian says we'll do a bulk merge from 1.24 to master some time.

**Comment by wallyworld** [comment]
Merged into master with branch wallyworld/merge-1.24

**Pull request closed without merging**
