### PR TITLE
DDL SQL files

### PR DESCRIPTION
**Pull request by SimonRichardson**
In order to get better IDE support for sql files, we can embed the sql files into the binary directly. This provides the best of both worlds. We can have independent sql files, that we can validate, format, and test. All whilst we read from embedded strings. There will be no disk reads when using this.

The files are read in order, so 0000-9999. This is per model, and controllers will have their independent range.

Linting is out of scope of this initial PR. We can employ a github action to perform the correct linting over the ddl files.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing

## QA steps

The existing tests should pass.

Regression testing:

```
$ juju bootstrap lxd test
$ juju add-model default
$ juju deploy ubuntu
```

## Links

**Jira card:** JUJU-

### CODE REVIEW

**Review by manadart — COMMENTED** [review]
I think I'm OK with this, but I'd like @wallyworld et al to chime in.

To-date, I've found it very fast to open the schema files with the fuzzy finder - "domain schema model|controller", but I'd probably get used to searching for the right sub-domains quickly enough.

**Comment by wallyworld** [comment]
Nice idea, +1 from me

**Review by nvinuesa — APPROVED** [review]
LGTM, this is going to be really helpful

**Pull request merged**
