### PR TITLE
Revert cmr bundle changes from 2.6

### PR DESCRIPTION
**Pull request by achilleasa**
This PR removed all cmr bundle changes from 2.6 so we can merge this to develop and then re-land our changes there.

### CODE REVIEW

**Comment by achilleasa** [comment]
!!build!!

(DNS lookup errors)

**Comment by SimonRichardson** [comment]
!!build!!

> statusUnitTestSuite.TestMigrationInProgress

**Comment by achilleasa** [comment]
!!build!!

(toolsSuite.TestToolsUploadedSecurely)

**Comment by SimonRichardson** [comment]
$$merge$$

**Pull request merged**
