### PR TITLE
Logtailer test fix

### PR DESCRIPTION
**Pull request by wallyworld**
The ci race tests sometimes fail running the log tailer tests. It's very intermittent and hard to repro locally - maybe 1 in 30 attempts.
In the 2 tests where the log tailer is started and then additonal logs are written, introduce a small sleep to allow the log tailer go routine to run before writing the additional logs.

## QA steps

go test --race

## Links

**Jira card:** [JUJU-6004](https://warthogs.atlassian.net/browse/JUJU-6004)

[JUJU-6004]: https://warthogs.atlassian.net/browse/JUJU-6004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by hpidcock** [comment]
What does the addition of the `Poll: true` do?

**Comment by wallyworld** [comment]
> What does the addition of the `Poll: true` do?

That shouldn't be there. Fixed.

**Review by hpidcock — APPROVED** [review]
Thanks, I hate the sleeps, but that's ok.

**Comment by wallyworld** [comment]
> Thanks, I hate the sleeps, but that's ok.

Me too. But with the upstream it is what it is.

**Pull request merged**
