### PR TITLE
[JUJU-4322] Remove JujuConnSuite from remaining uniter worker tests

### PR DESCRIPTION
**Pull request by wallyworld**
The last uses of JujuConnSuite in worker/uniter packages are removed.

In some cases, the tests were checking server side behaviour - these have been deleted, eg adding storage with bad params where validation is done server side.

## QA steps

go test ./...

### CODE REVIEW

**Comment by hpidcock** [comment]
Probably unrelated failure
```
----------------------------------------------------------------------
FAIL: <autogenerated>:1: WatcherSuiteSidecar.TestWorkloadSignal

[LOG] 0:00.000 DEBUG test starting secrets rotation watcher
[LOG] 0:00.000 DEBUG test starting secret revisions expiry watcher
[LOG] 0:00.000 DEBUG test starting obsolete secret revisions watcher (leader=true)
[LOG] 0:00.001 DEBUG test got address change for mysql/0: ok=true, hashes=[addresseshash]
[LOG] 0:00.001 DEBUG test got action change for mysql/0: [] ok=true
[LOG] 0:00.001 DEBUG test got application change for mysql/0
[LOG] 0:00.001 DEBUG test got secrets change for mysql/0: []
[LOG] 0:00.001 DEBUG test got latest secret info: map[string]secrets.SecretRevisionInfo{}
[LOG] 0:00.001 DEBUG test deleted secrets: []
[LOG] 0:00.001 DEBUG test obsolete secrets: map[]
[LOG] 0:00.001 DEBUG test got relations change for mysql/0: ok=true: []
[LOG] 0:00.001 DEBUG test got update status interval change for mysql/0: ok=true
[LOG] 0:00.001 DEBUG test got storage change for mysql/0: [] ok=true
[LOG] 0:00.001 DEBUG test got config change for mysql/0: ok=true, hashes=[confighash]
[LOG] 0:00.001 DEBUG test got trust config change for mysql/0: ok=true, hashes=[trusthash]
[LOG] 0:00.001 DEBUG test got leader settings change for mysql/0: ok=true
[LOG] 0:00.001 DEBUG test got unit change for mysql/0
[LOG] 0:00.001 DEBUG test workloadEvent enqueued for mysql/0: 0
[LOG] 0:00.002 DEBUG test workloadEvent enqueued for mysql/0: 0
watcher_test.go:1208:
    c.Assert(snap.WorkloadEvents, gc.HasLen, 0)
... obtained []string = []string{"0"}
... n int = 0

OOPS: 113 passed, 1 FAILED
--- FAIL: TestPackage (5.97s)
FAIL
```

**Review by hpidcock — APPROVED** [review]
Nice 🍸

**Comment by wallyworld** [comment]
> TestWorkloadSignal

Yeah, this was existing code which was untouched in the PR. Something to fix in a follow up as the cause does to seem to immediately jump out

**Pull request merged**
