### PR TITLE
More multiwatcher tags

### PR DESCRIPTION
**Pull request by howbazaar**
Hopefully the last of it. Updated the serialization tags on the some instance types. Added an address type for the multiwatcher. Stopped the apiserver importing types from the api client, and stop passing structs from the charm package over the wire.

(Review request: http://reviews.vapour.ws/r/5185/)

### CODE REVIEW

**Comment by howbazaar** [comment]
$$__JFDI__$$ multiwatcher and tags for serializing charm data.

**Comment by howbazaar** [comment]
$$oops$$

**Comment by howbazaar** [comment]
$$and-again$$

**Comment by howbazaar** [comment]
$$missed$$

**Comment by frankban** [comment]
$$and-again$$

**Pull request merged**
