### PR TITLE
2.7 Update Gorilla WebSocket Dependency

### PR DESCRIPTION
**Pull request by manadart**
## Description of change

This is a simple dependency update as advised by on the [project releases](https://github.com/gorilla/websocket/releases) page. 

## QA steps

- Bootstrap and deploy some units.
- Check that things look sane.

## Documentation changes

None.

## Bug reference

N/A

### CODE REVIEW

**Comment by manadart** [comment]
[2.7 - Update Gorilla WebSocket Dependency](https://trello.com/c/vZKRUdS2/2637-27-update-gorilla-websocket-dependency)

**Comment by hpidcock** [comment]
$$merge$$

**Comment by howbazaar** [comment]
$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
I updated the s3 deps for this to merge.

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
@manadart looks like might have broken unit tests

**Comment by manadart** [comment]
$$merge$$

**Comment by howbazaar** [comment]
trying again $$merge$$

**Comment by howbazaar** [comment]
$$merge$$

**Comment by howbazaar** [comment]
$$merge$$

**Comment by hpidcock** [comment]
!!build!!

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
!!build!!

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
!!build!!

**Comment by hpidcock** [comment]
!!build!!

**Comment by howbazaar** [comment]
$$merge$$

**Pull request merged**
