### PR TITLE
Send errors related to metrics gathering to STDERR instead of STDOUT

### PR DESCRIPTION
**Pull request by flimzy**
Follow-up to https://github.com/juju/juju/pull/12552#discussion_r564584040

### CODE REVIEW

**Review by jameinel — APPROVED** [review]
This is meant to be a debugging tool, so isn't in the critical user path, but it is good to clean up some of these things.

**Comment by jameinel** [comment]
$$merge$$

**Comment by flimzy** [comment]
> This is meant to be a debugging tool, so isn't in the critical user path, but it is good to clean up some of these things.

This code is executed when I run `juju collect-metrics`. Does this mean `collect-metrics` is intended as a debugging tool?

Or am I missing some other context here?

**Comment by achilleasa** [comment]
@flimzy You will need to update the following tests to check the stderr output (`cmdtesting.Stderr`) instead of stdout: 

```
FAIL: collectmetrics_test.go:300: collectMetricsSuite.TestCollectMetricsLocal

running test 0: missing args
running test 1: invalid application name
running test 2: all is well
[LOG] 0:00.007 INFO juju.cmd.juju.collect-metrics ran action id action-01234567-89ab-cdef-0123-456789abcdef
running test 3: invalid tag returned
collectmetrics_test.go:319:
    c.Assert(cmdtesting.Stdout(ctx), gc.Matches, test.stdout)
... value string = ""
... regex string = "failed to collect metrics: \"invalid\" is not a valid tag\\n"


----------------------------------------------------------------------
FAIL: collectmetrics_test.go:324: collectMetricsSuite.TestCollectMetricsRemote

running test 0: missing args
running test 1: invalid application name
running test 2: all is well
[LOG] 0:00.003 INFO juju.cmd.juju.collect-metrics ran action id action-01234567-89ab-cdef-0123-456789abcdef
running test 3: invalid tag returned
collectmetrics_test.go:343:
    c.Assert(cmdtesting.Stdout(ctx), gc.Matches, test.stdout)
... value string = ""
... regex string = "failed to collect metrics: \"invalid\" is not a valid tag\\n"
```

**Comment by flimzy** [comment]
@achilleasa Thanks for the hint. Should be done now.

**Comment by achilleasa** [comment]
!!build!! (transient error in flaky relation test)

**Comment by achilleasa** [comment]
$$merge$$

**Pull request merged**
