### PR TITLE
Increment juju to 2.2-beta4

### PR DESCRIPTION
**Pull request by ExternalReality**
## Please provide the following details to expedite Pull Request review:

----

## Description of change

Increment version for release 2.2-beta3

## QA steps

N/A

## Documentation changes

N/A

## Bug reference

N/A

### CODE REVIEW

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by axw** [comment]
$$merge$$

**Comment by Veebers** [comment]
$$merge$$

**Comment by axw** [comment]
$$merge$$

**Comment by axw** [comment]
Force merging this as it's just a version change, and mongo 3.2 failures keep happening. My PR will be queued next, which should address that.

**Pull request merged**
