### PR TITLE
Updated Dependabot for go.mod

### PR DESCRIPTION
**Pull request by nathannaveen**
Updated Dependabot for go.mod.

### CODE REVIEW

**Review by SimonRichardson — CHANGES_REQUESTED** [review]
I'm unsure about if we actually want this. As we need to be careful what we bump and don't just bump things without consideration. A case in point is the `hashicorp/raft` which required a lot of changes to logging to get it working, another was the `lxc/lxd` package that broke all the errors in juju. 
That then forces people to page in and potentially do unscheduled work, instead of doing it at better intervals.

**Comment by jameinel** [comment]
Does this actually change dependencies, or does it just inform us with a daily check so that we can know if there are dependencies that need updating?
If it is informative (with good ways to squelch when we don't want to update yet), I think it is useful. Just changing dependencies underneath doesn't seem useful.

**Comment by nathan-415** [comment]
> Does this actually change dependencies, or does it just inform us with a daily check so that we can know if there are dependencies that need updating?
> If it is informative (with good ways to squelch when we don't want to update yet), I think it is useful. Just changing dependencies underneath doesn't seem useful.

Yes, it is informative, and does not merge automatically.

**Review by SimonRichardson — APPROVED** [review]

**Comment by SimonRichardson** [comment]
Closing this because of no activity, please reopen if you want to move this forward.

**Pull request closed without merging**
