### PR TITLE
Bump lxd api

### PR DESCRIPTION
**Pull request by tych0**
update the version of the go LXD bindings, and update some small incompatibilities.

### CODE REVIEW

**Comment by jameinel** [comment]
I wonder why this didn't get a review-board request. Is it a user issue, or is it because you didn't provide a review comment (which would then get used in the commit message when it is merged).

Anyway, the changes LGTM.

**Comment by jameinel** [comment]
$$merge$$

**Comment by tych0** [comment]
On Tue, Jan 19, 2016 at 12:35:41AM -0800, John Arbash Meinel wrote:
> I wonder why this didn't get a review-board request. Is it a user issue, or is it because you didn't provide a review comment (which would then get used in the commit message when it is merged).

I don't know :). Is there something I have to do?

**Comment by tych0** [comment]
On Tue, Jan 19, 2016 at 12:39:04AM -0800, Juju bot wrote:
> Build failed: Does not match ['fixes-1533750']
>         build url: http://juju-ci.vapour.ws:8080/job/github-merge-juju/6005
> 

Not quite sure I understand the output here. Is this my fault?

**Comment by cherylj** [comment]
@tych0 No, master is currently blocked trying to get stabilization for an upcoming 2.0-alpha1 release.  Once we get a blessed build and release 2.0-alpha1, master will be unblocked and you can try and merge this PR again.

**Comment by jameinel** [comment]
master is now blessed, so likely we just have to wait for a release to go.

I think one thing to change is that when you create a pull request, just make sure to include a comment. That should allow our automated system to generate a Review Board entry, where we prefer to do our reviews. http://reviews.vapour.ws/dashboard/

It is also the commit message we will use when merging your changes, so it is nice to have a simple summary of the changes you've made. I'll try to keep tabs on the bug so I can land this as soon as Master is unblocked again.

**Comment by jameinel** [comment]
I tried testing this out after having bootstrapped lxd previously.
It turns out the path is not consistent with the old code.
Specifically I got this error:
2016-01-20 12:57:09 INFO juju.cmd supercommand.go:58 running juju [2.0-alpha1 gc]
2016-01-20 12:57:12 DEBUG juju.container.lxd.lxdclient client.go:53 loading LXD client config from "/home/jameinel/.config/lxc/juju-lxd"
2016-01-20 12:57:12 DEBUG juju.cmd.juju common.go:98 Destroying environment info.
2016-01-20 12:57:12 INFO cmd cmd.go:129 Bootstrap failed, cleaning up the environment.
2016-01-20 12:57:12 ERROR cmd supercommand.go:448 there was an issue examining the environment: invalid config: cannot read config file: read /home/jameinel/.config/lxc/juju-lxd: is a directory

If I then deleted that directory, because I had already destroyed the environment, I then got this failure:
2016-01-20 12:58:50 INFO juju.cmd supercommand.go:58 running juju [2.0-alpha1 gc]
2016-01-20 12:58:50 DEBUG juju.container.lxd.lxdclient client.go:53 loading LXD client config from "/home/jameinel/.config/lxc/juju-lxd"
2016-01-20 12:58:50 DEBUG juju.container.lxd.lxdclient client.go:60 using LXD remote "local"
2016-01-20 12:58:51 DEBUG juju.cmd.juju common.go:98 Destroying environment info.
2016-01-20 12:58:51 INFO cmd cmd.go:129 Bootstrap failed, cleaning up the environment.
2016-01-20 12:58:51 ERROR cmd supercommand.go:448 there was an issue examining the environment: invalid config: Can not change ZFS config. Images or containers are still using the ZFS pool: [images/1032903165a677e18ed93bde5057ae6287841ae756d1a6296eef8f2e5a825e4a]


Obviously, I didn't look over the code thoroughly enough. Apparently passing in config isn't doing the same thing that we were getting by creating a directory for config.

**Comment by tych0** [comment]
On Wed, Jan 20, 2016 at 05:00:53AM -0800, John Arbash Meinel wrote:
> I tried testing this out after having bootstrapped lxd previously.
> It turns out the path is not consistent with the old code.
> Specifically I got this error:
> 2016-01-20 12:57:09 INFO juju.cmd supercommand.go:58 running juju [2.0-alpha1 gc]
> 2016-01-20 12:57:12 DEBUG juju.container.lxd.lxdclient client.go:53 loading LXD client config from "/home/jameinel/.config/lxc/juju-lxd"
> 2016-01-20 12:57:12 DEBUG juju.cmd.juju common.go:98 Destroying environment info.
> 2016-01-20 12:57:12 INFO cmd cmd.go:129 Bootstrap failed, cleaning up the environment.
> 2016-01-20 12:57:12 ERROR cmd supercommand.go:448 there was an issue examining the environment: invalid config: cannot read config file: read /home/jameinel/.config/lxc/juju-lxd: is a directory
> 
> If I then deleted that directory, because I had already destroyed the environment, I then got this failure:
> 2016-01-20 12:58:50 INFO juju.cmd supercommand.go:58 running juju [2.0-alpha1 gc]
> 2016-01-20 12:58:50 DEBUG juju.container.lxd.lxdclient client.go:53 loading LXD client config from "/home/jameinel/.config/lxc/juju-lxd"
> 2016-01-20 12:58:50 DEBUG juju.container.lxd.lxdclient client.go:60 using LXD remote "local"
> 2016-01-20 12:58:51 DEBUG juju.cmd.juju common.go:98 Destroying environment info.
> 2016-01-20 12:58:51 INFO cmd cmd.go:129 Bootstrap failed, cleaning up the environment.
> 2016-01-20 12:58:51 ERROR cmd supercommand.go:448 there was an issue examining the environment: invalid config: Can not change ZFS config. Images or containers are still using the ZFS pool: [images/1032903165a677e18ed93bde5057ae6287841ae756d1a6296eef8f2e5a825e4a]
> 
> 
> Obviously, I didn't look over the code thoroughly enough. Apparently passing in config isn't doing the same thing that we were getting by creating a directory for config.

Bah, I think I know what happened. I broke it during a rebase :(. I
will post a fix shortly.

**Comment by tych0** [comment]
Ok, I believe I've fixed that and one other issue that @jamespage reported by bumping to the 0.27 client.

**Comment by tych0** [comment]
Oh, whoops. Wrong james page, sorry :)

**Comment by javacruft** [comment]
This fix really needs to land; juju is not currently compatible with the lxd version in xenial

**Comment by perrito666** [comment]
$$merge$$

**Comment by cherylj** [comment]
Please don't merge this until master is unblocked.

**Comment by jameinel** [comment]
$$merge$$

**Comment by cherylj** [comment]
This shouldn't have been merged into master yet.  It was being tested in a feature branch and had known issues and now master is broken :(

**Comment by jameinel** [comment]
So the feature branch was involving a lot more code rather than just bringing in an updated LXD agent version, wasn't it? How did it pass the bot if it broke master? Is there a bigger dependency problem that  I was missing? I had tested it a bit manually and it seemed sane, was it just a dependency we are/were missing on some platforms/versions of go?

**Pull request merged**
