### PR TITLE
Check extension on file uploads

### PR DESCRIPTION
**Pull request by natefinch**
compare the filename of the uploaded file to the Path value declared in the metadata, and error out if they don't match.

(Review request: http://reviews.vapour.ws/r/4047/)

### CODE REVIEW

**Comment by natefinch** [comment]
$$merge$$

**Comment by natefinch** [comment]
$$merge$$

**Comment by kat-co** [comment]
Hoping these failures are spurious while I investigate the failures. $$merge$$

**Comment by kat-co** [comment]
Continuing development here: https://github.com/juju/juju/pull/4683

**Pull request closed without merging**
