### PR TITLE
Verify copyright

### PR DESCRIPTION
**Pull request by SimonRichardson**
## Description of change

The following ensures that the copyright notices are in place. I've
been caught out too many times and I need help to prevent someone
looking at a PR checking this simple step!

So the following validates that a copy right file for every file
exists.

## QA steps

Run the following:

```sh
./scripts/copyright.sh
```

### CODE REVIEW

**Comment by SimonRichardson** [comment]
https://trello.com/c/KQMYainZ/700-verify-copyright-notice-on-files

**Comment by SimonRichardson** [comment]
!!build!!

> github.com can not be resolved

**Comment by SimonRichardson** [comment]
!!build!!

> windows box being flaky

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by jameinel** [comment]
LGTM. Thanks for doing this.

**Comment by SimonRichardson** [comment]
$$merge$$

**Pull request merged**
