### PR TITLE
Remove max-logs-age and max-logs-size Controller Config Articles

### PR DESCRIPTION
**Pull request by manadart**
## Description of change

This patch addresses a _TODO_ for the 2.7 branch, removing the controller configuration items `max-logs-age` and `max-logs-size`. These are no longer required.

## QA steps

Bootstrap a 2.6 controller, upgrade to this patch, and check that there are no controller log errors.

## Documentation changes

Yes.

## Bug reference

N/A

### CODE REVIEW

**Comment by manadart** [comment]
Doc change at https://jaas.ai/docs/configuring-controllers @timClicks

**Comment by manadart** [comment]
[Remove Deprecated Controller Log Config](https://trello.com/c/7W1Hdrga/1941-remove-deprecated-controller-log-config)

**Comment by howbazaar** [comment]
We should probably add an upgrade step to remove them from controller-config if they are set.

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
