### PR TITLE
Merge 2.9 into develop

### PR DESCRIPTION
**Pull request by manadart**
Merge from 2.9 bringing forward:
- #13303 from wallyworld/unit-relation-tracing
- #13279 from juju/dependabot/github_actions/actions/setup-go-2.1.4
- #13293 from wallyworld/rotate-secret-watcher
- #13300 from manadart/2.9-net-info-mod-cfg
- #13292 from achilleasa/2.9-use-cidr-in-cidr-fallback-when-matching-machine-addr-cidrs-to-subnets
- #12569 from juju/devVersions
- #13286 from hpidcock/fix-report-hook-error
- #13285 from ycliuhw/fix/registry-basic-auth
- #13289 from achilleasa/2.9-ignore-fan-subnets-when-querying-equinix-api
- #13290 from wallyworld/remote-application-history
- #13281 from ycliuhw/fix/lp-1941055
- #13288 from SimonRichardson/add-logging-for-missing-relation-key
- #13287 from SimonRichardson/trap-upgrade-series-interrupt
- #13283 from SimonRichardson/remote-connections-not-found
- #13284 from wallyworld/remote-relationunit-notfound
- #13276 from manadart/2.9-lease-manager-tick-schedule
- #13282 from manadart/2.9-net-get-bridge-address
- #13280 from SimonRichardson/upstream-raft-part-deux
- #13192 from ycliuhw/fix/lp-1935953
- #13251 from jameinel/2.9-proxy-issue-4
- #13275 from jujubot/increment-to-2.9.13
- #13273 from wallyworld/update-secrets
- #13270 from manadart/2.9-remote-rels-suite

Conflicts:
- .github/workflows/build.yml
- .github/workflows/client-tests.yml
- .github/workflows/static-analysis.yml
- CONTRIBUTING.md
- caas/broker.go
- caas/kubernetes/provider/bootstrap.go
- caas/kubernetes/provider/bootstrap_test.go
- caas/kubernetes/provider/operator.go
- caas/mocks/broker_mock.go
- cloudconfig/podcfg/image.go
- cloudconfig/podcfg/podcfg_test.go
- cmd/juju/commands/upgrademodel.go
- cmd/juju/commands/upgrademodel_test.go
- controller/config_test.go
- feature/flags.go
- scripts/win-installer/setup.iss
- snap/snapcraft.yaml
- version/version.go
- worker/uniter/relation/statetracker.go
- worker/uniter/uniter_test.go

### CODE REVIEW

**Comment by manadart** [comment]
[Merge 2.9 into develop](https://trello.com/c/bmJbXGr2/3927-merge-29-into-develop)

**Review by achilleasa — APPROVED** [review]
Given the range of changes and conflicts here we should probably set up a bot to periodically run n-1 -> develop merges and ping us if we need to resolve a conflict manually.

**Comment by hpidcock** [comment]
$$merge$$

**Comment by manadart** [comment]
!!build!!

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
