### PR TITLE
Replace missing links.

### PR DESCRIPTION
**Pull request by juanmanuel-tirado**
The README.md file contains a bunch of links that do not exist. Actually, they end up pointing to the default https://juju.is/about page. This is a naive review of the non-existing links where I have replaced them with existing pages I consider they contain the expected information from the original link. 

I cannot say I found the corresponding page to every link in the previous version. For example, I could not find a page containing the architecture in some sort of diagram or summary. Maybe other pages may be considered to explain the architecture. Most of the changes should be OK until the documentation is complete enough.

## Checklist

 - [ ] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change
 - [ ] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - [ ] Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed
 - [ ] Comments answer the question of why design decisions were made

## QA steps

NA

## Documentation changes

NA

## Bug reference

NA

### CODE REVIEW

**Review by hpidcock — APPROVED** [review]
Before landing this PR can we ensure we keep within 80 character line length. Otherwise looks good.

**Comment by juanmanuel-tirado** [comment]
!!build!!

**Comment by juanmanuel-tirado** [comment]
!!merge!!

**Comment by juanmanuel-tirado** [comment]
second attempt

!!merge!!

**Pull request merged**
