### PR TITLE
Refactor of HookVars to use env interface.

### PR DESCRIPTION
**Pull request by tlm**
This is a tidy up PR to address a previous fix (#12929) for bug. LP-1892255

## Checklist

 - [x] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change
 - [x] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - [x] Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed
 - [x] Comments answer the question of why design decisions were made

## QA steps

See bug report. https://bugs.launchpad.net/juju/+bug/1892255

## Bug reference

https://bugs.launchpad.net/juju/+bug/1892255

### CODE REVIEW

**Comment by hpidcock** [comment]
[LP 1892255 Kubernetes ENV Vars V2](https://trello.com/c/ZcIUYh8E/1555-lp-1892255-kubernetes-env-vars-v2)

**Review by hpidcock — APPROVED** [review]
LGTM. Only thing, which this is a sidebar discussion is we probably should make a policy on creating packages that conflict in both name and common contents with the standard library. @jameinel maybe we should try to avoid package names like `context`, `testing`, `net`, `http` etc.

Instead we should either fully prefix a package name like, jujutesting or runnercontext etc.

**Comment by tlm** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Pull request merged**
