### PR TITLE
Ensure that marking a machine for removal is idempotent, without attempting to insert duplicate records

### PR DESCRIPTION
**Pull request by manadart**
The server-side transaction implementation does not allow the insertion of duplicate records, whereas under client-side transactions such operations will succeed provided no assertion is made that the document is absent from the collections.

When marking a machine for removal, check if there is already a removal record and if so, do nothing.

This brings up something interesting - with server-side transactions, there is no need to assert that a document exists when inserting at a specific ID. This is effectively done for free and all such assertions can be removed. Presumably this would result in a slight performance benefit.

## QA steps

- Apply this patch:
```diff
diff --git a/state/open.go b/state/open.go
index e1e6284012..930a7da75e 100644
--- a/state/open.go
+++ b/state/open.go
@@ -136,7 +136,7 @@ func newState(
        // plus txn.Op slices that are wrong, eg insert dup or missing asserts.
        // Related test failures here:
        // https://jenkins.juju.canonical.com/job/github-make-check-juju/9317/testReport/
-       sstxn = false
+       sstxn = true

        if sstxn {
                logger.Infof("using server-side transactions")
```
- Run the _TestMarkingAndCompletingMachineRemoval_ unit test in the state package.

## Documentation changes

None.

## Bug reference

N/A

### CODE REVIEW

**Comment by manadart** [comment]
[Fix transaction operations for marking machine for removal](https://trello.com/c/Wyvm4dbF/3418-fix-transaction-operations-for-marking-machine-for-removal)

**Review by SimonRichardson — APPROVED** [review]
This code is good, but I have concerns about turning server-side transactions on for existing deployments. I say this because we have no idea how badly this will go if we turn on sstxn and there are documents within existing collections that could potentially cause a lot of fallout.

I see either we need to write one monumental upgrade step that attempts to sanitize the collections or we need to disable sstxn for existing deployments.

Thoughts?

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
