### PR TITLE
Remove more obsolete facade apis

### PR DESCRIPTION
**Pull request by wallyworld**
Remove v10 and earlier of the provisioner facade.
Also remove storage provisioner v1 and machiner v3 and earlier.

## QA steps

bootstrap
deploy a charm with storage

### CODE REVIEW

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
[remove obsolete machine, provisioner facades](https://trello.com/c/4bsGecTF/1417-remove-obsolete-machine-provisioner-facades)

**Review by hpidcock — APPROVED** [review]

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
