### PR TITLE
Increment juju to 2.3.6

### PR DESCRIPTION
**Pull request by anastasiamac**
## Description of change

Increments Juju to next version, 2.3.6

### CODE REVIEW

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by jameinel** [comment]
$$merge$$ ShowOutputSuite.TestRun looks to be an intermittent failure

**Comment by anastasiamac** [comment]
$$merge$$

**Pull request merged**
