### PR TITLE
Merge 3.1 into develop

### PR DESCRIPTION
**Pull request by manadart**
Merge from 3.1 bringing forward:
- #15199 from manadart/3.0-into-3.1
- #15174 from jameinel/3.1-hide-apis

Only conflict was in _schema.json_, solved by regeneration.

### CODE REVIEW

**Review by wallyworld — APPROVED** [review]
Looks like there's an issue with the mock gen check to fix before landing?

**Comment by manadart** [comment]
I think Simon's got a fix for generate.
/merge

**Pull request merged**
