### PR TITLE
Merge 2.9 into develop

### PR DESCRIPTION
**Pull request by manadart**
Merge from 2.9 to bring forward:
- #13791 from tlm/darwin-makefile-changes
- #13790 from SimonRichardson/clean-up-error-message-for-raft-request
- #13789 from SimonRichardson/prevent-panic-in-uniter-report
- #13788 from manadart/2.9-retry-raft-leader-errors
- #13781 from tlm/caas-probe-support
- #13787 from ycliuhw/fix/nw-model-migration-amd64-gce
- #13765 from SimonRichardson/charmhub-channel-branches
- #13784 from arnodel/juju-606-remove-script
- #13740 from arnodel/juju-583-connector-interface
- #13778 from arnodel/juju-606-move-apiserver-params-to-rpc
- #13780 from arnodel/juju-582-remove-group-api-clients-script
- #13783 from benhoyt/fix-caasunitprovisioner-race
- #13782 from wallyworld/introspection-fixes
- #13773 from arnodel/juju-582-group-api-clients
- #13776 from juju/dependabot/pip/acceptancetests/cryptography-3.3.2
- #13779 from jack-w-shaw/Fix_shfmt_fail
- #13775 from ycliuhw/fix/nw-model-migration-amd64-gce
- #13568 from benhoyt/pebble-checks-integration
- #13774 from ycliuhw/disable-kubeflow-gh-action
- #13753 from jack-w-shaw/JUJU-422_Drop_Space.Subnets
- #13771 from wallyworld/fix-git-whoami
- #13754 from manadart/2.9-cleanup-force-destroy-storage
- #13770 from wallyworld/more-robust-ec2
- #13769 from ycliuhw/fix/nw-deploy-kubeflow
- #13630 from hmlanigan/set-series
- #13759 from hmlanigan/duplicate-error-messages
- #13762 from SimonRichardson/fix-charm-revisioner
- #13760 from ycliuhw/fix/nw-deploy-kubeflow
- #13761 from wallyworld/upgrade-tests
- #13758 from ycliuhw/fix/crd-upgrade
- #13659 from SimonRichardson/start-removing-model-cache-from-api
- #13747 from manadart/2.9-cleanup-enhancements
- #13744 from manadart/2.9-container-address-origin
- #13803 from tlm/darwin-makefile-changes

Conflicts:
- api/agent/provisioner/provisioner_test.go
- api/agent/uniter/state_test.go
- api/client/application/client.go
- api/client/application/client_test.go
- api/client/bundle/client_test.go
- api/controller/controller/controller.go
- api/controller/controller/controller_test.go
- api/controller/controller/gui.go
- api/controller/controller/gui_test.go
- api/controller/controller/identity_url.go
- api/controller/controller/mongo.go
- api/uniter/state_test.go
- api/uniter/uniter_test.go
- apiserver/facades/agent/upgradesteps/upgradesteps.go
- apiserver/facades/client/action/legacy.go
- apiserver/facades/client/action/legacy_test.go
- apiserver/facades/client/application/application_unit_test.go
- apiserver/facades/client/application/charmstore.go
- apiserver/facades/client/application/charmstore_test.go
- apiserver/facades/client/application/get.go
- apiserver/facades/client/backups/create.go
- apiserver/facades/client/backups/deprecated.go
- apiserver/facades/client/charmhub/charmhub.go
- apiserver/facades/client/charmhub/charmhub_test.go
- apiserver/facades/client/charmhub/convert.go
- apiserver/facades/client/client/bundles.go
- apiserver/facades/client/client/bundles_test.go
- apiserver/facades/client/cloud/cloudV2_test.go
- apiserver/facades/client/controller/controller.go
- apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
- apiserver/facades/controller/firewaller/firewaller_base_test.go
- apiserver/gui.go
- apiserver/gui_test.go
- caas/kubernetes/provider/bootstrap.go
- caas/kubernetes/provider/k8s.go
- cmd/containeragent/initialize/package_test.go
- cmd/juju/action/action.go
- cmd/juju/action/cancel_test.go
- cmd/juju/action/common.go
- cmd/juju/action/package_test.go
- cmd/juju/action/run_test.go
- cmd/juju/action/runaction.go
- cmd/juju/action/runaction_test.go
- cmd/juju/action/showoutput.go
- cmd/juju/action/showtask_test.go
- cmd/juju/action/status.go
- cmd/juju/action/status_test.go
- cmd/juju/application/bundle_test.go
- cmd/juju/application/removesaas_test.go
- cmd/juju/application/setseries.go
- cmd/juju/application/store/mocks/store_mock.go
- cmd/juju/caas/add_test.go
- cmd/juju/caas/update_test.go
- cmd/juju/commands/exec.go
- cmd/juju/commands/exec_test.go
- cmd/juju/commands/main_test.go
- cmd/juju/commands/mocks/statusapi_mock.go
- cmd/juju/controller/listcontrollers_test.go
- cmd/juju/controller/listmodelsold.go
- cmd/juju/gui/export_test.go
- cmd/juju/gui/gui.go
- cmd/juju/gui/gui_test.go
- cmd/juju/gui/upgradegui.go
- cmd/juju/gui/upgradegui_test.go
- cmd/juju/model/exportbundle.go
- cmd/juju/model/exportbundle_test.go
- cmd/juju/ssh/debughooks.go
- cmd/juju/ssh/ssh_container_test.go
- cmd/juju/ssh/ssh_unix_test.go
- worker/caasapplicationprovisioner/application.go
- worker/machineactions/worker.go
- worker/machineactions/worker_test.go
- worker/uniter/operation/runaction.go
- worker/uniter/remotestate/snapshot.go
- worker/uniter/runner/context/context_test.go
- worker/uniter/runner/context/mocks/hookunit_mock.go
- worker/uniter/runner/factory.go
- worker/uniter/runner/jujuc/mocks/context_mock.go
- Makefile
- go.mod
- go.sum

### CODE REVIEW

**Review by tlm — APPROVED** [review]
I am happy that my changes are merged correctly.

**Review by wallyworld — APPROVED** [review]
My patches look ok

**Review by ycliuhw — APPROVED** [review]
My patches look ok as well

**Comment by hpidcock** [comment]
!!build!!

**Pull request merged**
