### PR TITLE
Update dependencies.tsv for Goose header fix

### PR DESCRIPTION
**Pull request by gnuoy**
Update dependencies.tsv to pickup fix in Goose for
OpenStack Mitaka+ clouds. Fixes lp:1625624

### CODE REVIEW

**Comment by gnuoy** [comment]
!!build!!

**Comment by bz2** [comment]
Thanks Liam, two pre-review notes. First I sent a mail about the goos api breakage, and if we want to work around it it like this, or do something different. Secondly, can you flatten the commits here into one? After review before landing is fine generally.

**Comment by bz2** [comment]
!!build!!

**Comment by bz2** [comment]
Spurious check failure, branch is good.

```
----------------------------------------------------------------------
FAIL: hookqueue_test.go:164: HookQueueSuite.TestAliveHookQueue

test 0: Nothing happens if a unit departs before its joined is run.
  step 0
  step 1
  step 2
hookqueue_test.go:175:
    expect{}.check(c, in, out)
hookqueue_test.go:306:
    c.Fatalf("got %#v", unexpected)
... Error: got hook.Info{Kind:"relation-joined", RelationId:21345, RemoteUnit:"u/0", ChangeVersion:7, StorageId:""}

OOPS: 11 passed, 1 FAILED
--- FAIL: TestPackage (0.19s)
FAIL
FAIL	github.com/juju/juju/worker/uniter/relation	0.303s
```

**Comment by bz2** [comment]
$$merge$$

**Comment by bz2** [comment]
$$retry$$

```
----------------------------------------------------------------------
FAIL: socket_test.go:69: suite.TestPprofStartWithExistingSocketFile

socket_test.go:81:
    c.Assert(err, gc.IsNil)
... value *os.PathError = &os.PathError{Op:"stat", Path:"/mnt/tmp/pprof.pprof.test.14882", Err:0x2} ("stat /mnt/tmp/pprof.pprof.test.14882: no such file or directory")

OOPS: 6 passed, 1 FAILED
--- FAIL: TestSuite (0.03s)
FAIL
FAIL	github.com/juju/juju/cmd/pprof	0.087s
```

**Comment by bz2** [comment]
$$retry$$

```
----------------------------------------------------------------------
FAIL: hookqueue_test.go:164: HookQueueSuite.TestAliveHookQueue

test 0: Nothing happens if a unit departs before its joined is run.
  step 0
  step 1
  step 2
hookqueue_test.go:175:
    expect{}.check(c, in, out)
hookqueue_test.go:306:
    c.Fatalf("got %#v", unexpected)
... Error: got hook.Info{Kind:"relation-joined", RelationId:21345, RemoteUnit:"u/0", ChangeVersion:7, StorageId:""}

OOPS: 11 passed, 1 FAILED
--- FAIL: TestPackage (0.18s)
FAIL
FAIL	github.com/juju/juju/worker/uniter/relation	0.313s
```

**Comment by bz2** [comment]
$$retry$$

```
FAIL: hookqueue_test.go:164: HookQueueSuite.TestAliveHookQueue
```

**Pull request merged**
