### PR TITLE
Add a strict-migration feature flag

### PR DESCRIPTION
**Pull request by howbazaar**
## Description of change

This branch adds a strict validation check to migrations it ensure that all status, status history, annotations, and settings are exported.

During this change, it was identified that the unit workload version was not using the status documents already retrieved, and also that the cloud instance status was being migrated from the wrong place. The Status field in the instanceDoc was depricated, but not removed, nor even mentioned that it was deprecated. This branch removes it from the instanceDoc, and updates the migration code to migrate the status and status history for the instance status.

## Documentation changes

None.

### CODE REVIEW

**Comment by howbazaar** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
Scary but true...

I suspect that it is actually a failure related to the patch:
FAIL: migration_internal_test.go:316: MigrationSuite.TestInstanceDataFields

migration_internal_test.go:335:
    s.AssertExportedFields(c, instanceData{}, fields)
migration_internal_test.go:838:
    c.Assert(removed, gc.HasLen, 0)
... obtained set.Strings = set.Strings{"Status":true}
... n int = 0

OOPS: 1845 passed, 1 skipped, 1 FAILED
--- FAIL: TestPackage (679.50s)

**Comment by howbazaar** [comment]
$$merge$$

**Comment by howbazaar** [comment]
$$wat?$$

**Pull request merged**
