### PR TITLE
Set permissions for GitHub actions

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions

https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@hpidcock / @wallyworld  👀  please

**Comment by SimonRichardson** [comment]
@naveensrinivasan you need to sign the CLA.

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan you need to sign the CLA.

@SimonRichardson Can you please provide me the link for CLA?

**Comment by juanmanuel-tirado** [comment]
https://ubuntu.com/legal/contributors

**Comment by naveensrinivasan** [comment]
> https://ubuntu.com/legal/contributors

I have signed it. 
image

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan it looks like you might have signed the CLA cert with a different email address, as we're not picking it up in the CLA job.

I just re-did it. Can you please re-run the job? Thanks

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan it looks like you might have signed the CLA cert with a different email address, as we're not picking it up in the CLA job.

@SimonRichardson Friendly ping!

**Comment by juanmanuel-tirado** [comment]
!!build!!

**Comment by naveensrinivasan** [comment]
OK, I just signed the commits and the CLA.

**Pull request closed without merging**
