### PR TITLE
Move wrench package to internal/wrench

### PR DESCRIPTION
**Pull request by SimonRichardson**
The following moves another package into the internal package. There are still a few more to do, just adding more as I go.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc

## QA steps

Tests should pass.

```sh
$ juju bootstrap lxd test --build-agent
```

JUJU-4597

### CODE REVIEW

**Review by hmlanigan — APPROVED** [review]
Since we no longer support windows as a workload, let's remove `internal/wrench/wrench_windows*.go?

QA is good - and the wrenches still work.

**Comment by hmlanigan** [comment]
side note,  after the controller was up a bit - I started to get repeated:
```
machine-0: 18:18:52 WARNING juju.worker.changestreampruner Watermark "0" is outside of window, check logs to see if the change stream is keeping up
machine-0: 18:18:57 WARNING juju.worker.changestreampruner Watermark "0" is outside of window, check logs to see if the change stream is keeping up
machine-0: 18:19:02 WARNING juju.worker.changestreampruner Watermark "0" is outside of window, check logs to see if the change stream is keeping up
machine-0: 18:19:07 WARNING juju.worker.changestreampruner Watermark "0" is outside of window, check logs to see if the change stream is keeping up
machine-0: 18:19:12 WARNING juju.worker.changestreampruner Watermark "0" is outside of window, check logs to see if the change stream is keeping up
```

**Comment by SimonRichardson** [comment]
> side note, after the controller was up a bit - I started to get repeated:
> 
> ```
> machine-0: 18:18:52 WARNING juju.worker.changestreampruner Watermark "0" is outside of window, check logs to see if the change stream is keeping up
> machine-0: 18:18:57 WARNING juju.worker.changestreampruner Watermark "0" is outside of window, check logs to see if the change stream is keeping up
> machine-0: 18:19:02 WARNING juju.worker.changestreampruner Watermark "0" is outside of window, check logs to see if the change stream is keeping up
> machine-0: 18:19:07 WARNING juju.worker.changestreampruner Watermark "0" is outside of window, check logs to see if the change stream is keeping up
> machine-0: 18:19:12 WARNING juju.worker.changestreampruner Watermark "0" is outside of window, check logs to see if the change stream is keeping up
> ```

Yeah this is fine, nobody is writing to the db... one unit or machine is in there, the message will go away

**Pull request merged**
