### PR TITLE
provider/ec2: catch additional error status

### PR DESCRIPTION
**Pull request by axw**
## Description of change

When detaching a volume, if it is not attached
to any machine an IncorrectState status code
will be returned from EC2.

Also, fix an improper errors.Annotatef when
attaching volumes, which would cause a nil error
to be returned under error conditions.

Introduced a reverse proxy into the local test
server to simplify testing of edge cases.
Individual tests can manipulate the reverse
proxy to return responses that will trigger
those edge cases.

## QA steps

This cannot be QA'd completely without additional changes. With the changes to attach and detach storage, I found this bug by doing the following:

1. juju deploy -n2 storagetest
2. juju add-storage storagetest/0 disks=ebs
(wait)
3. juju detach-storage disks/0
(wait for the storage-detaching hook to fire, but not long enough for the EBS volume to be detached from the EC2 instance)
4. juju attach-storage storagetest/0 disks/0

The volume would show up as attached in state. The reason for that is because when we call AttachVolumes, it first describes the volume; the volume's state is "in-use", because it's still attached to storagetest/0's machine. We're checking all the right things, but then using `errors.Annotate` on a nil error, instead of just calling `errors.Errors` like we should be doing.

Then, calling "detach-storage" would cause DetachVolumes to be called, but that would fail because the EBS volume isn't actually attached to anything by that stage, and IncorrectState would be returned.

## Documentation changes

None.

## Bug reference

None. Only affects the feature branch, since volumes couldn't previously be detached.

### CODE REVIEW

**Comment by axw** [comment]
$$merge$$

**Comment by axw** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by howbazaar** [comment]
$$merge$$

**Comment by axw** [comment]
$$merge$$

**Comment by axw** [comment]
$$merge$$

**Pull request merged**
