### PR TITLE
juju-txn-helper: Allow querying of the full transaction collection

### PR DESCRIPTION
**Pull request by Vultaire**
The first version of this script worked to walk the transactions associated with a specific model's txn-queue.  Failing transactions may be found in other documents, thus this update allows for searching the full transaction collection, filtering by status code.

It is backwards compatible with the previous version.

While limited, some unit tests have also been added for the sake of preserving existing behavior and adding minimal, albeit incomplete, test coverage.

### CODE REVIEW

**Review by hmlanigan — APPROVED** [review]
LGTM, apologies for the delay

**Comment by SimonRichardson** [comment]
@Vultaire can you [sign your commit](https://docs.github.com/en/authentication/managing-commit-signature-verification), otherwise we can't land it.

**Pull request merged**
