### PR TITLE
Patch version.Current.Arch to arch.AMD64 so tests pass on non-AMD64 hosts

### PR DESCRIPTION
**Pull request by dooferlad**
Fixes: lp:1420049

(Review request: http://reviews.vapour.ws/r/985/)

### CODE REVIEW

**Comment by dooferlad** [comment]
$$merge$$

**Comment by dooferlad** [comment]
$$ping$$

**Comment by dooferlad** [comment]
$$dollar$$

**Comment by dimitern** [comment]
$$fixes-1420049$$

**Pull request merged**
