### PR TITLE
[2.7] A bunch of fixes to unblock CI

### PR DESCRIPTION
**Pull request by achilleasa**
## Description of change

This PR lands a number of changes to unblock our CI. More specifically:

- Go will not allow TLS handshakes with TLS1.2+ if key is 64 bytes long. This PR removes the PatchValue calls from the various test suites that forced a 512bit key length so that all our tests use the preferred (384 byte long) default key size.
- In addition, this PR cherry-picks a commit from https://github.com/juju/juju/pull/11632 to fetch a snapshot of the vendor folder from S3 and includes additional commits to bypass 'dep ensure' (which is called multiple times by the various Makefile targets) when using the cached deps.
- Finally, the PR backports the fixes from https://github.com/juju/juju/pull/11654 and https://github.com/juju/juju/pull/11594.

### CODE REVIEW

**Comment by achilleasa** [comment]
!!build!!

**Comment by achilleasa** [comment]
@hmlanigan @SimonRichardson @manadart I pushed some extra commits which should hopefully also fix the linter warnings (it was goimports that was complaining).

**Comment by achilleasa** [comment]
!!build!!

**Comment by hmlanigan** [comment]
tests blew up on systemd timeouts, rerunning.

!!build!!

**Comment by hmlanigan** [comment]
Less and mostly different failures this time.  Trying to merge in case the one build succeeds.

$$merge$$

**Comment by hmlanigan** [comment]
a single fail in apiclientWhiteboxSuite.TestDialWebsocketMultiCancelled

$$merge$$

**Comment by hmlanigan** [comment]
2 different fails - last try before my EOD

$$merge$$

**Comment by howbazaar** [comment]
Which CI bits are broken with this? These are unit tests only, are the tests not passing?

**Comment by manadart** [comment]
@howbazaar On 2.7, if you run tests from `MachineLegacyLeasesSuite` there are multiple failures with this as the root cause:
```
[LOG] 0:06.867 WARNING juju.worker.httpserver http: TLS handshake error from 127.0.0.1:38084: tls: certificate RSA key size too small for supported signature algorithms
```

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
"lxc: command not found" ?
$$merge$$

**Comment by achilleasa** [comment]
$$merge$$ (dep ensure hanged)

**Comment by achilleasa** [comment]
!!build!! Restarting because dep ensure took forever to complete and the CI job would timeout anyway

**Comment by achilleasa** [comment]
!!build!! refreshed vendor snapshot.

**Comment by achilleasa** [comment]
!!build!! (timeout waiting for agent to terminate in MachineLegacyLeasesSuite.TestDyingMachine)

**Comment by achilleasa** [comment]
!!build!! (TestDialWebsocketMultiCancelled failed)

**Comment by achilleasa** [comment]
!!build!! (snap timeouts)

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
Finally 🎉😆

**Pull request merged**
