### PR TITLE
2.6 into develop

### PR DESCRIPTION
**Pull request by manadart**
## Description of change

Merge from 2.6 branch to bring forward:
- #10444 from hmlanigan/newregions
- #10436 from hmlanigan/checkerropforce
- #10415 from hmlanigan/bug-1834553
- #10411 from manadart/2.6-cache-charm-set-messages
- #10383 from hmlanigan/status
- #10431 from manadart/2.6-revert-uniter-to-state

### CODE REVIEW

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
[Merge 2.6 into Develop](https://trello.com/c/FVu3jNvw/1659-merge-26-into-develop)

**Comment by manadart** [comment]
```
17:50:52 FAIL: caasoperator_test.go:360: WorkerSuite.TestRemovedUnit
17:50:52 
17:50:52 [LOG] 0:00.247 DEBUG juju.charm charm is not in revision control directory
17:50:52 [LOG] 0:00.248 INFO juju.worker.uniter.charm downloading cs:gitlab-1 from API server
17:50:52 [LOG] 0:01.842 DEBUG juju.worker.uniter.charm preparing to deploy charm "cs:gitlab-1"
17:50:52 [LOG] 0:06.723 DEBUG juju.worker.uniter.charm deploying charm "cs:gitlab-1"
17:50:52 caasoperator_test.go:361:
17:50:52     w, _ := s.assertUniterStarted(c)
17:50:52 caasoperator_test.go:296:
17:50:52     c.Fatal("timed out sending application change")
17:50:52 ... Error: timed out sending application change
```

Couldn't reproduce locally.
$$merge$$

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
intermittent failure in StatusSuite.TestStatusAllFormats

$$merge$$

**Comment by hmlanigan** [comment]
intermittent fail in loginSuite.TestOtherModel

$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
