### PR TITLE
OpenStack Provider: Add IPv6 rules when setting up global group

### PR DESCRIPTION
**Pull request by fnordahl**

### CODE REVIEW

**Comment by fnordahl** [comment]
retest this please

**Comment by mitechie** [comment]
Would like to get @macgreagoir and @jameinel to peek at this please. 

Thanks for the PR @fnordahl

**Comment by macgreagoir** [comment]
@fnordahl Thanks very much for the PR. The changes look good to me, but we will at least need one change, please. PR https://github.com/juju/juju/pull/6552 is due to land very soon, and introduces the use of Neutron proper, rather than the deprecated proxying via nova-network.

Can I ask you to make your changes against the new library, please? You should also be able to update the test suite for your new IPv6 rules.

Thanks again.

**Comment by fnordahl** [comment]
@macgreagoir New patch based on the newly merged code added. Also updated test case. Tests are currently failing due to an error in the go-goose Neutron test service. I have added PR go-goose/goose#32 to address that.

If that lands I would probably have to update this patch with correct commit position for the go-goose dependency to proceed?

**Comment by fnordahl** [comment]
Whee, the go-goose PR landed. Patch set updated with correct dependency for go-goose.

**Comment by axw** [comment]
$$merge$$

**Pull request merged**
