### PR TITLE
Merge 2.8

### PR DESCRIPTION
**Pull request by wallyworld**
Merge 2.8 with these PRs:

#12712 Fix eks CI
#12706 Use juju repos for mgo, txn, blobstore instead of gopkg.in

Conflicts were all related to import clashes.
```
# Conflicts:
#       agent/agentbootstrap/bootstrap.go
#       api/applicationoffers/client.go
#       apiserver/facades/client/application/charmstore.go
#       apiserver/facades/client/application/charmstore_test.go
#       apiserver/facades/client/applicationoffers/applicationoffers_test.go
#       apiserver/facades/client/applicationoffers/mock_test.go
#       apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
#       apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
#       apiserver/params/crossmodel.go
#       charmstore/client.go
#       charmstore/jar.go
#       charmstore/jar_test.go
#       charmstore/stub_test.go
#       cmd/juju/application/deploy.go
#       cmd/juju/application/deployer/lxdprofilestep.go
#       cmd/juju/application/deployer/register_test.go
#       cmd/juju/application/refresh.go
#       cmd/juju/application/refresh_resources_test.go
#       cmd/juju/application/refresh_test.go
#       cmd/juju/application/store.go
#       cmd/juju/romulus/budget/budget.go
#       cmd/juju/romulus/resolve.go
#       cmd/juju/romulus/setplan/set_plan_test.go
#       cmd/jujud/agent/machine.go
#       cmd/modelcmd/apicontext_test.go
#       controller/config.go
#       go.mod
#       go.sum
#       mongo/mongo.go
#       mongo/open.go
#       state/action.go
#       state/applicationoffers.go
#       state/backups/restore.go
#       state/cloudimagemetadata/image.go
#       state/container.go
#       state/globalclock/updater.go
#       state/initialize.go
#       state/logs.go
#       state/migration_export.go
#       state/migration_import_input_mock_test.go
#       state/migration_import_mock_test.go
#       state/ports.go
#       state/ports_ops.go
#       state/reboot.go
#       state/relationunit.go
#       state/resources.go
#       state/resources_persistence.go
#       state/resources_state_resource.go
#       state/user.go
#       state/watcher_profilecharm_test.go
#       worker/firewaller/firewaller.go
#       worker/firewaller/firewaller_test.go
#       worker/peergrouper/initiate.go
```

## QA steps

See PRs

### CODE REVIEW

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Review by benhoyt — APPROVED** [review]
Lots of import churn, yum! LGTM.

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
