### PR TITLE
Migrations: use controller tag to identify controllers

### PR DESCRIPTION
**Pull request by mjs**
Model tags were being inappropriately used in some areas of migrations when controller tags should have been used instead.

(Review request: http://reviews.vapour.ws/r/5648/)

### CODE REVIEW

**Comment by mjs** [comment]
$$merge$$

**Comment by mjs** [comment]
$$merge$$

**Comment by mjs** [comment]
$$merge$$

**Comment by mjs** [comment]
$$unexpected-message$$

**Comment by mjs** [comment]
$$hello$$

**Comment by Veebers** [comment]
$$merge$$

**Comment by reedobrien** [comment]
$$merge$$

**Comment by reedobrien** [comment]
$$merge$$

**Pull request merged**
