### PR TITLE
Merge 2.9 into develop

### PR DESCRIPTION
**Pull request by hmlanigan**
Merge 2.9 into develop.  Includes the following PRs:
- #13177
- #13180 
- #13186 
- #13188
- #13190 
- #13195 
- #13196
- #13197 

Fixed conflicts in:
- apiserver/facades/client/charms/client.go
- cmd/jujud/agent/machine.go 
- state/state.go 
- tests/suites/network/network_health.sh 
- worker/peergrouper/worker_test.go 
- worker/raft/rafttransport/worker.go
- go.mod
- go.sum

### CODE REVIEW

**Review by achilleasa — APPROVED** [review]

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
$$merge$$

**Pull request merged**
