### PR TITLE
Add constraints to show-machine output

### PR DESCRIPTION
**Pull request by macgreagoir**
Fixes lp:1650258

QA steps:
 * Bootstrap with constraints
 * `juju show-machine 0 -m controller` should include a constraints item, similarly formatted to the hardware item
 * `--format json` and `juju status`, with yaml or json format, should also include the constraints item

### CODE REVIEW

**Comment by voidspace** [comment]
LGTM

**Comment by macgreagoir** [comment]
!!build!!

**Comment by macgreagoir** [comment]
!!build!!

**Comment by macgreagoir** [comment]
$$merge$$

**Pull request merged**
