### PR TITLE
refactor: remove juju/errors

### PR DESCRIPTION
**Pull request by tlm**
This is a trial run pull request to remove juju/errors from the domain package completely. As we want to remove `juju/errors` from Juju in 4.0 there exists a set of scripts included in this pull request that can automatically go through and perform the refactor of removing `juju/errors`.

To test the scripts in this pull request I did  the following `scripts/errors-patch/run.sh  domain`

If succsefull in landing this PR the goal will be to keep running these scripts on other packages in Juju with associated PR's and extending the scripts to support new use cases discovered.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- ~[ ] Go unit tests, with comments saying what you're testing~
- ~[ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- ~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

See above for steps to run the scripts.

## Documentation changes

N/A

## Links

**Jira card:** JUJU-

### CODE REVIEW

**Review by hpidcock — APPROVED** [review]
Happy to give a preliminary +1. Thank-you for scripting this, it has helped in the review of the manual changes separately from the automatic changes.

**Review by SimonRichardson — APPROVED** [review]
Fix all the things.

**Comment by tlm** [comment]
Closing this PR. Will open a new one. There is a bug in this refactor that CI has high lighted. Will need to do another full run from the start to get it cleared.

**Comment by tlm** [comment]
Closing this PR. Will open a new one. There is a bug in this refactor that CI has high lighted. Will need to do another full run from the start to get it cleared.

**Pull request closed without merging**
