### PR TITLE
enhance certificate auth type for k8s

### PR DESCRIPTION
**Pull request by ycliuhw**
## Description of change

- Enhance k8s credentials of `ClientData` auth type

## QA steps

- prepare a kubeconfig file with `clientKey` auth type

```bash
gcloud config set container/use_client_certificate True
gcloud container clusters get-credentials <cluster-name> --zone <zone>

gcloud config set container/use_client_certificate False
gcloud container clusters get-credentials <cluster-name> --zone <zone>

kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user $(gcloud config get-value account) --user client  --context <cluster-context-name>

gcloud config set container/use_client_certificate True
gcloud container clusters get-credentials <cluster-name> --zone <zone>
```

- add ur cluster using add-k8s

```bash
kubectl config view --raw | juju add-k8s <your-cloud-name> --cluster-name=<ur-cluster-name>
```
- add k8s model to the cloud

```bash
juju add-model <your-k8s-model> <your-cloud-name>
```
- ensure storage pool for operator pod
```bash
juju create-storage-pool operator-storage kubernetes storage-class=juju-operator-storage storage-provisioner=kubernetes.io/gce-pd parameters.type=pd-standard
```

- deploy caas app to test authentication of the credentials imported

```bash
juju deploy cs:~kelvin.liu/kubeflow-tf-job-operator-6
```

### CODE REVIEW

**Comment by ycliuhw** [comment]
[enhance certificate auth type for k8s](https://trello.com/c/eR6tSvUq/39-enhance-certificate-auth-type-for-k8s)

**Comment by ycliuhw** [comment]
!!build!!

**Comment by ycliuhw** [comment]
!!build!!

**Comment by ycliuhw** [comment]
$$merge$$

**Comment by ycliuhw** [comment]
!!build!!

**Comment by ycliuhw** [comment]
$$merge$$

**Comment by ycliuhw** [comment]
!!build!!

**Comment by wallyworld** [comment]
$$merge$$

**Comment by ycliuhw** [comment]
$$merge$$

**Pull request merged**
