### PR TITLE
[JUJU-518] Remove CMR reliance on the model cache

### PR DESCRIPTION
**Pull request by SimonRichardson**
The following is a start to remove the model cache from various api
calls, so that we can fully understand where the model cache is actually
required.

This looks like an easy one but will require some thought on why it was
placed there in the first place.

The reason for this change is to fully remove the model cache for the new
database work lands.

## QA steps

```
$ juju bootstrap lxd src
$ juju deploy mysql
$ juju offer mysql:db
$ juju status --relations
```

```
$ juju add-model other
$ juju deploy wordpress
$ juju add-relation wordpress:db admin/default.mysql
```

### CODE REVIEW

**Comment by juanmanuel-tirado** [comment]
This is an interesting PR. Thanks for preparing it.

**Comment by wallyworld** [comment]
I agree that for this particular use case, it is likely not overly expensive to load a single application from the backend db and read its status. And the status won't change very often at all. So it's reasonable to remove the complexity of using the model cache to try and reduce the footprint of where the cache is used pending further evaluation.

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by juanmanuel-tirado** [comment]
QA steps are working.

**Comment by SimonRichardson** [comment]
$$merge$$

**Pull request merged**
