### PR TITLE
Ensure device bridging for containers happens at most once per NIC

### PR DESCRIPTION
**Pull request by manadart**
## Description of change

This patch addresses an issue with link-layer device updates caused by the asynchronous nature of container provisioning tasks.

We were querying for host network changes _before_ locking the machine to apply requisite device bridging, which meant that for multiple containers with the same space constraints it was possible to be asked to bridge the same device multiple times.

Though unnecessary, this manifested no errors for regular Ethernet devices - the bridge always gets the same MAC address as the NIC. But for VLANs, re-bridging caused a new hardware address to be generated for the bridge. This messed up device matching when the host networking configuration was re-queried and updated in state.

Locking the machine first, then querying for host changes means that we are not asked to create a bridge that already exists, and VLAN bridges will retain a static MAC address.

## QA steps

For this, I used my local virtual MAAS.
- Add a new space. _space-siksiksix_ to the fabric with MAAS DHCP.
- Add a new VLAN, _vlan-666_ to this space/fabric.
- Add a new subnet with some unused /24 CIDR to the VLAN/space.
- Choose an interface on one of the machines and add this VLAN/subnet to is as a tag, with auto-assigned IP.
- Enable DHCP relay via the untagged VLAN on the same fabric.
- Now bootstrap, ensuring that a different machine is the controller.
- Deploy this bundle:
```yaml
description: Test bundle for bridging VLANs
series: bionic
machines:
  '0':
    constraints: spaces=space-siksiksix
    series: bionic
applications:
    postgres:
        charm: "cs:postgresql-208"
        num_units: 2
        to: ["lxd:0", "lxd:0"]
        bindings:
            "": space-siksiksix
    mysql:
        charm: "cs:percona-cluster-291"
        num_units: 2
        to: ["lxd:0", "lxd:0"]
        bindings:
            "": space-siksiksix
    mongo:
        charm: "cs:mongodb-56"
        num_units: 2
        to: ["lxd:0", "lxd:0"]
        bindings:
            "": space-siksiksix
```
- Machine logs should show that the bridge was created just once:
```
machine-0: 10:30:51 DEBUG juju.machinelock acquire machine lock for provisioner (bridging devices)
machine-0: 10:30:51 DEBUG juju.machinelock machine lock acquired for provisioner (bridging devices)
machine-0: 10:30:51 DEBUG juju.container.broker.lxd bridging [{DeviceName:ens4.666 BridgeName:br-ens4-666 MACAddress:52:54:00:75:bc:e6}] devices on host "machine-0" for container "machine-0-lxd-1" with delay=0
...
machine-0: 10:31:01 INFO juju.network bridger returned nothing
machine-0: 10:31:01 INFO juju.api.common no addresses observed on interface "ens7"
machine-0: 10:31:01 INFO juju.api.common no addresses observed on interface "ens4.666"
machine-0: 10:31:01 DEBUG juju.container.broker.lxd updating observed network config for "machine-0" to
...
machine-0: 10:31:02 DEBUG juju.machinelock machine lock released for provisioner (bridging devices)
machine-0: 10:31:02 DEBUG juju.container.broker.lxd using multi-bridge networking for container "0/lxd/1"
machine-0: 10:31:02 DEBUG juju.machinelock machine lock acquired for provisioner (bridging devices)
machine-0: 10:31:02 DEBUG juju.container.broker.lxd container "machine-0-lxd-3" requires no additional bridges
machine-0: 10:31:02 DEBUG juju.machinelock machine lock released for provisioner (bridging devices)
machine-0: 10:31:02 DEBUG juju.container.broker.lxd using multi-bridge networking for container "0/lxd/3"
machine-0: 10:31:02 DEBUG juju.machinelock machine lock acquired for provisioner (bridging devices)
machine-0: 10:31:02 DEBUG juju.container.broker.lxd container "machine-0-lxd-5" requires no additional bridges
machine-0: 10:31:02 DEBUG juju.machinelock machine lock released for provisioner (bridging devices)
machine-0: 10:31:02 DEBUG juju.container.broker.lxd using multi-bridge networking for container "0/lxd/5"
machine-0: 10:31:02 DEBUG juju.machinelock machine lock acquired for provisioner (bridging devices)
machine-0: 10:31:02 DEBUG juju.container.broker.lxd container "machine-0-lxd-0" requires no additional bridges
machine-0: 10:31:02 DEBUG juju.machinelock machine lock released for provisioner (bridging devices)
machine-0: 10:31:02 DEBUG juju.container.broker.lxd using multi-bridge networking for container "0/lxd/0"
machine-0: 10:31:02 DEBUG juju.machinelock machine lock acquired for provisioner (bridging devices)
machine-0: 10:31:02 DEBUG juju.container.broker.lxd container "machine-0-lxd-2" requires no additional bridges
machine-0: 10:31:02 DEBUG juju.machinelock machine lock released for provisioner (bridging devices)
machine-0: 10:31:02 DEBUG juju.container.broker.lxd using multi-bridge networking for container "0/lxd/2"
machine-0: 10:31:02 DEBUG juju.machinelock machine lock acquired for provisioner (bridging devices)
machine-0: 10:31:02 DEBUG juju.container.broker.lxd container "machine-0-lxd-4" requires no additional bridges
machine-0: 10:31:02 DEBUG juju.machinelock machine lock released for provisioner (bridging devices)
machine-0: 10:31:02 DEBUG juju.container.broker.lxd using multi-bridge networking for container "0/lxd/4"
```
- Note that the bridged VLAN has no NAT to the outside world, so agents cannot actually deploy.
- Bug is verified fixed by ensuring that Mongo contains an IP address for the VLAN bridge, in the bound space:
```
{
        "_id" : "333bfa89-d13b-4a6d-8eb9-9d183b7658a8:m#0#d#br-ens4-666#ip#172.16.0.1",
        "model-uuid" : "333bfa89-d13b-4a6d-8eb9-9d183b7658a8",
        "device-name" : "br-ens4-666",
        "machine-id" : "0",
        "subnet-cidr" : "172.16.0.0/24",
        "config-method" : "static",
        "value" : "172.16.0.1",
        "origin" : "machine",
        "txn-revno" : NumberLong(2),
        "txn-queue" : [
                "5f48ddc0cda7630d4079374c_7a47eda9"
        ]
}
```

Without the patch, the same bundle causes the bridging to occur multiple times:
```
machine-0: 16:01:08 DEBUG juju.container.broker.lxd bridging [{DeviceName:ens7.666 BridgeName:br-ens7-666 MACAddress:52:54:00:5f:d0:15}] devices on host "machine-0" for container "machine-0-lxd-0" with delay=0
machine-0: 16:01:08 DEBUG juju.machinelock acquire machine lock for provisioner (bridging devices)
machine-0: 16:01:08 DEBUG juju.machinelock machine lock acquired for provisioner (bridging devices)
machine-0: 16:01:10 DEBUG juju.container.broker.lxd bridging [{DeviceName:ens7.666 BridgeName:br-ens7-666 MACAddress:52:54:00:5f:d0:15}] devices on host "machine-0" for container "machine-0-lxd-2" with delay=0
machine-0: 16:01:10 DEBUG juju.machinelock acquire machine lock for provisioner (bridging devices)
machine-0: 16:01:11 DEBUG juju.container.broker.lxd bridging [{DeviceName:ens7.666 BridgeName:br-ens7-666 MACAddress:52:54:00:5f:d0:15}] devices on host "machine-0" for container "machine-0-lxd-5" with delay=0
machine-0: 16:01:11 DEBUG juju.machinelock acquire machine lock for provisioner (bridging devices)
machine-0: 16:01:11 DEBUG juju.container.broker.lxd bridging [{DeviceName:ens7.666 BridgeName:br-ens7-666 MACAddress:52:54:00:5f:d0:15}] devices on host "machine-0" for container "machine-0-lxd-3" with delay=0
machine-0: 16:01:11 DEBUG juju.machinelock acquire machine lock for provisioner (bridging devices)
machine-0: 16:01:11 DEBUG juju.container.broker.lxd bridging [{DeviceName:ens7.666 BridgeName:br-ens7-666 MACAddress:52:54:00:5f:d0:15}] devices on host "machine-0" for container "machine-0-lxd-1" with delay=0
machine-0: 16:01:11 DEBUG juju.machinelock acquire machine lock for provisioner (bridging devices)
machine-0: 16:01:12 DEBUG juju.container.broker.lxd bridging [{DeviceName:ens7.666 BridgeName:br-ens7-666 MACAddress:52:54:00:5f:d0:15}] devices on host "machine-0" for container "machine-0-lxd-4" with delay=0
machine-0: 16:01:12 DEBUG juju.machinelock acquire machine lock for provisioner (bridging devices)
```

## Documentation changes

None.

## Bug reference

https://bugs.launchpad.net/juju/+bug/1891044

### CODE REVIEW

**Review by SimonRichardson — COMMENTED** [review]
The code looks good, but Q&A will be interesting!

**Comment by manadart** [comment]
[Ensure NICs are bridged at most once](https://trello.com/c/C8GduYy8/2885-ensure-nics-are-bridged-at-most-once)

**Review by jameinel — APPROVED** [review]
I'm very comfortable that we are only moving the point where we take out the shared lock.

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
