### PR TITLE
Merge 2.9 into develop

### PR DESCRIPTION
**Pull request by manadart**
Merge from 2.9 bringing forward:
- #13932 from arnodel/juju-888-remove-ping-connection-iface-method
- #13936 from ycliuhw/fix-build_push_operator_image
- #13935 from benhoyt/fix-caas-test-names
- #13930 from arnodel/juju-884-remove-allfacadeversions-connection-iface-method
- #13868 from jack-w-shaw/JUJU-801_honor_JUJU_MODEL_when_show_offer
- #13929 from benhoyt/sidecar-deploy-remove-test
- #13927 from benhoyt/update-pebble-2
- #13925 from tlm/pkg-errors
- #13926 from manadart/2.9-zones-cleanup
- #13905 from jack-w-shaw/Fix_occasional_worker_unittest_fails
- #13847 from SimonRichardson/fix-centos-deployments
- #13864 from wallyworld/azure-lighthouse
- #13924 from benhoyt/caasapplicationprovisioner-fixes
- #13920 from SimonRichardson/handle-already-exists-error
- #13915 from hmlanigan/modelconfig-no-op-txn
- #13916 from hmlanigan/cockroach-assumes
- #13919 from manadart/2.9-hook-unit-interface
- #13914 from arnodel/juju-848-move-client-facade-client-to-api-client

Conflicts:
- api/apiclient.go
- api/client/client/client.go
- api/client/client/client_test.go
- api/state_test.go
- apiserver/common/charms/charminfo_test.go
- apiserver/facades/client/application/application_test.go
- apiserver/facades/client/client/client_test.go
- cmd/juju/application/refresh.go
- cmd/juju/crossmodel/show_test.go
- cmd/juju/machine/remove.go
- cmd/juju/ssh/ssh.go
- go.mod
- go.sum
- provider/azure/config_test.go
- provider/maas/environ.go
- provider/maas/environ_whitebox_test.go
- worker/caasapplicationprovisioner/application_test.go

### CODE REVIEW

**Review by SimonRichardson — COMMENTED** [review]
Some issues with logs not being initialized at the right time.

**Comment by manadart** [comment]
!!build!!

**Review by hmlanigan — APPROVED** [review]
LGTM - but I'm unsure based on @SimonRichardson comment about log initialization.

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
