### PR TITLE
Changed the batch value.

### PR DESCRIPTION
**Pull request by perrito666**
The previously set value was still triggering the bug in some cases so I reduced it a bit more.

(Review request: http://reviews.vapour.ws/r/5605/)

### CODE REVIEW

**Comment by perrito666** [comment]
$$merge$$

**Comment by perrito666** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by perrito666** [comment]
I forgot to push the patch for the test (git add eludes me sometimes)
uploading as soon as I return home

**Comment by perrito666** [comment]
$$merge$$

**Pull request merged**
