### PR TITLE
[JUJU-1670] Update Go to v1.19

### PR DESCRIPTION
**Pull request by barrettj12**
## Changes
- update Go version to 1.19 in go.mod
- Set GOROOT before linting to fix golangci/golangci-lint#3107
- update go-macaroon-bakery to fix go-macaroon-bakery/macaroon-bakery#276
- Run Go 1.19's `go fmt` over everything (there have been some changes in 1.19)
- Rebuild facade schema to catch minor formatting change.

Most of the changes are minor formatting tweaks from gofmt. Go 1.18's `gofmt` still passes.

## QA steps

Wait for CI to pass.

### CODE REVIEW

**Comment by barrettj12** [comment]
An upstream issue in go-macaroon-bakery ([#276](https://github.com/go-macaroon-bakery/macaroon-bakery/issues/276)) is causing some unit test failures. We'll have to wait for a fix here until we can upgrade the Go version.

**Comment by barrettj12** [comment]
Waiting for go-macaroon-bakery/macaroon-bakery#277 to merge, then I will update the dependency in go.mod.

**Review by wallyworld — APPROVED** [review]

**Pull request merged**
