### PR TITLE
Remove legacy actions code and feature flag

### PR DESCRIPTION
**Pull request by wallyworld**
Remove the actions-v2 feature flag and support for legacy actions.
The new CLI (run, show-task, exec etc) replaces the old (run-action, show-action-output etc).

Most of the PR is deleted code and some test fallout.

There's 4 main chunks:
- the worker/uniter records action results as map[string]interface{} not map[string]string
- the actions facade had a bunch of deleted code
- the CLI removes compatibility support for handling legacy action results
- the old CLI is removed

## QA steps

bootstrap 2.8 controller and no feature flag
deploy a charm with actions
juju run-action someaction, use juju show-action-output to inspect
juju run --machine 0 "pwd"

upgrade controller to this PR
use juju operations and juju show-task to inspect the completed tasks
juju run someaction, use juju show-task to inspect
juju run --machine 0 "pwd"

### CODE REVIEW

**Comment by wallyworld** [comment]
[actions v2 by default, remove compatibility code](https://trello.com/c/qkzyPqxb/1287-actions-v2-by-default-remove-compatibility-code)

**Comment by hpidcock** [comment]
#12345

**Review by hpidcock — APPROVED** [review]
@wallyworld this will probably need some changes to pylibjuju but otherwise LGTM

Can you please make sure a card exists to fix pylibjuju?

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
