### PR TITLE
apiserver/metricsender: Set meter status on held batches when transmit-vendor-metrics is off

### PR DESCRIPTION
**Pull request by mattyw**
(Review request: http://reviews.vapour.ws/r/5575/)

### CODE REVIEW

**Comment by mattyw** [comment]
$$merge$$

**Comment by mattyw** [comment]
$$merge$$

**Comment by cmars** [comment]
$$merge$$, just more dirty sockets

**Comment by mattyw** [comment]
$$merge$$

**Comment by cmars** [comment]
$$merge$$

**Pull request merged**
