### PR TITLE
Allow multiple constraints flag

### PR DESCRIPTION
**Pull request by amandahla**
## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [ ] ~Comments saying why design decisions were made~
- [x] Go unit tests, with comments saying what you're testing
- [ ] ~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

```juju bootstrap --constraints "a=b" --constraints "b=c"```
```juju bootstrap --bootstrap-constraints "a=b" --bootstrap-constraints "b=c"```
```juju deploy indico --constraints "a=b" --constraints "b=c"```
```juju add-machine --constraints "a=b" --constraints "b=c"```
```juju enable-ha --constraints "a=b" --constraints "b=c"```

## Links

**Launchpad bug:** https://bugs.launchpad.net/juju/+bug/2049439
**Jira card:** JUJU-

## TODO

- [x] the "--bootstrap-constraints" flag on the bootstrap command.
- [x] the "--constraints" flag on the deploy command.
- [x] the "--constraints" flag on the add-machine command.
- [x] the "--constraints" flag on the enable-ha command.

### CODE REVIEW

**Comment by hpidcock** [comment]
@amandahla thank-you for the contribution. Could you please re-base this to 3.5 as this is a feature rather than a true bug fix.

Also I think we should strive to have consistency here, so if you could also please implement the same logic for:
- the "--bootstrap-constraints" flag on the bootstrap command.
- the "--constraints" flag on the deploy command.
- the "--constraints" flag on the add-machine command.
- the "--constraints" flag on the enable-ha command.

Please let me know if you have any questions.

**Comment by hpidcock** [comment]
> > @amandahla thank-you for the contribution. Could you please re-base this to 3.5 as this is a feature rather than a true bug fix.
> > Also I think we should strive to have consistency here, so if you could also please implement the same logic for:
> > 
> > * the "--bootstrap-constraints" flag on the bootstrap command.
> > * the "--constraints" flag on the deploy command.
> > * the "--constraints" flag on the add-machine command.
> > * the "--constraints" flag on the enable-ha command.
> > 
> > Please let me know if you have any questions.
> 
> Hi, could you please confirm? I was asked to target 3.3 here: [#17123 (review)](https://github.com/juju/juju/pull/17123#pullrequestreview-1966412418)

This will need to target 3.6 now, since 3.5 has gone to rc1. Since this is a feature, we don't typically land these in released versions. It will also need to address inconsistency it introduces between constraints flags, otherwise we can't land it.

We are happy for this feature to go ahead as it makes sense from a design perspective, just need to iron out the issues around bootstrap/deploy/add-machine/enable-ha uses of constraints.

**Comment by amandahla** [comment]
Thanks @hpidcock , the bootstrap/deploy/add-machine/enable-ha commands were updated now to support multiple constraints.

**Review by hpidcock — APPROVED** [review]
Thank-you for the patch. This is a excellent improvement.

**Pull request merged**
