### PR TITLE
3.1 to 4.x migrate job

### PR DESCRIPTION
**Pull request by hpidcock**
Convert the 2.9 migrate job into testing 3.1 migrations.

## QA steps

Migrate jobs should pass.

## Documentation changes

N/A

## Links

N/A

### CODE REVIEW

**Review by SimonRichardson — COMMENTED** [review]
This won't work until 3.1.6 is released.

**Comment by hpidcock** [comment]
> This won't work until 3.1.6 is released.

like magic

**Review by SimonRichardson — APPROVED** [review]

**Pull request merged**
