### PR TITLE
Update Pebble: enable "pebble run --verbose" logging and starting services as different user/group

### PR DESCRIPTION
**Pull request by benhoyt**
This enables the new `--verbose` flag on the `pebble run` command used by Juju for sidecar charms, which forwards service stdout and stderr through to Pebble's stdout (and adds timestamps and service name).

The latest version of Pebble also supports the user/user-id/group/group-id fields in the Pebble layer configuration for a service, allowing charmers to start services as a non-root user.

Specifically, it includes these three Pebble PRs:

* https://github.com/canonical/pebble/pull/29: Foundation work for service log buffers with pebble run -v
* https://github.com/canonical/pebble/pull/45: Don't log requests to /v1/system-info to avoid noise from health checks
* https://github.com/canonical/pebble/pull/35: Allow starting services as another user

## QA steps

Below are QA steps (for just the logging feature):

```
# Bootstrap and deploy a sidecar charm
$ juju bootstrap microk8s
$ juju add-model snappass
$ juju deploy snappass-test

# View logs using kubectl logs on the workload containers
$ microk8s.kubectl logs -n snappass snappass-test-0 redis
2021-05-21T05:02:17.373Z [pebble] Started daemon.
2021-05-21T05:02:22.268Z [pebble] GET /v1/services?names=redis 120.548µs 200
2021-05-21T05:02:22.822Z [pebble] GET /v1/services?names=redis 40.28µs 200
2021-05-21T05:02:22.823Z [pebble] POST /v1/layers 158.323µs 200
2021-05-21T05:02:22.832Z [pebble] POST /v1/services 8.953673ms 202
2021-05-21T05:02:22.868Z [redis] 15:C 21 May 2021 05:02:22.867 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
2021-05-21T05:02:22.868Z [redis] 15:C 21 May 2021 05:02:22.867 # Redis version=6.2.1, bits=64, commit=00000000, modified=0, pid=15, just started
2021-05-21T05:02:22.868Z [redis] 15:C 21 May 2021 05:02:22.867 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
2021-05-21T05:02:22.870Z [redis] 15:M 21 May 2021 05:02:22.870 * monotonic clock: POSIX clock_gettime
2021-05-21T05:02:22.871Z [redis] 15:M 21 May 2021 05:02:22.871 * Running mode=standalone, port=6379.
2021-05-21T05:02:22.871Z [redis] 15:M 21 May 2021 05:02:22.871 # Server initialized
2021-05-21T05:02:22.872Z [redis] 15:M 21 May 2021 05:02:22.872 * Ready to accept connections

$ microk8s.kubectl logs -n snappass snappass-test-0 snappass
2021-05-21T05:02:17.575Z [pebble] Started daemon.
2021-05-21T05:02:23.934Z [pebble] GET /v1/services?names=snappass 301.57µs 200
2021-05-21T05:02:23.937Z [pebble] POST /v1/layers 470.062µs 200
2021-05-21T05:02:23.950Z [pebble] POST /v1/services 11.297726ms 202
2021-05-21T05:02:24.490Z [snappass]  * Serving Flask app "snappass.main" (lazy loading)
2021-05-21T05:02:24.490Z [snappass]  * Environment: production
2021-05-21T05:02:24.490Z [snappass]    WARNING: This is a development server. Do not use it in a production deployment.
2021-05-21T05:02:24.490Z [snappass]    Use a production WSGI server instead.
2021-05-21T05:02:24.490Z [snappass]  * Debug mode: off
2021-05-21T05:02:24.503Z [snappass]  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

To ensure the user/group feature was in place, I made some local edits to the snappass-test charm to add a user and group. The user/group didn't exist in the redis container, but it was clear that Pebble was trying to set the UID/GID.

### CODE REVIEW

**Review by wallyworld — APPROVED** [review]
lgtm once real pebble upstream lands

**Comment by axinojolais** [comment]
Adding a timestamp (or even the service name) will sadly break every single application parsing logs and expecting them to be in a specific format

**Comment by benhoyt** [comment]
> Adding a timestamp (or even the service name) will sadly break every single application parsing logs and expecting them to be in a specific format

@axinojolais Thanks. Can you give an example of this in a K8s context? Would piping it through something like `cut -d' ' -f3-` work?

**Comment by axinojolais** [comment]
> @axinojolais Thanks. Can you give an example of this in a K8s context? Would piping it through something like `cut -d' ' -f3-` work?

We generally deploy filebeat on our kubernetes workers, and they ship all the logs to a graylog instance, which then parses the logs with grok filters. Sure, you can rework your grok filters, but it's one more thing that takes time and effort if you decide to use Juju.

**Comment by benhoyt** [comment]
> We generally deploy filebeat on our kubernetes workers, and they ship all the logs to a graylog instance, which then parses the logs with grok filters. Sure, you can rework your grok filters, but it's one more thing that takes time and effort if you decide to use Juju.

Good to know, thanks @axinojolais. After discussion internally, we've decided to go ahead with the current approach for 2.9.3, and revisit adding a `--raw` or similar option later.

**Comment by benhoyt** [comment]
$$merge$$

**Pull request merged**
