### PR TITLE
Upgrade api version to v1 for addmissioncontroller;

### PR DESCRIPTION
**Pull request by ycliuhw**
*Upgrade api version to v1 for addmissioncontroller;*

## Checklist

 - [ ] ~Requires a [pylibjuju](https://github.com/juju/python-libjuju) change~
 - [ ] ~Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR~
 - [ ] ~Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed~
 - [x] Comments answer the question of why design decisions were made

## QA steps

Run unit tests;

## Documentation changes

No

## Bug reference

No

### CODE REVIEW

**Comment by ycliuhw** [comment]
[Upgrade api version to v1 for addmissioncontroller](https://trello.com/c/cFWe90eN/1350-upgrade-api-version-to-v1-for-addmissioncontroller)

**Review by tlm — APPROVED** [review]
lgtm

**Comment by ycliuhw** [comment]
$$merge$$

**Comment by ycliuhw** [comment]
[Upgrade api version to v1 for addmissioncontroller](https://trello.com/c/swjOIgvu/1353-upgrade-api-version-to-v1-for-addmissioncontroller)

**Pull request merged**
