### PR TITLE
3.5 into main

### PR DESCRIPTION
**Pull request by jack-w-shaw**
Forward merge:
- https://github.com/juju/juju/pull/17050
- https://github.com/juju/juju/pull/17051
- https://github.com/juju/juju/pull/17035
- https://github.com/juju/juju/pull/17066
- https://github.com/juju/juju/pull/17071
- https://github.com/juju/juju/pull/17073
- https://github.com/juju/juju/pull/17074
- https://github.com/juju/juju/pull/17077
- https://github.com/juju/juju/pull/17078
- https://github.com/juju/juju/pull/17083
- https://github.com/juju/juju/pull/17085
- https://github.com/juju/juju/pull/17087
- https://github.com/juju/juju/pull/17088
- https://github.com/juju/juju/pull/17090
- https://github.com/juju/juju/pull/17094
- https://github.com/juju/juju/pull/17095
- https://github.com/juju/juju/pull/17096
- https://github.com/juju/juju/pull/17092
- https://github.com/juju/juju/pull/17101
- https://github.com/juju/juju/pull/17109

Conflicts:
- api/controller/crossmodelrelations/crossmodelrelations.go
- apiserver/facades/client/keymanager/keymanager.go
- apiserver/facades/client/modelupgrader/upgrader.go
- apiserver/facades/client/modelupgrader/upgrader_test.go
- cmd/modelcmd/base.go
- go.mod
- go.sum
- internal/worker/remoterelations/remoteapplicationworker.go
- internal/worker/uniter/resolver.go
- state/migration_export.go

Conflicts were mostly resolved trivially, as they were a result of contexts being added to all faacdes.

Keymanager was slightly more difficult. There are 4 unit test failures in `github.com/juju/juju/apiserver/facades/client/keymanager` which I have not been able to resolve. @Aflynn50 could you take a look?

### CODE REVIEW

**Review by wallyworld — APPROVED** [review]
Conflict resolution looks ok

**Review by Aflynn50 — APPROVED** [review]
The tests are failing because the `github.com/juju/utils/v4` package needs updating to `v4.0.2`. The keymanager tests were import `v3` in earlier versions of juju so this wasn't caught by git. I've pushed the change

**Pull request merged**
