### PR TITLE
2.3 into develop

### PR DESCRIPTION
**Pull request by jameinel**
## Description of change

Merge 2.3 into develop, resolving all of the conflicts.

This seems to pull in a lot of 2.3 patches that hadn't been brought into develop yet. Tim's log watcher change, audit logging, cloudinit-userdata.

## QA steps

No changes that weren't present in 2.3.

## Documentation changes

None.

## Bug reference

None.

### CODE REVIEW

**Comment by jameinel** [comment]
!!build!!

**Comment by jameinel** [comment]
!!build!!

**Comment by howbazaar** [comment]
Please hold off breaking develop until 2.2 is fixed for https://bugs.launchpad.net/juju/+bug/1738728

**Comment by howbazaar** [comment]
The fix is in 2.3 now I beleive. Can you refresh this merge?

**Comment by jameinel** [comment]
Yeah, I'm working on it. It seems we had a conflux of 3 changes that all
play in the same place, making it hard to resolve them. (audit logging,
moving machine agent to dependency engine, and changing how the state pool
work all touch the machine agent code.)

I might start from scratch again, but 2.3 and 2.4 are a like upset
siblings. :)

John
=:->

**Comment by howbazaar** [comment]
I say we land this ASAP and deal with any fallout :)  $$merge$$

**Comment by howbazaar** [comment]
Perhaps we should look to do this is smaller hunks?

**Comment by jameinel** [comment]
$$merge$$
self approving a 2.3 merge into develop. maybe we're finally in sync

**Pull request merged**
