### PR TITLE
Use Generated Mock for caasunitprovisioner Tests

### PR DESCRIPTION
**Pull request by manadart**
## Description of change

The custom channel-based verification of mock calls in `worker/caasunitprovisioner` are brittle and difficult to reason about. In particular, the one for `ProvisioningStatusSetter` was the source of intermittent test failures.

This replaces that mock with a generated one and adjusts test composition accordingly.

## QA steps

Run `worker/caasunitprovisioner` tests in a loop.

## Documentation changes

None.

## Bug reference

https://bugs.launchpad.net/juju/+bug/1873241

### CODE REVIEW

**Comment by manadart** [comment]
[Fix Intermittent Test Failure in caasunitprovisioner](https://trello.com/c/pNWgMJtZ/2490-fix-intermittent-test-failure-in-caasunitprovisioner)

**Comment by hmlanigan** [comment]
fixing the build failure: worker/caasunitprovisioner/worker_test.go:47:22: undefined: "github.com/juju/juju/worker/caasunitprovisioner".MockProvisioningStatusSetter

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
unrelated intermittent fails in github.com/juju/juju/cmd/juju/commands

$$merge$$

**Comment by manadart** [comment]
Derp. Thanks for adding that.

**Pull request merged**
