### PR TITLE
CI: Sync 2.3 acceptancetests from develop.

### PR DESCRIPTION
**Pull request by Veebers**
This includes:
  - Improved use of --existing argument
  - Addition of spaces test
  - Improved README.md docs
  - Updated requirements.txt

### CODE REVIEW

**Comment by nskaggs** [comment]
We'll want to pull #8327 in with this.

**Comment by Veebers** [comment]
!!veebers!!

**Comment by Veebers** [comment]
!!veebers!!

**Comment by Veebers** [comment]
!!veebers!!

**Comment by Veebers** [comment]
!!veebers!!

**Comment by Veebers** [comment]
!!veebers!!

**Comment by Veebers** [comment]
!!veebers!!

**Comment by Veebers** [comment]
!!veebers!!

**Comment by Veebers** [comment]
!!veebers!!

**Comment by Veebers** [comment]
!!veebers!!

**Comment by Veebers** [comment]
!!veebers!!

**Comment by Veebers** [comment]
#veebers#

**Comment by Veebers** [comment]
!!build!!

**Comment by Veebers** [comment]
!!build!!

**Comment by Veebers** [comment]
!!build!!

**Comment by Veebers** [comment]
!!build!!

**Comment by jameinel** [comment]
Is there something missing for us to merge this?

**Comment by nskaggs** [comment]
$$merge$$

**Pull request merged**
