### PR TITLE
update assess_upgrade.py. 

### PR DESCRIPTION
**Pull request by hmlanigan**
## Description of change

media wiki appears to be an unmaintained charm and is causing issues in the success of assess_upgrade.py.  replace with keystone which is maintained.

## QA steps

1. Setup up a snap version of juju at the beta channel
2. Setup environment per acceptancetests/Readme.md
3. Run with:  ./assess_upgrade.py lxd $GOPATH/bin/juju /tmp/artifacts testme --stable-juju-bin /snap/juju/current/bin/juju

### CODE REVIEW

**Comment by babbageclunk** [comment]
Running this failed with `HookFailedError: ('keystone/0', 'hook failed: "shared-db-relation-changed" for percona-cluster:shared-db')`

Digging into the keystone unit logs, I can see this:
```
2018-12-13 02:23:38 DEBUG shared-db-relation-changed Traceback (most recent call last):
2018-12-13 02:23:38 DEBUG shared-db-relation-changed   File "/var/lib/juju/agents/unit-keystone-0/charm/hooks/shared-db-relation-changed", line 882, in <module>
2018-12-13 02:23:38 DEBUG shared-db-relation-changed     main()
2018-12-13 02:23:38 DEBUG shared-db-relation-changed   File "/var/lib/juju/agents/unit-keystone-0/charm/hooks/shared-db-relation-changed", line 875, in main
2018-12-13 02:23:38 DEBUG shared-db-relation-changed     hooks.execute(sys.argv)
2018-12-13 02:23:38 DEBUG shared-db-relation-changed   File "/var/lib/juju/agents/unit-keystone-0/charm/charmhelpers/core/hookenv.py", line 909, in execute
2018-12-13 02:23:38 DEBUG shared-db-relation-changed     self._hooks[hook_name]()
2018-12-13 02:23:38 DEBUG shared-db-relation-changed   File "/var/lib/juju/agents/unit-keystone-0/charm/charmhelpers/contrib/openstack/utils.py", line 1479, in wrapped_f
2018-12-13 02:23:38 DEBUG shared-db-relation-changed     stopstart, restart_functions)
2018-12-13 02:23:38 DEBUG shared-db-relation-changed   File "/var/lib/juju/agents/unit-keystone-0/charm/charmhelpers/core/host.py", line 739, in restart_on_change_helper
2018-12-13 02:23:38 DEBUG shared-db-relation-changed     r = lambda_f()
2018-12-13 02:23:38 DEBUG shared-db-relation-changed   File "/var/lib/juju/agents/unit-keystone-0/charm/charmhelpers/contrib/openstack/utils.py", line 1478, in <lambda>
2018-12-13 02:23:38 DEBUG shared-db-relation-changed     (lambda: f(*args, **kwargs)), __restart_map_cache['cache'],
2018-12-13 02:23:38 DEBUG shared-db-relation-changed   File "/var/lib/juju/agents/unit-keystone-0/charm/hooks/shared-db-relation-changed", line 391, in db_changed
2018-12-13 02:23:38 DEBUG shared-db-relation-changed     leader_init_db_if_ready(use_current_context=True)
2018-12-13 02:23:38 DEBUG shared-db-relation-changed   File "/var/lib/juju/agents/unit-keystone-0/charm/hooks/shared-db-relation-changed", line 373, in leader_init_db_if_ready
2018-12-13 02:23:38 DEBUG shared-db-relation-changed     migrate_database()
2018-12-13 02:23:38 DEBUG shared-db-relation-changed   File "/var/lib/juju/agents/unit-keystone-0/charm/charmhelpers/core/decorators.py", line 40, in _retry_on_exception_inner_2
2018-12-13 02:23:38 DEBUG shared-db-relation-changed     return f(*args, **kwargs)
2018-12-13 02:23:38 DEBUG shared-db-relation-changed   File "/var/lib/juju/agents/unit-keystone-0/charm/hooks/keystone_utils.py", line 756, in migrate_database
2018-12-13 02:23:38 DEBUG shared-db-relation-changed     subprocess.check_output(cmd)
2018-12-13 02:23:38 DEBUG shared-db-relation-changed   File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
2018-12-13 02:23:38 DEBUG shared-db-relation-changed     **kwargs).stdout
2018-12-13 02:23:38 DEBUG shared-db-relation-changed   File "/usr/lib/python3.5/subprocess.py", line 708, in run
2018-12-13 02:23:38 DEBUG shared-db-relation-changed     output=stdout, stderr=stderr)
2018-12-13 02:23:38 DEBUG shared-db-relation-changed subprocess.CalledProcessError: Command '['sudo', '-u', 'keystone', 'keystone-manage', 'db_sync']' returned non-zero exit status 1
```

But I don't know why that command is failing. (I have to work on something else now before my flight, but  I'll pick this up again after that unless someone else has.)

**Comment by hmlanigan** [comment]
@babbageclunk I'll try to pick back up if I can figure out the core dump from make install-deps

**Comment by hmlanigan** [comment]
I couldn't run the test, because i didn't have the python-simplestreams pkg installed.  The test works past the issue found by @babbageclunk, verification of the two charm succeeds.  However I was unable to run the test correctly for the rc1 binaries to be used so the upgrade failed: "upgrader" manifold worker returned unexpected error: no matching agent binaries available  

./assess_upgrade.py lxd $GOPATH/bin/juju /tmp/artifacts testme-thursday --stable-juju-bin /snap/juju/current/bin/juju --stable-juju-agent /snap/juju/current/bin/jujud --devel-juju-agent $GOPATH/bin/jujud

**Comment by hmlanigan** [comment]
$$merge$$

**Pull request merged**
