### PR TITLE
Merge 2.5 into develop

### PR DESCRIPTION
**Pull request by hmlanigan**
## Description

Merge 2.5 into develop:
- Merge pull request #9755 
- Merge pull request #9744
- Merge pull request #9752 
- Merge pull request #9713 
- Merge pull request #9708
- Merge pull request #9768
- Merge pull request #9754 
- Merge pull request #9756 
- Merge pull request #9770 

## QA steps

bootstrap and deploy

### CODE REVIEW

**Comment by hmlanigan** [comment]
Hit 181500: apiclient_test.go:792: apiclientSuite.TestOpenTimeoutAffectsDial failing intermittently.

Updated status_internal_test.go to handle the differences in test between two branches.

**Comment by hmlanigan** [comment]
Hit 1817142: CAASProvisionerSuite.TestUpdateApplicationsUnitsWithStorage failed with: mismatch at top level: length mismatch, 2 vs 3

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
Hit 1817142: CAASProvisionerSuite.TestUpdateApplicationsUnitsWithStorage failed with: mismatch at top level: length mismatch, 2 vs 3

Hit 1817207: firewallerSuite.TestWatch failed with: watcher sent unexpected change: (_, true) 

Hit 1793276: Intermittent Failure: TestDowngradeOnMasterWhenOtherControllerDoesntStartUpgrade

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
$$merge$$

**Pull request merged**
