### PR TITLE
revert: move session token login provider

### PR DESCRIPTION
**Pull request by kian99**
This PR partially reverts a change introduced in #17451, where CLI specific login providers were moved to an internal package. The problem with this change is that JAAS uses/imports the session token login provider so I've reverted the move.

Currently the only internal login provider is the `tryInOrderLoginProvider` kept in `cmd/internal/loginprovider`.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [ ] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

### CODE REVIEW

**Comment by kian99** [comment]
cc @SimonRichardson

**Comment by SimonRichardson** [comment]
> The problem with this change is that JAAS uses/imports the session token login provider so I've reverted the move.

I did ask about this in the original PR.

You don't need to revert it, just move it to a better location.

**Comment by kian99** [comment]
Yeah it's my bad, I forgot that we use it in JAAS, it's only used for tests.
Any preferences on where to move it to?

**Comment by SimonRichardson** [comment]
> Any preferences on where to move it to?

Move it to `api/common/loginprovider` or copy and duplicate the code to JAAS.

**Review by SimonRichardson — APPROVED** [review]

**Pull request merged**
