### PR TITLE
[dev] Remove joyent provider

### PR DESCRIPTION
**Pull request by achilleasa**
## Description of change

This PR removes support for the joyent provider from the upcoming 2.9 release.

### CODE REVIEW

**Comment by achilleasa** [comment]
NOTE: I haven't been able to remove the joyent entry from https://github.com/juju/juju/blob/develop/environs/imagedownloads/testdata/index.sjson#L6-L49 as it breaks the hash signature check. Any ideas how we can update that?

**Review by hpidcock — APPROVED** [review]
LGTM

**Comment by wallyworld** [comment]
> NOTE: I haven't been able to remove the joyent entry from https://github.com/juju/juju/blob/develop/environs/imagedownloads/testdata/index.sjson#L6-L49 as it breaks the hash signature check. Any ideas how we can update that?

There's a set of keys defined in environs/simplestreams/testing/testing.go (see SignedMetadataPrivateKey etc)
The json would have been signed with that key using gpg --clearsign

**Comment by achilleasa** [comment]
!!build!! (windows box)

**Comment by hmlanigan** [comment]
@achilleasa I wonder how this will impact the clouds.yaml users can update via `juju update-public-clouds`?

**Comment by achilleasa** [comment]
!!build!!

**Comment by achilleasa** [comment]
!!build!! (DNS lookup failure in test)

**Comment by achilleasa** [comment]
I have also removed the joyent bits from https://streams.canonical.com/juju/public-clouds.syaml

**Comment by achilleasa** [comment]
!!build!! (timeout reading cloud info)

**Comment by achilleasa** [comment]
$$merge$$

**Pull request merged**
