### PR TITLE
romulus/show-budget: Demoted some error messages (that can happen in normal operation) to debug

### PR DESCRIPTION
**Pull request by mattyw**
These errors have no effect on the usefulness of the command, and are confusing, I've demoted them as appropriate

### CODE REVIEW

**Comment by mattyw** [comment]
!!build!!

**Comment by cmars** [comment]
!!build!!

**Comment by cmars** [comment]
LGTM. Obligatory QA steps: 1. Deploy a charm with allocation, destroy the model, run show-budget, confirm debug level for log messages. 1. Deploy a charm with allocation, destroy the controller machine outside Juju or take down network interface to make it inaccessible, confirm warning level for log messages.

**Comment by mattyw** [comment]
$$merge$$

**Pull request merged**
