### PR TITLE
Fix wrong DNS name in certificates issued to HA controllers.

### PR DESCRIPTION
**Pull request by Pekkari**
PR 7748 rebased upon 2.2.

lp:1710886.

Signed-off-by: José Pekkarinen <jose.pekkarinen@canonical.com>

### CODE REVIEW

**Comment by Pekkari** [comment]
!!retry!!

**Comment by Pekkari** [comment]
!!build!!

**Comment by Pekkari** [comment]
!!build!!

**Comment by nskaggs** [comment]
@Pekkari looks like some unit test failures.

**Comment by Pekkari** [comment]
Yep, though I cannot find any relation to the change itself, it seems to be problems connecting to the api, and this is fixing connectivity to db. I'll try to retrigger to see what is going on. Thanks @nskaggs!

**Comment by Pekkari** [comment]
!!build!!

**Comment by Pekkari** [comment]
!!build!!

**Comment by Pekkari** [comment]
!!build!!

**Comment by Pekkari** [comment]
Hummm... so actually the name local is needed in the certificate, why?

**Comment by howbazaar** [comment]
I have landed a branch that renames local to localhost, and updates the test.

**Comment by Pekkari** [comment]
So, now Tim Penhey fix this. Congrats Tim!

**Pull request closed without merging**
