### PR TITLE
Rename space and subnet services into NetworkService

### PR DESCRIPTION
**Pull request by nvinuesa**
~This small patch adds the subnet method to provide the subnet service via the service provider, along with the mocks that needed to be regenerated.~

~_Note: the subnet service needs to be injected in the apiserver so that's why we need this change._~

EDIT: This patch has changed in order to have the `SpaceService` and `SubnetService` merged into a single service named after the domain `Network`, thus the service factory will now only provide `Network()`. 

In the apiserver, only one service will be injected thus simplifying it's usage.

## Checklist

- [X] Code style: imports ordered, good names, simple structure, etc
- [ ] ~Comments saying why design decisions were made~
- [ ] ~Go unit tests, with comments saying what you're testing~
- [ ] ~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- [ ] ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

Bootstrap and deploy:

```
juju bootstrap localhost c
juju add-model m
juju deploy ubuntu
```

## Links

**Jira card:** JUJU-5759

### CODE REVIEW

**Review by cderici — APPROVED** [review]

**Comment by SimonRichardson** [comment]
We should change this to be in the network domain tbh.

**Comment by nvinuesa** [comment]
@SimonRichardson 
> We should change this to be in the network domain tbh.

What do you mean? That we should have only one service constructor `NetworkService` instead of `SpaceService` and `SubnetService`?

**Review by cderici — APPROVED** [review]
This LGTM, and I agree that consolidating them into one looks better 👍

**Review by manadart — APPROVED** [review]

**Pull request merged**
