### PR TITLE
Fix manually provisioned machines machine-status.

### PR DESCRIPTION
**Pull request by wupeka**
## Description of change
Manually provisioned machines had machine-status stuck in 'Pending'. This PR fixes this issue.

## QA steps
Set up a model, add a manually provisioned machine - juju add-machine ssh:1.2.3.4, after it's jujued see if juju show-machine shows machine-status as 'running'.

## Documentation changes
None

## Bug reference
https://bugs.launchpad.net/juju/+bug/1678981

### CODE REVIEW

**Comment by wupeka** [comment]
$$merge$$

**Comment by wupeka** [comment]
$$mergeagain$$

**Comment by wupeka** [comment]
Merge request issued by mistake, TIL that jujubot will accept merge requests for unapproved PRs

**Comment by howbazaar** [comment]
$$merge$$

**Comment by wupeka** [comment]
$$merge$$

**Comment by wupeka** [comment]
$$merge$$

**Comment by wupeka** [comment]
$$doit$$

**Comment by wupeka** [comment]
!!test!!

**Comment by wupeka** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
Build failed: Tests failed

This is not being picked up because bot already wanted to merge but no failure message was issued. The above message should re-set the world \o/

**Comment by anastasiamac** [comment]
$$merge$$

**Pull request merged**
