### PR TITLE
move coretesting clock to jujutesting

### PR DESCRIPTION
**Pull request by jrwren**
(Review request: http://reviews.vapour.ws/r/5220/)

### CODE REVIEW

**Comment by jrwren** [comment]
$$merge$$

**Comment by jrwren** [comment]
$$merge$$

**Comment by jrwren** [comment]
$$merge$$

**Comment by jrwren** [comment]
$$merge$$

**Comment by jrwren** [comment]
$$merge$$

**Comment by rogpeppe** [comment]
$$merge$$

**Comment by rogpeppe** [comment]
$$merge$$

**Comment by jrwren** [comment]
$$merge$$

**Comment by jrwren** [comment]
$$merge$$

**Pull request merged**
