### PR TITLE
Remove the rest of the targetted CI scripts, add back remote.py

### PR DESCRIPTION
**Pull request by nskaggs**
Remove the rest of the targetted CI scripts, add back remote.py. This is a follow-on to #8464 .

This will unbreak the functional test failures we currently see.

### CODE REVIEW

**Comment by nskaggs** [comment]
[Remove juju-ci-tools dependency in cleanup scripts, fix infastructure failures @ functional tests](https://trello.com/c/nZJBp9Gc/126-remove-juju-ci-tools-dependency-in-cleanup-scripts-fix-infastructure-failures-functional-tests)

**Comment by Veebers** [comment]
I take it the clean_*.py scripts are removed here because they will be pulled in by the 'fix' on the pr#32?

LGTM.

**Comment by nskaggs** [comment]
Yes, the "fix" in CI is functional, but needs design decisions. Either way, we don't want them in-tree.

**Comment by nskaggs** [comment]
$$merge$$

**Pull request merged**
