### PR TITLE
[JUJU-3813] Add lunar to supported series

### PR DESCRIPTION
**Pull request by barrettj12**
Adds a new constant to `core/series/supported.go` for lunar.

### CODE REVIEW

**Comment by barrettj12** [comment]
Have to rebase on top of #15624.

**Comment by juanmanuel-tirado** [comment]
check-multi-juju is broken. Some additional changes have to be done:
```
09:06:14 expected call at /home/jenkins/go/src/github.com/juju/juju/apiserver/facades/client/modelupgrader/upgrader_test.go:213 has the wrong number of arguments. Got: 21, want: 20
09:06:14 expected call at /home/jenkins/go/src/github.com/juju/juju/apiserver/facades/client/modelupgrader/upgrader_test.go:208 has the wrong number of arguments. Got: 21, want: 12
```

**Review by hpidcock — APPROVED** [review]

**Pull request merged**
