### PR TITLE
Merge 3.5 to main

### PR DESCRIPTION
**Pull request by hpidcock**
An attempt to merge 3.5 to main...

Conflicts:
    - Makefile
    - api/client/resources/client.go
    - api/client/resources/client_upload_test.go
    - apiserver/facades/client/client/perm_test.go
    - caas/kubernetes/provider/klog.go
    - cmd/containeragent/unit/errors.go
    - cmd/containeragent/unit/manifolds.go
    - cmd/juju/application/deploy_test.go
    - cmd/juju/application/deployer/charm.go
    - cmd/juju/application/utils/interface.go
    - cmd/juju/application/utils/mocks/charmresource_mock.go
    - cmd/juju/application/utils/utils.go
    - cmd/juju/resource/deploy_test.go
    - cmd/jujud-controller/agent/agent_test.go
    - cmd/jujud-controller/agent/controllercharm.go
    - cmd/jujud-controller/agent/engine_test.go
    - cmd/jujud-controller/agent/machine.go
    - cmd/jujud-controller/agent/machine/manifolds.go
    - cmd/jujud-controller/agent/machine/manifolds_test.go
    - cmd/jujud-controller/agent/machine/startupmanifold.go
    - cmd/jujud-controller/agent/machine/startupmanifold_test.go
    - cmd/jujud-controller/agent/machine/stateflag.go
    - cmd/jujud-controller/agent/machine_test.go
    - cmd/jujud-controller/agent/mocks/machine_mock.go
    - cmd/jujud-controller/agent/model/errors_test.go
    - cmd/jujud-controller/agent/model/manifolds_test.go
    - cmd/jujud-controller/agent/package_test.go
    - cmd/jujud-controller/agent/util_test.go
    - cmd/jujud-controller/main.go
    - cmd/jujud-controller/util/stateflag.go
    - cmd/jujud/agent/engine_test.go
    - cmd/jujud/agent/machine.go
    - cmd/jujud/agent/machine/manifolds.go
    - cmd/jujud/agent/machine/manifolds_test.go
    - cmd/jujud/agent/machine/stateflag.go
    - cmd/jujud/agent/machine_test.go
    - cmd/jujud/agent/util_test.go
    - cmd/package_test.go
    - controller/config.go
    - controller/config_test.go
    - controller/configschema.go
    - go.mod
    - go.sum
    - internal/worker/lease/doc.go
    - internal/worker/uniter/actions/resolver.go
    - internal/worker/uniter/actions/resolver_test.go
    - scripts/win-installer/setup.iss
    - snap/snapcraft.yaml
    - state/controller_test.go
    - version/version.go

### CODE REVIEW

**Review by nvinuesa — APPROVED** [review]
LGTM, thanks!

**Review by SimonRichardson — APPROVED** [review]
Also looks clean.

**Pull request merged**
