### PR TITLE
Merge maas-spaces-multi-nic-containers-with-master

### PR DESCRIPTION
**Pull request by cherylj**
This branch is ready to be merged.  It had a bless on its last CI run: http://reports.vapour.ws/releases/3825

And has no outstanding bugs against it:  https://bugs.launchpad.net/juju-core/maas-spaces-multi-nic-containers-with-master/+bugs

### CODE REVIEW

**Comment by bz2** [comment]
LGTM.

**Comment by frobware** [comment]
See my comments in email about some unit test removals and other "things".

**Comment by dimitern** [comment]
I agree a few disabled tests need fixing, and the removal of ntpdate should be fixed (we already discussed this - e.g. rebooting the node rather than applying the modified /e/n/i).
In any case, it's better to address these once we merge.

**Comment by dimitern** [comment]
Let's :shipit:

**Comment by dimitern** [comment]
$$merge$$

**Pull request merged**
