### PR TITLE
Update to the latest txn dependency

### PR DESCRIPTION
**Pull request by SimonRichardson**
## Description of change

The following is a very simple update to the txn dependency.

### CODE REVIEW

**Comment by SimonRichardson** [comment]
https://trello.com/c/JvXkZXHn/1010-bump-txn-dependency

**Comment by SimonRichardson** [comment]
> worker_test.go:281: WorkerSuite.TestNoLeaderTimeout
> https://pastebin.canonical.com/p/N88mb8VmNZ/

!!build!!

**Comment by jameinel** [comment]
is this still pending? I thought it landed in a different patch

**Comment by SimonRichardson** [comment]
@jameinel I backed it out for 2.5.1 so we didn't have to work on these changes as well, as txn also affected 2.5 branch. I'll sort this out early next week, so that we can have everything up to date.

**Pull request closed without merging**
