### PR TITLE
Merge 2.9

### PR DESCRIPTION
**Pull request by wallyworld**
Merge 2.9 with these PRs:

#12566 Make `coreos/go-systemd' buildable on windows
#12594 [Charmhub] - `Juju info` updates based on upcoming api changes.
#12596 Pebble support with *-workload-ready hook.
#12602 Static analysis checks
#12604 [2.9] Do not attempt to set proxy settings for windows/centos workloads
#12605  [2.9] Use positional arguments for azure clients
#12607 Clean up model migration code
#12608 Allow bundle to update existing offers
#12609 EC2 fix panic
#12614 Errcheck linter fixes
#12615 Allow bundle to update existing offers
#12617 Fixes permission for model operator.
#12619  Add set-series integration test
#12620  Fix asserts used when finalising an action
#12621 Relocates DNS and resolve.conf parsing from network to core/network
#12622 Move NetworkConfigSource from api/common to core/network
#12623  Indirection for network config sourced addresses
#12627 Ensure relation units
#12629 Record why a cloud credential gets marked invalid and expose via show-model, status
#12630 Fix double upgraded
#12633  Update how channel is created in ApplicationsInfo.
#12634 Fix uniter loop when a relation is removed out of bandge case.
#12637 Improve maas cli output handling in acceptance tests
#12638 Bundle export with channel
#12641  Bundle diff output with charm url names
#12643  Expose charm channel in juju status
#12644 Fix service type translation for k8s applications
#12647 Fix acceptance test bug in get_uptime
#12650 Ensure we normalize the charm url in bundle handler
#12651 Use python 3.6 compat fix for handling maas cli output
#12652  Use python 3.6 compatible way to capture subprocess stdout/err output
#12653  missing container status of creating
#12654 Move 2.8.10 upgrade step to 2.8.9

```
# Conflicts:
#       api/backups/restore.go
#       apiserver/facades/client/backups/restore.go
#       caas/kubernetes/provider/operator.go
#       cloudconfig/podcfg/image.go
#       cmd/containeragent/main_nix.go
#       cmd/containeragent/main_test.go
#       cmd/containeragent/unit/agent.go
#       cmd/containeragent/unit/agent_test.go
#       cmd/juju/action/run.go
#       cmd/juju/action/showoutput.go
#       cmd/juju/commands/exec.go
#       cmd/juju/commands/exec_test.go
#       go.mod
#       go.sum
#       juju/testing/conn.go
#       state/action_test.go
#       state/applicationoffers.go
#       state/backups/files.go
#       state/backups/restore_test.go
#       state/upgrades.go
#       worker/machineactions/worker.go
#       worker/restorewatcher/manifold.go
#       worker/restorewatcher/worker.go
#       worker/uniter/runner/jujuc/mocks/context_relation_mock.go
#       worker/uniter/util_test.go
```

## QA steps

See PRs

### CODE REVIEW

**Comment by hpidcock** [comment]
```
cmd/juju/application/config_test.go:18:2: imported and not used: "gopkg.in/yaml.v2" as yaml
cmd/juju/application/config_test.go:183:15: undefined: goyaml
cmd/juju/application/config_test.go:186:9: undefined: goyaml
cmd/juju/application/config_test.go:190:9: undefined: goyaml
```

**Comment by wallyworld** [comment]
> ```
> cmd/juju/application/config_test.go:18:2: imported and not used: "gopkg.in/yaml.v2" as yaml
> cmd/juju/application/config_test.go:183:15: undefined: goyaml
> cmd/juju/application/config_test.go:186:9: undefined: goyaml
> cmd/juju/application/config_test.go:190:9: undefined: goyaml
> ```

Fixed, goimport mess up.

**Comment by wallyworld** [comment]
!!build!!

**Review by hpidcock — APPROVED** [review]

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
[merge 2.9 into develop](https://trello.com/c/AqVKX5q0/1403-merge-29-into-develop)

**Pull request merged**
