### PR TITLE
Progress bar test susceptible to timing failures

### PR DESCRIPTION
**Pull request by SimonRichardson**
The progress bar tests are susceptible to timing failures if running on
slow CI boxes. The fix is to pass in a clock to prevent that from
happening, so when we run the tests we can pass in our own mock clock
which we can target exactly the time we want to test against.

## QA steps

Tests pass, along with the following still working!

```sh
$ export JUJU_DEV_FEATURE_FLAGS=charm-hub
$ juju bootstrap lxd test
$ juju download ubuntu
```

### CODE REVIEW

**Review by achilleasa — APPROVED** [review]
Ah. Sorry I missed the use of the real clock in the tests.

**Comment by SimonRichardson** [comment]
> Ah. Sorry I missed the use of the real clock in the tests.

Which makes me think that upstream doesn't test this on slow machines or how have they never run into this before :thinking:

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
$$merge$$

**Pull request merged**
