### PR TITLE
Update links in README

### PR DESCRIPTION
**Pull request by schoettkr**
Update to fix dead link to Juju Tutorials and add link to developer How-To guides.

## Checklist

~- [ ] Code style: imports ordered, good names, simple structure, etc~
~- [ ] Comments saying why design decisions were made~
~- [ ] Go unit tests, with comments saying what you're testing~
~- [ ] [Integration tests](https://github.com/juju/juju/tree/develop/tests), with comments saying what you're testing~
~- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps
N/A

### CODE REVIEW

**Comment by SimonRichardson** [comment]
Thanks for the contribution, @schoettkr, but you need to sign the CLA (launchpad account) for us to land this.

**Comment by schoettkr** [comment]
Thanks for the ping @SimonRichardson, just signed the CLA - wasn't sure who to put under `Please add the Canonical Project Manager or contact` so I put your name, hope that's fine.

**Review by barrettj12 — APPROVED** [review]

**Pull request merged**
