### PR TITLE
Unwind jujud part2

### PR DESCRIPTION
**Pull request by SimonRichardson**
This removes all jujud imports from the outside of the cmd/jujud package. Most
of the code is just relocated to the `agent/engine` package, which makes
refactoring the code really simple. I'm unsure why this wasn't done earlier tbh.

There is a question about if the code in agent should directly depend on the `api/base`
package. It feels like a slightly wrong inversion. I'd rather relocate some of the interfaces
in `api/base` to `core/api` and force a nice separation of concerns.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing

## QA steps

```sh
$ make install
```

### CODE REVIEW

**Review by wallyworld — APPROVED** [review]
Would be good to clean up the `api/base` dependencies also, as you suggest.

**Comment by SimonRichardson** [comment]
> FAIL: uniter_test.go:2806: uniterSuite.TestWatchRelationUnits

**Pull request merged**
