### PR TITLE
Align scale and rev columns right.

### PR DESCRIPTION
**Pull request by howbazaar**
Also only shows n/m for scale when they are different.
Highlights different numbers with color.

Fixes http://pad.lv/1620062

### CODE REVIEW

**Comment by howbazaar** [comment]
FFS, RB didn't pick it up: http://imgur.com/a/grXtj  <-- QA

**Comment by wallyworld** [comment]
LGTM

**Comment by wallyworld** [comment]
$$merge$$

**Comment by howbazaar** [comment]
$$merge$$

**Pull request merged**
