### PR TITLE
Merge 2.8

### PR DESCRIPTION
**Pull request by wallyworld**
Merge 2.8

#12827 Unsubscribe from hub when closing state pool
#12829 Correct default bootstrap-timeout value displayed in help.
#12840 Constraint tags can be used for pod affinity

## QA steps

See PRs

### CODE REVIEW

**Review by jameinel — APPROVED** [review]
rubber stamp based on conflict less merge of 2.8 into 2.9

**Review by benhoyt — APPROVED** [review]

**Comment by wallyworld** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Pull request merged**
