### PR TITLE
fix juju find with no query specified.

### PR DESCRIPTION
**Pull request by hmlanigan**
Adding a `q=` to a charmhub find query causes a 403 error to be returned.  Can be caused by `juju find`, which expects a result of all, rather than `juju find ubuntu`.  Ensure we never add a query key for charmhub requests if the value provided is empty.

## QA steps

```console
$ export JUJU_DEV_FEATURE_FLAGS="charm-hub"
$ juju bootstrap localhost testme
$ juju add-model seven --config charm-hub-url="https://api.staging.snapcraft.io"
$ juju find
...              <- returns values to scroll off the screen, not an error.
$ juju find ubuntu
Name                     Bundle  Version  Supports                                        Publisher              Summary
ubuntu                   -       11       xenial,bionic,artful,cosmic,disco,trusty,focal  charmers               A pristine Ubuntu Server
ubuntu-repository-cache  -       4        xenial,trusty                                   cloud-images           Ubuntu archive caching proxy mirror
ubuntu-devenv            -       11       bionic,xenial,trusty                            kwmonroe               Simple Ubuntu development and test environment
ubuntu-qa                -       3        focal,bionic,xenial                             Canonical Juju QA Bot  juju-qa version of the ubuntu charm.

```

### CODE REVIEW

**Review by SimonRichardson — APPROVED** [review]

**Comment by hmlanigan** [comment]
!!build!!

**Comment by hmlanigan** [comment]
!!build!!

**Comment by hmlanigan** [comment]
The windows UT is aborting in check merge.

**Comment by hmlanigan** [comment]
$$merge$$

**Pull request merged**
