### PR TITLE
Static analysis checks

### PR DESCRIPTION
**Pull request by SimonRichardson**
This PR introduces golangcl-lint for linting tasks so it makes it easier to iterate
over the linters we have. The good thing about golangci-lint is that if you're
iterating locally, then the use of golangci-lint makes it really easy to lint
continuously using the local caching mechanism.

Additionally, this PR also introduces deadcode elimination to remove any code
that isn't being obviously used.

---

Both github and `make static-analysis` use precisely the same workflow, which should
mean that nobody has to change their setup. By using the config file, it should be
also possible to get their IDE to pick that up and ensure that every modification is also
linted correctly.

## Q&A Steps

Tests pass.

### CODE REVIEW

**Review by manadart — APPROVED** [review]
That sweet, sweet, red.

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
$$merge$$

```
16:31:02 /bin/sh: 1: go: not found
16:31:02 Installing go-1.14 snap
16:31:41 error: cannot install "go": cannot query the store for updates: got unexpected
16:31:41        HTTP status code 503 via POST to
16:31:41        "https://api.snapcraft.io/v2/snaps/refresh"
```

**Comment by petevg** [comment]
Failure to dollar dollar merge seems to have been a github infra issue rather than an issue w/ the code. I went ahead and merged this.

**Pull request merged**
