### PR TITLE
Remove core/description and use external repo.

### PR DESCRIPTION
**Pull request by howbazaar**
Use the new extraced juju/description package.

### CODE REVIEW

**Comment by howbazaar** [comment]
$$merge$$

**Comment by jameinel** [comment]
The general rule there is to have a test that the two are in sync. It's ok
for tests to cross pollinate as long as the code itself doesn't.

Didn't we have one that would fail if you added/changed a database doc
without updating the description?

John
=:->

**Comment by babbageclunk** [comment]
Ugh, I guess that means the changes I'm making to add remote applications to the description need to happen there now.

**Comment by howbazaar** [comment]
$$windows-mongo$$

**Comment by howbazaar** [comment]
We have tests in the state package to make sure things are migrated. The serialisation format is separate.

**Comment by howbazaar** [comment]
$$intermittent-windows-again$$

**Pull request merged**
