### PR TITLE
[JUJU-823] Add log label CMR.

### PR DESCRIPTION
**Pull request by hmlanigan**
Cross model relations is a complex item in juju. Add a log label tohelp simplify the knowledge necessary to debug it.

Other loggers may be added in the future.  Starting with the ones referenced in https://bugs.launchpad.net/juju/+bug/1965590/comments/2. 

## QA steps

```console
$ juju bootstrap localhost testme
$ juju model-config "logging-config=#cmr=TRACE;<root>=INFO" -m controller
$ juju deploy mysql
$ juju offer mysql:db
$ juju add-model one
$ juju deploy wordpress --series bionic --force
$ juju add-relation wordpress admin/default.mysql
$ juju debug-log -m controller --include-label cmr
... 
machine-0: 13:32:55 DEBUG juju.apiserver.common.crossmodel cmr changed unit tag for unit id 0 is unit-remote-068c6055b6ad4a4c8b9fe9e264003c27-0
...
```

### CODE REVIEW

**Comment by hmlanigan** [comment]
@wallyworld are there any other loggers which would be handy to add to the CMR label at this time?

**Review by SimonRichardson — APPROVED** [review]

**Comment by hmlanigan** [comment]
Github issues - https://jenkins.juju.canonical.com/job/github-make-check-juju/14817/ was green.

**Comment by hmlanigan** [comment]
!!build!!

**Review by wallyworld — APPROVED** [review]

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
force push to kick off the gihub actions to allow for merge

**Comment by hmlanigan** [comment]
$$merge$$

**Pull request merged**
