### PR TITLE
build: silence makefile when there is no lxdbr0 present

### PR DESCRIPTION
**Pull request by tych0**
Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

(Review request: http://reviews.vapour.ws/r/4777/)

### CODE REVIEW

**Comment by tych0** [comment]
$$merge$$

**Comment by mitechie** [comment]
$$merge$$

**Comment by mitechie** [comment]
$$jfdi$$

**Comment by anastasiamac** [comment]
$$__JFDI__$$

**Pull request merged**
