### PR TITLE
Disable debinterfaces tests on Windows

### PR DESCRIPTION
**Pull request by wupeka**
## Please provide the following details to expedite Pull Request review:
Disable debinterfaces activation tests on Windows, those are Linux specific. 
Fix debinterfaces parsing tests on Windows.

## Description of change
Tests were failing on Windows

## QA steps
Tests for debinterfaces should pass on Windows.

### CODE REVIEW

**Comment by wupeka** [comment]
!!Test!!

**Comment by wupeka** [comment]
I don't think SkipIfWindowsBug is appropriate here because it's not a bug, we are skipping some tests this way.
parser_tests are fixed - those should work on Windows without problem now (although I don't have environment to test it)

**Comment by babbageclunk** [comment]
$$merge$$

**Comment by babbageclunk** [comment]
Merging  because @wupeka asked me to on IRC.

**Pull request merged**
