### PR TITLE
#1489477 Add M4 instance types to AWS where available

### PR DESCRIPTION
**Pull request by buggtb**
https://bugs.launchpad.net/juju-core/+bug/1489477

Went through the available AWS regions and added M4 instance types and USD costs.

### CODE REVIEW

**Comment by mitechie** [comment]
@perrito666 can you please take a look at this and help @buggtb get this in for 2.0 please? Thanks!

**Comment by perrito666** [comment]
Thank you so much for this contribution, LGTM $$merge$$

**Comment by perrito666** [comment]
This will be merged as soon as master is unlocked.

**Comment by wallyworld** [comment]
$$__JFDI__$$

**Comment by wallyworld** [comment]
This work can't land because go fmt is sad. Please run go fmt and push

**Comment by wallyworld** [comment]
$$__JFDI__$$

**Pull request merged**
