### PR TITLE
Fix data races in various unit tests

### PR DESCRIPTION
**Pull request by benhoyt**
Fix the following data races reported by `go test -race` in CI:

* Concurrent access of fakeContext.deployed set in worker/deployer tests
* Overwriting global http.DefaultClient's Jar field in cmd/jujud/agent tests (fixed in juju/http repo)

This fixes the actual "WARNING: DATA RACE" issues reported by https://jenkins.juju.canonical.com/job/RunUnittests-race-amd64/ ... though I think there are other issues with the unittests-race job that aren't actual data races.

See related fix: https://github.com/juju/juju/pull/12159

### CODE REVIEW

**Review by hpidcock — APPROVED** [review]
LGTM thank-you

**Comment by benhoyt** [comment]
!!build!!

**Comment by benhoyt** [comment]
!!build!!

**Comment by benhoyt** [comment]
$$merge$$

**Pull request merged**
