### PR TITLE
chore: merge idempotent secrets from 3.6

### PR DESCRIPTION
**Pull request by wallyworld**
This merges https://github.com/juju/juju/pull/17677  from 3.6.

Because part of the implementation was done in mongo in 3.6, it needs to be redone in dqlite. This PR doesn't do that yet, so the stored checksum is empty for now. Secrets still works but without idempotency. A follow up PR will add in the replacement code.

Conflicts were essentially because code has been removed from facades in 4.0, so accept the 4.0 version.
Also because  worker code has moved around a bit.

```
# Conflicts:
#       api/agent/secretsmanager/client.go
#       api/client/secrets/client.go
#       api/client/secrets/client_test.go
#       api/common/secretsdrain/client.go
#       api/common/secretsdrain/client_test.go
#       apiserver/common/secrets/secrets.go
#       apiserver/common/secrets/secrets_test.go
#       apiserver/facades/agent/secretsmanager/secrets.go
#       apiserver/facades/agent/secretsmanager/secrets_test.go
#       apiserver/facades/client/secrets/secrets.go
#       apiserver/facades/client/secrets/secrets_test.go
#       apiserver/facades/schema.json
#       cmd/juju/secrets/show_test.go
#       core/secrets/secret.go
#       go.mod
#       go.sum
#       internal/worker/secretsdrainworker/worker_test.go
#       internal/worker/uniter/runner/context/context.go
#       internal/worker/uniter/runner/context/context_test.go
#       internal/worker/uniter/runner/testing/utils.go
#       state/secrets.go
#       state/secrets_test.go
#       worker/uniter/runner/context/flush_test.go
#       worker/uniter/runner/context/util_test.go
#
```

## QA steps

bootstrap
add and update a secret secret
add and update a charm secret

## Links

Launchpad bug: https://bugs.launchpad.net/juju/+bug/2069238

Jira card: [JUJU-6225](https://warthogs.atlassian.net/browse/JUJU-6225)

[JUJU-6225]: https://warthogs.atlassian.net/browse/JUJU-6225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by barrettj12** [comment]
Unfortunately I think these commits will have to be re-merged.

Git still thinks that the commits from your PR #17677 do not exist in this branch - see
https://github.com/wallyworld/juju/compare/merge-idempotent-secrets...juju:juju:3.6

This is because cherry-picking changes the commit hash, and Git cannot match the commits in this PR with the commits on 3.6.

So even after this PR merges, those commits will still have to be merged through to main.

**Comment by hpidcock** [comment]
> Unfortunately I think these commits will have to be re-merged.
> 
> Git still thinks that the commits from your PR #17677 do not exist in this branch - see [wallyworld/juju@merge-idempotent-secrets...juju:juju:3.6](https://github.com/wallyworld/juju/compare/merge-idempotent-secrets...juju:juju:3.6)
> 
> This is because cherry-picking changes the commit hash, and Git cannot match the commits in this PR with the commits on 3.6.
> 
> So even after this PR merges, those commits will still have to be merged through to main.

This is a cherry pick and new changes. There will need to be a follow-up merge to resolve anything else.

**Comment by wallyworld** [comment]
> > Unfortunately I think these commits will have to be re-merged.
> > Git still thinks that the commits from your PR #17677 do not exist in this branch - see [wallyworld/juju@merge-idempotent-secrets...juju:juju:3.6](https://github.com/wallyworld/juju/compare/merge-idempotent-secrets...juju:juju:3.6)
> > This is because cherry-picking changes the commit hash, and Git cannot match the commits in this PR with the commits on 3.6.
> > So even after this PR merges, those commits will still have to be merged through to main.
> 
> This is a cherry pick and new changes. There will need to be a follow-up merge to resolve anything else.

rebased seamlessly on tip of main with no conflicts

**Review by hpidcock — APPROVED** [review]

**Pull request merged**
