### PR TITLE
Merge 25 into 26 on 21/06.

### PR DESCRIPTION
**Pull request by anastasiamac**
Fairly simple merge, includes:
https://github.com/juju/juju/pull/10341
https://github.com/juju/juju/pull/10354

### CODE REVIEW

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
FCO  juju.testing mgo.go:216 failed to start mongo: mongod failed to listen on port 35982

**Comment by anastasiamac** [comment]
$$merge$$

**Pull request merged**
