### PR TITLE
Bootstrap focal if requested

### PR DESCRIPTION
**Pull request by SimonRichardson**
## Description of change

This will attempt to bootstrap focal if you provide BOOTSTRAP_SERIES.
If you attempt to reuse a bootstrapped controller that doesn't match
series you're after it will attempt to bootstrap another in the
right series.

I've not tested this but should work in theory.

## QA steps

```sh
BOOTSTRAP_SERIES=focal ./main.sh deploy
```

### CODE REVIEW

**Comment by hmlanigan** [comment]
I attempted to fix the static analysis failure by adding the double quotes.  However, while the bootstrap command looked correct, it failed silently.  Running the bootstrap command externally works correctly.

Output with double quotes:
https://pastebin.canonical.com/p/wdMT2dyG8Y/

**Comment by hmlanigan** [comment]
QA:
BOOTSTRAP_SERIES=focal ./main.sh deploy. <- good
BOOTSTRAP_SERIES=focal ./main.sh -V -l friday  deploy <- fail still tried to use the friday controller, where friday was bootstrapped with bionic.

**Comment by hmlanigan** [comment]
QA: 
- ./main.sh -V -S focal deploy <-- good.
- ./main.sh -V -S focal -l friday  deploy. <- fail still tried to use the friday controller, where friday was bootstrapped with bionic.  even after fixing fail with controller reuse above

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
$$merge$$

> 16:01:35 Build timed out (after 60 minutes). Marking the build as failed.

**Pull request merged**
