### PR TITLE
Fixed most windows tests for go 1.6

### PR DESCRIPTION
**Pull request by perrito666**
(Review request: http://reviews.vapour.ws/r/4687/)

### CODE REVIEW

**Comment by perrito666** [comment]
$$merge$$

**Comment by perrito666** [comment]
$$merge$$

**Comment by perrito666** [comment]
$$merge$$

**Comment by dimitern** [comment]
@perrito666 Have you seen the issue I posted on RB?

**Comment by perrito666** [comment]
yes, too late albeit, since this actually works ill prepare a second pr later to patch it.

**Pull request merged**
