### PR TITLE
Don't release resources until all current requests are complete.

### PR DESCRIPTION
**Pull request by howbazaar**
If a websocket connection is closed while the login is in process, the rpc package was releasing the apiHandler resources before all the current requests were finished. If one of those requests would add resources, like an agent pinger, these would be leaked.

This branch changes the connection code to wait for all current requests to be finished before it kills the root object (which calls StopAll on the resources).

## Bug reference

Other part of the fix for https://bugs.launchpad.net/juju/+bug/1731745

### CODE REVIEW

**Comment by howbazaar** [comment]
At the top of the method the connection is marked as closing, which rejects any new connections.

A pinger is started for each successful login before it writes the login response. It is the writing of the login repsonse that fails.

Although this does have me wondering about other watchers, watchers where there aren't any current events. Perhaps we need to keep the Kill before the waitgroup wait as well as after?

**Comment by jameinel** [comment]
[test Tim's branch](https://trello.com/c/6aGBj1bh/8-test-tims-branch)

**Comment by jameinel** [comment]
This seems better, but it isn't quite sufficient. I seem to be stable at:
> db.presence.beings.aggregate([{$group: {_id: {$concat: [{$substr: ["$_id", 0, 4]}, "-", "$key"]}, count: {$sum: 1}}}, {$sort: {count: -1}}, {$limit: 10}])
{ "_id" : "fe59-m#1", "count" : 28 }
{ "_id" : "fe59-m#0", "count" : 28 }
{ "_id" : "fe59-m#2", "count" : 28 }

And while its great that it isn't growing, those numbers should be closer to 2 maybe 4.

**Comment by jameinel** [comment]
I see the counts vary a little bit, going up to 30, and then back down to 24. We should certainly seek to understand where those extra 6 temporary ones are coming from. Something *is* cleaning them up eventually, but why are we creating them. But at the same time, that's still about 20 too many baseline.

**Comment by jameinel** [comment]
$$merge$$

**Comment by nskaggs** [comment]
$$merge$$

**Comment by jameinel** [comment]
Running with development tip I see:
> db.presence.beings.aggregate([{$group: {_id: {$concat: [{$substr: ["$_id", 0, 4]}, "-", "$key"]}, count: {$sum: 1}}}, {$sort: {count: -1}}, {$limit: 10}])
{ "_id" : "44e8-m#1", "count" : 4 }
{ "_id" : "44e8-m#2", "count" : 4 }
{ "_id" : "44e8-m#0", "count" : 4 }

So it appears that we've properly stabilized.
I'll try adding a bit of load and see if that stays steady.

**Pull request merged**
