### PR TITLE
Merge 2.9

### PR DESCRIPTION
**Pull request by wallyworld**
Merge 2.9

#12800  Fix/enable rbac
#12768 Use system instead of core for writing proxy settings.
#12799 shfmt tests files
#12806 Fix logging
#12802 Bump deps to always use juju mgo pkg and ensure we use collections package
#12813 Add architecuture to url for UploadCharm during migration.
#12811 Bump juju/testing dep
#12819 Fix agent lookup on upgraded 2.8 controllers
#12809 Validate units and applications
#12555 Standardize a number of error messages and help text
#12817 Use bootstrap-timeout for controller service retry
#12821 Ensure openstack unit tests pass on non amd64 hosts
#12818 Use charm-base as the repository for charm oci base images.
#12824 Fix CI upgrade tests and non amd64 unit tests

```
# Conflicts:
#       apiserver/facades/client/application/application.go
#       apiserver/facades/client/application/application_test.go
#       apiserver/facades/client/application/mock_test.go
#       cmd/jujud/agent/agenttest/agent.go
#       go.mod
#       mongo/mongo.go
#       service/snap/snap.go
#       service/snap/snap_test.go
#       tests/suites/controller/mongo_memory_profile.sh
#       tests/suites/deploy/deploy_charms.sh
#       tests/suites/expose_ec2/expose_app.sh
#       tests/suites/hooks/dispatch.sh
#       tests/suites/hooktools/state_tools.sh
#       tests/suites/network/network_health.sh
#       tests/suites/relations/relation_data_exchange.sh
#       tests/suites/relations/relation_list_app.sh
#       tests/suites/spaces_ec2/util.sh
```

## QA steps

See PRs

### CODE REVIEW

**Review by benhoyt — APPROVED** [review]
LGTM

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
