### PR TITLE
Remove obsolete raft code and cleanup go.mod and old +build directives

### PR DESCRIPTION
**Pull request by wallyworld**
The `core/raftlease` package is obsolete so is removed. It was referenced by the lease introspection worker, so has been ripped out of there also, as no valid metrics are available until the introspection is re-implemented on top of the new db backed leases.

Also cleanup unneeded go.mod overrides, and fix some imports.

And remove obsolete `+build` directives.

## Checklist

- [X] Code style: imports ordered, good names, simple structure, etc
- [X] Comments saying why design decisions were made
- [X] Go unit tests, with comments saying what you're testing
- ~[ ] [Integration tests](https://github.com/juju/juju/tree/develop/tests), with comments saying what you're testing~
- ~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

bootstrap 
ssh to controller
juju_goroutines

### CODE REVIEW

**Review by SimonRichardson — CHANGES_REQUESTED** [review]
>  As a driveby, start using the latest upstream dustin/humanize release - this adds a space between the number and the unit, eg120 MiB

I'm going to be that person and say I want at least 2 PRs. This isn't a driveby, it isn't changing a typo or fixing one word, this is changing something in a distinct way. We may want to revert one over another, so it should be two PRs.

**Comment by wallyworld** [comment]
> > As a driveby, start using the latest upstream dustin/humanize release - this adds a space between the number and the unit, eg120 MiB
> 
> I'm going to be that person and say I want at least 2 PRs. This isn't a driveby, it isn't changing a typo or fixing one word, this is changing something in a distinct way. We may want to revert one over another, so it should be two PRs.

Reverted the humanize dep change

**Review by SimonRichardson — APPROVED** [review]

**Pull request merged**
