### PR TITLE
Merge service to application

### PR DESCRIPTION
**Pull request by wallyworld**
Merge service-to-application rename feature branch.

### CODE REVIEW

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$__JFDI__$$

**Comment by rogpeppe** [comment]
Just saying - it would be really nice if this branch was rebased before landing so every
commit has a review and a meaningful message. Commits like "Fix test" and "Back out some
changes to make the diff smaller" don't really belong in the mainline history that we might
end up bisecting over at some point, IMHO.

**Comment by wallyworld** [comment]
You and I differ on this - history is history and should not be messed with.
With the correct git log commands you can hide such detail by default. eg use
--first-parent. It's personal preference where it will be hard to get agreement
across the team since I know folks on both sides of the argument.

**Comment by rogpeppe** [comment]
--first-parent is useful but doesn't help when there's a merged feature branch.

Is there a set of flags I can use on git log that will show me all the code-reviewed
commits, including those inside feature branches that were later merged?

Also, this does seem like something we should try to standardise on across the board.

I'll raise the subject in the mailing list.

**Pull request merged**
