### PR TITLE
DB logging infrastructure

### PR DESCRIPTION
**Pull request by mjs**
This branch includes:

* Low-level functionality for writing logs to MongoDB
* A new logsink API for agents to use to report logs to the state servers
* A new dblogpruner worker for removing old stored logs 

(Review request: http://reviews.vapour.ws/r/1174/)

### CODE REVIEW

**Comment by howbazaar** [comment]
All work on db-log as been reviewed already.

$$merge$$

**Comment by howbazaar** [comment]
$$merge$$

**Comment by mjs** [comment]
$$merge$$

**Comment by mjs** [comment]
$$damn-substrate$$

**Comment by mjs** [comment]
$$puh-leeeeeese$$

**Pull request merged**
