### PR TITLE
Stop using pkg/errors in juju code

### PR DESCRIPTION
**Pull request by natefinch**
goimports betrayed me

QA: run go test in cmd/juju/cloud

### CODE REVIEW

**Comment by voidspace** [comment]
LGTM

**Comment by natefinch** [comment]
Note that due to transitive dependencies, this is still required in dependencies.tsv, but juju code itself should not be using it.

**Comment by natefinch** [comment]
$$merge$$

**Comment by natefinch** [comment]
$$merge$$

**Pull request merged**
