### PR TITLE
Add machine status to juju status --format=tabular

### PR DESCRIPTION
**Pull request by wupeka**
## Description of change
Add Machine status field (e.g. downloading LXD image) to juju status --format=tabular

## QA steps
Bootstrap controller, deploy an application and check that 'juju status --format=tabular' shows the Message for the machine (same as machine-status in format=yaml)

## Documentation changes
There is a change in CLI output

## Bug reference
https://bugs.launchpad.net/juju/+bug/1557914

### CODE REVIEW

**Comment by wupeka** [comment]
!!test!!

**Comment by wupeka** [comment]
!!test!!

**Comment by wupeka** [comment]
!!retry!!

**Comment by wupeka** [comment]
!!retry!!

**Comment by wupeka** [comment]
!!retry!!

**Comment by wupeka** [comment]
!!retry!!

**Comment by wupeka** [comment]
!!retest!!

**Comment by wupeka** [comment]
!!test!!

**Comment by wupeka** [comment]
!!test!!

**Comment by wupeka** [comment]
!!retry!!

**Comment by wupeka** [comment]
!!retest!!

**Comment by wupeka** [comment]
I've checked it with lxd provider before and it looked nice, now I've rechecked with AWS and it also looks sane. Merging

**Comment by wupeka** [comment]
$$merge$$

**Comment by wupeka** [comment]
$$merge$$

**Comment by wupeka** [comment]
$$merge$$

**Comment by jameinel** [comment]
Btw this is a user visible change so we should make sure it ends up in
release notes.

John
=:->

**Comment by jameinel** [comment]
Also, I seem to recall there is a big where if Juju cannot provision a
machine the machine record goes into "error" but that gets overridden by
agent status of "down". There is code that intentionally overrides machine
status under certain circumstances but I believe it shouldn't for "error"
status. That might be really good to fix along with this patch.

John
=:->

**Comment by anastasiamac** [comment]
@juju/docs Please take note of changes in CLI output \o/

**Pull request merged**
