### PR TITLE
Added extra provisioning status information to ec2

### PR DESCRIPTION
**Pull request by perrito666**
Adds extra machine status information to the ec2 provisioning process.

(Review request: http://reviews.vapour.ws/r/4423/)

### CODE REVIEW

**Comment by hoenirvili** [comment]
Could this point now to ```juju:develop``` or close?

**Comment by jameinel** [comment]
I like the idea of this, but it needs to be fixed for conflicts.

**Comment by perrito666** [comment]
@jameinel conflicts fixed, ptal again

**Comment by perrito666** [comment]
!!retry!!

**Comment by perrito666** [comment]
!!reretry!!

**Comment by hoenirvili** [comment]
@jameinel +1 for the "starting machine attempt 1/3" thing.

**Comment by perrito666** [comment]
Sadly we dont know, attempts are time based so its "as many as we can fit in that timeframe"

**Comment by perrito666** [comment]
$$merge$$

**Pull request merged**
