### PR TITLE
Update goose dependency

### PR DESCRIPTION
**Pull request by axw**
Fixes https://bugs.launchpad.net/juju/+bug/1636648

### CODE REVIEW

**Comment by axw** [comment]
> Are there QA steps that don't involve standing up a new openstack?

Nope. just ran tests and bootstrapped.

**Comment by axw** [comment]
$$merge$$

**Comment by bz2** [comment]
$$retry$$

**Comment by bz2** [comment]
$$retry$$

Unhappy mongo in upgradeSuite.TestLoginsDuringUpgrade on trusty tests.

**Comment by bz2** [comment]
$$stilldirtysockets$$

**Comment by bz2** [comment]
$$lxdthistime$$

13:10:38 ERROR juju.tools.lxdclient client_instance.go:278 while removing instance "juju-4480c5-0": Failed to destroy ZFS filesystem: cannot open 'lxd-pool/containers/juju-4480c5-0': dataset does not exist

13:10:38 ERROR juju.cmd.juju.commands bootstrap.go:1021 error cleaning up: removing hosted model instances: some instance removals failed: [juju-4480c5-0]
13:10:38 ERROR cmd supercommand.go:458 unable to contact api server after 1 attempts: unable to connect to API: websocket.Dial wss://10.0.8.52:17070/model/55a032b4-6c36-4d44-8d00-a59f67219509/api: x509: certificate signed by unknown authority
13:10:38 DEBUG cmd supercommand.go:459 (error details: [{github.com/juju/juju/cmd/juju/common/controller.go:164: unable to contact api server after 1 attempts} {github.com/juju/juju/cmd/juju/common/controller.go:88: } {github.com/juju/juju/juju/api.go:77: } {github.com/juju/juju/api/apiclient.go:185: } {github.com/juju/juju/api/apiclient.go:464: } {github.com/juju/juju/api/apiclient.go:494: } {github.com/juju/juju/api/apiclient.go:540: unable to connect to API} {websocket.Dial wss://10.0.8.52:17070/model/55a032b4-6c36-4d44-8d00-a59f67219509/api: x509: certificate signed by unknown authority}])
2016-11-03 13:10:38 ERROR Command '('juju', '--debug', 'bootstrap', '--constraints', 'mem=2G', 'lxd/localhost', 'merge-juju-lxd', '--config', '/tmp/tmpQmUbGT.yaml', '--default-model', 'merge-juju-lxd', '--agent-version', '2.1-beta1', '--bootstrap-series', 'xenial')' returned non-zero exit status 1
Traceback (most recent call last):

**Pull request merged**
