### PR TITLE
[JUJU-764] Compute base channel for centos

### PR DESCRIPTION
**Pull request by SimonRichardson**
The following allows centos charm authors to use just the series number
for the series instead of centos7. The code is backwards compatible with
older style series naming. Because we pushed this to the edges for
normalisation, the data stored in the database is correct. It reports it
as centos7 and we don't leak the implementation information outside of
the charmhub repository.

## QA steps

```sh
$ juju bootstrap aws test
$ juju deploy slurmdbd --series=centos7
Located charm "slurmdbd" in charm-hub, revision 18
Deploying "slurmdbd" from charm-hub charm "slurmdbd", revision 18 in channel stable
$ juju status
```

Notice: charm URL and origin are stored correctly for what __juju__ needs. 

```sh
$ juju mongo
juju:PRIMARY> db.applications.find().pretty()
{
        "_id" : "74bb1e61-39ef-4604-865c-7a73db2107db:slurmdbd",
        "name" : "slurmdbd",
        "model-uuid" : "74bb1e61-39ef-4604-865c-7a73db2107db",
        "series" : "centos7",
        "subordinate" : false,
        "charmurl" : "ch:amd64/centos7/slurmdbd-18",
        "cs-channel" : "stable",
        "charm-origin" : {
                "source" : "charm-hub",
                "type" : "charm",
                "id" : "4HKauFz7wnQVmpl0Zb8Z6is7JeDlsWvK",
                "hash" : "7d666cd89c9b2cb566caf9e830ab153f86f1edd15389250b99fcb83b36827a08",
                "revision" : 18,
                "channel" : {
                        "risk" : "stable"
                },
                "platform" : {
                        "architecture" : "amd64",
                        "os" : "centos",
                        "series" : "centos7"
                }
        },
        "charmmodifiedversion" : 0,
        "forcecharm" : false,
        "life" : 0,
        "unitcount" : 1,
        "relationcount" : 1,
        "minunits" : 0,
        "txn-revno" : NumberLong(2),
        "metric-credentials" : BinData(0,""),
        "exposed" : false,
        "scale" : 0,
        "passwordhash" : "",
        "txn-queue" : [
                "62331927a08d2f3e1586cd07_6eba802f"
        ]
}
```

### CODE REVIEW

**Review by manadart — COMMENTED** [review]
This fixes it for the Slurm charms that we saw, but what about others that still exist with "centos7" as the channel?

**Review by manadart — APPROVED** [review]
It works.

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by heitorPB** [comment]
Is this already available in the `2.9/edge` snap?

**Comment by heitorPB** [comment]
I have a controller with 2.9.28 (from 2.9/candidate). I refreshed the snap to 2.9/edge and still can't deploy centos charms, from CharmHub and from a locally built charm I get the same errors as before.

**Comment by heitorPB** [comment]
After bootstraping a new controller with the snap from 2.9/edge, I can deploy centos7 charms from charmhub, but not from a locally built charms:

```bash

$ juju deploy slurmd --series centos7 --debug
17:16:02 INFO  juju.cmd supercommand.go:56 running juju [2.9.29 2b414f4ad76499e361f4a4a9b92d44f1008f2d60 gc go1.17.8]
17:16:02 DEBUG juju.cmd supercommand.go:57   args: []string{"/snap/juju/18773/bin/juju", "deploy", "slurmd", "--series", "centos7", "--debug"}
17:16:02 INFO  juju.juju api.go:78 connecting to API addresses: [10.107.185.250:17070]
17:16:02 DEBUG juju.api apiclient.go:1153 successfully dialed "wss://10.107.185.250:17070/api"
17:16:02 INFO  juju.api apiclient.go:688 connection established to "wss://10.107.185.250:17070/api"
17:16:02 INFO  juju.juju api.go:78 connecting to API addresses: [10.107.185.250:17070]
17:16:02 DEBUG juju.api apiclient.go:1153 successfully dialed "wss://10.107.185.250:17070/model/bbb50bd0-2d11-4046-80af-424eea9452a9/api"
17:16:02 INFO  juju.api apiclient.go:688 connection established to "wss://10.107.185.250:17070/model/bbb50bd0-2d11-4046-80af-424eea9452a9/api"
17:16:02 DEBUG juju.cmd.juju.application.deployer deployer.go:387 cannot interpret as local charm: file does not exist
17:16:02 DEBUG juju.cmd.juju.application.deployer deployer.go:207 cannot interpret as a redeployment of a local charm from the controller
17:16:03 DEBUG juju.cmd.juju.application.store charmadapter.go:139 cannot interpret as charmstore bundle: centos7 (series) != "bundle"
17:16:03 INFO  cmd charm.go:443 Preparing to deploy "slurmd" from the charmhub
17:16:04 INFO  juju.cmd.juju.application.deployer series_selector.go:141 with the user specified series "centos7"
17:16:09 INFO  cmd charm.go:522 Located charm "slurmd" in charm-hub, revision 29
17:16:09 INFO  cmd charm.go:236 Deploying "slurmd" from charm-hub charm "slurmd", revision 29 in channel stable
17:16:09 DEBUG juju.api monitor.go:35 RPC connection died
17:16:09 DEBUG juju.api monitor.go:35 RPC connection died
17:16:09 INFO  cmd supercommand.go:544 command finished


$ juju deploy ./slurmd_ubuntu-20.04-amd64_centos-7-amd64.charm --series centos7 --debug asdf
17:16:17 INFO  juju.cmd supercommand.go:56 running juju [2.9.29 2b414f4ad76499e361f4a4a9b92d44f1008f2d60 gc go1.17.8]
17:16:17 DEBUG juju.cmd supercommand.go:57   args: []string{"/snap/juju/18773/bin/juju", "deploy", "./slurmd_ubuntu-20.04-amd64_centos-7-amd64.charm", "--series", "centos7", "--debug", "asdf"}
17:16:17 INFO  juju.juju api.go:78 connecting to API addresses: [10.107.185.250:17070]
17:16:17 DEBUG juju.api apiclient.go:1153 successfully dialed "wss://10.107.185.250:17070/api"
17:16:17 INFO  juju.api apiclient.go:688 connection established to "wss://10.107.185.250:17070/api"
17:16:17 INFO  juju.juju api.go:78 connecting to API addresses: [10.107.185.250:17070]
17:16:17 DEBUG juju.api apiclient.go:1153 successfully dialed "wss://10.107.185.250:17070/model/bbb50bd0-2d11-4046-80af-424eea9452a9/api"
17:16:17 INFO  juju.api apiclient.go:688 connection established to "wss://10.107.185.250:17070/model/bbb50bd0-2d11-4046-80af-424eea9452a9/api"
17:16:17 DEBUG juju.core.charm computedseries.go:27 series "focal, panther" for charm "slurmd" with format 2, Kubernetes false
17:16:17 DEBUG juju.api monitor.go:35 RPC connection died
17:16:17 DEBUG juju.api monitor.go:35 RPC connection died
ERROR series "centos7" not supported by charm, supported series are: focal,panther
17:16:17 DEBUG cmd supercommand.go:537 error stack:
series "centos7" not supported by charm, supported series are: focal,panther
/build/snapcraft-juju-75838bb53a71a92bfcabc0864992a355/parts/juju/src/cmd/juju/application/deployer/deployer.go:363:
/build/snapcraft-juju-75838bb53a71a92bfcabc0864992a355/parts/juju/src/cmd/juju/application/deployer/deployer.go:620:
/build/snapcraft-juju-75838bb53a71a92bfcabc0864992a355/parts/juju/src/cmd/juju/application/deployer/deployer.go:364:
/build/snapcraft-juju-75838bb53a71a92bfcabc0864992a355/parts/juju/src/cmd/juju/application/deployer/deployer.go:70:
/build/snapcraft-juju-75838bb53a71a92bfcabc0864992a355/parts/juju/src/cmd/juju/application/deploy.go:864:
```

**Comment by heitorPB** [comment]
Found the issue: we removed the deprecated `series` in the `metadata.yaml` file. The slurm-charms from `latest/stable` have the `series` in the metadata file, but the new ones (from `latest/edge` and from our repo) do not have this deprecated metadata, as suggested in [LP#1964815](https://bugs.launchpad.net/juju/+bug/1964815/comments/16).

This PR fixes the deploy if the centos charms have the `series` in the metadata.

**Pull request merged**
