### PR TITLE
Small cleanups to EnvWorkerManager

### PR DESCRIPTION
**Pull request by jameinel**
This is a small bit of changes to improve cleanups wrt EnvWorkerManager and its tests.

1) Instead of calling m.tomb.Done() after m.tomb.Kill() use a defer m.tomb.Done(). I audited the code and the other places use the defer syntax. This lets a panic() enforce that the tomb will be finished.

2) change waitOrPanic into waitOrFatal(c, ...) which lets us just call c.Fatal rather than triggering a panic inside the test suite.

3) Stop requiring a Dying() as part of the Runner interface just to allow EnvWorkerManager to shutdown if its runner is stopping. Other code that does something similary uses:
  go func() { my.tomb.Kill(dependent.Wait()) }
So that if the thing I depend on stops, I will kill my own tomb.
This lets us shrink the interface, and it makes this code conform to the other changes.

4) Add defer m.runner.Kill() as well, which ensures that even if our loop exits because of a different error, we make sure to shut down our runner.

Associated with this is a test which actually exercises that code path by injecting an error. It is is a bit more coupled to implementation than I'd like, but I don't think injecting errors to test error handling can be done a lot better than that.

(Review request: http://reviews.vapour.ws/r/949/)

### CODE REVIEW

**Comment by jameinel** [comment]
$$merge$$

**Comment by jameinel** [comment]
TestAddRemoveSet strikes again...
$$merge$$

**Comment by dimitern** [comment]
@jameinel should this still land?

**Comment by jameinel** [comment]
yes. there appear to be some intermittent failures, and I didn't want to add more, so I'm trying to sort through it.

**Comment by jameinel** [comment]
$$merge$$

I can reproduce the intermittent failures on master, so I don't think it is caused by this branch.

**Pull request merged**
