### PR TITLE
Remove KVM broker in favour of LXD virtual-machines broker

### PR DESCRIPTION
**Pull request by SimonRichardson**
This removes the KVM broker in favour of the LXD virtual-machine support. As LXD VMs are based on QEMU, which you get via libvirt, they're analogous to each other. Although, fundamentally, the LXD VMs have a more opinionated setup; based on a more modern layout (Q35) with UEFI and SecureBoot by default and driven by a simpler experience. All the LXD VMs are virtio based, the same as KVM.

It's expected that the LXD broker will take over from the KVM broker for VM support. This will be a breaking change for 4.0, so it is expected that models with KVM VMs will be redeployed to LXD VMs before finally migrating to 4.0. Additional work could be done to make this more painless, for now though, an extra hop will be required.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing

## QA steps

This is removal of code, I'd just expect that bootstrapping works.

## Documentation changes

Dropping support for KVM broker.

## Links

**Jira card:** JUJU-

### CODE REVIEW

**Comment by SimonRichardson** [comment]
As the code was not self-contained and leaked out among lots of tests, I'm marking this PR as do-not-merge until we've ironed out all the locations for the mock/test leakages.

**Review by hmlanigan — COMMENTED** [review]
Random thoughts taking a quick look at the code.

What is the plan for KVM in the providers? I see it in the code, but haven't dived deep. GCE, MAAS, Oracle etc.

We still need the MachineStartup worker, but MachineAgent setupContainerSupport can be removed I think, though a call to m.SetSupportedContainers is needed for LXD.

When do you plan to add a step in Migration to prevent KVM containers from being moved over? - And will have to update existing machines to remove KVM from supported containers.

**Comment by SimonRichardson** [comment]
> When do you plan to add a step in Migration to prevent KVM containers from being moved over? - And will have to update existing machines to remove KVM from supported containers.

They can't move over, because the machine description will fail on model export.

**Comment by hmlanigan** [comment]
> > What is the plan for KVM in the providers
> 
> They're just not supported.

More code to remove then?

> 
> > When do you plan to add a step in Migration to prevent KVM containers from being moved over? - And will have to update existing machines to remove KVM from supported containers.
> 
> They can't move over, because the machine description will fail on model export.

Can we do a check in the 4.0 client then on migration? Or maybe it's the 3.last - there are migration pre-checks.

**Comment by SimonRichardson** [comment]
> More code to remove then?

Nope.

> Can we do a check in the 4.0 client then on migration? Or maybe it's the 3.last - there are migration pre-checks.

Happy to do that in a follow up pr. This one is already too big.

**Review by hmlanigan — APPROVED** [review]
LGTM

**Pull request merged**
