### PR TITLE
Introduce charm.v5-unstable.

### PR DESCRIPTION
**Pull request by frankban**
This mechanical branch updates the charm package to the
v5-unstable version. The legacy charm store code is
adjusted as required.
This is a preparatory work for the migration to the new
charm store API v4.

(Review request: http://reviews.vapour.ws/r/1236/)

### CODE REVIEW

**Comment by cmars** [comment]
$$merge$$

**Comment by frankban** [comment]
This failure seems due to missing charm.v5-unstable testing dependencies in the dependency file.
Testing dependencies are not included transitively in godeps.
This could be solved by a temporary workaround, e.g.
```go
var _ = charmstore.NewServer
``` 
in a testing package.
We are going to import charmstore.v4 for tests anyway.

**Comment by cmars** [comment]
@frankban You'll need to add the missing dependencies to Juju's `dependencies.tsv` in order for this to land. Use `godeps -t $(go list $PKG)` where $PKG is the transitively included package with the test dependencies (there might be more than one).

**Comment by frankban** [comment]
$$merge$$

**Pull request merged**
