### PR TITLE
Merge develop into 3.0-dqlite

### PR DESCRIPTION
**Pull request by manadart**
Merge from develop to bring forward:
- #13938 from manadart/2.9-into-develop
- #13945 from neoaggelos/quickfix/typo-in-bootstrap

Only go.mod conflicts needed resolving.

### CODE REVIEW

**Review by juanmanuel-tirado — APPROVED** [review]
LG2M

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
