### PR TITLE
Restore fix status

### PR DESCRIPTION
**Pull request by wallyworld**
Fixes: https://launchpad.net/bugs/1569467

William fixed the restore status update issue. Restore bootstrap still did not complete. The restore was not writing out the new controller addresses nor ca cert so the client could not connect.

The code to do the above is moved from bootstrap.go to cmd/juju/common so it can be shared between bootstrap and restore.

Tested with lxd provided. Worked once and then a second time the jujud machine agent needed to be restarted by hand before clients could connect. Appears unrelated to restore. A followup can be done to fix any remaining issue found by CI. This fix at the least is a step in the right direction.

(Review request: http://reviews.vapour.ws/r/4720/)

### CODE REVIEW

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by cherylj** [comment]
$$__JFDI__$$

**Comment by cherylj** [comment]
Using JFDI as this is fixing a different CI regression.

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$ffs$$

**Pull request merged**
