### PR TITLE
Use vSphere template VMs for instance creation

### PR DESCRIPTION
**Pull request by timClicks**
Make use of vSphere's template VM feature. This change enables Juju to bootstrap itself and deploy charms/bundles on vSphere instances that are backed by vSAN. 

## QA steps

* juju bootstrap vsphere
* juju deploy ubuntu

## Documentation changes

Required 

## Bug reference

* https://bugs.launchpad.net/juju/+bug/1800940

### CODE REVIEW

**Comment by timClicks** [comment]
This PR supersedes #10461

**Comment by FrederikNS** [comment]
I tried this out once again, the bootstrapping went just fine using a vSAN, however deploying charmed-kubernetes, didn't work.

The datastore and network settings for my bootstrap and charmed-kubernetes is identical, and most of the VMs for kubernetes started up just fine. However vm number 7 & 9 both got created, but juju didn't power them on. Then shortly after that juju tried creating the two VMs again, and failed because they already exists. Here's the status from juju:

```
Model     Controller       Cloud/Region                      Version  SLA          Timestamp
k8s-test  juju-controller  cloud-vsphere-a9c/K8s Datacenter  2.6.7.1  unsupported  09:52:55+02:00

App                    Version  Status   Scale  Charm                  Store       Rev  OS      Notes
containerd                      waiting      0  containerd             jujucharms    2  ubuntu
easyrsa                         waiting    0/1  easyrsa                jujucharms  254  ubuntu
etcd                            waiting    0/3  etcd                   jujucharms  434  ubuntu
flannel                         waiting      0  flannel                jujucharms  425  ubuntu
kubeapi-load-balancer           waiting    0/1  kubeapi-load-balancer  jujucharms  649  ubuntu  exposed
kubernetes-master               waiting    0/2  kubernetes-master      jujucharms  700  ubuntu
kubernetes-worker               waiting    0/3  kubernetes-worker      jujucharms  552  ubuntu  exposed

Unit                     Workload  Agent       Machine  Public address   Ports  Message
easyrsa/0                waiting   allocating  0        192.168.161.221         waiting for machine
etcd/0                   waiting   allocating  1        192.168.161.222         waiting for machine
etcd/1                   waiting   allocating  2        192.168.161.223         waiting for machine
etcd/2                   waiting   allocating  3        192.168.161.228         waiting for machine
kubeapi-load-balancer/0  waiting   allocating  4        192.168.161.229         waiting for machine
kubernetes-master/0      waiting   allocating  5        192.168.161.225         waiting for machine
kubernetes-master/1      waiting   allocating  6        192.168.161.227         waiting for machine
kubernetes-worker/0      waiting   allocating  7                                waiting for machine
kubernetes-worker/1      waiting   allocating  8        192.168.161.224         waiting for machine
kubernetes-worker/2      waiting   allocating  9                                waiting for machine

Machine  State    DNS              Inst id        Series  AZ  Message
0        pending  192.168.161.221  juju-8a9a27-0  bionic      poweredOn
1        pending  192.168.161.222  juju-8a9a27-1  bionic      poweredOn
2        pending  192.168.161.223  juju-8a9a27-2  bionic      poweredOn
3        pending  192.168.161.228  juju-8a9a27-3  bionic      poweredOn
4        pending  192.168.161.229  juju-8a9a27-4  bionic      poweredOn
5        pending  192.168.161.225  juju-8a9a27-5  bionic      poweredOn
6        pending  192.168.161.227  juju-8a9a27-6  bionic      poweredOn
7        down                      pending        bionic      failed to start machine 7 in zone "K8s Cluster 00/kubernetes-kubespray", retrying in 10s with new availability zone: The name 'juju-8a9a27-7'
 already exists.
8        pending  192.168.161.224  juju-8a9a27-8  bionic      poweredOn
9        down                      pending        bionic      failed to start machine 9 in zone "K8s Cluster 00/K8s Cluster 00%2fResources%2fkubernetes-kubespray", retrying in 10s with new availability z
one: The name 'juju-8a9a27-9' already exists.
```

To see if I could break juju out of this state, I first tried powering the two VMs on, but juju just kept trying to re-create them. Then I tried shutting them down and deleting them, Juju then promptly recreated them and then went back to trying to recreate them again... failing to do it because they already exist.

So this is clearly moving in the right direction, however it seems there are still some issues.

**Comment by timClicks** [comment]
@FrederikNS Thank you very much for taking the time to test this out. It's very strange to see those naming conflicts. I'll take some time to attempt to hunt down the problem. Excellent to see that we're getting closer.

**Comment by timClicks** [comment]
$$merge$$

**Comment by timClicks** [comment]
Thanks again for the early testing @FrederikNS. Your input helped uncover an issue with how we were using the vSphere API.

**Pull request merged**
