### PR TITLE
[JUJU-462] Prevent needless link-layer update attempts by instance-poller

### PR DESCRIPTION
**Pull request by manadart**
For providers that do not implement `NetworkInterfaces`, the instance-poller worker creates `NetworkConfig` from instance addresses, using dummy devices that have only a `DeviceIndex`.

This is necessary in order that provider-sourced addresses, particularly FIPs and VIPs, are recorded in the `machines` collection. However, we are attempting to update link-layer devices addresses using such configuration, causing low-value log context as described in the linked bug.

Here we prevent the attempt to update link-layer device addresses when we detect such config.

## QA steps

- Bootstrap to OpenStack ensuring that public IPs are allocated to machines.
- Once complete, check the controller logs. There should be no occurrences of "updating provider-sourced link-layer devices...".
- But `juju show-machine -m controller 0 --format yaml` should include the public IP; for example, here we see the public, private and Fan IPs:
```
    ip-addresses:
    - 10.245.164.31
    - 10.5.3.32
    - 252.3.32.1
```

## Documentation changes

None.

## Bug reference

https://bugs.launchpad.net/juju/+bug/1951331

### CODE REVIEW

**Comment by manadart** [comment]
!!build!!

**Review by achilleasa — APPROVED** [review]
LGTM. I will propose patches for implementing NetworkInterfaces across the board.

**Comment by manadart** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Pull request merged**
