### PR TITLE
all: use v5 of the charmstore API

### PR DESCRIPTION
**Pull request by rogpeppe**
This implies the new publishing model, so charms need to be published
before they are available in the default (stable) channel.

Because the new ussologin VisitWebPage API needed changing
in many places, we factor out everywhere that uses it into
a single place rather than just change it everywhere.

(Review request: http://reviews.vapour.ws/r/4249/)

### CODE REVIEW

**Comment by rogpeppe** [comment]
$$merge$$

**Comment by urosj** [comment]
:+1:

**Comment by natefinch** [comment]
:+1:

**Comment by rogpeppe** [comment]
$$merge$$

**Comment by rogpeppe** [comment]
$$merge$$

**Comment by rogpeppe** [comment]
$$merge$$

**Pull request merged**
