### PR TITLE
Merge pull request #1503 from wallyworld/longer-maas-wait-time

### PR DESCRIPTION
**Pull request by dooferlad**
Increase timeout to wait for maas node deployment

MAAS nodes can take longer to transition to deploy state that Juju allows for.
The time to wait has been increased to 600s.
Additional debug added to see what the node state is when polling.

Fixes: https://bugs.launchpad.net/juju-core/+bug/1415961

(Review request: http://reviews.vapour.ws/r/825/)

(Review request: http://reviews.vapour.ws/r/1028/)

### CODE REVIEW

**Comment by dimitern** [comment]
$$fixes-1415961$$

**Comment by dimitern** [comment]
$$retry-aws-issue$$

**Comment by dooferlad** [comment]
$$prod$$

**Comment by dimitern** [comment]
$$WTF$$ ?

**Comment by dooferlad** [comment]
$$gogogo$$

**Pull request merged**
