### PR TITLE
2.9 into develop

### PR DESCRIPTION
**Pull request by tlm**
Merge of 2.9 into develop. Includes:

- #13821 from tlm/makefile-output
- #13748 from rwcarlsen/action-key-guard
- #13818 from ycliuhw/k8s-introspection
- #13816 from hpidcock/scale-sidecar-on-delete
- #13817 from tlm/darwin-arm64-support
- #13815 from tlm/darwin-arm64-support
- #13749 from hmlanigan/lp1960276-use-ping-instead
- #13814 from SimonRichardson/pass-macaroons-with-api-root
- #13795 from SimonRichardson/config-raft-batch-fsm
- #13813 from wallyworld/strict-snap-plugs
- #13812 from tlm/darwin-arm64-support
- #13805 from wallyworld/remote-controller-ref-count
- #13806 from SimonRichardson/set-application-arch-constraint
- #13808 from hmlanigan/download-ch-schema
- #13807 from hmlanigan/report-unit-state

Conflicts:
```
          apiserver/facades/client/application/get_test.go
          apiserver/facades/client/client/client.go
          apiserver/facades/client/client/client_test.go
          cmd/containeragent/unit/agent.go
          cmd/containeragent/unit/agent_test.go
          feature/flags.go
          scripts/win-installer/setup.iss
          snap/snapcraft.yaml
          version/version.go
```

### CODE REVIEW

**Review by wallyworld — APPROVED** [review]

**Review by hmlanigan — APPROVED** [review]
Checked the conflict files.

**Comment by tlm** [comment]
!!build!!

**Comment by tlm** [comment]
!!build!!

**Comment by tlm** [comment]
!!build!!

**Comment by tlm** [comment]
$$merge$$

**Pull request merged**
