### PR TITLE
Fix path used for mongorestore

### PR DESCRIPTION
**Pull request by wallyworld**
The path used to invoke mongorestore was hard coded.
We fix it in line with how the  path to mongodump is found.

(Review request: http://reviews.vapour.ws/r/4564/)

### CODE REVIEW

**Comment by wallyworld** [comment]
$$fixes-1568943$$

**Comment by wallyworld** [comment]
$$fixes-1568943$$

**Comment by wallyworld** [comment]
$$fixes-1568943$$

**Comment by axw** [comment]
$$merge$$

**Pull request merged**
