### PR TITLE
Add Life methods to IPAddress

### PR DESCRIPTION
**Pull request by voidspace**
This adds the methods Life and EnsureDead to IPAddress. Remove requires the IPAddress to be Dead before removal. This is a precursor to having an address worker responsible for removing IP addresses.

Upgrade step needed to add Life: Alive to existing IPAddresses.

(Review request: http://reviews.vapour.ws/r/1160/)

### CODE REVIEW

**Comment by voidspace** [comment]
$$merge$$

**Comment by voidspace** [comment]
$$merge$$

**Comment by dimitern** [comment]
$$retry$$

**Comment by dimitern** [comment]
$$retry-flaky-test$$

**Pull request merged**
