### PR TITLE
Do not use model's default-series when locating charm.

### PR DESCRIPTION
**Pull request by ExternalReality**
## Description of change

When issuing a `juju deploy` command without specifying a series juju would use the model's default series. This behavior was undesirable since the model's default series can cause a charm revision other than the latest to be deployed by default. To fix this we no longer take into account the model's default series when no series is specified by a `juju deploy` command.

## QA steps
Get a charm whose latest revision does not have support for the model's default:

`juju mode-config default-series=xenial`
`juju deploy cs:~ecjones/ubuntu-series-upgrade`

There are two revisions of the deployed charm. Before this change set, revision 0 would be deployed by the above command. After applying this change set revision 1 should be deployed. Different revision are deployed since juju no longer takes into account the `default-series` when deciding what revision of the charm to deploy by default, that is, when no revision or series is specified. So if a model's `default-series` is `xenial` and the latest charm revision supports only bionic, then by default, the latest charm revision will be deployed not being excluded by the model's default. 

## Documentation changes

Changes what cham revision gets deployed in certain cases. 

## Bug reference

https://bugs.launchpad.net/juju/+bug/1788604

### CODE REVIEW

**Comment by howbazaar** [comment]
Sorry I wasn't around when the original discussion around this was done, but I seem to recall that the entire purpose of the model default-series was to be used when the user didn't specify one. If we are removing this logic, what is the point of the default-series?

**Comment by ExternalReality** [comment]
@howbazaar short answer - I don't know. I'll put this on hold and inquire more about this. Thank you for pointing that out.

**Comment by mitechie** [comment]
The model default is used when there's no other sane one to fall back to. The current issue is that the order of series from the charm author is what's best to run it on. In the current code paths there's no way that list priority is taken into account as Juju uses the model default every time and most folks don't actually set that in any fashion. So a blind default overrides the author's best choice and so this change puts the author above the model default. 

Eric was going to look into the cases around local charms that don't have any charmstore logic to help resolve this and make sure the model default provided a fallback for those cases.

**Comment by howbazaar** [comment]
@mitechie OK, that makes sense. So is this just a change of priorities?  If the charm specifies a list of series, choose the first one if one isn't specified, but if it doesn't then use the default series?

**Comment by manadart** [comment]
!!build!!

**Comment by ExternalReality** [comment]
@mitechie 

> Eric was going to look into the cases around local charms that don't have any charmstore logic to help resolve this and make sure the model default provided a fallback for those cases.

The only logic that was changed was logic specifically related to the charmstore (and that code which threaded the config through to it) - code related to deploying local charms is unchanged.

**Comment by hmlanigan** [comment]
@ExternalReality, I'll take a look at this on Monday.

**Comment by hmlanigan** [comment]
@ExternalReality, i'm still getting the permission denied error deploying cs:~ecjones/ubuntu-series-upgrade.

Why does a different revision of the charm get deployed with this change?

**Comment by ExternalReality** [comment]
$$MERGE$$

**Pull request merged**
