### PR TITLE
fix up error handling when no current controller

### PR DESCRIPTION
**Pull request by natefinch**
fixes https://bugs.launchpad.net/juju/+bug/1618998
list-models should point out list-controllers command in error message

copy of #6306

### CODE REVIEW

**Comment by nskaggs** [comment]
makeitso

**Comment by mitechie** [comment]
!!build-take-2!!

**Comment by nskaggs** [comment]
test this please

**Comment by nskaggs** [comment]
!!buildme!!

**Comment by nskaggs** [comment]
!!build!!

**Comment by natefinch** [comment]
$$merge$$

**Pull request merged**
