### PR TITLE
Change algorithm for picking addresses to always prefer provider

### PR DESCRIPTION
**Pull request by voidspace**
When choosing a preferred public or private address for a machine always prefer the provider over machine addresses, even if the scope doesn't exactly match. This is because the provider usually will have a better idea what addresses should be used for a machine and the machine addresses should only be used as a fallback.

(Review request: http://reviews.vapour.ws/r/3097/)

### CODE REVIEW

**Comment by voidspace** [comment]
$$merge$$

**Comment by voidspace** [comment]
$$merge$$

**Comment by voidspace** [comment]
$$merge$$

**Comment by voidspace** [comment]
$$merge$$

**Comment by voidspace** [comment]
$$merge$$

**Comment by voidspace** [comment]
$$merge$$

**Comment by voidspace** [comment]
$$merge$$

**Comment by voidspace** [comment]
$$merge$$

**Comment by dimitern** [comment]
$$merge$$

**Pull request merged**
