### PR TITLE
Addressable Containers Feature Flag.

### PR DESCRIPTION
**Pull request by voidspace**
Forward-port PRs #2097 and #2103 from 1.23. Put addressable containers behind a feature flag.

(Review request: http://reviews.vapour.ws/r/1534/)

### CODE REVIEW

**Comment by dimitern** [comment]
$$merge$$ - this I believe should stabilize 1.24 and get a blessed revision.

**Comment by dimitern** [comment]
@voidspace Sorry, there seems to be some mix up here - we need this to land on 1.24 first. Can you please do that?

**Comment by voidspace** [comment]
Will do.

**Comment by voidspace** [comment]
See https://github.com/juju/juju/pull/2188

**Comment by voidspace** [comment]
$$merge$$

**Comment by voidspace** [comment]
$$__JFDI__$$

This is part of the fix for https://bugs.launchpad.net/juju-core/+bug/1442801

**Pull request merged**
