### PR TITLE
Inject controller config machiner

### PR DESCRIPTION
**Pull request by SimonRichardson**
The following injects controller config into machiner api facade.
It builds off the apiserver common PR changes (#16295), which does
a lot of the heavy lifting.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing

## QA steps

```sh
$ juju bootstrap lxd test --build-agent
$ juju add-model default
$ juju enable-ha
$ juju deploy ubuntu
$ juju add-machine -n 1
```
## Links

**Jira card:** JUJU-4327

### CODE REVIEW

**Review by manadart — COMMENTED** [review]
This one is not working. It cannot be bootstrapped. Logs show:
```
2023-09-27 07:56:57 DEBUG juju.worker.dependency engine.go:580 "db-accessor" manifold worker started at 2023-09-27 07:56:57.869734525 +0000 UTC
2023-09-27 07:56:57 INFO juju.worker.dbaccessor worker.go:507 host is configured as a Dqlite node
2023-09-27 07:56:57 INFO juju.worker.dbaccessor worker.go:618 serving Dqlite application (ID: 1)
2023-09-27 07:56:57 INFO juju.worker.dbaccessor worker.go:622 current cluster: []dqlite.NodeInfo(nil)
2023-09-27 07:56:57 DEBUG juju.worker.dbaccessor runner.go:402 start "controller"
2023-09-27 07:56:57 INFO juju.worker.dbaccessor runner.go:578 start "controller"
2023-09-27 07:56:57 INFO juju.worker.dbaccessor worker.go:901 shutting down Dqlite node
2023-09-27 07:56:57 DEBUG juju.worker.dbaccessor runner.go:410 "controller" started
2023-09-27 07:56:57 DEBUG juju.worker.dbaccessor runner.go:288 killing runner 0xc00061ec60
2023-09-27 07:56:57 INFO juju.worker.dbaccessor runner.go:396 runner is dying
2023-09-27 07:56:57 DEBUG juju.worker.dbaccessor runner.go:557 killing "controller"
2023-09-27 07:56:57 INFO juju.worker.dbaccessor runner.go:609 stopped "controller", err: <nil>
2023-09-27 07:56:57 DEBUG juju.worker.dbaccessor runner.go:416 "controller" done: <nil>
2023-09-27 07:56:57 DEBUG juju.worker.dbaccessor runner.go:495 no restart, removing "controller" from known workers
2023-09-27 07:56:57 DEBUG juju.worker.dependency engine.go:618 "db-accessor" manifold worker stopped: missing port in address
stack trace:
missing port in address
github.com/juju/juju/worker/dbaccessor.(*dbWorker).initialiseDqlite:562:
github.com/juju/juju/worker/dbaccessor.(*dbWorker).startExistingDqliteNode:532:
github.com/juju/juju/worker/dbaccessor.(*dbWorker).loop:281:
2023-09-27 07:56:57 ERROR juju.worker.dependency engine.go:695 "db-accessor" manifold worker returned unexpected error: missing port in address
```

**Comment by SimonRichardson** [comment]
> This one is not working. It cannot be bootstrapped. Logs show:
> 
> ```
> 2023-09-27 07:56:57 DEBUG juju.worker.dependency engine.go:580 "db-accessor" manifold worker started at 2023-09-27 07:56:57.869734525 +0000 UTC
> 2023-09-27 07:56:57 INFO juju.worker.dbaccessor worker.go:507 host is configured as a Dqlite node
> 2023-09-27 07:56:57 INFO juju.worker.dbaccessor worker.go:618 serving Dqlite application (ID: 1)
> 2023-09-27 07:56:57 INFO juju.worker.dbaccessor worker.go:622 current cluster: []dqlite.NodeInfo(nil)
> 2023-09-27 07:56:57 DEBUG juju.worker.dbaccessor runner.go:402 start "controller"
> 2023-09-27 07:56:57 INFO juju.worker.dbaccessor runner.go:578 start "controller"
> 2023-09-27 07:56:57 INFO juju.worker.dbaccessor worker.go:901 shutting down Dqlite node
> 2023-09-27 07:56:57 DEBUG juju.worker.dbaccessor runner.go:410 "controller" started
> 2023-09-27 07:56:57 DEBUG juju.worker.dbaccessor runner.go:288 killing runner 0xc00061ec60
> 2023-09-27 07:56:57 INFO juju.worker.dbaccessor runner.go:396 runner is dying
> 2023-09-27 07:56:57 DEBUG juju.worker.dbaccessor runner.go:557 killing "controller"
> 2023-09-27 07:56:57 INFO juju.worker.dbaccessor runner.go:609 stopped "controller", err: <nil>
> 2023-09-27 07:56:57 DEBUG juju.worker.dbaccessor runner.go:416 "controller" done: <nil>
> 2023-09-27 07:56:57 DEBUG juju.worker.dbaccessor runner.go:495 no restart, removing "controller" from known workers
> 2023-09-27 07:56:57 DEBUG juju.worker.dependency engine.go:618 "db-accessor" manifold worker stopped: missing port in address
> stack trace:
> missing port in address
> github.com/juju/juju/worker/dbaccessor.(*dbWorker).initialiseDqlite:562:
> github.com/juju/juju/worker/dbaccessor.(*dbWorker).startExistingDqliteNode:532:
> github.com/juju/juju/worker/dbaccessor.(*dbWorker).loop:281:
> 2023-09-27 07:56:57 ERROR juju.worker.dependency engine.go:695 "db-accessor" manifold worker returned unexpected error: missing port in address
> ```

I'll rebase with all the new changes and have a look again

**Comment by SimonRichardson** [comment]
@manadart this just needed rebasing because the underlying changes from Tom had broken things. Everything looks like it's happy again.

**Review by manadart — APPROVED** [review]
Thanks. All looks good now.

**Pull request merged**
