### PR TITLE
Context logger v2

### PR DESCRIPTION
**Pull request by SimonRichardson**
Introduces `context.Context` to the `logger.Logger` interface. The main driver behind this is the following:

- For all model facade requests, a model uuid is inserted into the context[1]. This will allow us to annotate all lot messages with a model uuid. This will pay dividends when we're exporting all logs to loki or similar. This also has the advantage that logs can be bifurcated based on the uuid to different log files for machines.
- Trace IDs can also be associated with log messages, so it will be possible to see which logs are associated with a trace.
- Status history epic. Long term we don't want to store the information in the database, instead we want the information be part of the logging system. For this to work, we need the model UUID to be part of the logs (first point), but more work is required to make sure the model UUID is part of the model workers. That will have to be added later.
- This opens up the avenue for using the std library slog package in the future.

1. https://github.com/juju/juju/blob/5e972995681ae74a95bef063a31e4e253e6157c7/apiserver/apiserver.go#L1085-L1088

---

The code is relatively simple, it just introduces a context.Context as part of the method signature and the wire up of the context either via a TODO or Background context is used.

## QA Steps

```sh
$ juju bootstrap lxd test
$ juju add-model default
$ juju deploy ubuntu
```

### CODE REVIEW

**Review by hpidcock — APPROVED** [review]
LGTM - couple of unit test failures to correct

**Review by tlm — COMMENTED** [review]
Thanks @SimonRichardson,

I like the direction this is heading. I am almost happy to give this +1 but want to clarify our posture around just wiring up TODO every where considering a lot of the apiserver changes have a context available. Should we not do the work to plumb up a context if we have it available in this PR?

I am assuming the reason for not doing this is because of find and replace burden. I am happy to see if I can make go patch do this. Not confident I can make it do the thing but happy to at least try.

**Comment by SimonRichardson** [comment]
> Should we not do the work to plumb up a context if we have it available in this PR?
> 
> I am assuming the reason for not doing this is because of find and replace burden. I am happy to see if I can make go patch do this. Not confident I can make it do the thing but happy to at least try.

There is a problem with k8s not tearing down correctly, hence me using TODO everywhere. My prior attempt https://github.com/juju/juju/pull/18315, did try to wire everything up in one PR, but we had issues with k8s again. There is some logic that I need to fix in k8s that can't handle a context in a certain place.

**Comment by SimonRichardson** [comment]
I'll have to think of another approach.

Essentially, there is a k8s logger somewhere which causes the model to die early.

**Pull request closed without merging**
