### PR TITLE
Fixed lp:1445063 - non-FQDN in maas not resolvable from containers

### PR DESCRIPTION
**Pull request by TheMue**
Fix is for 1.24

See also https://github.com/juju/juju/pull/2090

(Review request: http://reviews.vapour.ws/r/1522/)

### CODE REVIEW

**Comment by TheMue** [comment]
$$fixes-1445063$$

**Comment by TheMue** [comment]
$$fixes-1445063$$

**Comment by dimitern** [comment]
$$__JFDI__$$

**Comment by dimitern** [comment]
$$retry$$

**Pull request merged**
