### PR TITLE
Update to use juju/txn/v2 and enable sstxn when supported by mongo

### PR DESCRIPTION
**Pull request by wallyworld**
The mongo to use is set to 4.4 track and sstxn are enabled when mongo says they are supported.
Most of the PR is import churn to pick up a new upstream juju/txn/v2 release which tunes the txn retry behaviour to better deal with sstxn.

Also a small driveby for a juju dashboard error message when connecting to an older controller.

## QA steps

unit tests

bootstrap and deploy and relate a few charms, eg mariadb, mediawiki
run an action or two

### CODE REVIEW

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
[enable mongo 4.4 sstxn](https://trello.com/c/o3Tr7UZl/1496-enable-mongo-44-sstxn)

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by hpidcock** [comment]
@wallyworld ```
$ juju create-backup
ERROR while creating backup archive: while dumping juju state database: error dumping databases: error executing "/snap/bin/juju-db.mongodump": 2021-04-08T01:30:36.577+0000	WARNING: --sslAllowInvalidCertificates and --sslAllowInvalidHostnames are deprecated, please use --tlsInsecure instead; 2021-04-08T01:30:36.644+0000	Failed: error creating intents to dump: error creating intents for database config: error counting config.system.indexBuilds: (Unauthorized) not authorized on config to execute command { count: "system.indexBuilds", lsid: { id: UUID("375fd83a-3f3e-4c0b-962c-8f182fd15cb9") }, $clusterTime: { clusterTime: Timestamp(1617845435, 2), signature: { hash: BinData(0, A2C7DF43F70387D5DC4E6860B2E225EA05D9D3EC), keyId: 6948592035012018180 } }, $db: "config", $readPreference: { mode: "primaryPreferred" } };
```

**Review by hpidcock — APPROVED** [review]

**Comment by wallyworld** [comment]
> @wallyworld
> 
> ```
> $ juju create-backup
> ERROR while creating backup archive: while dumping juju state database: error dumping databases: error executing "/snap/bin/juju-db.mongodump": 2021-04-08T01:30:36.577+0000	WARNING: --sslAllowInvalidCertificates and --sslAllowInvalidHostnames are deprecated, please use --tlsInsecure instead; 2021-04-08T01:30:36.644+0000	Failed: error creating intents to dump: error creating intents for database config: error counting config.system.indexBuilds: (Unauthorized) not authorized on config to execute command { count: "system.indexBuilds", lsid: { id: UUID("375fd83a-3f3e-4c0b-962c-8f182fd15cb9") }, $clusterTime: { clusterTime: Timestamp(1617845435, 2), signature: { hash: BinData(0, A2C7DF43F70387D5DC4E6860B2E225EA05D9D3EC), keyId: 6948592035012018180 } }, $db: "config", $readPreference: { mode: "primaryPreferred" } };
> ```

Damn, mongotools is the wrong version in the snap. The juju-db snap will need to be rebuilt

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
