### PR TITLE
Verify Endpoint Bindings Integrity When Moving Subnets

### PR DESCRIPTION
**Pull request by manadart**
## Description of change

This patch adds a verification to ensure that the integrity of endpoint bindings is maintained when moving subnets between spaces.

This is the first of two patches for the functionality and simply considers violation to be when not all units of the application are connected to a bound space.

Subsequent logic will interrogate the unit connectivity, and if the binding can be preserved by changing it to the destination space, that action will be taken.

## QA steps

- Bootstrap to AWS
- Carve one of the subnets into a new space. E.g. `juju add-space beta 172.31.16.0/20`.
- `juju deploy postgresql --bind "beta" --to subnet=172.31.16.0/20`.
- `juju move-to-space alpha 172.31.16.0/20`.
- Error should read:
```bash
ERROR cannot update space "alpha": moving subnet(s) to space "alpha" violates endpoint binding db:beta for application "postgresql"
        units not connected to the space: postgresql/0
```
- Other subnets can be moved; these should both succeed:
  - `juju move-to-space beta 172.31.0.0/20`.
  - `juju move-to-space alpha 172.31.0.0/20`.

## Documentation changes

None.

## Bug reference

N/A

### CODE REVIEW

**Comment by manadart** [comment]
[Spaces API - MoveSubnets Endpoint Validation Part 1](https://trello.com/c/IXE8vYvV/2518-spaces-api-movesubnets-endpoint-validation-part-1)

**Comment by manadart** [comment]
[Spaces API - MoveSubnets Endpoint Validation Part 1](https://trello.com/c/IXE8vYvV/2518-spaces-api-movesubnets-endpoint-validation-part-1)

**Comment by manadart** [comment]
[Spaces API - MoveSubnets Endpoint Validation Part 1](https://trello.com/c/IXE8vYvV/2518-spaces-api-movesubnets-endpoint-validation-part-1)

**Comment by hmlanigan** [comment]
@manadart, I've been trying to QA this PR, but having issues.

I created the beta space, deploy with the binding, and the unit deploys to the alpha space.  Checking show-applications says it should be the beta space.  And the move-to-space succeeds.

I'm not sure if the correct jujud agent is being used.  The jujud doesn't list the sha of the build:
machine-0: 21:00:33 INFO juju.cmd running jujud [2.8-rc1.1 0  gc go1.14.2]

I did bootstrap with --build-agent.

There's a bug out ([1876366](https://bugs.launchpad.net/juju/+bug/1876366)) that upgrade-controller --build-agent isn't working, perhaps it isn't working for bootstrap either.

**Comment by manadart** [comment]
@hmlanigan, I investigated this today. The issue is that endpoint bindings are not translated into any constraining data for AWS. 

I would consider this a long-standing bug unrelated to the patch. I'll raise it and discuss a fix with the team; I have one in mind.

I modified the QA steps to use subnet placement, so that we are guaranteed to land in the bound/moving subnet. It passes for me.

**Comment by hmlanigan** [comment]
QA is good with new instructions.

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
