### PR TITLE
Remove the GO ioutil pkg

### PR DESCRIPTION
**Pull request by vianamjr**
Remove deprecated ioutil lib form std library.
## Checklist

*If an item is not applicable, use `~strikethrough~`.*

- [ ] Code style: imports ordered, good names, simple structure, etc
- [ ] Comments saying why design decisions were made
- [ ] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/develop/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

This a change in a test file, so the tests must keep passing: 
```sh
go test ./worker/filenotifywatcher/watcher_test.go
```
Also all tests must pass as this is a really small change.

## Documentation changes

*How it affects user workflow (CLI or API). Delete section if not applicable.*

## Bug reference

*Link to Launchpad bug. Delete section if not applicable.*

### CODE REVIEW

**Comment by juanmanuel-tirado** [comment]
Please provide QA steps

**Comment by vianamjr** [comment]
I had to change my email used in the commit.

**Review by SimonRichardson — CHANGES_REQUESTED** [review]
This doesn't do the same thing at all. `ioutil.TempDir` creates a new folder inside your `$TMPDIR` under `inotify`. `os.TempDir` just returns the `$TMPDIR`. That's not what we'd want, we'd need to namespace the temp directories to prevent potential collisions.

**Comment by vianamjr** [comment]
@SimonRichardson you're right, my bad, fixed it!

**Comment by vianamjr** [comment]
@SimonRichardson hope I can contribute more soon!

**Review by SimonRichardson — APPROVED** [review]

**Pull request merged**
