### PR TITLE
Fixes lp#1822117: expose credential validity in show-model and show-credential.

### PR DESCRIPTION
**Pull request by anastasiamac**
## Description of change

Juju was not exposing cloud credential validity very well. It will tell the user if credential becomes invalid via either 'juju status' or 'juju models'. However, credential validity was not easily discoverable any time.

This PR exposes credential validity as an output in 'show-credential' and 'show-model' commands. 

## Bug reference

https://bugs.launchpad.net/juju/+bug/1822117

### CODE REVIEW

**Comment by anastasiamac** [comment]
[surface credential validity in show-model and show-credential](https://trello.com/c/JvaLzyhv/841-surface-credential-validity-in-show-model-and-show-credential)

**Comment by pmatulis** [comment]
> Juju was not exposing cloud credential validity very well. It will tell the user if credential becomes invalid via either 'juju status' or 'juju models'.

According to the bug, credential validity was not exposed at all. (?)

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
intermittent failure in github.com/juju/juju/worker/peergrouper.TestPackage

**Comment by anastasiamac** [comment]
!!build!!

**Comment by anastasiamac** [comment]
intermittent failure in github.com/juju/juju/state/lease.TestPackage

**Comment by anastasiamac** [comment]
!!build!!

**Comment by anastasiamac** [comment]
$$merge$$

**Pull request merged**
