### PR TITLE
3.3-to-3.4 merge

### PR DESCRIPTION
**Pull request by anvial**
3.3 to 3.4 merge forward. 

- 7f87af8d7a (origin/3.3, 3.3) Merge pull request #17078 from anvial/fix-secret_k8s-test-suite
- e1e9b67ea3 Merge pull request #17077 from anvial/fix-run_deploy_exported_charmhub_bundle_with_fixed_revisions-test

No Conflicts.

### CODE REVIEW

**Review by cderici — APPROVED** [review]

**Comment by wallyworld** [comment]
Replaced by https://github.com/juju/juju/pull/17085

**Pull request closed without merging**
