### PR TITLE
chore(instancedata): full cleanup of instance data on legacy state

### PR DESCRIPTION
**Pull request by nvinuesa**
This patch removes the last pieces of instance data from the legacy
state (the collection, and some bits of the methods `SetInstanceInfo` 
and `SetProvisioned`). 

The only non-removal code is a fix in the
provisioner_integration_test.go, where one test was still calling
SetProvisioned from the legacy state. This was easily replaced by the
service method.

## Checklist

- [X] Code style: imports ordered, good names, simple structure, etc
- [X] Comments saying why design decisions were made
- [X] Go unit tests, with comments saying what you're testing
- [ ] ~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- [ ] ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

This is the last patch for the instance data domain, so everything should work and no errors observed:

### Aws
```
juju bootstrap aws c
juju add-model m
juju add-machine
# check status and wait until machine State is ACTIVE
juju deploy ubuntu
```
Check outputs:
```
juju status
Model  Controller  Cloud/Region   Version      Timestamp
m      c2          aws/eu-west-3  4.0-beta5.1  16:01:09+02:00

App     Version  Status  Scale  Charm   Channel        Rev  Exposed  Message
ubuntu  22.04    active      1  ubuntu  latest/stable   25  no

Unit       Workload  Agent  Machine  Public address  Ports  Message
ubuntu/0*  active    idle   1        13.39.13.64

Machine  State    Address         Inst id              Base          AZ          Message
0        started  35.180.130.173  i-011143154353bcec3  ubuntu@22.04  eu-west-3b  running
1        started  13.39.13.64     i-0e8d2642f8198cff4  ubuntu@22.04  eu-west-3c  running

juju status --format yaml
model:
  name: m
  type: iaas
  controller: c2
  cloud: aws
  region: eu-west-3
  version: 4.0-beta5.1
  model-status:
    current: available
    since: 11 Oct 2024 15:59:48+02:00
machines:
  "0":
    juju-status:
      current: started
      since: 11 Oct 2024 16:00:50+02:00
      version: 4.0-beta5.1
    hostname: ip-172-31-28-136
    dns-name: 35.180.130.173
    ip-addresses:
    - 35.180.130.173
    - 172.31.28.136
    instance-id: i-011143154353bcec3
    machine-status:
      current: running
      message: running
      since: 11 Oct 2024 16:00:05+02:00
    modification-status:
      current: idle
      since: 11 Oct 2024 15:59:51+02:00
    base:
      name: ubuntu
      channel: "22.04"
    network-interfaces:
      enp39s0:
        ip-addresses:
        - 172.31.28.136
        mac-address: 0a:00:90:7c:8b:f1
        gateway: 172.31.16.1
        space: alpha
        is-up: true
    hardware: arch=amd64 cores=2 cpu-power=895 mem=8192M root-disk=8192M availability-zone=eu-west-3b
  "1":
    juju-status:
      current: started
      since: 11 Oct 2024 16:00:50+02:00
      version: 4.0-beta5.1
    hostname: ip-172-31-36-6
    dns-name: 13.39.13.64
    ip-addresses:
    - 13.39.13.64
    - 172.31.36.6
    instance-id: i-0e8d2642f8198cff4
    machine-status:
      current: running
      message: running
      since: 11 Oct 2024 16:00:01+02:00
    modification-status:
      current: idle
      since: 11 Oct 2024 15:59:54+02:00
    base:
      name: ubuntu
      channel: "22.04"
    network-interfaces:
      enp39s0:
        ip-addresses:
        - 172.31.36.6
        mac-address: 0e:73:fe:56:2a:23
        gateway: 172.31.32.1
        space: alpha
        is-up: true
    constraints: arch=amd64
    hardware: arch=amd64 cores=2 cpu-power=895 mem=8192M root-disk=8192M availability-zone=eu-west-3c
applications:
  ubuntu:
    charm: ubuntu
    base:
      name: ubuntu
      channel: "22.04"
    charm-origin: charmhub
    charm-name: ubuntu
    charm-rev: 25
    charm-channel: latest/stable
    exposed: false
    application-status:
      current: active
      since: 11 Oct 2024 16:00:54+02:00
    units:
      ubuntu/0:
        workload-status:
          current: active
          since: 11 Oct 2024 16:00:54+02:00
        juju-status:
          current: idle
          since: 11 Oct 2024 16:00:56+02:00
          version: 4.0-beta5.1
        leader: true
        machine: "1"
        public-address: 13.39.13.64
    version: "22.04"
storage: {}
controller:
  timestamp: 16:01:30+02:00
```

### LXD
```
juju bootstrap localhost c
juju add-model m
juju add-machine
# check status and wait until machine State is ACTIVE
juju deploy ubuntu
```
Check outputs:
```
juju status
Model  Controller  Cloud/Region         Version      Timestamp
m      c           localhost/localhost  4.0-beta5.1  15:59:17+02:00

App     Version  Status  Scale  Charm   Channel        Rev  Exposed  Message
ubuntu  22.04    active      1  ubuntu  latest/stable   25  no

Unit       Workload  Agent  Machine  Public address  Ports  Message
ubuntu/0*  active    idle   1        10.165.241.210

Machine  State    Address         Inst id        Base          AZ  Message
0        started  10.165.241.126  juju-735fb3-0  ubuntu@22.04      Running
1        started  10.165.241.210  juju-735fb3-1  ubuntu@22.04      Running

juju status --format yaml
model:
  name: m
  type: iaas
  controller: c
  cloud: localhost
  region: localhost
  version: 4.0-beta5.1
  model-status:
    current: available
    since: 11 Oct 2024 15:58:11+02:00
machines:
  "0":
    juju-status:
      current: started
      since: 11 Oct 2024 15:58:58+02:00
      version: 4.0-beta5.1
    hostname: juju-735fb3-0
    dns-name: 10.165.241.126
    ip-addresses:
    - 10.165.241.126
    instance-id: juju-735fb3-0
    machine-status:
      current: running
      message: Running
      since: 11 Oct 2024 15:58:23+02:00
    modification-status:
      current: idle
      since: 11 Oct 2024 15:58:17+02:00
    base:
      name: ubuntu
      channel: "22.04"
    network-interfaces:
      eth0:
        ip-addresses:
        - 10.165.241.126
        mac-address: 00:16:3e:d2:55:8c
        gateway: 10.165.241.1
        space: alpha
        is-up: true
    hardware: arch=amd64 cores=0 mem=0M virt-type=container
  "1":
    juju-status:
      current: started
      since: 11 Oct 2024 15:58:58+02:00
      version: 4.0-beta5.1
    hostname: juju-735fb3-1
    dns-name: 10.165.241.210
    ip-addresses:
    - 10.165.241.210
    instance-id: juju-735fb3-1
    machine-status:
      current: running
      message: Running
      since: 11 Oct 2024 15:58:27+02:00
    modification-status:
      current: idle
      since: 11 Oct 2024 15:58:22+02:00
    base:
      name: ubuntu
      channel: "22.04"
    network-interfaces:
      eth0:
        ip-addresses:
        - 10.165.241.210
        mac-address: 00:16:3e:97:46:2e
        gateway: 10.165.241.1
        space: alpha
        is-up: true
    constraints: arch=amd64
    hardware: arch=amd64 cores=0 mem=0M virt-type=container
applications:
  ubuntu:
    charm: ubuntu
    base:
      name: ubuntu
      channel: "22.04"
    charm-origin: charmhub
    charm-name: ubuntu
    charm-rev: 25
    charm-channel: latest/stable
    exposed: false
    application-status:
      current: active
      since: 11 Oct 2024 15:59:02+02:00
    units:
      ubuntu/0:
        workload-status:
          current: active
          since: 11 Oct 2024 15:59:02+02:00
        juju-status:
          current: idle
          since: 11 Oct 2024 15:59:04+02:00
          version: 4.0-beta5.1
        leader: true
        machine: "1"
        public-address: 10.165.241.210
    version: "22.04"
storage: {}
controller:
  timestamp: 15:59:33+02:00
```
make sure to have correct values on the machines' `instance-id` and `hardware`.

### Migration

Set up two controllers and one model. Migrate that model to the target controller:

```
juju bootstrap localhost tgt
juju bootstrap localhost src
juju add-model m
juju deploy ubuntu
# Wait until ACTIVE
juju migrate m tgt
```
Make sure the status shows everything OK on the target controller and no errors in the logs.

## Links

**Jira card:** JUJU-6703

### CODE REVIEW

**Review by jack-w-shaw — APPROVED** [review]
LGTM, QA passes.

However, QA could do with being a little more specific. What am I looking for in the big `juju status --format yaml` block? It's hard to tell what a pass/fail would look like

**Comment by nvinuesa** [comment]
@jack-w-shaw specifically the machines `instance-id` and `hardware`, but everything should be OK just in case.

**Review by SimonRichardson — APPROVED** [review]

**Pull request merged**
