### PR TITLE
[JUJU-1200] Complete coverage of nw model migration test in bash tests

### PR DESCRIPTION
**Pull request by jack-w-shaw**
Cover remain parts of our the acceptance test nw-model-migration in our bash-based test suites. Namely:
- Check debug-logs are maintained
- Check it's possible to add a unit to a migrated application
- Check it's possible to add a unit to a migrated application when the original controller has been destroyed

## Checklist

 - ~[ ] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change~
 - [x] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - ~[ ] Added or updated [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) related to packages changed~
 - [ ] Comments answer the question of why design decisions were made

## QA steps

```sh
./main.sh -v -s "test_model_config,test_model_multi,test_model_metrics" model
BOOTSTRAP_PROVIDER=aws BOOTSTRAP_CLOUD=aws ./main.sh -v -s "test_model_config,test_model_multi,test_model_metrics" model
```

### CODE REVIEW

**Comment by hmlanigan** [comment]
@jack-w-shaw there should be no requirement to setup the environment variables to run any integration test.  

`(cd tests; ./main.sh -v -s "test_model_config,test_model_multi,test_model_metrics" model)` should work.

**Comment by jack-w-shaw** [comment]
@hmlanigan fixed

**Review by hmlanigan — APPROVED** [review]
I have problems running subsequent tests locally, but not the one changed.

**Pull request merged**
