### PR TITLE
2.9 proxy issue 4

### PR DESCRIPTION
**Pull request by jameinel**
Update to the new change from stgraber.

proxy: Add trailing newline to AsScriptEnvironment

This makes /etc/juju-proxy.conf be a properly formatted shell script
with a trailing new line (makes it easier to read).

## QA steps

When using a proxy in the environment, see that /etc/proxy.conf now contains a trailing newline.

```sh
$ juju bootstrap --config ftp-proxy=https://test.invalid
```

## Documentation changes

None

## Bug reference

None

### CODE REVIEW

**Comment by jameinel** [comment]
Current failure is win2012 failing to start

**Review by hpidcock — APPROVED** [review]
LGTM

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Pull request merged**
