### PR TITLE
Improve go vet checks

### PR DESCRIPTION
**Pull request by mjs**
Instead of selectively enabling specific checks, just disable the ones that don't work for Juju. Also, enable checking of a lot more print style functions commonly used within Juju, defining them in a maintainable way.

Fixed two incorrect format strings found by the changes.

(Review request: http://reviews.vapour.ws/r/5634/)

### CODE REVIEW

**Comment by mjs** [comment]
$$merge$$

**Comment by mjs** [comment]
$$merge$$

**Comment by mjs** [comment]
$$intermittent-tests$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
