### PR TITLE
Add macaroon authentication and bundle deployment (chicago-cubs merge)

### PR DESCRIPTION
**Pull request by rogpeppe**
This merges the chicago-cubs feature branch into trunk.
This adds macaroon authentication support (along
with much API server cleanup) and support
for bundle deployment.

(Review request: http://reviews.vapour.ws/r/2991/)

### CODE REVIEW

**Comment by mhilton** [comment]
LGTM

**Comment by rogpeppe** [comment]
All commits have already been reviewed, and the feature branch is blessed, so merging without further ado.

**Comment by rogpeppe** [comment]
$$merge$$

**Comment by rogpeppe** [comment]
$$merge$$

**Comment by frankban** [comment]
Spurious?
$$merge$$

**Pull request merged**
