### PR TITLE
Move to go1.17

### PR DESCRIPTION
**Pull request by hpidcock**
Moves to go1.17 and applies gofmt changes for build tags.

### CODE REVIEW

**Review by wallyworld — APPROVED** [review]

**Comment by benhoyt** [comment]
Do we also need changes to the hard-coded "1.16" in `CONTRIBUTING.md`, `snap/snapcraft.yaml`, and `Makefile`?

**Comment by hpidcock** [comment]
!!build!!

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Pull request merged**
