### PR TITLE
Fixes lp#1804140: misleading unhelpful message when running status for non-existing model.

### PR DESCRIPTION
**Pull request by anastasiamac**
## Description of change

Straight forward port of https://github.com/juju/juju/pull/9520 

## Bug reference

https://bugs.launchpad.net/juju/+bug/1804140

### CODE REVIEW

**Comment by anastasiamac** [comment]
self-approving as trivial

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
[lp#1804140: client-side retries need to get a new api connection for every re-try](https://trello.com/c/VcnpfLDi/558-lp1804140-client-side-retries-need-to-get-a-new-api-connection-for-every-re-try)

**Comment by anastasiamac** [comment]
!!build!!

**Comment by mitechie** [comment]
!!build!!

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
