### PR TITLE
Retry EOF and connection errors while bootstrapping.

### PR DESCRIPTION
**Pull request by howbazaar**
As the API server is coming up, it goes through a number of steps.
Initially the upgrade steps run, but the api server allows some
calls to be processed during the upgrade, but not the list blocks.
It is also possible that the underlying database causes connections
to be dropped as it is initialising, or reconfiguring. These can
lead to EOF or "connection is shut down" error messages. We skip
these too, hoping that things come back up before the end of the
retry poll count.

(Review request: http://reviews.vapour.ws/r/2081/)

### CODE REVIEW

**Comment by howbazaar** [comment]
$$merge$$

**Comment by davecheney** [comment]
$$merge$$

**Comment by davecheney** [comment]
$$merge$$

**Comment by davecheney** [comment]
godeps: cannot update "/var/lib/jenkins/workspace/github-merge-juju/tmp.3fLtciAcj3/RELEASE/src/launchpad.net/tomb": cannot create repo: bzr: ERROR: Invalid http response for http://bazaar.launchpad.net/~niemeyer/tomb/trunk/.bzr/repository/packs/199d0e3049412782facfb6f380ddc250.pack: Unable to handle http code 503: Service Temporarily Unavailable

This is a new record

$$merge$$

**Pull request merged**
