### PR TITLE
provider/openstack: disable API version discovery

### PR DESCRIPTION
**Pull request by axw**
Update goose, and disable API version discovery.
We can reenable it when we stop using deprecated
APIs. Even then, we should probably specify
microversions.

Fixes https://bugs.launchpad.net/juju/+bug/1638704
Fixes https://bugs.launchpad.net/juju/+bug/1638304
Fixes https://bugs.launchpad.net/juju/+bug/1636648

### CODE REVIEW

**Comment by axw** [comment]
**QA**

Bootstrapped canonical/lcy01

**Comment by axw** [comment]
$$merge$$

**Comment by axw** [comment]
$$howaboutnow$$

**Comment by bz2** [comment]
$$retry$$

**Pull request merged**
