### PR TITLE
run-action --wait

### PR DESCRIPTION
**Pull request by stub42**
## Description of change

Actions will remain generally unused until the command line user experience is better than the alternatives 'juju run' or 'juju ssh'. This branch adds a --wait option to the 'run-action', allowing run-action it to be effectively used from the command line, rather than the current cumbersome approach of needing to run two separate commands and cutting and pasting the action-id between them. ~A --timeout option was also added, as in many automation situations we can't wait indefinitely for a result and should terminate and flag the error. The timeout was not combined with the '--wait' flag, as this would have made the most common use case of 'juju run-action --wait' to wait indefinitely to  become more cumbersome and require a timeout to be specified like 'juju run-action --wait=-1s'.~

https://bugs.launchpad.net/bugs/1445066 for history.

## QA steps

The following should two commands should return the same action results. The second (new) invocation method will have an additional action-id key in the results.

```
juju run-action unit/1 some-action
juju show-action-output <action-id> --wait=0
```

```
juju run-action unit/1 some-action --wait
```

Similarly, the following will behave equivalently (1ns timeout should always trigger timeout):

```
juju run-action unit/1 some-action
juju show-action-output <action-id> --wait=1ns
```

```
juju run-action unit/1 some-action --wait=1ns
```

## Documentation changes

Existing documentation needs to be adjusted, ideally preferring the new --wait example. Command line examples using the  run-action/show-action-output sequence are cumbersome and put people off.

## Bug reference

https://bugs.launchpad.net/bugs/1445066

### CODE REVIEW

**Comment by anastasiamac** [comment]
@stub42 
Please re-target to develop - this is the development branch and will become the bones of 2.2 :D 
Thank you for proposal!

**Comment by axw** [comment]
@stub42 thank you! was this this branched of staging? it needs to land in develop, so I'll retarget if it's safe to do so (github just says "some commits *may* be lost...)

I'd like to do a bit of investigation about whether it's possible to have "--wait" (meaning wait indefinitely) and "--wait=5m" (wait for 5 minutes). Then we can fix up show-action-output to match.

**Comment by axw** [comment]
@stub42 https://gist.github.com/axw/423a7e51034a57ad1d038ddbd32c65e7

If you're willing, please consider adding that in with some tests. Otherwise I can look at doing it when I have some more time to spare.

**Comment by stub42** [comment]
I have retargetted this at develop.

From my investigations, neither the standard Go library nor juju/gnuflag let you have a flag that works as both '--wait' or '--wait=value'. It would need to be added as a new feature (say, a flag that has a default value, that is overridden with a secondary default value if specified on the command line with no value, or the provided value if one given on the command line). It is arguable if this would be a good idea. I'm quite happy with the two distinct arguments, and you can explicitly choose which one makes the most sense rather than worry about implementation details like if you need to wait for 0s or -1s for indefinite wait.

I looked at testing, but it seems beyond my current abilities. It seems I'd need to pull in a pile of infrastructure from from showoutput_test.go, or somehow work out how to mock the call to GetActionResult (which is already tested, so no need to duplicate those details).

**Comment by stub42** [comment]
I've updated this to use @axw's code, collapsing --wait and --timeout arguments into one.

**Comment by jameinel** [comment]
Things like CLI like this feel reasonably as a CI test to me. Especially
testing that something waits for a command to finish (have a charm with an
action that just sleeps for 5s, and prints something, and show that
'run-action foo --wait' always gives you the result). As a CI test it
doesn't feel terrible to sleep for a bit.

**Comment by axw** [comment]
@stub42 I'll land this as-is, and we'll take on the responsibility of adding tests as needed. Thanks again!

**Comment by axw** [comment]
$$merge$$

**Comment by axw** [comment]
@stub42 can you please run "go fmt" on waitflag.go. While you're there, please copy the copyright header from one of the other files (changing the year).

**Comment by stub42** [comment]
Run go fmt and updated copyright stanzas and headers as requested

**Comment by axw** [comment]
$$merge$$

**Pull request merged**
