### PR TITLE
cmd/juju/user: correct padding for user registration string

### PR DESCRIPTION
**Pull request by 4a6f656c**
The current code incorrectly pads the ASN.1 encoded user registration
data with remainder bytes, rather than padding it to a multiple of
three bytes. This results in equal signs being appended for base64
padding.

Also add test coverage that verifies the registration string only
consists of alphanumeric characters.

### CODE REVIEW

**Comment by babbageclunk** [comment]
Actually, I got @howbazaar  to do it.

$$merge$$

**Comment by babbageclunk** [comment]
Let's try now.

$$merge$$

**Comment by babbageclunk** [comment]
gofmt is unhappy with this - line 118 of add_test.go should be:
``` go
s.mockAPI.secretKey = []byte(strings.Repeat("X", 32+i))
```
(No spaces in `32+i`.)

I'd fix it but I don't have the privs required to edit the PR.

**Comment by 4a6f656c** [comment]
Ugh, fixed!

**Comment by babbageclunk** [comment]
Sorry, missed that this was updated.

$$merge$$

**Pull request merged**
