### PR TITLE
Change version to 2.2.0-alpha1.

### PR DESCRIPTION
**Pull request by anastasiamac**
What is source-tag in snapcraft.yaml? Should it be changed to 2.2... something as well?

### CODE REVIEW

**Comment by sinzui** [comment]
LGTM, thank you.

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
2.2.0-alpha1 is not a valid version. Changed to 2.2-alpha1

**Comment by anastasiamac** [comment]
$$merge$$

**Pull request merged**
