### PR TITLE
[JUJU-2990] Refactor add-cloud command docs

### PR DESCRIPTION
**Pull request by tmihoc**
Moved Examples and See also to fields inside Info for the add-cloud command.

## Checklist

*If an item is not applicable, use `~strikethrough~`.*

- [x ] Code style: imports ordered, good names, simple structure, etc
- [ ] Comments saying why design decisions were made
- [ ] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/develop/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

 Run `juju documentation --split --out=tmp` 

## Documentation changes

This is a documentation PR.

### CODE REVIEW

**Comment by juanmanuel-tirado** [comment]
Run go format and push again.
`gofmt -s -w cmd/juju/cloud/add.go`

**Review by juanmanuel-tirado — APPROVED** [review]
LG2M

Thanks

**Review by juanmanuel-tirado — APPROVED** [review]
LG2M

**Comment by juanmanuel-tirado** [comment]
The static analysis has failed

**Comment by tmihoc** [comment]
Ran `gofmt -s -w cmd/juju/cloud/add.go` and didn't find any errors.

**Comment by hpidcock** [comment]
I fixed the issue with the code changes, but it looks like the Examples field is never used with juju commands across the rest of the codebase, so I'm not sure we want it this way. All the other commands just put the examples as apart of the help text.

**Pull request merged**
