### PR TITLE
fix(tests): unregister tests checks for empty controllers.yaml

### PR DESCRIPTION
**Pull request by nvinuesa**
In https://github.com/juju/juju/pull/17516 we added the ability to switch controllers, and this adds fields on the controllers.yaml file for the juju client.

Since our unregister test checks for that file to have no controllers, and it's a textual comparison, we need to also add the line
```
has-controller-changed-on-previous-switch: false
```
which will always be on controllers.yaml

## Checklist

- [ ] ~Code style: imports ordered, good names, simple structure, etc~
- [ ] ~Comments saying why design decisions were made~
- [ ] ~Go unit tests, with comments saying what you're testing~
- [X] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing
- [ ] ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

```
cd tests && ./main.sh -v cli test_unregister 
```

## Links

**Jira card:** JUJU-6887

### CODE REVIEW

**Review by Aflynn50 — APPROVED** [review]
LGTM

**Review by gfouillet — APPROVED** [review]
LGTM & QA ok

**Pull request merged**
