### PR TITLE
lxdclient: add a flag indicating whether to check the local bridge co…

### PR DESCRIPTION
**Pull request by tych0**
…nfig

The problem here is a chicken and egg problem: the container type needs to
connect to the local LXD to figure out how to configure the bridge,
but lxdclient has code to check the (old style) bridge configuration when
connecting to the local LXD.

Really, this code that checks the bridge configuration should live in the
LXD provider, but I suspect that there'd need to be some abstraction
untangling to do that.

Instead, for now, let's add a boolean flag to Connect() that just indicates
whether or not we should verify the bridge configuration.

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

### CODE REVIEW

**Comment by wallyworld** [comment]
$$merge$$

**Comment by tych0** [comment]
$$merge$$

**Comment by howbazaar** [comment]
$$merge$$

**Comment by howbazaar** [comment]
$$merge$$

**Pull request merged**
