### PR TITLE
Change dependencies to use go-1.10.

### PR DESCRIPTION
**Pull request by jameinel**
## Description of change

This also reformats our code base to match go-1.10 expectations.

## QA steps

Test suite and CI should pass with Go 1.10 instead of Go 1.9.

## Documentation changes

None.

## Bug reference

None.

### CODE REVIEW

**Comment by jameinel** [comment]
!!build!!

**Comment by jameinel** [comment]
[use go 1.10 in 2.3 and develop](https://trello.com/c/iFDLHLDF/118-use-go-110-in-23-and-develop)

**Comment by jameinel** [comment]
$$merge$$

**Comment by nskaggs** [comment]
Looks like I missed this :-) I wanted to mention updating the README.md as well to mention we've revved to go 1.10. That said, we would also need to add go 1.10 to the golang ppa if we wanted the instructions for apt installation to stay the same. We should probably just point at ppa:gophers/archive instead.

**Comment by nskaggs** [comment]
One more thing to note for future reference. Due to 

https://bugs.launchpad.net/snapcraft/+bug/1616985

we are forced into using the golang ppa as go for the snap builds. Therefore, we must ensure https://code.launchpad.net/~juju/+archive/ubuntu/golang/+packages is also revved to the version of go we want (and specifically, golang-defaults).

**Comment by jameinel** [comment]
does this mean we need to revert this from 2.3 while we sort it out in
develop, and then bring it back to 2.3 possibly for 2.3.6?

John
=:->

**Comment by jameinel** [comment]
we should leave the test suite fixes but we could revert the formatting and
dependency on 1.10. Especially if it is going to be a problem to release
2.3.5. Obviously it was enough for developers but that doesn't mean all the
release works.

John
=:->

**Comment by nskaggs** [comment]
No, I took care of the issue with the ppa by copying in the golang 1.10 packages, and a suitable golang-defaults. However this is domain knowledge that needs captured everytime we want to rev a go version. Slightly more involved than desirable, but a far cry from before, trust me :-). Ideally that bug would be fixed, and then it would be as simple as this PR.

**Comment by nskaggs** [comment]
To be clear, nothing was broken by this, but during a release the snaps are built against the ppa version of go, due to the mentioned bug. Inside of tooling / CI we control, we utilize the snap and can rev it as you've done.

**Pull request merged**
