### PR TITLE
Merge intermittent test fix from 2.7 to develop

### PR DESCRIPTION
**Pull request by babbageclunk**
## Description of change
This merges in the change from #11055 to the develop branch to fix the TestWatchRelationChangesV1Fallback test.

## QA steps

Running the test under stress-race doesn't fail anymore.

## Documentation changes
None

## Bug reference
None

### CODE REVIEW

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
