### PR TITLE
Add juju-ci-tools and juju-release-tools

### PR DESCRIPTION
**Pull request by nskaggs**
## Description of change

This change brings in the QA and CI tests and tools that were managed as separate projects. Yay!

Note, most authors match, but in cases where they don't, it's simpler to add the associated email to the github account vs rewriting history (I fixed mine by just adding the additional email).

This diff insanely large, so in summary

lp:juju-ci-tools -> acceptancetests
lp:juju-release-tools -> releasetests

All history from the bzr repo was preserved, and the commits are intermingled now with the rest of the greater juju repository. 

## QA steps

No change, but we'll have to update our tooling to utilize this location and deprecate the old locations for these projects.

## Documentation changes

N/A

## Bug reference

N/A

### CODE REVIEW

**Comment by bz2** [comment]
What method did you use to create this PR? The branch as presented does not preserve history, all the added files in the final revision are seen as new.

Compare:

https://github.com/nskaggs/juju/commits/fcd484dbc50d477d26d86c5f23186f7c57a2f40d/acceptancetests/Makefile

https://github.com/nskaggs/juju/commits/d370579ac762d0f54cbcd88a8e9d328bace00eb4/Makefile

**Comment by nskaggs** [comment]
@bz2 That's kind of odd. I used subtree merging to create this. You can see it did intermingle the history, and it seemed legit, hmm.

**Comment by nskaggs** [comment]
Are we happy with the quasi lost history? You can see the changes, but as pointed out, you can see a file's history anymore directly. I think this is a knock on affect of the subtree merge, but maybe I could do it better.

**Comment by nskaggs** [comment]
Actually, I think I can link them by committing a move. I'll try.

**Comment by nskaggs** [comment]
Idea failed. I'm happy as-is though if others are.

**Comment by nskaggs** [comment]
$$merge$$

**Pull request merged**
