### PR TITLE
Merge 2.9 into develop

### PR DESCRIPTION
**Pull request by manadart**
Merge from 2.9 bringing forward:
- #13546 from manadart/2.9-unit-charm-url
- #13564 from jujubot/increment-to-2.9.23
- #13556 from hmlanigan/deploy-bundle-2-8-controller

Minor conflicts including those typical to version bumps:
- apiserver/facades/agent/uniter/mocks/newlxdprofile.go
- cmd/juju/application/deployer/bundlehandler_test.go
- scripts/win-installer/setup.iss
- snap/snapcraft.yaml
- version/version.go

### CODE REVIEW

**Review by hmlanigan — APPROVED** [review]
LGTM, thank you.

**Comment by manadart** [comment]
Test failures:
- `BundleDeployRepositorySuite.TestDeployBundleSwitch`
- `BundleDeployRepositorySuite.TestDeployBundleTwiceScaleUp`

**Comment by hpidcock** [comment]
> Test failures:
> 
> * `BundleDeployRepositorySuite.TestDeployBundleSwitch`
> * `BundleDeployRepositorySuite.TestDeployBundleTwiceScaleUp`

@hmlanigan any insights on these two tests? it looks related to #13556

**Comment by hmlanigan** [comment]
@hpidcock, yes, new tests in develop which needed to be fix for #13556.  fixed them.

**Comment by hmlanigan** [comment]
$$merge$$

**Pull request merged**
