### PR TITLE
Include offer acl in export bundle output

### PR DESCRIPTION
**Pull request by achilleasa**
## Description of change

This PR brings in the changes from juju/description and charms.v6 and updates the bundle exporting code to include an ACL for each offer.

In addition, the (server-side) bundle exporting code will now suppress the offer list from the output unless the `bundle-cmr` feature flag has been set. This change is intentional as we don't want older clients to receive bundles with offers when they talk to a newer controller. 

This seems like a good idea, given that we may need to further tweak the bundle struct further until all the cmr in bundle bits land. For instance: we haven't yet reached a decision regarding whether the ACLs should be part of an overlay or not, etc.

## QA steps

```console 
$ export JUJU_DEV_FEATURE_FLAGS=bundle-cmr
$ juju bootstrap lxd test --no-gui

$ juju deploy ./testcharms/charm-repo/bundle/apache2-with-offers

Resolving charm: cs:apache2-26
Executing changes:
- upload charm cs:apache2-26 for series bionic
- deploy application apache2 on bionic using cs:apache2-26
- create offer my-offer using apache2:apache-website,website-cache
- create offer my-other-offer using apache2:apache-website
Deploy of bundle completed.

# Add a new user and grant them consume access to the offer
$ juju add-user foo
$ juju grant foo consume admin/default.my-offer

$ juju export-bundle
series: bionic
applications:
  apache2:
    charm: cs:apache2-26
    offers:
      my-offer:
        endpoints:
        - apache-website
        - website-cache
        acl:
          admin: admin
          everyone@external: read
          foo: consume
      my-other-offer:
        endpoints:
        - apache-website
        acl:
          admin: admin
          everyone@external: read
```

### CODE REVIEW

**Comment by mitechie** [comment]
can we use a simpler form like "bundle-cmr" or the like for the flag please?

**Comment by mitechie** [comment]
or maybe just "bundle" or "bundledev"

**Comment by achilleasa** [comment]
@mitechie I used this name to keep it similar with `trusted-bundles`. It's only a temporary flag but happy to push a commit and change it to something like `bundle-cmr` though...

**Comment by mitechie** [comment]
ok

**Comment by achilleasa** [comment]
!!build!!

(windows build aborted)

**Comment by achilleasa** [comment]
$$merge$$

(units tests pass but windows box is acting up and blocking the windows CI job)

**Pull request merged**
