### PR TITLE
Use netlink to retrieve observed machine addresses

### PR DESCRIPTION
**Pull request by manadart**
This patch addres a new dependency, [netlink](https://github.com/vishvananda/netlink), and uses it to discover on-machine IP addresses.

Unlike the standard library `net` package, `netlink` surfaces address flags, allowing us to detect when an IP is a secondary address via the `IFA_F_SECONDARY` flag. This detection and reporting will come in a subsequent patch.

To test:
- Bootstrap to LXD
- Connect to Mongo and check that we still get addresses:
```
juju:PRIMARY> db.ip.addresses.find().pretty()
{
        "_id" : "ffff009d-f244-4a8b-8de4-5107bc8d6bb4:m#0#d#lo#ip#127.0.0.1",
        "model-uuid" : "ffff009d-f244-4a8b-8de4-5107bc8d6bb4",
        "device-name" : "lo",
        "machine-id" : "0",
        "subnet-cidr" : "127.0.0.0/8",
        "config-method" : "loopback",
        "value" : "127.0.0.1",
        "origin" : "machine",
        "txn-revno" : NumberLong(2),
        "txn-queue" : [
                "5f96bcc52f987a1dcf1de8fe_19a8f071"
        ]
}
{
        "_id" : "ffff009d-f244-4a8b-8de4-5107bc8d6bb4:m#0#d#lo#ip#::1",
        "model-uuid" : "ffff009d-f244-4a8b-8de4-5107bc8d6bb4",
        "device-name" : "lo",
        "machine-id" : "0",
        "subnet-cidr" : "::1/128",
        "config-method" : "loopback",
        "value" : "::1",
        "origin" : "machine",
        "txn-revno" : NumberLong(2),
        "txn-queue" : [
                "5f96bcc52f987a1dcf1de8fe_19a8f071"
        ]
}
{
        "_id" : "ffff009d-f244-4a8b-8de4-5107bc8d6bb4:m#0#d#eth0#ip#10.161.87.173",
        "model-uuid" : "ffff009d-f244-4a8b-8de4-5107bc8d6bb4",
        "device-name" : "eth0",
        "machine-id" : "0",
        "subnet-cidr" : "10.161.87.0/24",
        "config-method" : "static",
        "value" : "10.161.87.173",
        "gateway-address" : "10.161.87.1",
        "is-default-gateway" : true,
        "origin" : "machine",
        "txn-revno" : NumberLong(3),
        "txn-queue" : [
                "5f96bcd02f987a1dcf1deac4_0f8685ed"
        ],
        "provider-network-id" : "net-lxdbr0",
        "provider-subnet-id" : "subnet-lxdbr0-10.161.87.0/24"
}
```

### CODE REVIEW

**Comment by manadart** [comment]
[Secondary addresses returned for relation endpoints](https://trello.com/c/pFR7PzxT/3030-secondary-addresses-returned-for-relation-endpoints)

**Comment by petevg** [comment]
For the record, I'm +1 to moving forward with this dependency change.

What are the reasons that we might not want to do so?

**Comment by jameinel** [comment]
Just to discuss the concept about dependencies, irrespective of this specific library.
Every dependency we bring in is something that needs to be maintained. If there are security/bugs in the library, we have to have a solution for it. Whether we fork it and maintain it ourselves, upstream is good at maintaining the library, etc.
It is less about whether the dependency provides the functionality, and more about whether we trust that the library will continue to be maintained.

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by manadart** [comment]
This patch served its purpose as an illustrative example.
A real implementation patch will be submitted presently.

**Pull request closed without merging**
