### PR TITLE
Fix backups under non-linux.

### PR DESCRIPTION
**Pull request by ericsnowcurrently**
Fixes https://bugs.launchpad.net/juju-core/+bug/1420426.

(Review request: http://reviews.vapour.ws/r/907/)

### CODE REVIEW

**Comment by ericsnowcurrently** [comment]
$$merge$$

**Comment by ericsnowcurrently** [comment]
$$fixes-1420426$$

**Comment by ericsnowcurrently** [comment]
$$fixes-1420426$$

**Comment by ericsnowcurrently** [comment]
$$fixes-1420426$$

**Comment by howbazaar** [comment]
$$maybe-intermittent$$

**Pull request merged**
