### PR TITLE
chore: api/agent context aware

### PR DESCRIPTION
**Pull request by SimonRichardson**
Threads through the `context.Context` for every method in the
`api/agent` package. This is a long and laborious set of manual changes.
The motivation behind this, is to allow observability from all agents
to the controller. The premise is to understand better how
calls interact with the server. This can help us better diagnose
the behaviour in the system and identify and fix bugs or
performance issues.

The client and controller API packages will follow in due course.

All of the code changes are mechanical, they're just either passing
in a context.Context from the parent caller or creating a scoped
context for things like workers.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing

## QA steps

```sh
$ juju bootstrap lxd test
$ juju add-model default
$ juju deploy ubuntu
```

## Links

~~**Jira card:** JUJU-~~ (external contribution)

### CODE REVIEW

**Comment by hpidcock** [comment]
Clean up the conflicts, then ping me and I'll set aside time to review this monster.

**Review by manadart — APPROVED** [review]
I did some grepping for background/TODO contexts, and I think you've got it covered here.

**Comment by SimonRichardson** [comment]
@hpidcock therenis an intermittent test failure in the uniter that I need to look at, otherwise this is ready for review

**Pull request merged**
