### PR TITLE
Merge 2.8 to 2.9

### PR DESCRIPTION
**Pull request by tlm**
Merge of 2.8 into 2.9.

Conflicts:
scripts/win-installer/setup.iss
snap/snapcraft.yaml
version/version.go

### CODE REVIEW

**Review by wallyworld — APPROVED** [review]

**Comment by tlm** [comment]
$$merge$$

**Comment by tlm** [comment]
$$merge$$

**Comment by tlm** [comment]
$$merge$$

**Comment by tlm** [comment]
$$merge$$

**Pull request merged**
