### PR TITLE
Get rid of assess_lxd_space test - it's no longer needed

### PR DESCRIPTION
**Pull request by wupeka**
## Description of change
assess_lxd_space test is no longer needed as we have container networking on AWS with FAN. This is only a test change.

### CODE REVIEW

**Comment by wupeka** [comment]
!!test!!

**Comment by wupeka** [comment]
@jameinel IMHO we should get rid of this as it is now, we might want to test spaces on AWS but that's not the way to do it.

**Comment by nskaggs** [comment]
I would prefer to see a substrate agnostic test in it's place, mirroring the changes to juju's internal networking codebase. However, this test was a stop-gap measure to prevent regressions until juju changed. That time has come, so it's served it's purpose. It would be useful to undertake a systematic review of the current networking specific feature tests to ensure you have coverage of everything desired.

**Comment by nskaggs** [comment]
$$merge$$

**Pull request merged**
