### PR TITLE
juju deploy create allocation ecotools

### PR DESCRIPTION
**Pull request by tasdomas**
(Review request: http://reviews.vapour.ws/r/3706/)

### CODE REVIEW

**Comment by tasdomas** [comment]
$$merge$$

**Comment by cmars** [comment]
$$merge$$ i said

**Comment by cmars** [comment]
$$merge$$ connection is shut down flakiness

**Comment by tasdomas** [comment]
$$merge$$ ?

**Comment by cmars** [comment]
$$bangs-head$$

**Comment by tasdomas** [comment]
$$merge$$

**Pull request merged**
