### PR TITLE
Fix Go 1.8 test failures (1.25 branch)

### PR DESCRIPTION
**Pull request by axw**
## Description of change

Back port various fixes from the develop branch, to enable building/testing with Go 1.8.

## QA steps

Run the tests with go 1.8.

## Documentation changes

None.

## Bug reference

None.

### CODE REVIEW

**Comment by axw** [comment]
$$merge$$

**Comment by nskaggs** [comment]
$$merge$$

**Comment by nskaggs** [comment]
$$merge$$

**Comment by axw** [comment]
$$merge$$

**Comment by jameinel** [comment]
[LOG] 0:01.013 DEBUG juju.worker no restart, removing "state" from known workers
upgrade_test.go:454:
    s.assertStateServerUpgrades(c)
upgrade_test.go:827:
    // System SSH key
    c.Assert(s.keyFile(), jc.IsNonEmptyFile)
... obtained string = "/mnt/tmp/check-7656312464723085864/240/var/lib/juju/system-identity"
... /mnt/tmp/check-7656312464723085864/240/var/lib/juju/system-identity does not exist


and
fatal error: concurrent map writes

goroutine 3571 [running]:
...
created by github.com/juju/juju/provider/maas.(*maasStorage).RemoveAll
	/home/ubuntu/juju-core_1.25.12/src/github.com/juju/juju/provider/maas/storage.go:238 +0x136
FAIL	github.com/juju/juju/provider/maas	7.369s

and some uniter failures remain.

**Comment by axw** [comment]
I believe they're all existing races, but I'll see what I can do to fix them.

**Comment by axw** [comment]
The uniter and maas things are existing issues: MAAS is in gomaasapi, and uniter is just the old 1.25 uniter test races that we've had since forever. The cmd/jujud/agent one was a race in the test.

$$merge$$

**Comment by axw** [comment]
$$merge$$

**Pull request merged**
