### PR TITLE
2.4 into 2.5

### PR DESCRIPTION
**Pull request by jameinel**
## Description of change

Sync 2.4 into 2.5. Bringing in:
 * Merge pull request #9445 from timClicks/2.4-add-rng-seed
 * Merge pull request #9443 from howbazaar/2.4-logpruner-report

## QA steps

See individual patches.

## Documentation changes

See individual patches.

## Bug reference

 * https://bugs.launchpad.net/juju/+bug/1802824

### CODE REVIEW

**Comment by jameinel** [comment]
$$merge$$ self approving a merge of 2.4 into 2.5

**Comment by jameinel** [comment]
$$merge$$ I had missed that 2.4 added an import of juju/utils/clock but 2.5 uses juju/clock.

**Comment by jameinel** [comment]
$$merge$$ when fixing the import, needed to sort it as well

**Comment by mitechie** [comment]
$$merge$$

Something with the machine charm updater that these commits should not have messed with.

**Comment by mitechie** [comment]
Porting over to https://github.com/juju/juju/pull/9456 to try to get landed.

**Comment by mitechie** [comment]
I screwed up and mixed up this PR with the one with the patches removal branch and closed the wrong one. Ian says he's moved the 2.4-add-rng-seed branch and the one from Tim needs some test fixes for 2.5 so letting this run to get the test run output for @howbazaar but don't think it really should merge or need to merge in the end.

**Comment by howbazaar** [comment]
Superceded by #9459

**Pull request closed without merging**
