### PR TITLE
apiserver - split the HTTP server out of the API server

### PR DESCRIPTION
**Pull request by babbageclunk**
## Description of change

- extracts `worker/httpserver` out of the API server. 
- introduce Authenticator and Authorizer interfaces for
  authenticating/authorizing HTTP requests
- split out a basic auth handler that wraps other
  handlers, and uses a provided Authenticator and Authorizer
- introduces a table defining endpoints in apiserver/apiserver.go,
  along with which ones require authentication, authorizers to
  use, which to track, etc.
- updates various apiserver tests to use a new base suite,
  rather than JujuConnSuite
- drops various apiserver tests which repeat testing auth
  and model UUID validation, which are orthogonal of the
  endpoints being tested.

There are numerous benefits to this (IMO), but the primary goal
is to enable rafttransport to attach to the httpserver mux, allowing
the raft object to fed into the apiserver worker.

## QA steps

Bootstrap a new controller, deploy some applications to it and relate them. Make sure upgrading the controller and hosted model works.

### CODE REVIEW

**Comment by babbageclunk** [comment]
BLOODY YES! <frolics maniacally>

**Comment by babbageclunk** [comment]
I think I've found a simple way to have the httpserver wait until the apiserver's stopped too. Since we're good and always remove the handlers we add to the mux, I can put a `wg.Add(1)` in AddHandler and `wg.Done()` in RemoveHandler. Then the httpserver worker can just wait on that group.

Trying it out it seems to work. 

Hmm, but I think there's something bad happening in the autocert handling that's preventing the cerver from shutting down, so I'm digging into that.

**Comment by babbageclunk** [comment]
No, that was fiddly and unnecessary - it meant that the authenticator also needs to be careful remove all its handlers, even though it's really not a client of the httpserver. Doing it the simpler and more explicit way now.

**Comment by babbageclunk** [comment]
!!chittychitty!!

**Comment by babbageclunk** [comment]
Hmm, I keep getting intermittent failures - first in the login delay tests (http://ci.jujucharms.com/job/github-check-merge-juju/631/console) and then in the show-output command tests (http://ci.jujucharms.com/job/github-check-merge-juju/632/console).

This former could be something to do with this change, I don't think the latter could be. Rerunning under the stress test script hasn't allowed reproducing the failures. Still trying to solve them.

**Comment by babbageclunk** [comment]
!!build!!

**Comment by babbageclunk** [comment]
Reviewed with @wallyworld on a hangout, he said he was happy for this to be landed (once I made the changes below).

* pull worker/httpserver/httpcontext and stateauthenticator types used in apiserver into apiserver/http
* remove AutocertDNSName from ServerConfig? Also APIserver worker.
* logtransfer handler needs to convert model notfound to UnknownModel
* resources migration test - unknown model errors here as well
* rest_test.go - reinstate -func (s *restSuite) TestGetRejectsWrongModelUUIDPath(c *gc.C) {
* move TestMinTLSVersion to HTTP server
* find uses of httpRequestParams and replace them with apiserver/testing/http.HTTPRequestParams
* move utils/bakeryutil/service back under apiserver.
* no header in worker/httpserver/stateauthenticator/auth.go
* chase down the start pinger logic - explain clearly that this pinger is for presence, which is why we don't want it for anonymous agents.

The only change I didn't make (of the above) was reinstating TestGetRejectsWrongModelUUIDPath - after trying it it became clear why it had been deleted. From my reading that endpoint didn't originally have any authentication, it's now protected by the normal username/password basic auth that the other endpoints have. The consequence of that is that the test doesn't ever get the "unknown model" error from trying to get a remote-app icon for a nonexistent model, because the authentication returns a 401 error before it gets to that point (there are no valid username/passwords in a model that doesn't exist). And we don't need to test that authentication here, it's already tested elsewhere.

**Comment by babbageclunk** [comment]
$$merge$$

**Comment by axw** [comment]
:tada:
glad to see this merged :)

**Comment by babbageclunk** [comment]
Thanks man - same! 🍻

**Pull request merged**
