### PR TITLE
Changed possible Status values.

### PR DESCRIPTION
**Pull request by perrito666**
There where changes in Unit status management.
Unit and Agent status used to be the same thing but
now have been split into two:
Workload
UnitAgent
Workload: holds statuses pertaining the actual workload
deployment such as hooks running and error in them.
UnitAgent: holds statuses for the juju agent running
on this unit.
A series of statuses has been added and valid statuses
for both have been defined.
Also a series of changes where necessary in tests that
where setting states that are no logner valid.
Finally juju status command suffered several changes
in the tests to reflect the two new values.

### CODE REVIEW

**Comment by wallyworld** [comment]
$$mergeandfollowupwithanotherbranchtoaddresstodos$$

**Comment by perrito666** [comment]
$$mergeandfollowupwithanotherbranchtoaddresstodos$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$FFS$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
