### PR TITLE
Merge 2.5 into 2.6

### PR DESCRIPTION
**Pull request by manadart**
Merge 2.5 into 2.6 bringing patch #10135.

Commits indicate #10100 coming in, but the child commits for that are already present - no file changes result from this.

### CODE REVIEW

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by mitechie** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by mitechie** [comment]
16:03:53 
FAIL: bootstrap_test.go:182: bootstrapSuite.TestBootstrap

$$merge$$ again

**Pull request merged**
