### PR TITLE
Move worker/modelworkermanager to dependency engine

### PR DESCRIPTION
**Pull request by axw**
## Description of change

Move worker/modelworkermanager to the machine agent dependency engine. Change the worker to use a StatePool to fetch Model objects, and remove the State.ModelActive helper.

## QA steps

Smoke test bootstrap/deploy/destroy-controller.

## Documentation changes

None.

## Bug reference

None.

### CODE REVIEW

**Comment by axw** [comment]
$$merge$$

**Comment by axw** [comment]
Build failed: ?

**Comment by axw** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
