### PR TITLE
Add resource tags to resource provisioning info

### PR DESCRIPTION
**Pull request by axw**
We now pass tags to set on resources (initially
instances, volumes and filesystems) through their
provisioning parameters, via the API. Tags make
their way into StartInstanceParams.InstanceConfig,
and into VolumeParams and FilesystemParams.

We introduce a new environs/tags package that holds
the names we use for common tags, as well as helpers
for creating tag sets.

The ec2 and openstack providers are updated to use
the tags when creating instances and volumes. Later
we should introduce a worker to keep tags up-to-date,
but for now we only set tags at instance creation
time.

(Review request: http://reviews.vapour.ws/r/1845/)

### CODE REVIEW

**Comment by axw** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by axw** [comment]
$$wat$$

**Comment by axw** [comment]
$$merge$$

**Comment by axw** [comment]
$$merge$$

**Pull request merged**
