### PR TITLE
Add Environ NetworkInterfaces for EC2

### PR DESCRIPTION
**Pull request by dooferlad**
This returns NetworkInterfaces information for an EC2 instance needed for container addressability.

(Review request: http://reviews.vapour.ws/r/824/)

### CODE REVIEW

**Comment by dooferlad** [comment]
$$ merge $$

**Comment by dooferlad** [comment]
$$mergethis$$

**Comment by dooferlad** [comment]
$$penguin$$

**Comment by dooferlad** [comment]
$$ping$$

**Comment by dooferlad** [comment]
$$ping$$

**Comment by dimitern** [comment]
$$landthisnow$$

**Pull request merged**
