### PR TITLE
acceptancetests: fix azure cleanup script

### PR DESCRIPTION
**Pull request by axw**
The Azure cleanup script has been broken since
we stopped using storage accounts in Juju, and
started using managed disks. There are several
changes in this PR to the script to fix and
improve matters:

 - we now use "deployments" to identify the
   age of a resource group. The timestamp of
   the oldest deployment in a resource group
   serves as the creation time of the group.
 - we now compare group names case-insensitively
   when filtering out "default-" groups.
 - we iterate through groups rather, rather
   than listing them all, when deleting a
   specific instance. This avoids fetching
   the details of groups unnecessarily.
 - we no longer load VMs, networks, etc. We
   now load only deployments. The VMs that
   Juju creates have the same name as the
   deployment that creates them; so deleting
   an instance needs only look through the
   deployments.

### CODE REVIEW

**Comment by axw** [comment]
[Fix Azure CI cleanup script](https://trello.com/c/B1p3qVmV/113-fix-azure-ci-cleanup-script)

**Comment by Veebers** [comment]
Nice, LGTM

**Comment by axw** [comment]
$$merge$$

**Comment by axw** [comment]
$$merge$$

**Pull request merged**
