### PR TITLE
Merge 2.6 into develop

### PR DESCRIPTION
**Pull request by manadart**
## Description of change

Merge 2.6 into develop for:
- #10358 from manadart/2.6-add-cache-config-settings
- #10357 from manadart/2.6-add-charm-config-defaults
- #10356 from achilleasa/2.6-apply-create-offer-changes-when-deploying-bundles
- #10353 from achilleasa/2.6-include-offers-in-exported-bundles
- #10349 from ycliuhw/fix/lp-1831770
- #10351 from manadart/2.6-branch-config-watch
- #10345 from hmlanigan/add-branch

### CODE REVIEW

**Comment by manadart** [comment]
[Merge 2.6 into Develop](https://trello.com/c/HT1qpkQv/1558-merge-26-into-develop)

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
Aborted. Trying to $$merge$$ again.

**Comment by hpidcock** [comment]
> Aborted. Trying to $$merge$$ again.

Sorry about that. Jenkins was upgraded and looked like the builds were not going to merge anyway.

**Pull request merged**
