### PR TITLE
Cloudimagesurlfix

### PR DESCRIPTION
**Pull request by thomnico**
This simple (hardcoded) fix allow to cache the initial lxc image when behind proxy and for orangebox. 

Ideally it should be set to image-metadata-url parameter.

Did test successfully on OB.

### CODE REVIEW

**Comment by thomnico** [comment]
Related to Bug #1357045 on launchpad

**Comment by thomnico** [comment]
#3153 created to track this

**Comment by mattyw** [comment]
@thomnico Is this still needed? If so can you resolve the conflicts?

**Comment by thomnico** [comment]
Working on moving to 1.24 or master (had to play on 1.22) and making it better (config option hopefully)

**Pull request closed without merging**
