### PR TITLE
Fixed lp:1414016 - Ensure LXC config has correct network settings ordering

### PR DESCRIPTION
**Pull request by dimitern**
This addresses the following critical bug - http://pad.lv/1414016.
In essence, the fix causes the generated LXC config files to have
correct ordering of lxc.network.* settings as the lxc tools expects.
All lxc.network.* settings found before an lxc.network.type setting
are moved after that lxc.network.type line.

This can mostly happen when cloning from a template with incorrect
settings, but is also enforced when not using lxc-clone for consistency.

Extensively tested with the local provider and different combinations
of lxc-clone, lxc-clone-aufs settings, trusty and precise images, in
a clean setup or with pre-existing juju-*-lxc-template containers.

(Review request: http://reviews.vapour.ws/r/802/)

### CODE REVIEW

**Comment by wallyworld** [comment]
$$fixes-1414016$$

**Comment by wallyworld** [comment]
$$fixes-1414016$$

**Comment by wallyworld** [comment]
$$fixes-1414016$$

**Comment by wallyworld** [comment]
$$fixes-1414016$$

**Comment by dimitern** [comment]
__JFDI__
$$fixes-1414016$$

**Comment by dimitern** [comment]
Aw c'mon... there is not a __single__ file in the repo containing "labix.org" except some slightly outdated docs! CI scripts seem overzealous.

**Comment by dimitern** [comment]
$$tryagain$$

**Pull request merged**
