### PR TITLE
[JUJU-1460] Recreated ubuntu test charm.

### PR DESCRIPTION
**Pull request by juanmanuel-tirado**
Recreate the test Ubuntu charm to use the latest template generated by charmcraft 1.7.1

## Checklist

NA

## QA steps

NA

## Documentation changes

NA

## Bug reference

NA

### CODE REVIEW

**Review by manadart — APPROVED** [review]
Do we need to check the license into the code-base? Not a big deal; we've still come up with a net deletion of lines...

**Comment by juanmanuel-tirado** [comment]
I will leave the license only for the sake of legality

**Comment by anvial** [comment]
Just in case, I checked the smoke test for aws cloud. 
It was successful.
https://pastebin.canonical.com/p/4wg4g8n6mC/

**Pull request merged**
