### PR TITLE
'update-credential' checks models.

### PR DESCRIPTION
**Pull request by anastasiamac**
## Description of change

Updating credential content on the controller, 'update-credential' command, now also checks the models that use this credential.

We provide more detailed output - what models have been checked? are they visible? if not visible, why?

The PR updates adds new facade call - UpdateCredentialsCheckModels - to version 3 of "Cloud" facade, removing "UpdateCredentials".

### CODE REVIEW

**Comment by anastasiamac** [comment]
!!build!!

**Comment by Veebers** [comment]
!!build!!

**Comment by Veebers** [comment]
!!build!!

**Comment by anastasiamac** [comment]
re-base went wrong: will re-propose once cloud facade changes land and the area is stable.

**Pull request closed without merging**
