### PR TITLE
Forward port fix for lp#1742697

### PR DESCRIPTION
**Pull request by anastasiamac**
## Please provide the following details to expedite Pull Request review:

----

## Description of change
Forward port of merge #8281 

## Bug reference

https://bugs.launchpad.net/juju/+bug/1742697

### CODE REVIEW

**Comment by anastasiamac** [comment]
$$merge$$
self-approving as a straightforward forward port.

**Comment by anastasiamac** [comment]
$$merge$$

unrelated intermittent failure

**Comment by jameinel** [comment]
Shouldn't we just be able to merge 2.3 into develop, rather than needing
individual patches and worrying whether we are in sync or not? Hopefully
that leads  to less work for you.

John
=:->

**Comment by anastasiamac** [comment]
@jameinel,
After recent painful merges, it has been decided that individual patches need to be forward-ported rather than the global-merge-all approach. It has been discussed at team meeting and has been decided that individual forward ports by the author are the best and most efficient way forward.

**Comment by jameinel** [comment]
Sorry to hear that. I had spent a lot of time to clean it up to make it
possible again. Hate to see us lose that.

John
=:->

**Comment by anastasiamac** [comment]
Your painful experience is precisely what prompted the decision - to avoid the repeat of pain :)

**Comment by jameinel** [comment]
The pain was only because we weren't maintaining it. Once it was done, it
is actually fairly easy to keep it up. Its the fact that we *weren't*
keeping it up that made it hard.

John
=:->

**Pull request merged**
