### PR TITLE
Update gomod for current LXD

### PR DESCRIPTION
**Pull request by stgraber**
Bump to 1.18 and refresh the LXD entry to be the latest version on our side.

### CODE REVIEW

**Comment by stgraber** [comment]
@manadart can you check the go.mod for whatever package usually caused you issues?

I didn't see anything raft-related in there and as I mentioned yesterday, we've removed our old dqlite logic so we don't have anything raft-related in LXD at all (at least not in Go).

**Comment by stgraber** [comment]
Branch isn't building because a bunch of things need updating for 1.18.

**Comment by manadart** [comment]
Thanks for this @stgraber. We would have to update our build infra for a move to Go 1.18, but the deps part looks like we've worked around the issue that we had with msgpack. I'll look at cherry-picking what we need onto a patch targeting 2.9.

**Comment by wallyworld** [comment]
PR #14000 updated juju 2.9 to use go 1.18 - will be carried forward to develop also

**Comment by tomponline** [comment]
@stgraber @manadart @wallyworld I'm not sure this PR should have been closed. Although PR #14000 does update Juju to use Go 1.18, it is missing the change from this PR that updates Juju to use the latest LXD client package.

I'm seeing it is still using a version from 2021 (https://github.com/juju/juju/blob/2.9/go.mod#L88) which has known limitations around error code handling.

Can we get this reopened?

**Comment by manadart** [comment]
Doing it under https://github.com/juju/juju/pull/14102.

**Pull request closed without merging**
