### PR TITLE
cmd/juju/package_test.go: Trivial spelling

### PR DESCRIPTION
**Pull request by mattyw**
(Review request: http://reviews.vapour.ws/r/1574/)

### CODE REVIEW

**Comment by mattyw** [comment]
$$merge$$

**Comment by mattyw** [comment]
$$merge$$

**Comment by mattyw** [comment]
$$merge$$

**Comment by mattyw** [comment]
$$merge$$

**Comment by bz2** [comment]
Build failed: github outage

**Comment by bz2** [comment]
$$merge

**Pull request merged**
