### PR TITLE
Introduce jaas-plugin plug

### PR DESCRIPTION
**Pull request by kian99**
This PR introduces a plug into Juju CLI's Snap, allowing it to be connected to a JAAS snap that will be used to extend the Juju CLI with functionality for JAAS. This PR follows from a similar [PR in JAAS](https://github.com/canonical/jimm/pull/1149) where we introduce the new Snap. The below is copied from that PR.
>The mechanism by which it  does this (extending the Juju CLI's functionality) is [Juju Plugins](https://juju.is/docs/juju/plugins) and Snapcraft's [content-interface](https://snapcraft.io/docs/content-interface). The juju-jaas snap shares a binary of the same name to a directory within the Juju Snap that is readable by the CLI. Because the name of the binary is juju-* the binary can be invoked via `juju jaas <command>`. It is still TBD whether it is okay to namespace the JAAS commands to `juju jaas` or whether all the JAAS commands should be surfaced as top-level commands under the Juju CLI. Regardless, the specifics for how JAAS commands are invoked can be easily changed after this by introducing symlinks/bash scripts into the JAAS Snap's `$SNAP/bin` directory of the form juju-<command> e.g. `juju-add-service-account`.

## Checklist

~- [ ] Code style: imports ordered, good names, simple structure, etc~
~- [ ] Comments saying why design decisions were made~
~- [ ] Go unit tests, with comments saying what you're testing~
~- [ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
~- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

Note these steps require branch https://github.com/canonical/jimm/pull/1149 to be merged, checkout that branch if you need to.

In the Juju repo:
- `snapcraft`
- `sudo snap install --dangerous --devmode ./<juju-snap-file>`

In a new folder:
- `git clone https://github.com/canonical/jimm.git`
- `git checkout feature-serviceaccounts`
- `make jaas-snap`
- `sudo snap install --dangerous --devmode ./<jaas-snap-file>`
- `sudo snap connect juju:jaas-plugin juju-jaas`
- `juju jaas --help`
- `juju jaas add 1234`

### CODE REVIEW

**Comment by kian99** [comment]
cc @jameinel @wallyworld this is for the JAAS plugin as discussed.

**Comment by wallyworld** [comment]
We should look to land this in 3.5 rather than 3.4?
Also, I'm not certain if it's the case with this particular plug, but when the dot-minikube plus was added, and was not yet approved by the security team, we couldn't publish any snaps until it got a +1. It may be that was because we were exposing a dot file in $HOME, and this one might be ok, but worth checking.
Do we need to land this now? You can make your own confined snap and install that right? And then you can get everything all designed and done before committing any changes to a publicly released juju snap.

**Comment by kian99** [comment]
@wallyworld We don't need to land it now, but there is no further work needed on Juju's end so it would be nice to land it and have everything just work when we release the JAAS snap. But I'll close the PR, determine if there is any issue with the Snapstore/Security team and then re-open this at a later date.
One question to discuss before I close the PR however, do you think the JAAS plugin commands should be namespaced under JAAS? I.e. `juju jaas <commands>` or should they all be surfaced top-level under `juju <commands>`?

**Comment by kian99** [comment]
And one other question, should this plug/content-interface be specifically for JAAS or should the plug be a generic for all plugins?

**Pull request closed without merging**
