### PR TITLE
Remove upgrades from state

### PR DESCRIPTION
**Pull request by SimonRichardson**
~~Requires https://github.com/juju/juju/pull/16496 to land first~~

----

This is the final piece for upgrades. We no longer provide logic
for upgrades in the state package. Upgrade logic should now only be
found in the domain upgrade package.

In doing the following, we have to blackhole the AbortModelUpgrade
method. The AbortModelUpgrade is now not supported. There is no way
to roll back in the current implementation. We don't currently have
a way to back up the databases easily and then roll back if they fail.
Nor do we have rollbacks implemented correctly in migrations, so more
thought would be needed.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing

### Idempotent updates

For changes that don't upgrade the version, then this flow works:

```sh
$ juju bootstrap lxd test --build-agent
$ juju add-model default
$ juju upgrade-controller --build-agent
```

Notice that the upgrade does not run the upgrade database/steps. This is essentially a no-op with the side effect of a restart and a build version increment.

### Verify the upgrade works with a version increase.

This will test that the upgrade database worker is called, you need to apply the following diffs:

```diff
diff --git a/environs/sync/sync.go b/environs/sync/sync.go
index fa63d84426..f536f5e434 100644
--- a/environs/sync/sync.go
+++ b/environs/sync/sync.go
@@ -316,12 +316,12 @@ func buildAgentTarball(
        builtVersion.Build = 0
        clientVersion := jujuversion.Current
        clientVersion.Build = 0
-       if builtVersion.Number.Compare(clientVersion) != 0 {
-               return nil, errors.Errorf(
-                       "agent binary %v not compatible with bootstrap client %v",
-                       toolsVersion.Number, jujuversion.Current,
-               )
-       }
+       // if builtVersion.Number.Compare(clientVersion) != 0 {
+       //      return nil, errors.Errorf(
+       //              "agent binary %v not compatible with bootstrap client %v",
+       //              toolsVersion.Number, jujuversion.Current,
+       //      )
+       // }
        fileInfo, err := f.Stat()
        if err != nil {
                return nil, errors.Errorf("cannot stat newly made agent binary archive: %v", err)
```

Then update the patch version in `version/version.go`

```diff
diff --git a/version/version.go b/version/version.go
index 33b01db1af..3f599876ed 100644
--- a/version/version.go
+++ b/version/version.go
@@ -18,7 +18,7 @@ import (
 // The presence and format of this constant is very important.
 // The debian/rules build recipe uses this value for the version
 // number of the release package.
-const version = "4.0-beta1"
+const version = "4.0-beta2"

 // UserAgentVersion defines a user agent version used for communication for
 // outside resources.
```

Incrementing the version will then log after the `juju upgrade-controller --build-agent`.

```
2023-10-30 16:46:06 INFO juju.worker.dbaccessor worker.go:618 serving Dqlite application (ID: 3297041220608546238)
2023-10-30 16:46:06 INFO juju.worker.dbaccessor worker.go:622 current cluster: []protocol.NodeInfo{protocol.NodeInfo{ID:0x2dc171858c3155be, Address:"240.60.0.196:17666", Role:0}}
2023-10-30 16:46:06 INFO juju.worker.dbaccessor runner.go:592 start "controller"
2023-10-30 16:46:06 INFO juju.worker.upgradedatabase worker.go:334 leading the database upgrade from: 4.0-beta2.1 to: 4.0-beta3.3
2023-10-30 16:46:06 INFO juju.worker.upgradedatabase worker.go:359 marking the controller ready for upgrade
2023-10-30 16:46:06 INFO juju.worker.upgradedatabase worker.go:375 database upgrade starting
2023-10-30 16:46:06 INFO juju.worker.upgradedatabase worker.go:435 upgrading controller database from: 4.0-beta2.1 to: 4.0-beta3.3
2023-10-30 16:46:06 INFO juju.worker.upgradedatabase worker.go:447 applied controller schema changes from: 21 to: 21
2023-10-30 16:46:06 INFO juju.worker.upgradedatabase worker.go:452 upgrading model databases from: 4.0-beta2.1 to: 4.0-beta3.3
2023-10-30 16:46:06 INFO juju.worker.dbaccessor runner.go:592 start "01d9d5fe-8a4e-4652-87b2-547a89404da3"
2023-10-30 16:46:06 INFO juju.worker.upgradedatabase worker.go:479 applied model schema changes from: 5 to: 5 for model 01d9d5fe-8a4e-4652-87b2-547a89404da3
2023-10-30 16:46:06 INFO juju.worker.upgradedatabase worker.go:386 database upgrade completed
2023-10-30 16:46:06 INFO juju.state open.go:192 creating cloud image metadata storage
2023-10-30 16:46:06 ERROR juju.worker.dependency engine.go:695 "api-caller" manifold worker returned unexpected error: [01d9d5] "machine-0" cannot open api: unable to connect to API: dial tcp 127.0.0.1:17070: connect: connection refused
2023-10-30 16:46:06 INFO juju.state state.go:447 starting standard state workers
2023-10-30 16:46:06 INFO juju.state.watcher runner.go:592 start "txnlog"
2023-10-30 16:46:06 INFO juju.state state.go:453 started state workers for model-01d9d5fe-8a4e-4652-87b2-547a89404da3 successfully
2023-10-30 16:46:06 INFO juju.state.pool.txnwatcher runner.go:592 start "txnlog"
2023-10-30 16:46:06 INFO juju.cmd.jujud machine.go:957 juju database opened
2023-10-30 16:46:06 INFO juju.state.pool.txnwatcher txnwatcher.go:305 txn watcher started
2023-10-30 16:46:06 INFO juju.state.allwatcher allwatcher.go:1751 allwatcher loaded for model "01d9d5fe-8a4e-4652-87b2-547a89404da3" in 8.409933ms
2023-10-30 16:46:06 INFO juju.worker.httpserver worker.go:315 listening on "[::]:17070"
2023-10-30 16:46:07 INFO juju.worker.objectstore runner.go:592 start "01d9d5fe-8a4e-4652-87b2-547a89404da3"
2023-10-30 16:46:10 INFO juju.api apiclient.go:706 connection established to "wss://localhost:17070/model/01d9d5fe-8a4e-4652-87b2-547a89404da3/api"
2023-10-30 16:46:10 INFO juju.apiserver.connection request_notifier.go:96 agent login: machine-0 for 01d9d5fe-8a4e-4652-87b2-547a89404da3
2023-10-30 16:46:10 INFO juju.worker.apicaller connect.go:163 [01d9d5] "machine-0" successfully connected to "localhost:17070"
2023-10-30 16:46:10 INFO juju.apiserver.common password.go:77 setting mongo password for "machine-0"
2023-10-30 16:46:10 INFO juju.apiserver.common password.go:102 setting password for "machine-0"
2023-10-30 16:46:10 INFO juju.worker.upgradesteps controllerworker.go:322 checking that upgrade can proceed
2023-10-30 16:46:10 INFO juju.worker.upgradesteps controllerworker.go:327 running upgrade steps for "machine-0"
2023-10-30 16:46:10 INFO juju.worker.upgradesteps worker.go:113 starting upgrade from 4.0-beta2.1 to 4.0-beta3.3 for "machine-0"
``` 

### Force the migrate error message

Note: You must ensure that both source and controller are at the same value, even the patch and build. So if you're attempting to migrate from source to destination, the destination needs to be ahead of it.

Ensure you bootstrap the other controller without the following changes, otherwise, it won't correctly start.

```sh
$ juju bootstrap lxd other --build-agent
$ juju switch test
$ juju add-model default
```

Apply the changes to force the delay:

```diff
diff --git a/internal/upgrade/lock.go b/internal/upgrade/lock.go
index 4544879f80..ef3f109d96 100644
--- a/internal/upgrade/lock.go
+++ b/internal/upgrade/lock.go
@@ -22,11 +22,11 @@ type Version interface {
 func NewLock(previous Version, current version.Number) gate.Lock {
        lock := gate.NewLock()

-       // Build numbers are irrelevant to upgrade steps.
-       upgradedToVersion := previous.UpgradedToVersion().ToPatch()
-       if upgradedToVersion == current.ToPatch() {
-               lock.Unlock()
-       }
+       // // Build numbers are irrelevant to upgrade steps.
+       // upgradedToVersion := previous.UpgradedToVersion().ToPatch()
+       // if upgradedToVersion == current.ToPatch() {
+       //      lock.Unlock()
+       // }

        return lock
 }
diff --git a/internal/upgradesteps/worker.go b/internal/upgradesteps/worker.go
index 7398f770b0..d12c19d243 100644
--- a/internal/upgradesteps/worker.go
+++ b/internal/upgradesteps/worker.go
@@ -89,11 +89,11 @@ func (w *BaseWorker) AlreadyUpgraded() bool {
                return true
        }

-       if w.FromVersion == w.ToVersion {
-               w.Logger.Infof("upgrade to %v already completed.", w.ToVersion)
-               w.UpgradeCompleteLock.Unlock()
-               return true
-       }
+       // if w.FromVersion == w.ToVersion {
+       //      w.Logger.Infof("upgrade to %v already completed.", w.ToVersion)
+       //      w.UpgradeCompleteLock.Unlock()
+       //      return true
+       // }
        return false
 }
diff --git a/worker/upgradedatabase/worker.go b/worker/upgradedatabase/worker.go
index 74644ac3ff..4a3f34097a 100644
--- a/worker/upgradedatabase/worker.go
+++ b/worker/upgradedatabase/worker.go
@@ -358,6 +358,9 @@ func (w *upgradeDBWorker) runUpgrade(upgradeUUID domainupgrade.UUID) error {
        }
        w.logger.Infof("marking the controller ready for upgrade")

+       w.logger.Errorf("Force a sleep!")
+       time.Sleep(30 * time.Second)
+
        for {
                select {
                case <-w.catacomb.Dying():
```

Ensure we switch back to the test controller and upgrade with the timesleep.

```sh
$ juju switch test
$ juju upgrade-controller --build-agent
```

Tail the logs to see the sleep, then try and perform a migration.

```sh
$ juju migrate test:default other
ERROR upgrade in progress (upgrade in progress)
```

Note: this will take 30 seconds to respond because the apiserver isn't up. If we move those to the upgradesteps we get a super fast response because the apiserver is up. It's good to know this happens in the worst case.

## Links

**Jira card:** JUJU-4837

### CODE REVIEW

**Review by manadart — COMMENTED** [review]
Some mock regen and unused variables to sort out.

**Comment by manadart** [comment]
Can you check that the QA steps are exact and correct?

Attempting to run the second upgrade/migrate, I get:
```
juju upgrade-controller --build-agent && juju migrate default other
no prepackaged agent binaries available, using local agent binary 4.0-beta2.2 (built from source)
best version:
    4.0-beta2.2
started upgrade to 4.0-beta2.2
ERROR source prechecks failed: controller: machine 0 agent binaries don't match model (4.0-beta1.1 != 4.0-beta2.2)
```

A second attempt blocks for a very long time, then returns:
```
ERROR unable to connect to API: dial tcp 10.62.163.85:17070: connect: connection refused
``` 

Logs have:
```
2023-10-30 13:04:16 DEBUG juju.cmd.jujud machine.go:1147 mongodb service is installed
2023-10-30 13:04:16 DEBUG juju.agent agent.go:1060 potential mongo addresses: [localhost:37017 10.62.163.85:37017]
2023-10-30 13:04:16 DEBUG juju.mongo open.go:174 dialed mongodb server at "127.0.0.1:37017"
2023-10-30 13:04:16 DEBUG juju.mongo open.go:174 dialed mongodb server at "10.62.163.85:37017"
2023-10-30 13:04:16 INFO juju.state open.go:192 creating cloud image metadata storage
2023-10-30 13:04:16 DEBUG juju.mongo open.go:174 dialed mongodb server at "10.62.163.85:37017"
2023-10-30 13:04:16 INFO juju.state state.go:447 starting standard state workers
2023-10-30 13:04:16 DEBUG juju.state.watcher runner.go:416 start "txnlog"
2023-10-30 13:04:16 INFO juju.state state.go:453 started state workers for model-6832be82-e31f-40a4-80a6-fca75bd5d8ec successfully
2023-10-30 13:04:16 INFO juju.state.watcher runner.go:592 start "txnlog"
2023-10-30 13:04:16 INFO juju.state.pool.txnwatcher runner.go:592 start "txnlog"
2023-10-30 13:04:16 DEBUG juju.state.watcher runner.go:424 "txnlog" started
2023-10-30 13:04:16 INFO juju.cmd.jujud machine.go:957 juju database opened
2023-10-30 13:04:16 DEBUG juju.worker.dependency engine.go:580 "state" manifold worker started at 2023-10-30 13:04:16.522337093 +0000 UTC
2023-10-30 13:04:16 INFO juju.state open.go:192 creating cloud image metadata storage
2023-10-30 13:04:16 INFO juju.state state.go:447 starting standard state workers
2023-10-30 13:04:16 DEBUG juju.state.watcher runner.go:416 start "txnlog"
2023-10-30 13:04:16 INFO juju.state state.go:453 started state workers for model-a24c1b92-8093-48b0-8b90-6551f16a9638 successfully
2023-10-30 13:04:16 INFO juju.state.watcher runner.go:592 start "txnlog"
2023-10-30 13:04:16 DEBUG juju.state.watcher runner.go:424 "txnlog" started
2023-10-30 13:04:16 DEBUG juju.mongo open.go:174 dialed mongodb server at "127.0.0.1:37017"
2023-10-30 13:04:16 DEBUG juju.worker.dependency engine.go:580 "object-store" manifold worker started at 2023-10-30 13:04:16.53189419 +0000 UTC
2023-10-30 13:04:16 DEBUG juju.state.bakerystorage config.go:153 using local users third party key: ZWYeN6ZPfFFWcocyfjuu4cr+2Ux4vvCMtd23d66F0RY=
2023-10-30 13:04:16 DEBUG juju.state.bakerystorage config.go:153 using local users key: 8Sv4W2zCOldDlVnJxxPCP2L0H0ifFn/N/xhj7pOUNng=
2023-10-30 13:04:16 DEBUG juju.worker.controlsocket worker.go:78 controlsocket worker listening on socket "/var/lib/juju/control.socket"
2023-10-30 13:04:16 DEBUG juju.worker.dependency engine.go:580 "control-socket" manifold worker started at 2023-10-30 13:04:16.53308241 +0000 UTC
2023-10-30 13:04:16 DEBUG juju.worker.controlsocket worker.go:119 controlsocket worker now serving
2023-10-30 13:04:16 DEBUG juju.worker.dependency engine.go:580 "http-server-args" manifold worker started at 2023-10-30 13:04:16.533458335 +0000 UTC
2023-10-30 13:04:16 DEBUG juju.mongo open.go:174 dialed mongodb server at "10.62.163.85:37017"
2023-10-30 13:04:16 DEBUG core.auditlog auditlog.go:205 created rotating log file "/var/log/juju/audit.log" with max size 300 MB and max backups 10
2023-10-30 13:04:16 DEBUG juju.worker.dependency engine.go:580 "audit-config-updater" manifold worker started at 2023-10-30 13:04:16.548903985 +0000 UTC
2023-10-30 13:04:16 INFO juju.state.pool.txnwatcher txnwatcher.go:305 txn watcher started
2023-10-30 13:04:17 INFO juju.worker.upgradedatabase worker.go:334 leading the database upgrade from: 4.0-beta1 to: 4.0-beta2.2
2023-10-30 13:04:17 DEBUG juju.worker.dependency engine.go:618 "upgrade-database-runner" manifold worker stopped: subscribing to namespace "upgrade_info_controller_node": event multiplexer wo
rker is dying
stack trace:
event multiplexer worker is dying
github.com/juju/juju/core/watcher/eventsource.(*ValueWatcher).loop:78: subscribing to namespace "upgrade_info_controller_node"
2023-10-30 13:04:17 ERROR juju.worker.dependency engine.go:695 "upgrade-database-runner" manifold worker returned unexpected error: subscribing to namespace "upgrade_info_controller_node": e
vent multiplexer worker is dying
2023-10-30 13:04:19 DEBUG juju.worker.apicaller connect.go:116 connecting with current password
2023-10-30 13:04:19 DEBUG juju.api apiclient.go:824 looked up localhost -> [127.0.0.1]
2023-10-30 13:04:19 DEBUG juju.worker.apicaller connect.go:160 [6832be] failed to connect
2023-10-30 13:04:19 DEBUG juju.worker.dependency engine.go:618 "api-caller" manifold worker stopped: [6832be] "machine-0" cannot open api: unable to connect to API: dial tcp 10.62.163.85:17070: connect: connection refused
stack trace:
dial tcp 10.62.163.85:17070: connect: connection refused
github.com/juju/juju/api.gorillaDialWebsocket:755:
github.com/juju/juju/api.dialer.dial1:1175:
github.com/juju/juju/api.dialer.dial:1150: unable to connect to API
github.com/juju/juju/api.dialWebsocketMulti:1046:
```

**Comment by SimonRichardson** [comment]
@manadart  don't do `juju upgrade-controller --build-agent && juju migrate default other`, that's dangerous, we have no sequencing to enforce that upgrade-controller will be performed before the migrate.

**Review by manadart — APPROVED** [review]
This now passes QA.

**Pull request merged**
