### PR TITLE
[2.6] Ensure kvm images are pulled from the configured image URL

### PR DESCRIPTION
**Pull request by achilleasa**
## Description of change

Back-port of #11550 to 2.6

## QA steps

Same as #11550

## Bug reference

https://bugs.launchpad.net/juju/+bug/1859121

### CODE REVIEW

**Comment by achilleasa** [comment]
!!build!!

**Comment by achilleasa** [comment]
!!build!! (timeout fetching gpg keys)

**Comment by achilleasa** [comment]
!!build!!

**Comment by achilleasa** [comment]
!!build!! (flaky uniter test)

**Comment by achilleasa** [comment]
!!build!! (tests generated expired tls cert)

**Comment by hmlanigan** [comment]
!!build!!

**Comment by hmlanigan** [comment]
!!build!!

**Comment by hmlanigan** [comment]
@achilleasa at least 2 of the last 3 builds were consistent in their failures:
https://jenkins.juju.canonical.com/job/github-make-check-juju/5543/
https://jenkins.juju.canonical.com/job/github-make-check-juju/5546/

Not sure of the one I just kicked off.

**Comment by achilleasa** [comment]
!!build!! (machine lease tests)

**Comment by achilleasa** [comment]
!!build!! (MachineLeases tests)

**Comment by achilleasa** [comment]
!!build!! (MachineLeases tests)

**Comment by achilleasa** [comment]
!!build!! almost there...

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by achilleasa** [comment]
$$merge$$ (DNS resolution timeout)

**Pull request merged**
