### PR TITLE
Removed unused endpoints on the facades

### PR DESCRIPTION
**Pull request by jack-w-shaw**
These was deprecated a long time ago and should have been removed for 3.0

Migrate some of the unit tests over which had been left behind on the old endpoints and are not already covered. This required migrating to GoMock style, so some could be significantly simplified

Also drop a few redundant lines I spotted as a fly by

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [ ] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [ ] [Integration tests](https://github.com/juju/juju/tree/develop/tests), with comments saying what you're testing
- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

## QA steps

```sh
juju bootstrap lxd lxd
juju deploy ubuntu -n2
juju remove-unit ubuntu/0
juju remove-application ubuntu
```

## Bug reference

https://github.com/juju/juju/pull/14946

### CODE REVIEW

**Comment by jack-w-shaw** [comment]
I'm pretty sure this endpoint is not used anywhere, but not certain, so I've submitted this as it's own PR so it gets some explicit attention

Also, it turns out that DestroyApplication is tested, the tests are just in a different file

**Review by anvial — APPROVED** [review]
QA passed,

LG2M

**Pull request merged**
