### PR TITLE
Securely handle /etc/snap.assertions

### PR DESCRIPTION
**Pull request by simondeziel**
## Bug reference

https://bugs.launchpad.net/juju/+bug/1942922

### CODE REVIEW

**Comment by wallyworld** [comment]
Thanks for the patch, can you please rebase and target at the 2.9 branch

**Comment by simondeziel** [comment]
@wallyworld should be better now, please let me know if I missed something, thanks!

**Review by wallyworld — APPROVED** [review]

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
!!build!!

**Pull request merged**
