### PR TITLE
Fix not_networks for MAAS 1.9

### PR DESCRIPTION
**Pull request by voidspace**
With MAAS 1.9 the not_networks parameter (for negative space constraints) should be specified as multiple values, not a comma separated list.

Fixes bug #1636969
There is a separate PR (against gomaasapi) to fix the same issue for MAAS 2.x where "not_networks" becomes "not_subnets".

QA
Bootstrap specifying negative space constraints. Juju must honour those constraints in the machine it picks.

### CODE REVIEW

**Comment by bz2** [comment]
!!build!!

**Comment by voidspace** [comment]
!!build!!

**Comment by dimitern** [comment]
LGTM and QA OK on MAAS Version 1.9.4+bzr4592-0ubuntu1 (14.04.1) - observed in /var/log/maas/maas.log during juju bootstrap with 2 negative spaces constraints:

Nov  2 13:21:35 vmaas-19 maas.api: [INFO] Request from user juju to acquire a node with constraints <QueryDict: {u'mem': [u'2048'], u'agent_name': [u'82119c1f-f741-49e2-8b83-626f2d375ff1'], u'arch': [u'amd64'], u'zone': [u'default'], u'not_networks': [u'space:2', u'space:1']}>

**Comment by voidspace** [comment]
!!build!!

**Comment by voidspace** [comment]
$$merge$$

**Pull request merged**
