### PR TITLE
Move DefaultSpaceName to "core" Package

### PR DESCRIPTION
**Pull request by manadart**
## Description of change

This patch is a mechanical change to move `environs.DefaultSpaceName` into the `core/network` package. It also adds `DefaultSpaceId`.

Depends on #10422. Change is in last commit.

## QA steps

Build and unit tests green.

## Documentation changes

None.

## Bug reference

N/A

### CODE REVIEW

**Comment by manadart** [comment]
[Move environs.DefaultSpaceName to core/network](https://trello.com/c/Zs8J2SKx/1633-move-environsdefaultspacename-to-core-network)

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
Github outage.
$$merge$$

**Comment by manadart** [comment]
Github outage is marked resolved.
Trying another $$merge$$

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
intermittent test fail

$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
