### PR TITLE
Added simple linting for python.

### PR DESCRIPTION
**Pull request by hpidcock**
## Added simple linting for python.

Uses the compileall module of python to make sure
python code is valid.

Includes fixes of non-3 python scripts. These changes should
work in the last version of 2.6.

## QA steps

`STATIC_ANALYSIS_JOB=test_static_analysis_python make static-analysis`

## Documentation changes

N/A

## Bug reference

#11210

### CODE REVIEW

**Comment by nammn** [comment]
!!build!! unrelated err

**Comment by hpidcock** [comment]
$$merge$$

**Comment by babbageclunk** [comment]
Are we sure that all of the tests run under Python3? I feel like I've seen some that didn't - issues like imports and stuff as well as print function differences. I guess this'll be a good impetus to fix those, since it's 2020!

**Comment by manadart** [comment]
Yes, there are quite a few Python2-isms. Various dict iterators and such also need updating for 3.

**Pull request merged**
