### PR TITLE
Merge maas-spaces into master

### PR DESCRIPTION
**Pull request by dimitern**
We had a Blessed build for both master and maas-spaces and last few CI runs seem to indicate similar reliability of both branches, I think it's time to merge now.

(Review request: http://reviews.vapour.ws/r/3834/)

### CODE REVIEW

**Comment by dimitern** [comment]
I'll check back later tonight to see if there are any replies

**Comment by frobware** [comment]
@dimiter - sinzui is preparing a PR, so check with him first.

**Comment by sinzui** [comment]
We can see this revision is blessed
    http://reports.vapour.ws/releases/3597

There are no open bugs
    https://bugs.launchpad.net/juju-core/maas-spaces

**Comment by cherylj** [comment]
$$__JFDI__$$

**Comment by cherylj** [comment]
$$__JFDI__$$

**Pull request merged**
