### PR TITLE
2.4 Fix for Ubuntu Hosts With LXD Not Installed

### PR DESCRIPTION
**Pull request by manadart**
## Description of change

Addresses an issue specifically with Ubuntu host machines *without* LXD installed, where the provisioner set-up for container infrastructure causes an attempted connection to the LXD server before the installation/config has been assured. 

Also checks whether LXD is running before attempting to update its proxy configuration. If it is not, then that fact is logged and a nil error is returned.

Includes some drive-by spelling fixes.

## QA steps

- Bootstrap to local LXD.
- Add a new machine.
- Exec `sudo apt remove lxd` in the new container.
- `juju add-machine 0:lxd`
- Check machine-0 log for errors.

## Documentation changes

None.

## Bug reference

https://bugs.launchpad.net/juju/+bug/1780388

### CODE REVIEW

**Comment by manadart** [comment]
[Errors on Systems Without LXD](https://trello.com/c/eUdqYaKe/342-errors-on-systems-without-lxd)

**Comment by jameinel** [comment]
I thought Xenial+ has LXD installed out of the box. Is this only for manual or Trusty machines?

**Comment by manadart** [comment]
There are two issues in the linked bug; this doesn't yet address both (hence WIP). They relate specifically to (custom) Ubuntu images without LXD installed.
- _proxyupdater_ appears to assume that LXD is installed and writes errors to the logs on an interval.
- The initialisation that ensures LXD is installed is not reached on account of an error when attempting to bring up containers on such machines.

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
