### PR TITLE
Use params.HostPort to encode the payload of API Redirect errors

### PR DESCRIPTION
**Pull request by achilleasa**
## Description of change

The changes introduced by #10069 accidentally used `network.HostPort` to encode the payload for server `RedirectErrors` instead of `params.HostPort`. These two types are essentially the same with the difference that the latter generates **lower-cased** names for fields when encoding to json.

### CODE REVIEW

**Comment by achilleasa** [comment]
$$merge$$

(previous one aborted due to intermittent `MachineSuite.TestMachineWorkers` test failure)

**Comment by mitechie** [comment]
Merge seems to be complaining about a syntax error?

**Comment by mitechie** [comment]
!!build!!

**Comment by mitechie** [comment]
Ah, looks like it's got conflicts now. I see.

**Comment by howbazaar** [comment]
$$merge$$

**Comment by howbazaar** [comment]
$$merge$$ mongo not listening

**Comment by achilleasa** [comment]
$$merge$$

(failed due to a mongo connection timeout in one of the tests)

**Comment by achilleasa** [comment]
$$merge$$

(this time MachineWithCharmsSuite.TestManageModelRunsCharmRevisionUpdater failed)

**Pull request merged**
