### PR TITLE
Migrate to charm.v6-unstable and macaroon-bakery.v1.

### PR DESCRIPTION
**Pull request by rogpeppe**
Several feature branches require this version of the charm package,
and the metadata is about to change to allow charms to declare their series
and that change should land in v6-unstable, not v5 as it's backwardly
incompatible.

(Review request: http://reviews.vapour.ws/r/2606/)

### CODE REVIEW

**Comment by rogpeppe** [comment]
$$merge$$

**Comment by rogpeppe** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by rogpeppe** [comment]
$$merge$$

**Comment by rogpeppe** [comment]
$$merge$$

**Pull request merged**
