### PR TITLE
chore: remove unused methods from instancepoller facade

### PR DESCRIPTION
**Pull request by barrettj12**
The following facade methods on the `instancepoller` facade are currently unused:
- `ProviderAddresses`, `SetProviderAddresses`
- `ModelConfig`, `WatchForModelConfigChanges` (inherited from `common.MongoModelWatcher`)

This PR removes these unused methods from the facade. I am told that we don't need to bump the facade version, since this is a controller facade.

This allows us to remove a bunch of unnecessary dependencies from `InstancePollerAPI`. In particular, this facade no longer needs to access model config.

Drive-bys:
- Move existing service interface definitions (`ControllerConfigService`, `NetworkService`) into a new file `service.go`, and put the generated mocks into `service_mock_test.go`, as per the new convention.
- Change the instancepoller tests to use generated service mocks, and delete unneeded tests for deleted methods.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- ~[ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- ~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

Check that model migration still works.
```
juju bootstrap lxd c2
juju bootstrap lxd c1
juju add-model m
juju deploy tiny-bash
juju migrate m c2
```

## Links

**Jira card:** JUJU-6102

### CODE REVIEW

**Comment by barrettj12** [comment]
It appears these model config methods on the facade are unused. Maybe better to remove them entirely from the facade.

**Review by tlm — COMMENTED** [review]
This looks fine to me. It looks like we can remove these facades because the instance poller worker directly goes to state now and not via the facade.

I am find for there to be no manly QA steps for this PR if the PR description is updated to give a quick explanation explaining that worker that using this before no longer goes via this code path.

**Comment by barrettj12** [comment]
> This looks fine to me. It looks like we can remove these facades because the instance poller worker directly goes to state now and not via the facade.
> 
> I am find for there to be no manly QA steps for this PR if the PR description is updated to give a quick explanation explaining that worker that using this before no longer goes via this code path.

QA should check that removal of these methods doesn't break anything.
As far as we know, these methods have not been used for a long, long time, just that no-one ever removed them.

**Comment by jameinel** [comment]
So I think the change is fine, but I would still bump the facade for *our* sanity. Having a rev 5 of the facade that supports XYZ but a rev 6 of the facade that only supports XY is just going to cause developer confusion.
If you want to drop rev 5 from the facade list I can get behind that (controller workers run in the same process as the API server), but if we don't rev the version it just makes it hard for *us* to know what's going on.

**Comment by barrettj12** [comment]
@jameinel there is strong consensus with the rest of the team that we shouldn't bump the facade version here. Apparently that is consistent with what we have always done.

**Review by tlm — APPROVED** [review]
I am giving this approval with out manual QA steps as nothing uses it. Harry has gone back 9 years and cannot find any call sites of these removed methods.

From everything we can see they have just been abandoned. Several reviews have all came to the same agreement.

As for bumping the facade version we have agreed not to worry as this is a controller only facade and the pattern that has been established till now has been to not worry about it. We have a number of cases where this has not been done.

**Pull request merged**
