### PR TITLE
Model migration actions

### PR DESCRIPTION
**Pull request by voidspace**
Migrate actions and action notifications.

(Review request: http://reviews.vapour.ws/r/5418/)

### CODE REVIEW

**Comment by howbazaar** [comment]
$$merge$$

**Comment by voidspace** [comment]
$$tryagain$$

**Comment by voidspace** [comment]
$$fixed$$

**Comment by voidspace** [comment]
$$fixed-again$$

**Comment by voidspace** [comment]
$$andagain$$

**Pull request merged**
