### PR TITLE
Add missing AWS regions

### PR DESCRIPTION
**Pull request by toabctl**
*Why this change is needed and what it does.*

It's required to be able to use (kind of) newer AWS regions.

### CODE REVIEW

**Comment by toabctl** [comment]
I can't see the build failures. is it related to my code changes?

**Comment by hmlanigan** [comment]
@toabctl I approved the workloads to run. Will update with results.

**Comment by hmlanigan** [comment]
@toabctl please rebase and reset this PR to land in the 2.9 branch.

You'll also need to fix 2 tests in the BootstrapSuite, see #13679 for an example. BootstrapSuite.TestBootstrapInvalidRegion and BootstrapSuite.TestBootstrapPrintCloudRegions failed in check-multi-juju job

**Comment by hmlanigan** [comment]
Note to juju team, once this PR lands, we'll need to update the streams versions of the files so that `juju update-cloud` will find them.

**Comment by toabctl** [comment]
> Note to juju team, once this PR lands, we'll need to update the streams versions of the files so that `juju update-cloud` will find them.

@hmlanigan what's the streams versions? is that related to simplestreams?

**Comment by hmlanigan** [comment]
@toabctl The file isn't in the simple streams format, but is located on streams.canonical.com to allow for juju's knowledge of regions and clouds to be updated without upgrading juju itself.

**Comment by toabctl** [comment]
> @toabctl please rebase and reset this PR to land in the 2.9 branch.
> 
> You'll also need to fix 2 tests in the BootstrapSuite, see #13679 for an example. BootstrapSuite.TestBootstrapInvalidRegion and BootstrapSuite.TestBootstrapPrintCloudRegions failed in check-multi-juju job

done

**Comment by toabctl** [comment]
@hmlanigan what's wrong now? could you post the errors please?

**Comment by hmlanigan** [comment]
@toabctl it looks like the jobs and GitHub actions are not running for some reason. I was able to kick off the check-multi-juju job. Not sure on the actions yet

**Review by hmlanigan — APPROVED** [review]
LGTM - thank you for your patience. Please squash the commits, and I'll merge the result tomorrow. 🤞 the tests should be good now.

**Comment by toabctl** [comment]
> LGTM - thank you for your patience. Please squash the commits, and I'll merge the result tomorrow.  the tests should be good now.

done

**Pull request merged**
