### PR TITLE
Merge provider trackers (IAAS & CAAS)

### PR DESCRIPTION
**Pull request by SimonRichardson**
This merges the provider trackers into just one provider tracker. Originally, the thought was to have two independent provider trackers, one for IAAS and one for CAAS. We could separate them via generics. That didn't pan out, as you can have a controller managing both IAAS and CAAS models.

The solution is the merging of the prior provider trackers and only handing out a provider based on the model type. The service factory will never have to care about which provider they're handed, it will be abstracted away from them. It's just a provider. If it supports their version of a provider then it will materialize that, otherwise, you'll get a not supported error.

In addition to doing this, we drop the burden of keeping up the infrastructure for two. It becomes:

```
     ┌─────────────┐             ┌─────────────┐                              ┌────────┐
   ┌─┤IAAS PROVIDER├─────────┐ ┌─┤CAAS PROVIDER├─────────┐                  ┌─┤PROVIDER├──────────────┐
   │ └─────────────┘         │ │ └─────────────┘         │                  │ └────────┘              │
   │                         │ │                         │                  │                         │
   │  ┌───────────────────┐  │ │                         │                  │  ┌───────────────────┐  │
   │  │                   │  │ │                         │                  │  │                   │  │
   │  │ MODEL          1  │  │ │                         │                  │  │ MODEL          1  │  │
   │  │                   │  │ │                         │                  │  │                   │  │
   │  └───────────────────┘  │ │                         │                  │  └───────────────────┘  │
   │                         │ │                         │                  │                         │
   │                         │ │  ┌───────────────────┐  │                  │  ┌───────────────────┐  │
   │                         │ │  │                   │  │                  │  │                   │  │
   │                         │ │  │ MODEL          2  │  │                  │  │ MODEL          2  │  │
   │                         │ │  │                   │  │                  │  │                   │  │
   │                         │ │  └───────────────────┘  │                  │  └───────────────────┘  │
   │                         │ │                         │  ────────────►   │                         │
   │  ┌───────────────────┐  │ │                         │                  │  ┌───────────────────┐  │
   │  │                   │  │ │                         │                  │  │                   │  │
   │  │ MODEL          3  │  │ │                         │                  │  │ MODEL          3  │  │
   │  │                   │  │ │                         │                  │  │                   │  │
   │  └───────────────────┘  │ │                         │                  │  └───────────────────┘  │
   │                         │ │                         │                  │                         │
   │  ┌───────────────────┐  │ │                         │                  │  ┌───────────────────┐  │
   │  │                   │  │ │                         │                  │  │                   │  │
   │  │ MODEL          4  │  │ │                         │                  │  │ MODEL          4  │  │
   │  │                   │  │ │                         │                  │  │                   │  │
   │  └───────────────────┘  │ │                         │                  │  └───────────────────┘  │
   │                         │ │                         │                  │                         │
   └─────────────────────────┘ └─────────────────────────┘                  └─────────────────────────┘
```

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing

## QA steps

```sh
$ juju bootstrap lxd test
$ juju add-model default
$ juju deploy ubuntu
```

## Links

**Jira card:** JUJU-

### CODE REVIEW

**Review by nvinuesa — APPROVED** [review]
Changes LGTM. I have QAd this with https://github.com/juju/juju/pull/17217 which was rebased on top of this branch and both microk8s and lxd bootstrap correctly!

**Review by manadart — APPROVED** [review]
Turns out to be a nice simplification over the prior.

**Pull request merged**
