### PR TITLE
Ignore machine addresses 1.22

### PR DESCRIPTION
**Pull request by howbazaar**
Backport of 1.24 fix

https://github.com/juju/juju/commit/2cf648b677ab9cd033afdef4e9a198158e3d96e6

(Review request: http://reviews.vapour.ws/r/2753/)

### CODE REVIEW

**Comment by howbazaar** [comment]
$$merge$$

**Comment by bz2** [comment]
$$retry$$

MongoSuite.TestAddRemoveSet (no reachable servers)
MachinerSuite.TestSetDeadWithDyingUnit
```
machiner_test.go:171:
    // With dying unit, machine can now be marked as dying.
    c.Assert(s.machine.Destroy(), gc.IsNil)
... value *state.HasAssignedUnitsError = &state.HasAssignedUnitsError{MachineId:"0", UnitNames:[]string{"wordpress/0"}} ("machine 0 has unit \"wordpress/0\" assigned")
```

**Comment by bz2** [comment]
Seems there are test fixes needed:

MachinerSuite.TestSetDeadWithDyingUnit (as before)
FilterSuite.TestUnitRemoval
```
filter_test.go:131:
    c.Assert(f.Wait(), gc.Equals, worker.ErrTerminateAgent)
... obtained *errors.Err = &errors.Err{message:"", cause:(*params.Error)(0xc210180260), previous:(*errors.Err)(0xc2102763c0), file:"github.com/juju/juju/worker/uniter/filter/filter.go", line:408} ("unit \"wordpress/0\" not found")
... expected *errors.errorString = &errors.errorString{s:"agent should be terminated"} ("agent should be terminated")
```

**Comment by howbazaar** [comment]
$$try-now$$

**Pull request merged**
