### PR TITLE
Lxd fixes

### PR DESCRIPTION
**Pull request by tych0**
previous review request: http://reviews.vapour.ws/r/4598/
(Review request: http://reviews.vapour.ws/r/4599/)

### CODE REVIEW

**Comment by tych0** [comment]
$$merge$$

**Comment by tych0** [comment]
Are these known failures? They look unrelated.

**Comment by cherylj** [comment]
Yes, TestStateWatcherTwoModels is flaky :(

**Comment by cherylj** [comment]
$$merge$$

**Comment by tych0** [comment]
On Thu, Apr 14, 2016 at 01:21:15PM -0700, Cheryl Jennings wrote:
> Yes, TestStateWatcherTwoModels is flaky :(

No problem, thanks!

**Comment by AlexisBruemmer** [comment]
$$merge$$

**Pull request merged**
