### PR TITLE
Fix lp:1573286 - oplog tests fail with mongod 3.2

### PR DESCRIPTION
**Pull request by babbageclunk**
Truncating the capped collection that was being tailed no longer causes an ErrCursor with mongod 3.2. Change `OplogTailer` to use `OplogSession` and `OplogIterator` interfaces so that we can test the iterator restarting behaviour by passing in a fake session instead.

https://bugs.launchpad.net/juju-core/+bug/1573286

(Review request: http://reviews.vapour.ws/r/4967/)

### CODE REVIEW

**Comment by babbageclunk** [comment]
$$merge$$

**Comment by babbageclunk** [comment]
$$merge$$

**Comment by AlexisBruemmer** [comment]
$$JFDI$$

**Comment by cherylj** [comment]
$$__JFDI__$$

**Pull request merged**
