### PR TITLE
Fix races in pingbatcher tests

### PR DESCRIPTION
**Pull request by wallyworld**
## Description of change

Fix races in the pingbatcher tests.

## QA steps

go test --race

### CODE REVIEW

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by jameinel** [comment]
Thanks for catching this. I had been running --race but failed to do so
after updating from reviews.

John
=:->

**Pull request merged**
