### PR TITLE
[CharmHub] - Resolve the series and arch when deploying a bundle.

### PR DESCRIPTION
**Pull request by SimonRichardson**
Pathalogical bundles where we use the same charm with a different series
and architecture now correctly install. There is a slight annoyance in
the fact that when attempting to resolve a charm we end up with a series
and architecture from the resolution that we don't want till later. In
that case, we empty the series, architecture will always be correct and
then refill it in again at a later stage when we're adding the charm.

## QA steps

```sh
$ juju bootstrap aws test
$ juju add-model one --config charm-hub-url="https://api.staging.snapcraft.io"
$ juju deploy ./testcharms/charm-hub/bundles/amalgam/.
```

### CODE REVIEW

**Comment by hmlanigan** [comment]
testing worked.  and this fixes an issue I can across in my own pr.  however the charmurl and the platform still say xenial instead of focal.

	"series" : "focal",
	"subordinate" : false,
	"charmurl" : "ch:amd64/xenial/ubuntu-17",
	"cs-channel" : "stable",
	"charm-origin" : {
		"source" : "charm-hub",
		"type" : "charm",
		"id" : "9NT4sM1gdNLkBPuXbxNu2IusUosDcmR9",
		"hash" : "e0a16ee2c880fe0a1942f48602377e5861d745c66f7523a0113726eb0dde7a0e",
		"revision" : 17,
		"channel" : {
			"risk" : "stable"
		},
		"platform" : {
			"architecture" : "amd64",
			"os" : "ubuntu",
			"series" : "xenial"
		}
	},

$ juju deploy ubuntu --series bionic ubuntu-bionic
produces:
	"series" : "bionic",
	"subordinate" : false,
	"charmurl" : "ch:amd64/xenial/ubuntu-17",
	"cs-channel" : "stable",
	"charm-origin" : {
		"source" : "charm-hub",
		"type" : "charm",
		"id" : "9NT4sM1gdNLkBPuXbxNu2IusUosDcmR9",
		"hash" : "e0a16ee2c880fe0a1942f48602377e5861d745c66f7523a0113726eb0dde7a0e",
		"revision" : 17,
		"channel" : {
			"risk" : "stable"
		},
		"platform" : {
			"architecture" : "amd64",
			"os" : "ubuntu",
			"series" : "bionic"
		}
	},

**Comment by hmlanigan** [comment]
QA: I'm getting a series of Xenial deployed with the bundle.yaml, instead of the bundle series of Focal.

**Review by hmlanigan — APPROVED** [review]
LGTM

**Comment by SimonRichardson** [comment]
$$merge$$

**Pull request merged**
