### PR TITLE
Update dependencies.tsv for Goose header fix

### PR DESCRIPTION
**Pull request by gnuoy**
Update dependencies.tsv to pickup fix in Goose for
OpenStack Mitaka+ clouds. Fixes lp:1625624

### CODE REVIEW

**Comment by reedobrien** [comment]
!!build!!

**Comment by bz2** [comment]
This is suffering from the log change, but I think we just change determineBestClient to be less perverse, it shouldn't depend on the signature of newClient.

```
+ go install github.com/juju/juju/...
# github.com/juju/juju/provider/openstack
tmp.iGuWcTlgUW/juju-core_2.0.3/src/github.com/juju/juju/provider/openstack/provider.go:626: cannot use newClient (type func(*identity.Credentials, identity.AuthMode, logging.CompatLogger) client.AuthenticatingClient) as type func(*identity.Credentials, identity.AuthMode, *log.Logger) client.AuthenticatingClient in argument to determineBestClient
```

**Comment by bz2** [comment]
See https://gist.github.com/bz2/fefb93eb053bcd52388de79ec559b85c for how I suggest we get around this.

**Comment by bz2** [comment]
!!build!!

**Comment by bz2** [comment]
!!retry!!

```
FAIL: bootstrap_test.go:637: BootstrapSuite.TestSystemIdentityWritten
...
bootstrap_test.go:644:
    c.Assert(err, jc.ErrorIsNil)
... value *errors.Err = &errors.Err{message:"", cause:(*errors.Err)(0xc820571db0), previous:(*errors.Err)(0xc820571db0), file:"github.com/juju/juju/cmd/jujud/agent/agent.go", line:102} ("failed to initialize state: cannot create index: local error: unexpected message")
... error stack:
	github.com/juju/juju/agent/agentbootstrap/bootstrap.go:131: failed to initialize state: cannot create index: local error: unexpected message
	github.com/juju/juju/cmd/jujud/agent/agent.go:102: 
```

**Comment by bz2** [comment]
!!build!!

**Comment by bz2** [comment]
!!build!!

**Comment by bz2** [comment]
Check failed with dirty sockets only, this is ready to go.

**Comment by bz2** [comment]
$$merge$$

**Pull request merged**
