### PR TITLE
Bump to 3.2-beta2

### PR DESCRIPTION
**Pull request by hpidcock**
3.2-beta1 to 3.2-beta2

### CODE REVIEW

**Review by juanmanuel-tirado — APPROVED** [review]
LG2M

**Review by manadart — APPROVED** [review]

**Comment by juanmanuel-tirado** [comment]
The Linter is failing 
`worker/firewaller/firewaller.go:168:2: field `modelFirewallRules` is unused (unused)`

**Comment by manadart** [comment]
Rebase over merge.

**Comment by hpidcock** [comment]
Thanks for fixing this @juanmanuel-tirado

**Pull request merged**
