### PR TITLE
Introduce Provider SpaceSetID

### PR DESCRIPTION
**Pull request by manadart**
## Description of change

Adds a new method, `SpaceSetID` to the environ `Networking` interface and implementations.

The return value will be used as the grouping key (instead of the current implicit model UUID) for space/subnet definitions. 

It's purpose is to allow coarser grained network topology definitions, avoiding the need to rediscover/re-specify the topology per model.

The implementations for providers are as follows:
- MAAS: a hash of the MAAS API endpoint.
- EC2: the default VPC, falling back to the credential access key (not secret key) if unavailable.
- Oracle: the credential identity.
- OpenStack: the credential tenant ID, falling back to the tenant name.
- Others: a `NotSuported` error.

## QA steps

Not yet recruited by Juju operational logic. Unit tests cover the implementations.

## Documentation changes

None.

## Bug reference

N/A

### CODE REVIEW

**Comment by manadart** [comment]
[Add provider SpaceSetID](https://trello.com/c/HVRQogbJ/2438-add-provider-spacesetid)

**Comment by howbazaar** [comment]
I'm super hesitant about landing a change like this at the end of the cycle. I feel like it is too risky.

**Comment by howbazaar** [comment]
I discussed this with @mitechie earlier today, and I said that I'd outline all of my concerns here.

I understand that real use of spaces on any provider other than maas really needs something like this.

My concerns are in three specific areas:

* model migration into a target controller where the space definitions differ
  * it is one thing to do a check and disallow, but how is the user supposed to move forwards?
  * can we create a different space set if the space definitions differ?
* controller upgrades
  * I guarantee that there will be a controller where a user has multiple models on AWS that use the same underlying networks but differing spaces
  * what is the upgrade process? how do we handle the difference?
* complete rewrite of all the space / network documents as they move to be global collections
  * since the space and network collections are currently model specific, changing them to be used across models would mean they need to move to be global collections.
  * what happens when a change in one model causes a break in another model?
  * how would we even know?

Those are the basics...

**Comment by howbazaar** [comment]
I guess some corollary questions would be:

 * if we keep model specific spaces, what is an alternative to sharing space definitions?
 * could we have a way to specify spaces in a "generic" way, then use "reload-spaces" to bring those changes into a particular model?

**Comment by manadart** [comment]
Happy to sit on this one.

We could introduce some form of copy-from-model-x for EC2 and Oracle as a stop-gap...

**Comment by mitechie** [comment]
The issues with "copying spaces" is that you have to manage that over time. It has two issues. The first is that if you go to change your spaces you have to walk all models using that common definition to reload-spaces on them all and have them deal with any fallout on a case by case basis. 

Second, it makes it harder if not impossible to sanity check changes at the time an operator makes it. If user A goes to move a subnet that they're not using to another space but it'll impact another model using that subnet I'd prefer that the command tosses an alert at that point in time that "hey, this is used over here. Are you sure?"

**Comment by mitechie** [comment]
What if we don't do the move to global this cycle and instead rely on a export/import space definition juju plugin. As a plugin we're not committed to maintaining it for the life of Juju 2.x. It also help smooth over the pain point of needing to run a series of add-space, move-to-space commands multiple times to set things up. The work on the plugins is low risk and can be updated out of band.

**Pull request closed without merging**
