### PR TITLE
[JUJU-230] Add additional unit test for WatchAllModels api

### PR DESCRIPTION
**Pull request by wallyworld**
Diagnosing https://bugs.launchpad.net/juju/+bug/1789545, I added extra test coverage to test any fix that would be needed, but it turned out things must have been sorted out since the bug was first raised 3 years ago, as the test passed.

It's good to have the additional test coverage so let's commit that.

## QA steps

unit tests

## Bug reference

https://bugs.launchpad.net/juju/+bug/1789545

### CODE REVIEW

**Review by hpidcock — APPROVED** [review]
Looks like this test now tests what it was supposed to test :laughing:. LGTM thanks

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
