### PR TITLE
[JUJU-3821] Fixed test-deploy-aks-charms

### PR DESCRIPTION
**Pull request by anvial**
This PR adds `tls-certificates-operator` to fix mattermot-k8s. 

That is because new psql does not have TLS built-in. Fix is simple, integrate psql with certificates charm. However, MM should not have container crash but go to the blocked state with clear error message to a user until TLS is available. 

Thx to https://bugs.launchpad.net/charm-k8s-mattermost/+bug/1997540

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made

## QA steps

```sh
cd tests
./main.sh -v deploy_aks run_deploy_aks
```

## Documentation changes

nope

## Bug reference

nope

### CODE REVIEW

**Comment by jack-w-shaw** [comment]
Static analysis fail. It looks like you're mixing tabs and spaces

**Comment by anvial** [comment]
> Static analysis fail. It looks like you're mixing tabs and spaces

fixed

**Review by barrettj12 — CHANGES_REQUESTED** [review]
May I remind you of the policy we agreed in cross-team discussions / private chat:
> Our current vision is to use 3-party charms (managed not by juju team) in CI *only* in cases when we need to check how Juju operates with this particular 3-party charm.

According to the test name and comments, the purpose of this test is checking that deploying / relating charms works on AKS. We are **not** trying to test the `postgresql-k8s` or `mattermost-k8s` charms.

Therefore, I suggest using Juju-controlled charms instead in this test. Maybe [juju-qa-dummy-source](https://charmhub.io/juju-qa-dummy-source) and [juju-qa-dummy-sink](https://charmhub.io/juju-qa-dummy-sink) would be suitable.

**Review by jack-w-shaw — APPROVED** [review]
Still getting some weirdness with `ERROR Juju command "machines" not supported on container models`, but I'm not worried. See above

**Comment by barrettj12** [comment]
@jack-w-shaw : that error seems to be coming from
https://github.com/juju/juju/blob/4436840d6046abbaa36c52c8b75c3767da68c2f8/tests/includes/juju.sh#L437-L447

Presumably we also need to check if `$BOOTSTRAP_PROVIDER == 'aks'` or something as well.

**Review by barrettj12 — APPROVED** [review]

**Comment by barrettj12** [comment]
@anvial can you please update the PR description here to reflect the changes :)

**Pull request merged**
