### PR TITLE
Merge 2.9 into develop

### PR DESCRIPTION
**Pull request by manadart**
Merge from 2.9 branch to bring forward:
- #12815 from gabriel-samfira/set-vm-hw-version
- #12835 from SimonRichardson/fix-1921722
- #12828 from manadart/2.9-transport-address-cidr
- #12837 from wallyworld/more-nonubuntu-fixes
- #12836 from jujubot/increment-to-2.9-rc9
- #12814 from tlm/2.9-add-unit
- #12834 from wallyworld/nonubuntu-tools-tests
- #12833 from benhoyt/update-pebble-3
- #12830 from tlm/2.9-model-permissions
- #12795 from hmlanigan/charmhub-bundle
- #12826 from hpidcock/node-selector-arch

No noteworthy conflicts, just those relating to incremented version.

### CODE REVIEW

**Comment by hpidcock** [comment]
> ```
> 07:53:04 caas/ecs/application.go:57:9: cannot use &app{...} (type *app) as type caas.Application in return argument:
> 07:53:04 	*app does not implement caas.Application (missing Scale method)
> ```
> 
> Something went wrong with the merge.

Not a merge fault, actually just a new implementation of caas.Application but also a new method

**Comment by hpidcock** [comment]
I'll fix this and get it going.

**Review by hpidcock — APPROVED** [review]

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by manadart** [comment]
```
09:31:35 ----------------------------------------------------------------------
09:31:35 FAIL: mux_test.go:115: MuxSuite.TestConcurrentRemoveHandler
09:31:35 
09:31:35 mux_test.go:157:
09:31:35     c.Assert(notfound, gc.Not(gc.Equals), 0)
09:31:35 ... obtained int = 0
09:31:35 ... expected int = 0
```

**Comment by manadart** [comment]
This does not fail for me when run in a loop.
!!build!!

**Comment by hpidcock** [comment]
$$merge$$

**Pull request merged**
