### PR TITLE
Update goamz dependencies

### PR DESCRIPTION
**Pull request by wallyworld**
go-amz is now at v3.
We update juju-core and make a few mods to the signing set up so that V4 algorithm is used for china and V2 elsewhere.

(Review request: http://reviews.vapour.ws/r/1046/)

### CODE REVIEW

**Comment by dimitern** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$_JFDI__$$

**Comment by wallyworld** [comment]
$$__JFDI__$$

**Comment by wallyworld** [comment]
$$__JFDI__$$

**Comment by wallyworld** [comment]
$$__JFDI__$$

**Comment by wallyworld** [comment]
$$__JFDI__$$

**Comment by wallyworld** [comment]
$$__JFDI__$$

**Pull request merged**
