### PR TITLE
Return a non-empty network topology when only alpha space has been explicitly set as constraint.

### PR DESCRIPTION
**Pull request by nvinuesa**
At the provisioning info facade, we fill the ProvisioningNetworkTopology field of the provisiong info struct with the subnets mapped to the AZs. We have this information because we have the constraints (and enpdoint bindings) and we then do a lookup to find the subnets that are in that space(s).

We merge the constraints *and* the bound endpoint spaces (which by the way is `alpha` by default) and then return the list of spaces merged. 
The issue is that later we make the following check: if only the alpha space is left after this merge, then we don't bother to fill a network topology that would have to be interpreted by the providers.
This check is wrong because it assumes that if we only have alpha in that resulting list it's because it was added by the default endpoint binding space. Another possibility is that the user had explicitly passed only the alpha space as a positive constraint.

This patch fixes this assumption, by not only checking if the merged list contains only alpha but also if the constraints weren't explicitly set to alpha only. If that's the case then we set a network topology and providers will be able to correctly instantiate the machine on the correct spaces (and in the case of openstack by creating only the correct ports).

## Checklist

- [X] Code style: imports ordered, good names, simple structure, etc
- [X] Comments saying why design decisions were made
- [ ] ~Go unit tests, with comments saying what you're testing~
- [ ] ~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- [ ] ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

Bootstrap on an openstack cloud with 3 subnets each one associated with a different network, and add a model. Then make sure to create 2 spaces so that they match the 3 o7k networks:
```
openstack subnet list
+--------------------------------------+-----------------------+--------------------------------------+-------------+
| ID                                   | Name                  | Network                              | Subnet      |
+--------------------------------------+-----------------------+--------------------------------------+-------------+
| 2ba502bb-af1b-4a6c-a4a4-e0d408c78483 | nvinuesa_admin_subnet | 791f3401-0a00-4aef-9497-0db9a91f326c | 10.5.0.0/16 |
| 391994b0-f180-4827-a178-e4675182e03a | test_subnet_2         | af78087c-6893-48c7-a4f8-019d7575d6a4 | 10.6.1.0/24 |
| cfb7d5a8-1f0f-4bec-83a7-ffb5d05a2bd6 | test-subnet           | 88ec2dd8-86f8-4b6d-ad77-447ee8ff2781 | 10.6.0.0/24 |
+--------------------------------------+-----------------------+--------------------------------------+-------------+
openstack network list
+--------------------------------------+--------------------+--------------------------------------+
| ID                                   | Name               | Subnets                              |
+--------------------------------------+--------------------+--------------------------------------+
| 5827fa17-882a-4c19-89a8-f6fe4c28d6dd | ext_net            | 7c9df7f7-dee8-4e63-aac8-f33fd1de7b81 |
| 791f3401-0a00-4aef-9497-0db9a91f326c | nvinuesa_admin_net | 2ba502bb-af1b-4a6c-a4a4-e0d408c78483 |
| 88ec2dd8-86f8-4b6d-ad77-447ee8ff2781 | net_test           | cfb7d5a8-1f0f-4bec-83a7-ffb5d05a2bd6 |
| af78087c-6893-48c7-a4f8-019d7575d6a4 | net_test_2         | 391994b0-f180-4827-a178-e4675182e03a |
+--------------------------------------+--------------------+--------------------------------------+
juju spaces
Name   Space ID  Subnets
alpha  0         10.5.0.0/16
                 10.6.0.0/24
                 10.6.1.0/24
                 252.0.0.0/8
                 253.0.0.0/8
                 254.0.0.0/8
juju add-space beta 10.6.0.0/24 
juju add-space gamma 10.6.1.0/24      
juju spaces 
Name   Space ID  Subnets
alpha  0         10.5.0.0/16
                 252.0.0.0/8
beta   1         10.6.0.0/24
                 254.0.0.0/8
gamma  2         10.6.1.0/24
                 253.0.0.0/8
```
Now deploy with only alpha as positive constraint (in this case, having negative space constraints doesn't have any effect because they are not interpreted by the openstack provider since it has to bring up the new ports so it's as if they weren't passed).
```
juju deploy ubuntu --constraints spaces=alpha,^beta,^gamma
```
Now you should see that the server that was created only has one network (the one corresponding to the `alpha` space - in this case the `nvinuesa_admin_net` network):
```
| 4a8fda0b-3970-437a-9260-f550f1fa9f28 | juju-d1cb58-m-0          | ACTIVE | nvinuesa_admin_net=10.5.3.203                 | auto-sync/ubuntu-jammy-22.04-amd64-server-20240514-disk1.img | m1.small           |
```

Also, even though this patch doesn't change the bindings merge with the constraints, we should make sure that it's not a regression with respect to https://github.com/juju/juju/pull/13422 and its QA steps:
```
On an OpenStack with multiple subnets:

    Bootstrap.
    Carve out 2 spaces, each with a different subnet.
    juju deploy --bind 'space-1 public=space-2' cs:nagios`.
    Check that the provisioned machine has 2 network devices.
```
## Links

**Launchpad bug:** https://bugs.launchpad.net/juju/+bug/2031891

**Jira card:** JUJU-5830

### CODE REVIEW

**Comment by manadart** [comment]
What happens if you `juju deploy ubuntu --bind beta --constraints spaces=alpha`?

**Comment by nvinuesa** [comment]
> `juju deploy ubuntu --bind beta --constraints spaces=alpha`

The server has two networks (one corresponding to alpha and the other one to beta):
```
| 3bfda25a-7775-4d62-947e-7a65528db02e | juju-0617fe-m-0          | ACTIVE | net_test=10.6.0.239; nvinuesa_admin_net=10.5.2.116 | auto-sync/ubuntu-jammy-22.04-amd64-server-20240514-disk1.img | m1.small           |
```
```
juju spaces
Name   Space ID  Subnets
alpha  0         10.5.0.0/16
                 252.0.0.0/8
beta   1         10.6.0.0/24
                 254.0.0.0/8
gamma  2         10.6.1.0/24
                 253.0.0.0/8
```

**Review by manadart — APPROVED** [review]
I think this is OK, as in a bug-fix and not a behavioural change, because as you point out, the check was insufficient - we intended to check if we had the default binding to alpha (which we treat as space-agnostic), but not if the alpha space was explicitly supplied.

**Pull request merged**
