### PR TITLE
Refactor userdata to have in .cs and .ps1 files + new param for filetoconst

### PR DESCRIPTION
**Pull request by hoenirvili**
- Splitted the hole three const strings into multiple files , this way their are more easy to manage.
- Updated the filetoconst tool to take one more param in order to gen for other packages

(Review request: http://reviews.vapour.ws/r/4809/)

### CODE REVIEW

**Comment by fwereade** [comment]
$$merge$$

**Comment by fwereade** [comment]
$$merge$$

**Comment by fwereade** [comment]
looks transient, $$merge$$

**Comment by fwereade** [comment]
I am assured that it builds now... $$merge$$ :)

**Comment by bogdanteleaga** [comment]
$$merge$$ launchpad doesn't want to give us golxc :(

**Comment by bogdanteleaga** [comment]
$$merge$$

**Pull request merged**
