### PR TITLE
Add fuzz to the bounce and restart durations in the dependency engine

### PR DESCRIPTION
**Pull request by dooferlad**
There was a TODO...

TODO(fwereade): we should add fuzz to the bounce and restart durations to more vigorously shake out the bugs...

It has been done. Fixed docs to match and also render correctly with godoc.

### CODE REVIEW

**Comment by bz2** [comment]
!!retry!!

**Comment by bz2** [comment]
!!reretry!!

**Comment by nskaggs** [comment]
mgz add to whitelist

**Comment by bz2** [comment]
!!rereretry!!

**Comment by bz2** [comment]
!!rerereretry!!

**Comment by bz2** [comment]
!!rererereretry!!

**Comment by dooferlad** [comment]
$$merge$$

**Comment by dooferlad** [comment]
$$merge$$

**Pull request merged**
