### PR TITLE
Move almost all actions to self-hosted runners.

### PR DESCRIPTION
**Pull request by hpidcock**
- Moves most of the github action jobs to use various sized self-hosted runners.
- Many changes around supporting arm64.
- Changes for supporting running as a different user (i.e. not running as the `runner` user). Upgrading the microk8s action was required here.
- Fixes a few logging issues within the shell test harness + tests.

### CODE REVIEW

**Comment by hpidcock** [comment]
/canonical/self-hosted-runners/run-workflows dd2f523b6aac501da9133fb5a421210a4d29271f

**Comment by hpidcock** [comment]
/canonical/self-hosted-runners/run-workflows f57761ccf76a44dd1be59934267ec7f570c6d0fb

**Review by barrettj12 — APPROVED** [review]
yes!

**Pull request merged**
