### PR TITLE
Remove file that was inadvertently added

### PR DESCRIPTION
**Pull request by johnweldon**
This file was accidentally added

(Review request: http://reviews.vapour.ws/r/720/)

### CODE REVIEW

**Comment by dimitern** [comment]
LGTM

**Comment by binary132** [comment]
$$shipit$$

**Comment by binary132** [comment]
$$shipit$$

**Comment by johnweldon** [comment]
$$merge$$

**Comment by johnweldon** [comment]
This seems unrelated:

```
megawatcher_internal_test.go:1014:
    s.Reset(c)
megawatcher_internal_test.go:69:
    c.Assert(err, jc.ErrorIsNil)
... value *errors.Err = &errors.Err{message:"", cause:(*net.OpError)(0xc21034f680), previous:(*errors.Err)(0xc2103b25a0), file:"github.com/juju/juju/state/open.go", line:68} ("cannot create log collection: local error: bad record MAC: local error: bad record MAC")
... error stack:
	local error: bad record MAC
	github.com/juju/juju/state/open.go:189: cannot create log collection: local error: bad record MAC
	github.com/juju/juju/state/open.go:57: 
	github.com/juju/juju/state/open.go:68: 
```


$$retry$$

**Pull request merged**
