### PR TITLE
apiserver: DestroyEnvironment

### PR DESCRIPTION
**Pull request by waigani**
DestroyEnvironment schedules machines and services in the environment to be
destroyed. It  no longer calls RemoveAllEnvironDocs directly. Once the
provisioner has decommissioned all resources and no machines or services are
left in the environment, the undertaker worker handles the removal of the
environment.

As environment removal is now asynchronous, several tests, which expect the
environment docs to be immediately removed, have been skipped (in particular
the DestroySystem tests). A follow up branch will make DestroySystem wait for
environment removal to complete.

Destroying an environment has been tested on a local provider with lxc
machines. The machines went down and a "dead" environment doc was left in
state, with the recorded time of death. 

(Review request: http://reviews.vapour.ws/r/2744/)

### CODE REVIEW

**Comment by waigani** [comment]
$$merge$$

**Comment by waigani** [comment]
$$merge$$

**Comment by waigani** [comment]
$$merge$$

**Comment by waigani** [comment]
$$merge$$

**Comment by bz2** [comment]
Looks like you need to do a trunk merge as a separate proposal to pick up the various bug fixes, then this can land.

**Comment by waigani** [comment]
$$merge$$

**Comment by waigani** [comment]
$$merge$$

**Comment by waigani** [comment]
$$merge$$

**Comment by waigani** [comment]
$$merge$$

**Pull request merged**
