### PR TITLE
feat(azure): support creds with managed identity

### PR DESCRIPTION
**Pull request by wallyworld**
add-credential for azure now supports the managed-identity credential type.
This allows true no credential bootstrap.

Using a managed-identity credential negates the need for an instance role constraint.

This was a non user facing credential type, but now the user had to enter the credential. And the existing "instance-role"  type was reused from AWS and is AWS specific, so we add a new credential type "managed-identity".

Also, the cloud metadata needs to know about the managed-identity auth type. This metadata comes from the public_clouds.yaml file. What is published doesn't have it. So we manually add it until upstream can be updated and people run `juju update-public-clouds`. Note that this also means the Azure FinaliseCloud helper is not longer needed as the cloud auth types are now correct out of the box.

You need to create the managed identity first.
Then can now do `juju add-credential azure` and select the "managed-identity" auth type.
You are prompted to enter the subscription id and the path to the managed identity, either `name` or `group/name`.
You can also add-credential with a yaml file.

The bootstrap must be done from a jump host or Azure cloud shell so the metadata endpoint can be reached.

This is just a front end change to the Azure bootstrap process. The heavy lifting is already done to support the managed identity workflow. This just allows the managed identity cred to be used instead of a conventional cred to create the bootstrap controller.

## QA steps

Create a managed identity...

```
$ export group=jujutest
$ export role=jujutestrole
$ export subscription=2eebf55a-1e02-45d8-a299-02aed8aea00b
$ az group create --name "${group}" --location westus
$ az identity create --resource-group "${group}" --name jmid
$ mid=$(az identity show --resource-group "${group}" --name jmid --query principalId --output tsv)
$ az role definition create --role-definition "{
      \"Name\": \"${role}\",
      \"Description\": \"Role definition for a Juju controller\",
      \"Actions\": [
                \"Microsoft.Compute/*\",
                \"Microsoft.KeyVault/*\",
                \"Microsoft.Network/*\",
                \"Microsoft.Resources/*\",
                \"Microsoft.Storage/*\",
                \"Microsoft.ManagedIdentity/userAssignedIdentities/*\"
      ],
      \"AssignableScopes\": [
            \"/subscriptions/${subscription}\"
      ]
  }"
$ az role assignment create --assignee-object-id "${mid}" --assignee-principal-type "ServicePrincipal" --role "${role}" --scope "/subscriptions/${subscription}"
```

This next bit needs to be tested running in an Azure cloud shell or jump host.

Add a local credential

```
$ juju add-credential azure --client
Enter credential name: test


Regions
  centralus
  eastus
  eastus2
  northcentralus
  southcentralus
  westcentralus
  westus
  westus2
  westus3
  northeurope
  westeurope
  eastasia
  southeastasia
  japaneast
  japanwest
  brazilsouth
  australiacentral
  australiacentral2
  australiaeast
  australiasoutheast
  centralindia
  southindia
  westindia
  canadacentral
  canadaeast
  uksouth
  ukwest
  koreacentral
  koreasouth
  francecentral
  francesouth
  southafricanorth
  southafricawest
  germanynorth
  germanywestcentral
  uaecentral
  uaenorth
  norwayeast
  norwaywest
  switzerlandnorth
  switzerlandwest
  swedencentral
  qatarcentral
  polandcentral

Select region [any region, credential is not region specific]:

Auth Types
  interactive
  service-principal-secret
  managed-identity

Select auth type [interactive]: managed-identity

Enter managed-identity-path: jujutest/jmid

Enter subscription-id: 2eebf55a-1e02-45d8-a299-02aed8aea00b

Credential "test" added locally for cloud "azure".
```

```
$ juju bootstrap azure 
$ juju enable-ha
$ juju destroy-controller
```

Can also test adding a credential from a file.
mycreds.yaml
```
credentials:
  azure:
    foo:
      auth-type: managed-identity
      managed-identity-path: group/name
      subscription-id: sub-id-123
```

`juju add-credential --client azure -f mycreds.yaml`

## Documentation changes

@tmihoc we'll need to add to the docs

## Links

**Jira card:** [JUJU-6339](https://warthogs.atlassian.net/browse/JUJU-6339])

[JUJU-6339]: https://warthogs.atlassian.net/browse/JUJU-6339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by hpidcock — APPROVED** [review]
Thanks for the clear QA steps. Works pretty well. Code looks decent. Thanks.

**Comment by dparv** [comment]
I've tested this with 3.6/edge and I got this error:

```
juju bootstrap --config resource-group-name=${group} --config network=${network} azure
ERROR ManagedIdentityCredential authentication failed. ManagedIdentityCredential authentication failed. the requested identity isn't assigned to this resource
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 400 Bad Request
--------------------------------------------------------------------------------
{
  "error": "invalid_request",
  "error_description": "Identity not found"
}
--------------------------------------------------------------------------------
To troubleshoot, visit https://aka.ms/azsdk/go/identity/troubleshoot#managed-id
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 400 Bad Request
--------------------------------------------------------------------------------
{
  "error": "invalid_request",
  "error_description": "Identity not found"
}
--------------------------------------------------------------------------------
To troubleshoot, visit https://aka.ms/azsdk/go/identity/troubleshoot#managed-id
```

az identity list
```
[
  {
    "clientId": "xxxxx",
    "id": "/subscriptions/d80e159e-f5b9-4854-8cdd-c9c11260a041/resourcegroups/mrg-managed-kubeflow-preview-20240710190928/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jmid",
    "location": "westeurope",
    "name": "jmid",
    "principalId": "xxxx",
    "resourceGroup": "mrg-managed-kubeflow-preview-20240710190928",
    "systemData": null,
    "tags": {},
    "tenantId": "xxxxxxxx",
    "type": "Microsoft.ManagedIdentity/userAssignedIdentities"
  }
]
```

cat credentials.yaml 
```
credentials:
  azure:
    foo:
      auth-type: managed-identity
      managed-identity-path: mrg-managed-kubeflow-preview-20240710190928/jmid
      subscription-id: xxxxxxx
```

Also the scope cannot be subscription level, as we don't have access over the subscription in a managed environment, of course there can be an option to use a subscription scope, but in a managed Azure application the only option can be --scope /subscriptions/${subscription}/resourcegroups/${group}

Then bootstrap should look like this:

```
juju bootstrap --config resource-group-name=${group} --config network=${network} azure
```
(The ${network} is part of that resource group too.)

**Comment by wallyworld** [comment]
@dparv 

I just retested and it seemed to work for the subscription we use.
My test set up a role definition with assignable scope set to the resource group to confirm that works.

`./juju bootstrap azure/westus test --config resource-group-name=jujutest`


az role definition list
```
az role definition list --name jujutestrole3
[
  {
    "assignableScopes": [
      "/subscriptions/xxxxx/resourcegroups/jujutest"
    ],
    "createdBy": "xxxx",
    "createdOn": "2024-07-11T22:10:19.875406+00:00",
    "description": "Role definition for a Juju controller",
    "id": "/subscriptions/xxxx/providers/Microsoft.Authorization/roleDefinitions/xxxx",
    "name": "xxxxx",
    "permissions": [
      {
        "actions": [
          "Microsoft.Compute/*",
          "Microsoft.KeyVault/*",
          "Microsoft.Network/*",
          "Microsoft.Resources/*",
          "Microsoft.Storage/*",
          "Microsoft.ManagedIdentity/userAssignedIdentities/*"
        ],
        "condition": null,
        "conditionVersion": null,
        "dataActions": [],
        "notActions": [],
        "notDataActions": []
      }
    ],
    "roleName": "jujutestrole",
    "roleType": "CustomRole",
    "type": "Microsoft.Authorization/roleDefinitions",
    "updatedBy": "xxxx",
    "updatedOn": "2024-07-11T22:10:19.875406+00:00"
  }
]
```
az role assignment list
```
{
  "condition": null,
  "conditionVersion": null,
  "createdBy": null,
  "createdOn": "2024-07-11T22:10:28.083087+00:00",
  "delegatedManagedIdentityResourceId": null,
  "description": null,
  "id": "/subscriptions/xxxx/resourceGroups/jujutest/providers/Microsoft.Authorization/roleAssignments/xxxx",
  "name": "xxxx",
  "principalId": "xxxx",
  "principalType": "ServicePrincipal",
  "resourceGroup": "jujutest",
  "roleDefinitionId": "/subscriptions/xxxx/providers/Microsoft.Authorization/roleDefinitions/xxxx",
  "scope": "/subscriptions/xxxx/resourceGroups/jujutest",
  "type": "Microsoft.Authorization/roleAssignments",
  "updatedBy": "27f86c31-bca0-4a37-b233-0e5030107696",
  "updatedOn": "2024-07-11T22:10:29.316106+00:00"
}
```

az identity list
```
  {
    "clientId": "xxxxx",
    "id": "/subscriptions/xxxx/resourcegroups/jujutest/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jmid",
    "location": "westus",
    "name": "jmid",
    "principalId": "xxxx",
    "resourceGroup": "jujutest",
    "systemData": null,
    "tags": {},
    "tenantId": "xxxx",
    "type": "Microsoft.ManagedIdentity/userAssignedIdentities"
  }
```

cat credentials.yaml
```
credentials:
  azure:
    test:
      auth-type: managed-identity
      managed-identity-path: jujutest/jmid
      subscription-id: xxxxx
```

**Pull request merged**
