### PR TITLE
Merge 2.9

### PR DESCRIPTION
**Pull request by wallyworld**
Merge 2.9

#13567 We were not recording when a log read successfully completed.
#13569 [JUJU-342] Use kubectl auth can-i to check RBAC;
#13572 [JUJU-342] Ignore exit code for kubectl auth check;
#13573 [JUJU-357] Reorder commands run in run_model_metrics.
#13507 [JUJU-194] [2.9] Remove charm-assumes feature flag
#13575 [JUJU-360] Reduce API server metric cardinality
#13576 [JUJU-362] Do not force channel for local charms
#13579 Handles permission errors for listing instance profiles.
#13582 [JUJU-369] Remove offers when a model is destroyed
#13583 Update pubsub library
#13585 [JUJU-358] Add explicit owner to params when creating an offer

```
# Conflicts:
#       apiserver/allfacades.go
#       apiserver/facades/client/application/deploy.go
#       apiserver/facades/client/applicationoffers/applicationoffers.go
#       apiserver/facades/client/modelmanager/modelinfo_test.go
#       apiserver/facades/schema.json
#       cmd/juju/application/deployer/mocks/charm_mock.go
#       cmd/juju/application/deployer/mocks/modelcmd_mock.go
#       cmd/juju/application/deployer/mocks/store_mock.go

```

[JUJU-342]: https://warthogs.atlassian.net/browse/JUJU-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JUJU-342]: https://warthogs.atlassian.net/browse/JUJU-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JUJU-357]: https://warthogs.atlassian.net/browse/JUJU-357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JUJU-194]: https://warthogs.atlassian.net/browse/JUJU-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JUJU-360]: https://warthogs.atlassian.net/browse/JUJU-360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JUJU-362]: https://warthogs.atlassian.net/browse/JUJU-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JUJU-369]: https://warthogs.atlassian.net/browse/JUJU-369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JUJU-358]: https://warthogs.atlassian.net/browse/JUJU-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by tlm — APPROVED** [review]
lgtm

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
