### PR TITLE
Feature/gcr.io

### PR DESCRIPTION
**Pull request by ycliuhw**
This PR introduces `gcr.io` support for

- pulling `jujud-operator`, `juju-db` and `charm-base` images from k8s controllers, application operators, and sidecar pods;
- fetching available controller versions to upgrade for `upgrade-controller` command;

Driveby: moved registry provider code into an internal package;

Tested registries are(the rest of the registries will be implemented and tested in the following PRs):

| Registry | Public | Private |
| --- | --- | --- |
| azurecr.io |  |  |
| docker.io | :white_check_mark: | :white_check_mark: |
| ecr.aws |  |  |
| gcr.io | :white_check_mark: | :white_check_mark: |
| ghcr.io |  | :white_check_mark: |
| registry.gitlab.com |  | :white_check_mark: |
| quay.io |  |  |

## Checklist

 - [ ] ~Requires a [pylibjuju](https://github.com/juju/python-libjuju) change~
 - [ ] ~Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR~
 - [ ] ~Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed~
 - [x] Comments answer the question of why design decisions were made

## QA steps

```console
# download your google cloud service account JSON key;
# docker login;
$ docker login -u _json_key -p "$(cat gcr-json-key.json)" gcr.io

# copy your gcr credentials from ~/.docker/config.json
$ cat gcr.json
{
    "auth": "xxxx==",
    "repository": "gcr.io/<project-id>",
    "serveraddress": "gcr.io"
}

$ juju bootstrap microk8s k1 --config caas-image-repo="'$(cat gcr.json)'" --debug

$ mkubectl -ncontroller-k1 get pod/controller-0 -o json | jq .spec.imagePullSecrets

[
  {
    "name": "juju-image-pull-secret"
  }
]

$ mkubectl -ncontroller-k1 get secret/juju-image-pull-secret -o json | jq -r '.data[".dockerconfigjson"]' | base64 --decode | jq
{
  "auths": {
    "gcr.io": {
      "auth": "xxxx==",
      "username": "",
      "password": "",
      "serveraddress": "gcr.io"
    }
  }
}

$ juju upgrade-controller --agent-stream=develop


# public registry:
$ juju bootstrap microk8s k1 --config caas-image-repo="gcr.io/<project-id>" --debug

$ juju upgrade-controller --agent-stream=develop
```

## Documentation changes

https://discourse.charmhub.io/t/initial-private-registry-support/5079

## Bug reference

https://bugs.launchpad.net/juju/+bug/1935830
https://bugs.launchpad.net/juju/+bug/1940820
https://bugs.launchpad.net/juju/+bug/1935953

### CODE REVIEW

**Comment by ycliuhw** [comment]
[integrate more registry support, for example gcr, azure, etc.](https://trello.com/c/K1isSDRz/1749-integrate-more-registry-support-for-example-gcr-azure-etc)

**Comment by ycliuhw** [comment]
[integrate GCR registry](https://trello.com/c/FUF2dor1/1760-integrate-gcr-registry)

**Review by hpidcock — APPROVED** [review]
LGTM, just some comments

**Comment by hpidcock** [comment]
@ycliuhw can you please describe in the PR description what documentation changes will be required.

**Comment by ycliuhw** [comment]
> @ycliuhw can you please describe in the PR description what documentation changes will be required.

Sure, I will write documentation on discourse.

**Comment by ycliuhw** [comment]
!!build!!

**Comment by ycliuhw** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Pull request merged**
