### PR TITLE
deploy, apiserver: Added support for not registering metered charms whose plan is optional

### PR DESCRIPTION
**Pull request by mattyw**
(Review request: http://reviews.vapour.ws/r/5535/)

### CODE REVIEW

**Comment by mattyw** [comment]
$$merge$$

**Comment by mattyw** [comment]
$$merge$$

**Comment by cmars** [comment]
@mattyw There's a compile error in this patch:
```
+ make check
# github.com/juju/juju/cmd/juju/application
cmd/juju/application/deploy_test.go:1117: undefined: getMetricCredentialsAPI
cmd/juju/application/deploy_test.go:1117: undefined: metricCredentialsAPI
cmd/juju/application/deploy_test.go:1140: undefined: getMetricCredentialsAPI
cmd/juju/application/deploy_test.go:1140: undefined: metricCredentialsAPI
cmd/juju/application/deploy_test.go:1191: undefined: getMetricCredentialsAPI
cmd/juju/application/deploy_test.go:1191: undefined: metricCredentialsAPI
make: *** [check] Error 2
```
(see http://juju-ci.vapour.ws:8080/job/github-merge-juju/9019/artifact/artifacts/trusty-err.log)

**Comment by mattyw** [comment]
$$merge$$

**Comment by mattyw** [comment]
$$merge$$

**Comment by cmars** [comment]
$$merge$$

**Pull request merged**
