### PR TITLE
Implement Support for Constraint allocate-public-ip on GCE

### PR DESCRIPTION
**Pull request by manadart**
## Description of change

This patch adds support to GCE for the `allocate-public-ip` constraint. It is done by omitting the `AccessConfig` from instance network interfaces when the constraint is `false`.

The default behaviour remains to create allocate public IPs, so no change in behaviour is manifest unless the operator explicitly passes the constraint as `false`.

Eschewing a public IP has an additional effect of removing egress to the public internet. For now this is in the hands of the operator. Google provides options to work around this via Cloud NAT; see: https://cloud.google.com/nat/docs/using-nat#gcloud_11.

## QA steps

- Bootstrap to GCE.
- `juju add-machine` and check that the machine is assigned a public IP.
- `juju add-machine --constraints allocate-public-ip=false` and check that the machine is not assigned a public IP.

## Documentation changes

Yes, accompanying he 2.9 release.

## Bug reference

https://bugs.launchpad.net/bugs/1897419

### CODE REVIEW

**Comment by manadart** [comment]
[Support allocate-public-ip Constraint on GCE](https://trello.com/c/UEluULyq/2972-support-allocate-public-ip-constraint-on-gce)

**Review by SimonRichardson — COMMENTED** [review]
Code looks good... nice drivebys as well!

Q&A to come later.

**Review by SimonRichardson — APPROVED** [review]
Sorry it took so long, sorting out my GCE creds.

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
