### PR TITLE
cherry-pick 2.7 fix-branches

### PR DESCRIPTION
**Pull request by nammn**
### Checklist

 - [x] Checked if it requires a [pylibjuju](https://github.com/juju/python-libjuju) change?
 - [x] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR?
 - [ ] Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed?
 - [x] Do comments answer the question of why design decisions were made?

----

## Description of change

cherry-pick latest pr merge  3a8db2d122815e2ee1df3cf5cd4f83e5ae2dcc93 from 2.7.
https://github.com/juju/juju/pull/11019 is already responsible for pulling 2.7 to develop.

### CODE REVIEW

**Comment by nammn** [comment]
!!build!!

```
17:53:23 fatal: unable to access 'https://github.com/golang/dep/': Could not resolve host: github.com
```

**Comment by nammn** [comment]
!!build!!

**Comment by hpidcock** [comment]
This should be a forward port.

**Comment by nammn** [comment]
@hpidcock yeah you are right, I should not run away from all those conflicts :running_man:

**Pull request closed without merging**
