### PR TITLE
Use jammy by default on 3.0

### PR DESCRIPTION
**Pull request by hpidcock**
Juju 3.0 will default to using jammy as the controller/unit preferred base-image.

## QA steps

`juju bootstrap localhost` => lxd container with jammy
`make microk8s-operator-update && juju bootstrap microk8s` => controller pod with a jammy based image
deploy an iaas and k8s charm that support jammy, should chose jammy

## Documentation changes

N/A

## Bug reference

N/A

### CODE REVIEW

**Review by ycliuhw — COMMENTED** [review]
Has charm-base changed to use jammy as well?

Some tests need to be fixed.

**Comment by hpidcock** [comment]
> Has charm-base changed to use jammy as well?
> 
> Some tests need to be fixed.

yes, and yeah I'll look at the failing tests

**Pull request merged**
