### PR TITLE
Bump gomaasapi to v2.1.0

### PR DESCRIPTION
**Pull request by r00ta**
Including the fix committed with https://github.com/juju/gomaasapi/pull/101 and released with v2.1.0

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc

## Bug reference

https://bugs.launchpad.net/maas/+bug/2034014

### CODE REVIEW

**Comment by SimonRichardson** [comment]
@r00ta this is only targeting 4.0, which is not scheduled to have a stable release for some time. I think it will be wise to target 2.9 and then we can merge it forward.

**Comment by r00ta** [comment]
> @r00ta this is only targeting 4.0, which is not scheduled to have a stable release for some time. I think it will be wise to target 2.9 and then we can merge it forward.

Thanks @SimonRichardson ! I've updated the PR and changed the base branch accordingly

**Review by hpidcock — APPROVED** [review]

**Pull request merged**
