### PR TITLE
chore: remove device backend

### PR DESCRIPTION
**Pull request by barrettj12**
Remove unused device backend code from state.

## Checklist

- ~[ ] Code style: imports ordered, good names, simple structure, etc~
- ~[ ] Comments saying why design decisions were made~
- ~[ ] Go unit tests, with comments saying what you're testing~
- ~[ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- ~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

This is a removal of unused code. Check Juju builds and that all unit tests pass.

## Links

**Jira card:** JUJU-6678

### CODE REVIEW

**Review by SimonRichardson — COMMENTED** [review]
Although this isn't used, it is part of the charm metadata. If we remove this, we need buy-in to also remove it from the metadata. If we don't we need to keep it.

We need to communicate that action.

**Comment by barrettj12** [comment]
> Although this isn't used, it is part of the charm metadata. If we remove this, we need buy-in to also remove it from the metadata. If we don't we need to keep it.
> 
> We need to communicate that action.

From my POV, all I want to do is get rid of the model config usage here:
https://github.com/juju/juju/blob/879c36f56d000e5775b04fde043f1e5d69506f42/state/devices.go#L47

So what's the minimal change here that will allow us to proceed with model config? I could remove that method from the struct? Or I could just wire in a model config service?

**Review by hpidcock — APPROVED** [review]
Non-functional change. LGTM.

**Review by SimonRichardson — APPROVED** [review]
This will need to be reimplemented on 4.0 at some point. It should be added to the risk register as a note.

Happy for this to land.

**Pull request merged**
