### PR TITLE
[JUJU-1261] Bye bye rackspace

### PR DESCRIPTION
**Pull request by hmlanigan**
Rackspace is no longer a public cloud.

Removal of the rackspace provider, includes removal of the openstack NetworkingDecorator which was only used by rackspace.

A bit of cleanup to remove reference to the multi-cloud feature flag in test, it hasn't been used for a while now.

A continuation of #14127, which removes rackspace from clouds in 2.9 and will be merged into develop.

## QA steps

Bootstrap an openstack cloud.
The unit tests should be clean.

## Documentation changes

We need to note the removal of the rackspace provider in juju 3.0

### CODE REVIEW

**Comment by jack-w-shaw** [comment]
:wave: :wave: :wave:

**Review by manadart — APPROVED** [review]
Nice. Bootstrapping to ServerStack worked fine.

**Pull request merged**
