### PR TITLE
Move worker package to internal

### PR DESCRIPTION
**Pull request by SimonRichardson**
The worker package should not be used from outside of juju/juju as it's very much implementation-specific. If we put it behind the internal package, we're very much stating that this should not be used outside of juju/juju.

If a project does need to use a worker we have options:

 1. Copy and paste the worker
 2. Move the worker to a shared package 

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing

## QA steps

Just bootstrapping should be enough.

```
$ juju bootstrap lxd test --build-agent
```

## Links

**Jira card:** JUJU-XXX

### CODE REVIEW

**Review by hmlanigan — COMMENTED** [review]
`juju bootstrap localhost --build-agent` fails for me.
```
Bootstrap agent now started
Contacting Juju controller at 10.74.147.87 to verify accessibility...
ERROR unable to contact api server after 60 attempts: unable to connect to API: dial tcp 10.74.147.87:17070: connect: connection refused
```

```
2023-12-15 17:45:01 ERROR juju.worker.dependency engine.go:695 "bootstrap" manifold worker returned unexpected error: open /var/lib/juju/tools/4.0-beta2.1-ubuntu-amd64/tools.tar.gz: no such file or directory
```

```
$ ls -R /var/lib/juju/tools
/var/lib/juju/tools:
4.0-beta2.1-ubuntu-amd64  machine-0

/var/lib/juju/tools/4.0-beta2.1-ubuntu-amd64:
FORCE-VERSION  downloaded-tools.txt  jujud
```

**Comment by SimonRichardson** [comment]
@hmlanigan and others following along, this fixes one problem https://github.com/juju/juju/pull/16714 - you'll need to `rm -rf _deps` folder to ensure you have the latest one.

**Review by hmlanigan — APPROVED** [review]
I needed to rebuild _deps.

LGTM, QA good.

**Pull request merged**
