### PR TITLE
Use model tag filter to list all ec2 instances

### PR DESCRIPTION
**Pull request by jack-w-shaw**
Use model tag filter to list all ec2 instances

Previously, we opted for sec group attachments instead. This caused issues because the sec group sometimes doesn't exists, meaning we need to wait for time out.

Recently we changed how to tag ec2 instances so tags are created at the same time as the instance itself, meaning we no longer need this hack

This will speed up many ec2 provider actions

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- ~[ ] [Integration tests](https://github.com/juju/juju/tree/develop/tests), with comments saying what you're testing~
- ~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

#### Verify tags are created at instance creation

Insert a panic after this line
https://github.com/juju/juju/blob/develop/provider/ec2/environ.go#LL1162C21-L1162C21

Then, build juju and bootstrap. Verify the created controller instance's tags are populated

#### Verify standard actions

Undo the change above and rebuild

```sh
juju boostrap aws/eu-west-2 
juju add-model m
juju deploy ubuntu
juju destroy-controller aws
```

Should run without issue

### CODE REVIEW

**Review by hmlanigan — COMMENTED** [review]
It looks straightforward, however I have some concerns about instances created with juju 2.x as the tag change is in 3.1. I'm unable to properly test this week.

**Review by SimonRichardson — COMMENTED** [review]
Can we devise any tests for this? I'm not really happy we're making changes without tests.

**Review by hmlanigan — COMMENTED** [review]
QA is good.

**Review by SimonRichardson — COMMENTED** [review]
Just checking you ran these tests with `-race`?

**Comment by jack-w-shaw** [comment]
I have now

**Review by SimonRichardson — APPROVED** [review]

**Pull request merged**
