### PR TITLE
Merge 2.9

### PR DESCRIPTION
**Pull request by wallyworld**
Merge 2.9

#13242 Fix test run steps for assess_caas_deploy_kubeflow
#13239 Add juju secrets backend and wire up to api facade
#13247 Create a channel in a more permissive manner
#13248 Use system state to construct StateControllerConfig for remote relations
#13246 Add list-secrets CLI
#13252 Use tox to run tests for github kubeflow action test;
#13250 Simplify ec2 ConfigSuite.
#13255 Secret get attribute
#13256 Ensure unsubscribe on error
#13257 Only update homebrew release on juju/juju
#13258 Make it clearer that model-default affects new models
#13261 Move snap proxy setting to cloud init runcmd rather than bootcmd
#13263 Do not get address device via machine
#13261 Move snap proxy setting to cloud init runcmd rather than bootcmd
#13238 Apply a floor to the calculated next lease manager tick
#13264 Use upstream hashicorp/raft
#13267 secret-create passes through the rotate duration
#13268 Remove raftleaseservice worker

Conflicts mainly in deleted files and removal of restore

```
# Conflicts:
#       cmd/jujud/agent/machine/manifolds_test.go
#       mongo/internal_test.go
#       state/backups/backups_linux.go
#       state/backups/backups_nonlinux.go
#       state/backups/restore.go
#       state/backups/restore_test.go
```

## QA steps

See PRs

### CODE REVIEW

**Review by ycliuhw — APPROVED** [review]

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
!!build!!

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Pull request merged**
