### PR TITLE
[JUJU-1080] Adds LXD server certificate credential validation.

### PR DESCRIPTION
**Pull request by tlm**
When Juju users call add-credential with their own LXD config.yaml they
need to make sure they make no mistakes with the paths to the various
pki components required.

It's possible for a user to set the wrong file for the server
certificate and for Juju to accept it and try and start using it for
secure communications with a LXD daemon. The LXD client doesn't
perform any checks on pki credentials like this so we have to do it ourselves.

What this change does is help to identify when mistakes like this have
been made by inspecting the LXD server certificate to make sure it
exists and that the certificate has been signed for server
authentication.

This is about the sum of all the checks we can perform on this
certificate without hard coding internal logic of LXD into Juju that
could change and introduce it's own further complications.

One other change was made here to how we process credentials in
add-credential where file credentials are expanded on the command
before being passed onto providers for finalisation.

## Checklist

 - [x] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change
 - [x] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - [x] Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed
 - [x] Comments answer the question of why design decisions were made

## QA steps

Test valid credentials succeed. Setup a remote LXD to properly test.
```sh
# 1. Get your LXD client certificate and key
cp  ~/snap/lxd/common/config/client.crt /tmp/client.cert
cp  ~/snap/lxd/common/config/client.key /tmp/client.key

# 2. Upload the client certificate in /tmp/client.cert to the remote LXD server and add it to the trust store
scp /tmp/client.cert <remote-host>:/tmp/client.cert
ssh <remote-host>
lxc config trust add /tmp/client.cert

# 3. Get the server certificate while on the remote host from step 2
lxc info # copy the certificate contents to your local machine at  /tmp/server.cert

# 4. Create a new lxd cloud in juju on the local host with the cloud name server-cert
juju add-cloud

# 5. Create the credentials.yaml file to test with at /tmp/credentials.yaml
#credentials:
#  server-cert:
#    test:
#      auth-type: certificate
#      client-cert: /tmp/client.cert
#      client-key: /tmp/client.key
#      server-cert: /tmp/server.cert

#6. Add the credentials to Juju with
juju add-credential server-cert -f /tmp/credentials.yaml

#7 Bootstrap to the new cloud
juju bootstrap server-cert
```

If the above all works it's now time to check that bad certificates fail. Steps 1-4 can be reused here from above if you delete the credentials added to Juju from step 6 above.
```sh
# 1. Get your LXD client certificate and key
cp  ~/snap/lxd/common/config/client.crt /tmp/client.cert
cp  ~/snap/lxd/common/config/client.key /tmp/client.key

# 2. Upload the client certificate in /tmp/client.cert to the remote LXD server and add it to the trust store
scp /tmp/client.cert <remote-host>:/tmp/client.cert
ssh <remote-host>
lxc config trust add /tmp/client.cert

# 3. Get the server certificate while on the remote host from step 2
lxc info # copy the certificate contents to your local machine at  /tmp/server.cert

# 4. Create a new lxd cloud in juju on the local host with the cloud name server-cert
juju add-cloud

# 5. Create the credentials.yaml file to test with at /tmp/credentials.yaml
#credentials:
#  server-cert:
#    test:
#      auth-type: certificate
#      client-cert: /tmp/client.cert
#      client-key: /tmp/client.key
#      server-cert: /tmp/client.cert

#6. Add the credentials to Juju with. This step should fail with an appropriate error message telling you the server certificate is invalid
juju add-credential server-cert -f /tmp/credentials.yaml
```

## Documentation changes

N/A

## Bug reference

https://bugs.launchpad.net/juju/+bug/1973834

### CODE REVIEW

**Review by hpidcock — APPROVED** [review]

**Comment by hpidcock** [comment]
$$merge$$

**Comment by tlm** [comment]
$$merge$$

**Pull request merged**
