### PR TITLE
Merge 2.1 into Develop

### PR DESCRIPTION
**Pull request by jameinel**
There were a few conflicts, hopefully they have all been resolved correctly.

This brings all of the 2.1 branch into the develop series, so that we know we haven't missed any 2.1 functionality or regress anything when we release 2.2.

### CODE REVIEW

**Comment by jameinel** [comment]
!!build!!

**Comment by jameinel** [comment]
$$merge$$

**Comment by jameinel** [comment]
$$merge$$
(turns out 2.1 had a newer version of 'utils' than 2.2, I thought 2.2 would have newer dependencies.)

**Comment by jameinel** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by jameinel** [comment]
$$merge$$

**Pull request merged**
