### PR TITLE
Budget command supports moving budgets between wallets.

### PR DESCRIPTION
**Pull request by tasdomas**
## Description of change
This change enables users to use the `juju budget` command to move a budget to a different wallet (as well as update the budget's limit).

This change was requested by beta users.
## QA steps
Running the `juju budget` command with a parameter referencing an existing wallet should move the budget to the new wallet.

## Documentation changes
The change augments the `juju budget` command.

### CODE REVIEW

**Comment by nskaggs** [comment]
Can you have a look at the acceptance test for budgets and add in this new functionality?  Or are you happy with unit tests?

https://github.com/juju/juju/blob/develop/acceptancetests/assess_budget.py

**Comment by tasdomas** [comment]
:build:

**Comment by tasdomas** [comment]
!!build!!

**Comment by tasdomas** [comment]
@howbazaar - @anastasiamac  suggested I should get your review on this

**Comment by anastasiamac** [comment]
@howbazaar,
Mostly, it needs your approval to be included in the next Juju release.

**Comment by tasdomas** [comment]
$$merge$$

**Comment by pmatulis** [comment]
Let the Docs team (me) know if something needs changing at the online documentation level.

**Pull request merged**
