### PR TITLE
Move the socket pprof code to a real worker

### PR DESCRIPTION
**Pull request by howbazaar**
Change the implementation to use abstract domain sockets with a well defined name.

(Review request: http://reviews.vapour.ws/r/5167/)

### CODE REVIEW

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by howbazaar** [comment]
$$merge$$

**Comment by howbazaar** [comment]
$$cert-updater-failure$$

**Comment by howbazaar** [comment]
$$unexpected-message$$

**Pull request merged**
