### PR TITLE
Unit Series Change Does Not Fire Config-Changed Hook

### PR DESCRIPTION
**Pull request by manadart**
## Description of change

This patch reverts early work intended as part of the upgrade-series functionality.
- Series is no longer passed in a uniter API call to `Refresh`.
- Series is not tracked in uniter local or remote state.
- Series being now absent is obviously not used to determine firing a config-changed hook.

The PR landing the changes was https://github.com/juju/juju/pull/7794. Some of those changes remain, such as the `Refresh` method itself, and the fact that it delivers both `Life` and `Resolved` members.

## QA steps

Bootstrap, deploy and execute a series-upgrade workflow. No errors are reported at the CLI or in the log.

## Documentation changes

None.

## Bug reference

N/A

### CODE REVIEW

**Comment by manadart** [comment]
[investigate how to deprecate old stuff](https://trello.com/c/b1o95Hc3/652-investigate-how-to-deprecate-old-stuff)

**Comment by hmlanigan** [comment]
I QA'd the juju update-series command, but not the juju upgrade-series command.

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
Mongo start faiure.
$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
```
11:38:28 Waiting for Cloud-init to finish.
11:38:31 Build was aborted
11:38:31 Aborted by Juju CI Workers
```
Give the $$merge$$ another shot.

**Comment by manadart** [comment]
```
12:12:29 provisioner_test.go:1634:
12:12:29     s.checkStartInstances(c, machines)
12:12:29 provisioner_test.go:330:
12:12:29     c.Fatalf("provisioner did not start an instance")
12:12:29 ... Error: provisioner did not start an instance
```
$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
Something's up.
```
15:49:01 Installing go-1.11 snap
15:49:21 error: cannot perform the following tasks:
15:49:21 - Mount snap "core" (5742) ([start snap-core-5742.mount] failed with exit status 1: A dependency job for snap-core-5742.mount failed. See 'journalctl -xe' for details.
```

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
