### PR TITLE
provider/azure: fix create-model

### PR DESCRIPTION
**Pull request by axw**
Add endpoint and storage-endpoint to,
and remove credentials and storage
account type from, restricted config
attributes.

Fixes https://bugs.launchpad.net/juju-core/+bug/1558769

(Review request: http://reviews.vapour.ws/r/4250/)

### CODE REVIEW

**Comment by wallyworld** [comment]
$$merge$$

**Comment by axw** [comment]
$$merge$$

**Comment by axw** [comment]
$$-_-$$

**Comment by axw** [comment]
$$FFS$$

**Pull request merged**
