### PR TITLE
feat(cmd-action): allow running actions without specifying unit number

### PR DESCRIPTION
**Pull request by ca-scribner**
Before this commit, `juju run` required the user to specify a unit by one of:
* full unit id, with number ("mysql/0")
* application name with leader alias ("mysql/leader")

After this commit, users can also specify the application name without any suffix and that will imply the action should run on the leader.  For example, `juju run mysql` resolves to `juju run mysql/leader`

A downside of this change is that, although the CLI still catches input errors, some cases are now ambiguous as to the *cause* of the error.  This is because application names, action names, and some key-value argument keys share the same schema.  For example, if a user does `juju run mysql/5 mysql action-name kvarg-missing-equal-sign`, we cannot definitively say whether "kvarg-missing-equal-sign" is a malformed key-value argument, or if "kvarg-missing-equal-sign" is the action name and instead "action-name" is actually a second application name.  In either case, users are alerted to there being *an* error.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [X] ~~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~~
- [X] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages
  - usage instructions in the CLI are updated
  - the [relevant discourse page](https://juju.is/docs/juju/manage-actions#heading--run-an-action) was not changed because it does not go into this level of detail

## QA steps

on a Kubernetes controller
```
juju add-model kubeflow
juju deploy kubeflow-profiles --channel 1.8/stable --trust
juju run kubeflow-profiles create-profile username=x profilename=x
```

note that this action should execute on unit 0, but will fail with the message from the charm "Failed to apply PodDefaults"

## Documentation changes

CLI usage docs are updated

## Links

**Launchpad bug:** https://bugs.launchpad.net/juju/+bug/2058262

### CODE REVIEW

**Comment by SimonRichardson** [comment]
@ca-scribner I think that's the wrong LP bug attached. That's talking about "error when destroying model with storage without destroy-storage option should display before confirmation prompt"

**Comment by ca-scribner** [comment]
Whoops copy/paste mistake.  Ty!  Fixed

**Comment by SimonRichardson** [comment]
@ca-scribner let me discuss this with others, the concept seems good though.

**Comment by wallyworld** [comment]
> @ca-scribner let me discuss this with others, the concept seems good though.

We agreed that a consequence of this change, given the challenges of parsing the (too many) positional args, we would enforce that all units specified must be homogeneous. The doc always said as much, but it was theoretically possible to specify running an action "backup" on "mysql/0" and "postgresql/1" and it could work by coincidence. We really don't want this and now, from the cli validation perspective at least, we won't allow it.

**Comment by manadart** [comment]
My concern with this is that the user could intuit that they are running on all units of an application.

The current syntax (unit/n|unit/leader) is unambiguous - it is obvious that a single unit is targeted.

This introduces a transitive meaning. What we are supply is an _application_ identity and it is interpreted as a special case to mean the application's leader.

**Comment by ca-scribner** [comment]
Yeah @manadart's raises a fair point.  If I read `juju run mysql do-a-unit-specific-thing`, I could see someone interpret that as "run do-a-unit-specific-thing on everything in the mysql application"

**Comment by ca-scribner** [comment]
Closing this based on @manadart's comment

**Pull request closed without merging**
