### PR TITLE
Revert "Migrate to charm.v6-unstable and macaroon-bakery.v1."

### PR DESCRIPTION
**Pull request by natefinch**
Reverts juju/juju#3228 due to multiple problems they're causing in CI.

<mgz> bug 1494441 bug 1494864 two more unrelated windows test failures and who knows what else after the build succeeds
<mup> Bug #1494441: ppc64el: cannot find package "encoding" <blocker> <ci> <ppc64el> <regression> <unit-tests> <juju-core:Triaged> <gccgo-go (Ubuntu):Invalid> <gccgo-go (Ubuntu Trusty):In Progress> <https://launchpad.net/bugs/1494441>
<mup> Bug #1494864: TestBlockChangeServiceUpdate fails on windows <blocker> <ci> <regression> <test-failure> <unit-tests> <windows> <juju-core:Triaged> <https://launchpad.net/bugs/1494864>

(Review request: http://reviews.vapour.ws/r/2641/)

### CODE REVIEW

**Comment by cmars** [comment]
@rogpeppe @frankban FYI ^^

**Comment by natefinch** [comment]
$$merge$$

**Comment by natefinch** [comment]
$$JDFI$$  This fixes some blockers to master

**Comment by natefinch** [comment]
$$merge$$

**Comment by natefinch** [comment]
$$__JFDI__$$

**Pull request merged**
