### PR TITLE
Send metrics before destroying the environment.

### PR DESCRIPTION
**Pull request by alesstimec**
The state server attempts to send metrics one last time before being destroyed.

(Review request: http://reviews.vapour.ws/r/2167/)

### CODE REVIEW

**Comment by cmars** [comment]
$$merge$$

**Comment by alesstimec** [comment]
$$merge$$

**Comment by mattyw** [comment]
I've added a comment to rb that we might want to fix before we try this again

**Comment by alesstimec** [comment]
$$merge$$

**Comment by alesstimec** [comment]
$$merge$$

**Pull request merged**
