### PR TITLE
[JUJU-960] Fix/init container image pull secret

### PR DESCRIPTION
**Pull request by ycliuhw**
This PR ensures the juju init container has the image pull secret if it's configured in the controller config.

Drive-by: refactored the params for passing image reposiotry details across different layers(apiserver -> api -> worker).

No facade version bumps up because all of them are controller facades.

## Checklist

 - [ ] ~Requires a [pylibjuju](https://github.com/juju/python-libjuju) change~
 - [ ] ~Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR~
 - [ ] ~Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed~
 - [x] Comments answer the question of why design decisions were made

## QA steps

```console
$ cat ecr.json | jq '.username = "foo" | .password = "bar"'
{
  "serveraddress": "689913858002.dkr.ecr.ap-southeast-2.amazonaws.com",
  "repository": "689913858002.dkr.ecr.ap-southeast-2.amazonaws.com/ycliuhw-888",
  "username": "foo",
  "password": "bar",
  "region": "ap-southeast-2"
}

$ juju bootstrap microk8s k1 --config caas-image-repo=./ecr.json --debug --show-log

$ juju add-model t1

$ juju deploy snappass-test

$ juju deploy cs:~juju/mariadb-k8s-3

$ mkubectl -ncontroller-k1 get pod/controller-0 -o json | jq .spec.imagePullSecrets
[
  {
    "name": "juju-image-pull-secret"
  }
]

$ mkubectl -nt1 get pods \
    snappass-test-0 \
    mariadb-k8s-operator-0 \
    mariadb-k8s-0 \
    modeloperator-645d7dfdcd-h6bgp -o json | jq '.items[].spec.imagePullSecrets'
[
  {
    "name": "juju-image-pull-secret"
  }
]
[
  {
    "name": "juju-image-pull-secret"
  }
]
[
  {
    "name": "mariadb-k8s-mariadb-k8s-secret"
  },
  {
    "name": "juju-image-pull-secret"
  }
]
[
  {
    "name": "juju-image-pull-secret"
  }
]

$ mkubectl -nt1 get pod/snappass-test-0 -o json | jq '.spec.containers[].image'
"689913858002.dkr.ecr.ap-southeast-2.amazonaws.com/ycliuhw-888/charm-base:ubuntu-20.04"
"registry.hub.docker.com/library/redis@sha256:27bea08330830c6e5efc456075d66eb1fb4b76e5518947e8c87556adf1df3e51"
"registry.hub.docker.com/benhoyt/snappass-test@sha256:32506b5ac7bde75b7a76bee003cf8c77f30fc936f446c8c52d457b8fe6fce96f"

$ mkubectl -nt1 get pod/mariadb-k8s-operator-0 -o json | jq '.spec.containers[].image'
"689913858002.dkr.ecr.ap-southeast-2.amazonaws.com/ycliuhw-888/jujud-operator:2.9.29"

$ mkubectl -nt1 get pod/modeloperator-76598cd988-pwtzk -o json | jq '.spec.containers[].image'
"689913858002.dkr.ecr.ap-southeast-2.amazonaws.com/ycliuhw-888/jujud-operator:2.9.29"

$ mkubectl -ncontroller-k1 get pod/controller-0  -o json | jq '.spec.containers[].image'
"689913858002.dkr.ecr.ap-southeast-2.amazonaws.com/ycliuhw-888/juju-db:4.4"
"689913858002.dkr.ecr.ap-southeast-2.amazonaws.com/ycliuhw-888/jujud-operator:2.9.29"

```

## Documentation changes

No

## Bug reference

https://bugs.launchpad.net/juju/+bug/1968527

### CODE REVIEW

**Comment by ycliuhw** [comment]
!!build!!

**Review by wallyworld — APPROVED** [review]

**Comment by ycliuhw** [comment]
!!build!!

**Comment by ycliuhw** [comment]
$$merge$$

**Comment by ycliuhw** [comment]
$$merge$$

**Pull request merged**
