### PR TITLE
Increment 2.0 beta13

### PR DESCRIPTION
**Pull request by nskaggs**
Increment master to beta13.

### CODE REVIEW

**Comment by nskaggs** [comment]
Given our troubles, let's hold this until beta12 is literally released, heh.

**Comment by sinzui** [comment]
Ship it, LGTM, r=me.

**Comment by nskaggs** [comment]
$$JFDI$$

**Comment by nskaggs** [comment]
$$merge$$ __jFDI__

**Comment by nskaggs** [comment]
CI will block until with iterate to the new version, hence the override.

**Comment by nskaggs** [comment]
$$merge$$ __JFDI__

**Pull request merged**
