### PR TITLE
3.0 to develop

### PR DESCRIPTION
**Pull request by jack-w-shaw**
Merge 3.0 -> develop

This merges:
- https://github.com/juju/juju/pull/15053
- https://github.com/juju/juju/pull/15052
- https://github.com/juju/juju/pull/14977
- https://github.com/juju/juju/pull/15056

There were a few conflicts around remove-* and destroy-* commands, which have been resolved

### QA Steps

Verify that the remove-* commands and destroy-* commands act as expected

### CODE REVIEW

**Comment by jack-w-shaw** [comment]
QA has been verified on my own machine

**Comment by jack-w-shaw** [comment]
QA has been verified on my own machine

**Review by anvial — APPROVED** [review]
PR build is OK
Tests are OK

I've checked test scenarios on "destroy controller/model confirmation" and also passed OK.
So +1 from me.

**Pull request merged**
