### PR TITLE
Remove acceptancetests

### PR DESCRIPTION
**Pull request by SimonRichardson**
We're spending too long on old testing infrastructure and not spending
time on working on real bugs we have in Juju. People keep adding and
changing this code, but it's deprecated and dead.

All this code is available in the history of the project. As these tests
are dead weight, we should look to the future and write new tests.
Either they be integration tests in bash or in go.

## Checklist

 - [ ] Requires updating our CI to not call them.

### CODE REVIEW

**Comment by juanmanuel-tirado** [comment]
I would be more than happy to get rid off all these tests if we can ensure that we continue testing these situations. Actually, this kind of tests should be done using pylibjuju, not ad-hoc python code.

**Comment by SimonRichardson** [comment]
> I would be more than happy to get rid off all these tests if we can ensure that we continue testing these situations

We've been wanting to remove these for over 2 years. Although we've made some progress, it's been rather small.

> Actually, this kind of tests should be done using pylibjuju, not ad-hoc python code.

Pylibjuju would never gain the powers to do what this jujupy code can do. They serve different purposes. One is for an operator of juju the other is testing juju from python i.e. jujupy can bootstrap, upload binaries and create simple stream servers, none of which we'd ever want pylibjuju to do.

**Review by wallyworld — CHANGES_REQUESTED** [review]
Personally I only want to remove these after we have the equivalent tests done the new way. We can do it in stages, but we should not delete tests without ensuring there's still coverage elsewhere.

**Comment by hpidcock** [comment]
Only complaint I have is this really should be on 3.0/develop. I agree removing them forces us to implement tests in the new way, but I'd rather that forced focus be on develop.

**Comment by SimonRichardson** [comment]
The first stage decision is to remove unused (webscale tests) and constantly failing tests from proving grounds. The second stage is then to work out if any tests have overlap with the bash tests and delete them also. Any tests leftover are deprecated and up for conversion then deletion.

**Pull request closed without merging**
