### PR TITLE
Merge 2.9 into develop

### PR DESCRIPTION
**Pull request by manadart**
Merge from 2.9 to bring forward:
- #12998 from wallyworld/merge-2.8-20210520
- #12996 from wallyworld/caas-remove-storage
- #12991 from ycliuhw/fix/lp-1927721
- #12995 from jnsgruk/2.9
- #12994 from SimonRichardson/upgrade-series-containers-regression
- #12992 from manadart/2.9-upgrades
- #12982 from manadart/2.9-net-get-sort
- #12990 from jujubot/increment-to-2.9.3
- #12988 from tlm/lp1928486-proxy-vars
- #12989 from wallyworld/ss-service-name
- #12987 from wallyworld/embeddedcli-macaroon-error
- #12985 from wallyworld/export-bundle-defaults
- #12984 from wallyworld/operator-charm-upgrade
- #12981 from wallyworld/remove-unit-panic
- #12979 from wallyworld/k8s-lxd-cloud
- #12978 from wallyworld/sidecar-charm-storage-fix
- #12980 from tlm/2.8-to-2.9-merge
- #12972 from SimonRichardson/add-relation-error
- #12970 from manadart/2.9-address-refactoring
- #12976 from jujubot/increment-to-2.9.2
- #12975 from wallyworld/merge-2.8-20210513
- #12968 from ycliuhw/fix/lp-1927311
- #12973 from achilleasa/2.9-fix-misc-refresh-with-switch-issues
- #12961 from manadart/2.9-store-is-secondary
- #12969 from SimonRichardson/fix-static-analysis
- #12964 from tlm/k8s-proxy-ssh
- #12951 from ycliuhw/fix/lp-1925734
- #12962 from tlm/k8s-proxying-python-rbac
- #12959 from SimonRichardson/bundle-scale-overlays
- #12960 from SimonRichardson/users-cli-help-directive
- #12954 from manadart/2.9-machine-config-per-nic
- #12958 from wallyworld/improve-add-relation-message
- #12956 from tlm/lp-1926595-libjuju
- #12955 from wallyworld/destroy-model-timeout
- #12957 from tlm/lp-1892255-env-vars
- #12953 from wallyworld/provider-context-refactor
- #12952 from manadart/2.9-transport-address-config
- #12944 from wallyworld/extra-destroymodel-info

Conficts:
- apiserver/facades/client/action/operation.go
- apiserver/facades/client/application/application.go
- apiserver/facades/client/application/application_unit_test.go
- apiserver/facades/controller/caasoperatorprovisioner/provisioner.go
- apiserver/params/network.go
- caas/kubernetes/provider/application/application_test.go
- cmd/juju/application/refresher/refresher_mock_test.go
- cmd/juju/application/utils/utils.go
- feature/flags.go
- go.mod
- go.sum
- provider/azure/environ.go
- provider/azure/storage.go
- scripts/win-installer/setup.iss
- snap/snapcraft.yaml
- version/version.go

### CODE REVIEW

**Comment by manadart** [comment]
[Merge 2.9](https://trello.com/c/MLrA8M86/3671-merge-29)

**Review by hpidcock — APPROVED** [review]

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Pull request merged**
