### PR TITLE
Tweak some of the logging messages.

### PR DESCRIPTION
**Pull request by jameinel**
## Description of change

A couple of messages could use a bit more context.

## QA steps

Watch `juju debug-log` while agents are starting up. Especially when dealing with a controller that has multiple models.

## Documentation changes

None.

## Bug reference

None.

### CODE REVIEW

**Comment by wallyworld** [comment]
$$merge$$

**Comment by jameinel** [comment]
$$merge$$

**Comment by jameinel** [comment]
$$merge$$ (I had missed another stub that passed a null func)

**Comment by jameinel** [comment]
$$merge$$ 'mongo failed to listen'

**Pull request merged**
