### PR TITLE
Add snapcraft.yaml, dependencies for building juju as a snap

### PR DESCRIPTION
**Pull request by nskaggs**
Upstreaming snapcraft.yaml file. The snapcraft.yaml file I'm checking in here re-pulls the source, as the plugin doesn't seem to yet support using the local source. The readme also could be improved once the plugin is improved in order to mention how to make a developer build and share it via the snap store.

### CODE REVIEW

**Comment by nskaggs** [comment]
In order to try this, you need the godeps plugin. Since there still hasn't been a new release of snapcraft, grab it from master.

sudo curl -o /usr/lib/python3/dist-packages/snapcraft/plugins/godeps.py https://raw.githubusercontent.com/snapcore/snapcraft/master/snapcraft/plugins/godeps.py

**Comment by nskaggs** [comment]
Added https://github.com/juju/cmd/pull/40, https://github.com/juju/romulus/pull/59, https://github.com/juju/utils/pull/230 PR's in support

**Comment by natefinch** [comment]
LGTM after adding in the updates to juju/cmd and juju/utils, once they get the same update to remove launchpad deps.

**Comment by nskaggs** [comment]
$$merge$$

**Comment by nskaggs** [comment]
$$merge$$

**Comment by nskaggs** [comment]
$$merge$$

**Comment by nskaggs** [comment]
$$merge$$

**Comment by nskaggs** [comment]
$$merge$$

**Comment by nskaggs** [comment]
$$merge$$

**Comment by nskaggs** [comment]
Splitting up this PR in an attempt to isolate what is causing the unit test failure.

**Comment by nskaggs** [comment]
$$merge$$

**Comment by nskaggs** [comment]
$$merge$$

**Pull request merged**
