### PR TITLE
environs/config: add automatically-retry-hooks option

### PR DESCRIPTION
**Pull request by bogdanteleaga**
What the title says.

If I missed anything please let me know.

(Review request: http://reviews.vapour.ws/r/3665/)

### CODE REVIEW

**Comment by bogdanteleaga** [comment]
$$merge$$

**Comment by cherylj** [comment]
Master is currently blocked in preparation for the 2.0-alpha2 release.  I can merge this for you once we've released alpha2

**Comment by bogdanteleaga** [comment]
Ok, thanks

**Comment by cherylj** [comment]
$$__JFDI__$$

**Pull request merged**
