### PR TITLE
chore(k8s): delete operator storage code

### PR DESCRIPTION
**Pull request by barrettj12**
Operator storage is only used for podspec charms, which are no longer supported in 4.0. Delete all code relating to operator storage.

`caasBroker` has been removed from the application deploy code, as we do not validate workload storage at deploy time.

## Checklist

- ~[ ] Code style: imports ordered, good names, simple structure, etc~
- ~[ ] Comments saying why design decisions were made~
- ~[ ] Go unit tests, with comments saying what you're testing~
- ~[ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- ~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

Run microk8s smoke tests.

## Links

**Jira card:** JUJU-6352

### CODE REVIEW

**Comment by jnsgruk** [comment]
@benhoyt this will have a downstream effect on the `ops` documentation and the `use_juju_for_storage` parameter on `main`.

**Comment by benhoyt** [comment]
Great, thanks @jnsgruk. I've opened https://github.com/canonical/operator/issues/1284 to track.

**Review by wallyworld — COMMENTED** [review]
Initial comment - we're now saying "workload-storage" is mandatory - previously it was optional. Don't think we can avoid it. but we should QA on more than just microk8s and there's also migration implications that need to be addressed. QA also needs to include add-k8s on a cluster without a default storage class just to check messaging etc.

**Comment by hpidcock** [comment]
> Initial comment - we're now saying "workload-storage" is mandatory - previously it was optional. Don't think we can avoid it. but we should QA on more than just microk8s and there's also migration implications that need to be addressed. QA also needs to include add-k8s on a cluster without a default storage class just to check messaging etc.

We are saying workload storage is required for the controller. Everything else only needs workload storage if the model has charms that need storage.

**Comment by tlm** [comment]
@barrettj12 can we please get the PR rebased and a reviewer to do a final pass?

**Comment by hpidcock** [comment]
@barrettj12 why did this PR close?

**Comment by barrettj12** [comment]
I am closing this because there are no plans to work on it in the foreseeable future. If we decide later that we would like to complete this work, we can reopen this PR.

**Pull request closed without merging**
