### PR TITLE
Merge 2.9 into develop

### PR DESCRIPTION
**Pull request by manadart**
Merge from 2.9 to bring forward:
- #13344 from manadart/2.9-model-migration-versions
- #13345 from wallyworld/reconnect-saas-offer
- #13302 from tlm/aws-instance-profile
- #13334 from SimonRichardson/raft-apply-operation
- #13339 from wallyworld/secret-rotate-hook
- #13337 from wallyworld/remove-offer-fix
- #13336 from hpidcock/fix-unknown-operation-runaction
- #13335 from wallyworld/fix-k8s-deployment
- #13322 from ycliuhw/feature/gcr.io
- #13333 from SimonRichardson/raft-lease-queue
- #13331 from wallyworld/rotate-secrets-worker
- #13332 from SimonRichardson/lease-manager-dropped-connection
- #13330 from manadart/2.9-status-test-race

Conflicts:
- go.mod
- go.sum
- state/applicationoffers.go
- state/remoteapplication.go
- worker/uniter/hook/hook.go
- worker/uniter/operation/interface.go
- worker/uniter/operation/mocks/interface_mock.go
- worker/uniter/operation/runhook_test.go

Required juju/charm merge from v8 to v9:
https://github.com/juju/charm/pull/381

### CODE REVIEW

**Review by SimonRichardson — COMMENTED** [review]
Some failing tests in here.

**Comment by manadart** [comment]
!!build!!

**Review by wallyworld — APPROVED** [review]

**Comment by manadart** [comment]
!!build!!

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
[Merge 2.9 into develop](https://trello.com/c/zj5cGjhg/3989-merge-29-into-develop)

**Pull request merged**
