### PR TITLE
Make juju show take positional model.

### PR DESCRIPTION
**Pull request by perrito666**
Model is now a positional argument of juju show-model.
This addresses lp:1596593

### CODE REVIEW

**Comment by mitechie** [comment]
Tried to QA against master and when I built it I did not get it accepting the model name as the model to show. 

    $ djuju show-model controller
    default: ....

where djuju is an alias to my gopath/bin/juju

**Comment by mitechie** [comment]
QA ok with the latest changes. I was able to successfully 

    juju show-model controller

while activated on the default model and get the details I was looking for.

**Comment by macgreagoir** [comment]
Does Info need an Args field now that the model name is a positional argument?

**Comment by perrito666** [comment]
$$merge$$

**Comment by perrito666** [comment]
Indeed @macgreagoir tx for that input, the Args field was added before merging, cheers.

**Pull request merged**
