### PR TITLE
Follow github.com/canonical/lxd for lxd changes

### PR DESCRIPTION
**Pull request by SimonRichardson**
The following updates all the references to LXD, so that they point to the new upstream.

Additional changes were required. These include updating the tests to factor in the new unit spacing for units. `4MiB` becomes `4 MiB` and removal of the lxd logger from the client.

## QA steps

```sh
$ juju bootstrap lxd test --build-agent
$ juju enable-ha
$ juju add-model default
$ juju deploy ubuntu -n 3
$ juju add-machine --constraints="virt-type=virtual-machine"
$ juju deploy ubuntu nested --to=4/lxd/0
```

### CODE REVIEW

**Review by jameinel — APPROVED** [review]
That does seem a bit more than "just a sed script", we seem to import it in far more places than I would want us to. (why would we import lxd in 'api/client/client/client.go' seems very bad mojo for us.
container/lxd and provider/lxd make a lot of sense, it appears that state/charm is only a comment.

Do we have someone with a desire to decouple our api client to follow up on removing that import?

**Comment by SimonRichardson** [comment]
> import lxd in 'api/client/client/client.go' seems very bad mojo for us.

I'll fix this, this is a bad import.

**Comment by hmlanigan** [comment]
The last qa step should be `juju deploy ubuntu nested --to=lxd:3`, machine 4/lxd/0 doesn't exist

**Pull request merged**
