### PR TITLE
Remove Oracle Classic provider

### PR DESCRIPTION
**Pull request by timClicks**
## Description of change

This PR removes the legacy provider, replaced by oci.

## QA steps

n/a

## Documentation changes

- `juju list-clouds` - `oci` no longer appears, `oracle` refers to the "Oracle Cloud Interface"

## Bug reference

n/a

### CODE REVIEW

**Comment by timClicks** [comment]
$$merge$$

**Comment by timClicks** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by timClicks** [comment]
[delete old oracle provider](https://trello.com/c/tLf9CUii/551-delete-old-oracle-provider)

**Comment by timClicks** [comment]
Checking to see that it's just the merge that's failing

!!build!!

**Comment by timClicks** [comment]
Merging as the CI cleanup script failed, not the juju tests. To verify, (check the build)[ci.jujucharms.com/job/make-check-juju/1733/console] and Ctrl+F `11:57:32 error: not found`

$$merge$$

**Comment by timClicks** [comment]
$$merge$$

**Pull request merged**
