### PR TITLE
[JUJU-1283] Remove any logic not targetting upgrade steps from 2.9.x to 3.0

### PR DESCRIPTION
**Pull request by juanmanuel-tirado**
The current develop branch will be tagged 3.0. The `upgrades` package contains all the required logic to perform `juju` upgrades between versions. This PR only removes any test not designed to upgrade from 2.9.x to 3.0. This will free `juju 3.0` from maintaining old/legacy code. Any logic needed to upgrade from 2.9.x to 3.0 remains for future PRs. 

Landing this PR will facilitate #14109 and #14141 

## Checklist

 - [ ] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change
 - [ ] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - [ ] Added or updated [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) related to packages changed
 - [ ] Comments answer the question of why design decisions were made

## QA steps

NA

## Documentation changes

NA

## Bug reference

NA

### CODE REVIEW

**Comment by juanmanuel-tirado** [comment]
That's it. Misleading title. Thanks.

**Comment by manadart** [comment]
Please don't land that merge commit.

**Comment by jameinel** [comment]
I think removing all upgrade steps pre 2.9 makes a lot of sense. We then need to add a check that we are upgrading from a known version (eg, 2.9.0 or 2.9.15, or 2.9.32) and we refuse the upgrade if it is older than that.

I think it makes the most sense to keep most of 2.9 as a valid starting version, mostly because it communicates better. If we feel 2.9.15 or whatever is an annoying upgrade step to preserve, we could remove that code, but then the validation needs to ensure that we're starting from a juju 2.9.X that is greater than our supported versions.

**Comment by juanmanuel-tirado** [comment]
We have decided to maintain upgrade steps for 2.9.

 I will close this PR and approach these changes from a different PR to reduce the list of changes.

**Pull request closed without merging**
