### PR TITLE
[JUJU-3969] Allow migration from 3.1

### PR DESCRIPTION
**Pull request by SimonRichardson**
The following updates the precheck migrations from 3.1.0 to 4.0. We
don't allow 2.9 and 3.0 explicitly. If we believe 3.1 is to early, we can
change that at a later date.

This also removes the charmstore checks. There is no way a charmstore
charm can get into 3.1 one now that we block it at the deploy level and never
allow it from a migration standpoint (both source and target checks). So
we can remove it from the 4.x source code. In theory, we could also remove it
in 3.2 or later, but we can decide to back port that at a later date.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [x] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing

### Attempting to migrate a 2.9 model should fail.

```sh
$ sudo snap install juju --channel 2.9/stable --classic
$ juju bootstrap lxd test29
$ juju add-model default
$ juju deploy ubuntu
$ sudo snap remove juju --purge
$ make go-install
$ juju bootstrap lxd test40
$ juju switch controller
$ juju wait-for application controller
$ juju switch test29
$ juju wait-for application ubuntu
$ sleep 10
$ juju migrate default test40
ERROR looking up model users in target controller: source prechecks failed: migrate to "4.0-beta1.1" is not supported from "2.9.42"
```

### Attempting to migrate a 3.1 model should succeed

Note this will only work with a local build of juju, because we haven't released 3.1 with the updated source checking.

```sh
$ snap install juju --channel=3.1/edge
$ /snap/bin/juju bootstrap lxd test31
$ /snap/bin/juju add-model m31
$ /snap/bin/juju deploy ubuntu
$ # wait for ubuntu to deploy 
$ juju bootstrap lxd test40 --build-agent
$ juju migrate m31 test40
$ juju switch test40:m31
```

### CODE REVIEW

**Comment by hmlanigan** [comment]
Following the `Attempting to migrate a 2.9 model should fail` steps, failure, but not the one we're looking for
```
# juju => 4.0-beta1-ubuntu-amd64
$ juju migrate move-me simon-test-40
ERROR juju client with version 4.0 used with a controller having major version 2 not supported
re-install your juju client to match the version running on the controller
# sjuju => 2.9.43
$ sjuju migrate move-me simon-test-40
ERROR looking up model users in target controller: juju client with version 2.9 used with a controller having major version 4 not supported
re-install your juju client to match the version running on the controller
```

**Review by hmlanigan — COMMENTED** [review]
Code LGTM, the QA steps for 2.9 -> 3.0 did not go as expected.

**Comment by SimonRichardson** [comment]
> Code LGTM, the QA steps for 2.9 -> 3.0 did not go as expected.

I'm guessing you mean 4.0?

**Comment by SimonRichardson** [comment]
Been open to long, will have to make a new one in the future.

**Comment by SimonRichardson** [comment]
@hmlanigan @jack-w-shaw probably want to get this Q&A again

**Comment by SimonRichardson** [comment]
That's correct

**Review by manadart — APPROVED** [review]
From 2.9, got:
```
ERROR refreshing model "default": juju client with version 2.9 used with a controller having major version 4 not supported
```

**Comment by SimonRichardson** [comment]
closing this again, as we're going to take a different approach. One that removes a lot of the technical dept of client/server side checking versions instead of API facade versions.

**Pull request closed without merging**
