### PR TITLE
Removed race in history pruner tests.

### PR DESCRIPTION
**Pull request by perrito666**
There was a report of a race in statushistorypruner tests https://bugs.launchpad.net/juju-core/+bug/1492095 this removes the race which consisted in a variable being written/read in various routines.

(Review request: http://reviews.vapour.ws/r/2592/)

### CODE REVIEW

**Comment by perrito666** [comment]
$$merge$$

**Comment by perrito666** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by perrito666** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by perrito666** [comment]
$$merge$$

**Comment by perrito666** [comment]
$$merge$$

**Comment by perrito666** [comment]
$$merge$$

**Comment by perrito666** [comment]
$$merge$$

**Comment by perrito666** [comment]
$$merge$$

**Comment by perrito666** [comment]
$$merge$$

**Comment by perrito666** [comment]
$$merge$$

**Pull request merged**
