### PR TITLE
zesty is eol

### PR DESCRIPTION
**Pull request by nskaggs**
## Description of change

Zesty will end of life this week. This removes zesty from our produced builds and charms.

## QA steps
CI builds should no longer produce a zesty binary. Further, release builds should also no longer produce a zesty binary. The release template documents have been updated already in light of this change.

### CODE REVIEW

**Comment by nskaggs** [comment]
[Zesty is EOL](https://trello.com/c/aqo9piHL/154-zesty-is-eol)

**Comment by nskaggs** [comment]
[Zesty is EOL](https://trello.com/c/aqo9piHL/154-zesty-is-eol)

**Comment by nskaggs** [comment]
[Zesty is EOL](https://trello.com/c/aqo9piHL/154-zesty-is-eol)

**Comment by nskaggs** [comment]
@Veebers , can I get a review?

**Comment by Veebers** [comment]
LGTM

**Comment by nskaggs** [comment]
$$merge$$

**Pull request merged**
