### PR TITLE
Fixes Bug 1546790: env var missing from hook context.

### PR DESCRIPTION
**Pull request by anastasiamac**
Availability zone environment variable was missing from hook context.

(Review request: http://reviews.vapour.ws/r/4043/)

### CODE REVIEW

**Comment by cholcombe973** [comment]
+1 from me.  Looks great

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by cholcombe973** [comment]
Awesome! Thanks again

**Comment by anastasiamac** [comment]
$$__JFDI__$$

**Pull request merged**
