### PR TITLE
[JUJU-1415] WIP: Replace Xenial network tests with Jammy

### PR DESCRIPTION
**Pull request by jack-w-shaw**
Also deploy testing charms from source locally after packing. This makes the tests more clear
and makes patching much easier

Also implement workaround for Jammy bug that breaks the network-test
webserver by disabling http server logging

## Checklist

 - ~[ ] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change~
 - [x] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - ~[ ] Added or updated [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) related to packages changed~
 - [ ] Comments answer the question of why design decisions were made

## QA steps

```sh
BOOTSTRAP_PROVIDER=localhost BOOTSTRAP_CLOUD=localhost ./main.sh network
BOOTSTRAP_PROVIDER=aws BOOTSTRAP_CLOUD=aws ./main.sh network
```

### CODE REVIEW

**Comment by anvial** [comment]
I've problems with passing QA steps:

https://pastebin.canonical.com/p/qyfwhQHTTR/

    | suites/network/network_health.sh: line 8: charm: command not found

**Comment by tlm** [comment]
This is not the same charm that we have been testing with. I am assuming the is the bzr one I found on lp?

**Comment by tlm** [comment]
Closing pr in favor of #14267

**Comment by jack-w-shaw** [comment]
@tlm If you're going to close my PR, a PR I worked _tirelessly_ on day and night, can you at least make sure your alternative solves the problem?
😉

**Pull request closed without merging**
