### PR TITLE
Use juju repos for mgo, txn, blobstore instead of gopkg.in

### PR DESCRIPTION
**Pull request by wallyworld**
A mechanical change to the imports for
- mgo
- txn
- blobstore
- testing

and also indirectly
- juju/charm
- juju/charmrepo
- juju/term-client
- juju/romulus
- juju/version

We were already replacing `gopkg.in/mgo.v2` with `github.com/juju/mgo v2`. However, the above upstream repos were still using the gopkg.in version without the fixes done in juju/mgo.

We also needed to update github.com/go-macaroon-bakerymacaroon-bakery to use juju/mgo/v2. However, since this is potentially a breaking api change and several canonical projects use it, we had to rev the version to v3. This then had the flow on effect of causing issues with other upstream repos used by juju. In particularalso need to update the upstream github.com/lxd/lxc repo as it uses gopkgin/macaroon-bakery.v2 and this is incompatible with the new v3 version.

However, the lxd/lxc sha we are using is 12 months out of date and the repo has diverged and is no longer compatible with juju without code changes. So I've forked the specific sha to a new https://github.com/juju/lxc and made the small updates to import the new v3 bakery. There's a go mod replace added to pull in this fork for use with juju.

The bulk of the juju changes are the import path updates.
The rest is go.mod updates to the shas.

There's no code changes as such.

## QA steps

bootstrap and deploy a charm or two

### CODE REVIEW

**Comment by wallyworld** [comment]
[update juju 2.8 to use juju/mgo everywhere](https://trello.com/c/QxFyFvLS/1421-update-juju-28-to-use-juju-mgo-everywhere)

**Review by jameinel — APPROVED** [review]
so we had just been redirecting the import in:
```
replace gopkg.in/mgo.v2 => github.com/juju/mgo v2.0.0-20201106044211-d9585b0b0d28+incompatible
```
Which meant we could import our version of the code without having to rewrite the world.
But it is probably a bit cleaner to move down this path.

**Comment by wallyworld** [comment]
> so we had just been redirecting the import in:
> 
> ```
> replace gopkg.in/mgo.v2 => github.com/juju/mgo v2.0.0-20201106044211-d9585b0b0d28+incompatible
> ```
> 
> Which meant we could import our version of the code without having to rewrite the world.
> But it is probably a bit cleaner to move down this path.

The upstream repos need to grab juju/mgo also and we either need to add the replace to all them, or clean things up here.
There's a lot of import churn anyway due to the upstream version changes due to the new juju/mgo import path for them, so we may as well handle the churn and make things cleaner.

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
