### PR TITLE
Improved layer separation for gce provider.

### PR DESCRIPTION
**Pull request by perrito666**
The existing storage provider for GCE had a layer piercing having compute imported in the wrong places, this is a step towards correcting that.

(Review request: http://reviews.vapour.ws/r/2480/)

### CODE REVIEW

**Comment by perrito666** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
