### PR TITLE
Merge from 3.1

### PR DESCRIPTION
**Pull request by hmlanigan**
Contains:

* #17004 from hmlanigan/merge-from-2.9

Merge conflicts, deleted both files:

* CONFLICT (modify/delete): cmd/jujuc/main_test.go deleted in HEAD and modified in upstream/3.1.  Version upstream/3.1 of cmd/jujuc/main_test.go left in tree.
CONFLICT (modify/delete): cmd/jujud/main_test.go deleted in HEAD and modified in upstream/3.1.  Version upstream/3.1 of cmd/jujud/main_test.go left in tree.

### CODE REVIEW

**Review by Aflynn50 — COMMENTED** [review]
This doesn't seem to contain changes from either:
- https://github.com/juju/juju/pull/16993
- https://github.com/juju/juju/pull/16992
Just:
- https://github.com/juju/juju/pull/16978
The PR description suggests all of them should be going in.

**Comment by hmlanigan** [comment]
I don't know of the details, but sometimes the references show up in the merge, but the code isn't needed. This means next merge forward, we won't see them at all. 

#16993 was back ported from 3.3 so it won't have code here.

The tests causing problems the GOCOVERDIR do not exist in 3.3 - per #16992

For #16992 - the supported operating systems work differently in 3.3 and the tests shouldn't fail there. - but will wait for the unit test results, however they would have already been failing if they were going to.

**Review by cderici — APPROVED** [review]
Yeah I think it's good to go 👍

**Pull request merged**
