### PR TITLE
Limit that model names may only contain safe characters

### PR DESCRIPTION
**Pull request by macgreagoir**
Safe characters are lowercase letters, digits and hyphens.

Fixes lp#1568944

QA steps:

  * requires names as per juju/names/pull/66

  * attempt to `juju add-model` using model names including characters outside the definition of safe above

(Review request: http://reviews.vapour.ws/r/4914/)

### CODE REVIEW

**Comment by mitechie** [comment]
I think it'd be worthwhile looking at limiting in the same way usernames, charm names, etc are handled. Having different rules for different things seems like it might make it tougher to maintain over time. 

Did you look at the rules in other parts of the system?

**Comment by macgreagoir** [comment]
Thanks Rick, that's a very good point, of course.. The short answer is that I had looked at the user names rule, which is more permissive, but had based the regexp for model names on the comments in the bug. I've now looked at the other naming rules, bu am not seeing much of a consensus pattern.

I'm going to make another mention in the bug before aligning this with user names.

As an aside, and based on another comment I've received, I'm also moving the validation check to names, alongside the UUID check.

**Comment by macgreagoir** [comment]
$$merge$$

**Comment by macgreagoir** [comment]
$$fixes-1568944$$

**Comment by macgreagoir** [comment]
$$merge$$

**Comment by macgreagoir** [comment]
$$fixes-1568944$$

**Pull request merged**
