### PR TITLE
Remove deprecated juju charm command, including juju charm resources.

### PR DESCRIPTION
**Pull request by hmlanigan**
Remove deprecated `juju charm` command, including `juju charm resources`. Deprecated in juju 2.3, and replaced with juju charm-resources.

## QA steps

```console
$ juju charm
ERROR juju: "charm" is not a juju command. See "juju --help".

Did you mean:
	grant
```

## Bug reference

https://bugs.launchpad.net/juju/+bug/1707836

### CODE REVIEW

**Comment by hmlanigan** [comment]
!!build!!

**Review by SimonRichardson — APPROVED** [review]

**Comment by hmlanigan** [comment]
resolving conflict.

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
$$merge$$

**Comment by hmlanigan** [comment]
$$merge$$

**Pull request merged**
