### PR TITLE
[JUJU-1222] Update LXD dependency to the latest 5.3 release

### PR DESCRIPTION
**Pull request by manadart**
LXD has some changes to behaviour since our venerable version of the dependency.

Here we update it to the latest 5.2 version. Additional changes include:
- Changes to certificate post requests for the new payload structure.
- Updates to the logging proxy to handle LXD's use of [Logrus](https://github.com/Sirupsen/logrus).
- Updates to error type detection to use the LXD helpers.

## QA steps

- Bootstrap to lxd/localhost.
- Include `lxd=TRACE` in the controller config `logging-level`.
- Deploy some workloads and observe the output in controller logs.

## Documentation changes

None.

## Bug reference

N/A

### CODE REVIEW

**Review by tomponline — APPROVED** [review]
Thanks!

**Comment by SimonRichardson** [comment]
You want to deploy a HA setup using prior version and then upgrade, I think I had problems in the past. Might be ok now, but worth checking...

**Comment by manadart** [comment]
@juanmanuel-tirado This won't build or merge at present. Unit tests fail because of the version of `juju/errors` that LXD is on, is in an intermediate state. @tlm is going to submit the required change and propose an update patch to LXD. Then we'll need to use _that_ dependency here once it is release-tagged.

**Comment by juanmanuel-tirado** [comment]
Gotcha. We have to consider using semantic versioning for the `juju/errors`. I find particularly cumbersome to take a look at the hashed tag.

**Review by wallyworld — APPROVED** [review]

**Pull request merged**
