### PR TITLE
Drop support for oracle classic provider

### PR DESCRIPTION
**Pull request by wallyworld**
## Description of change

The oracle classic provider is no longer functional (Oracle dropped upstream support, no images etc) so remove it from Juju.

## QA steps

```
$ juju bootstrap oracle-classic
ERROR unknown cloud "oracle-classic", please try "juju update-public-clouds"
```

## Documentation changes

We'll need to remove oracle classic in any docs.

### CODE REVIEW

**Review by ycliuhw — APPROVED** [review]
lgtm, thanks

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
[drop legacy oracle provider](https://trello.com/c/kcxGXYIc/1194-drop-legacy-oracle-provider)

**Comment by wallyworld** [comment]
$$merge$$

**Comment by manadart** [comment]
@wallyworld I removed the various artefacts for the legacy cloud from cloud-city. 
Doesn't look like we have any integration tests using the old cloud, but `z-clean-resources-oracle` needs an update to use the new OCI cloud.

**Pull request merged**
