### PR TITLE
Remove controller port api worker

### PR DESCRIPTION
**Pull request by SimonRichardson**
The following removes the controllerport worker. This is no longer
required as we're making the controller-config controller-api-port
immutable. This means we no longer need a worker to track the
changes.

Obviously, there will be documentation changes, but we've now removed
some inter-dependencies between the controller port worker and other
workers that were required to watch if it was bouncing or not.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing

## QA steps

```sh
$ juju bootstrap lxd test --build-agent --config controller-api-port=9999
$ juju controller-config controller-api-port=9998
ERROR invalid or read-only controller config values cannot be updated: [controller-api-port]
```

## Documentation changes

@tmihoc The controller-api-port is becoming immutable. It was always the intention to do this in 3.0, but it never made it. So we're now doing it in 4.0.

I think we'll need to change the following page to something like:

```
controller-api-port:
  type: int
  description: |-
    An optional port that may be set for controllers on bootstrap, which
    may have a very heavy load. If this port is set, this port is used by
    the controllers to talk to each other - used for the local API connection
    as well as the pubsub forwarders. If this value is set, the api-port isn't
    opened until the controllers have started properly.
```

### CODE REVIEW

**Review by manadart — APPROVED** [review]
I love this.

**Review by hmlanigan — CHANGES_REQUESTED** [review]
QA failure:

$ juju bootstrap localhost testme-port --config controller-api-port=9998
Creating Juju controller "testme-port" on localhost/localhost
Looking for packaged Juju agent version 4.0-beta1 for amd64
No packaged binary found, preparing local Juju agent binary
To configure your system to better support LXD containers, please see: https://documentation.ubuntu.com/lxd/en/latest/explanation/performance_tuning/
Launching controller instance(s) on localhost/localhost...
 - juju-54d979-0 (arch=amd64)
Installing Juju agent on bootstrap instance
Waiting for address
Attempting to connect to 10.74.147.4:22
Connected to 10.74.147.4
Running machine configuration script...
Bootstrap agent now started
Contacting Juju controller at 10.74.147.4 to verify accessibility...
ERROR unable to contact api server after 60 attempts: unable to connect to API: dial tcp 10.74.147.4:17070: connect: connection refused

**Review by hmlanigan — APPROVED** [review]
bootstrap is happy. lgtm

**Pull request merged**
