### PR TITLE
Make the facade names for payloads and resources consistent.

### PR DESCRIPTION
**Pull request by howbazaar**
Also adds tags to the api structs used by resources and payloads.

(Review request: http://reviews.vapour.ws/r/5186/)

### CODE REVIEW

**Comment by jameinel** [comment]
You didn't add them to https://github.com/juju/juju/blob/master/api/facadeversions.go
which should mean that the client ends up trying version 0 of the facades. I thought we had a test about the version in 'facadeversions' being the highest known registered version, but maybe that got dropped somewhere?

**Comment by jameinel** [comment]
oh, ffs, it looks like the component stuff is using a RegisterFacadeVersions call to mutate the in-memory structure at runtime, so that they can register whatever version they think they're using. So we do have a test in api/facadeversions_test.go but it uses the in-memory one. which breaks Adam Stokes from here: https://bugs.launchpad.net/juju-core/+bug/1597519

Maybe we just need to add an actual exposure of the current facade versions (something like 'juju list-facade-versions' ?)
That could even tell you what versions the client wants to use, and what versions the server is exporting?

**Comment by battlemidget** [comment]
@jameinel Yea I just need a way to grab a list of facades available and their versions to autogenerate my python api library. Currently I just copy and paste the list of facades from that file and build the queries around that

**Comment by howbazaar** [comment]
$$__JFDI__$$ yet more consistency changes.

**Pull request merged**
