### PR TITLE
[JUJU-1876] do not present %%s or %s to lxd via cloudinit

### PR DESCRIPTION
**Pull request by hmlanigan**
Avoid lxd/cloud-init interaction bug [user-data gets broken replacing %s with %!s(MISSING)](https://github.com/lxc/lxd/issues/10231), by changing how juju creates its cloud-init for deploying a machine. A back port of work done in develop with another commit to complete the change for other areas as well.

## QA steps

Steps in bug report. Other juju bootstrap and deploy.

```sh
$ juju bootstrap aws testing
$ juju model-config lxd-snap-channel=4.0/stable
$ juju add-machine --series focal
$ juju add-machine --series focal lxd:0

# verify that 0/lxd/0 succeeds in deployment.
```

## Bug reference

https://bugs.launchpad.net/juju/+bug/1990594

### CODE REVIEW

**Comment by hmlanigan** [comment]
@hpidcock there's a bug if you do the qa steps bootstrapping lxd that I need to squash.

**Review by hpidcock — APPROVED** [review]
Looks good, just had an issue following the QA steps on AWS, the lxd container can't connect to the controller to download the tools. But if I run the same curl command on the machine it pulls fine. Not sure if we've broken lxd networking configuration?

**Comment by hmlanigan** [comment]
Turns out from jammy, when using the lxd provider, I cannot `juju add-machine lxd` and have the container set out of pending, independent of this change.

**Comment by hmlanigan** [comment]
I'm having containers not being able to download tools from the controller starting today also. Not sure why, but reproduced in 2.9.34 also.

**Pull request merged**
