### PR TITLE
Fixes lp#1628148: help help-tool.

### PR DESCRIPTION
**Pull request by anastasiamac**
## Description of change

Adding more context to help for help-tool.

## Bug reference

https://bugs.launchpad.net/juju/+bug/1628148

### CODE REVIEW

**Comment by anastasiamac** [comment]
Personal preference, and avoids stuttering, is 'juju help hook-tools' :)
However, this is a bigger change and could affect users currently running this command... We could alias it :D What do you think?

**Comment by jameinel** [comment]
In my ideal scenario "juju help hook-tools" would actually give you the help documentation about all the hook tools (their names, when you'd want to use them, etc.)
Regardless this is still clearly better than what we had.

**Comment by evilnick** [comment]
Thanks for taking the time to address this - it makes things easier all-round!

I am also +1 on juju help hook-tools, but I know that involves more substantial work

**Comment by jameinel** [comment]
I can understand juju help-tool unit-get
which is meant to be the help for the tool unit-get. I'm not sure it's obvious for users.
But I definitely think we want an alias to 'help-tools' as an obvious misspelling and maybe 'juju help tools' as a topic?

It shouldn't be too hard to add aliases. I'm not sure how hard it would be to add a topic so 'juju help hook-tools' points you to  what is currently 'juju help-tool'. Either just the direct output or just a reference.

**Comment by anastasiamac** [comment]
I am working through the unit test at the moment.
However, since there is so much movement on this, I am committing the command code.
I have modified command to now be known as 'hook-tool' with aliases as 'hook-tools' and 'help-tool' (this one for current users that rely on it).

The output from 'juju help hook-tools' now contains the list of all hook tools and looks like this: http://pastebin.ubuntu.com/25864889/

The singular version is provided to make sens of an individual help hook tool enquiry 'juju hook-tool unit-get'...

However, this change means that all variations of 'juju help hook-tools', 'juju help hook-tool', 'juju hook-tools unit-get', etc... are valid...

**Comment by anastasiamac** [comment]
!!build!!
...Connection to ec2-52-90-197-237.compute-1.amazonaws.com closed by remote host.

**Comment by anastasiamac** [comment]
!!build!!

**Comment by anastasiamac** [comment]
$$merge$$

**Pull request merged**
