### PR TITLE
Introduce remove-{volume,filesystem,storage} commands

### PR DESCRIPTION
**Pull request by axw**
Introduce new commands for removing volumes,
filesystems, and storage instances from the model.
These will be used to remove persistent storage
when a unit or application is removed from the model.

### CODE REVIEW

**Comment by anastasiamac** [comment]
Please keep in mind to notify QA and doc teams whenever CLI changes, including additions, are done.

**Comment by axw** [comment]
> Please keep in mind to notify QA and doc teams whenever CLI changes, including additions, are done.

Will do. This is a feature branch for now.

**Comment by jameinel** [comment]
Given the other discussions, is this PR now abandoned/folded into another one?

**Comment by axw** [comment]
Yes, I've got a new branch in the works.

**Pull request closed without merging**
