### PR TITLE
fix(machine): clean up controller units when removing controller machines

### PR DESCRIPTION
**Pull request by nvinuesa**
This patch fixes an issue that appears when trying to remove a controller machine from an HA cluster.

The fix is basically to reintroduce the cleanup that was used before https://github.com/juju/juju/pull/17653.

## Checklist

- [X] Code style: imports ordered, good names, simple structure, etc
- [X] Comments saying why design decisions were made
- [X] Go unit tests, with comments saying what you're testing
- [ ] ~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- [ ] ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

Set up a HA cluster, remove two controller machines and then the controller should still be usable:
```
juju bootstrap lxc c
juju enable-ha
# Wait until HA replica set converges.

# This will fail:
juju  remove-machine -m controller 2
WARNING This command will perform the following actions:
will remove machine 2
- will remove unit controller/2

This will require `--force`

Continue [y/N]? y
ERROR removing machine failed: machine 2 has unit "controller/2" assigned

# Remove with --force works.
juju remove-machine -m controller 2 --force
# Wait until HA replica set converges.
juju remove-machine -m controller 1 --force
# Wait until HA replica set converges.
juju add-model m
juju deploy ubuntu
```
(The last two steps should work, this means the controller is still usable).

Also, the enable_ha CI tests should pass:
```
cd tests;  ./main.sh controller test_enable_ha
```

## Links

**Launchpad bug:** https://bugs.launchpad.net/juju/+bug/2073409

**Jira card:** JUJU-6388

### CODE REVIEW

**Review by SimonRichardson — COMMENTED** [review]
Can you add the error cases if you don't use force to remove the machine.

**Comment by nvinuesa** [comment]
> Can you add the error cases if you don't use force to remove the machine.

@SimonRichardson done, added to QA.

**Review by manadart — APPROVED** [review]
Looks perfect from here.
- Normal machine removal behaviour preserved.
- Can remove secondaries and get a successful back-stop for HA-1.
- Can go back into HA and remove the primary, with a new one elected.

I'd wrinkle my nose _a little_ at a new clean-up job type, but we're ditching this anyway.

**Comment by nvinuesa** [comment]
> I'd wrinkle my nose a little at a new clean-up job type, but we're ditching this anyway.

I definitely agree, but I copied the exact same one I had removed from my previous PR so at least we know where it came from. This will all go away soon(-ish) hopefully :)

**Pull request merged**
