### PR TITLE
Increment juju to 1.24.7

### PR DESCRIPTION
**Pull request by sinzui**
(Review request: http://reviews.vapour.ws/r/2681/)

### CODE REVIEW

**Comment by sinzui** [comment]
$$merge$$

**Comment by sinzui** [comment]
$$merge$$

**Comment by bz2** [comment]
$$merge$$

**Comment by howbazaar** [comment]
status_test.go:3133

Version available in expected output should be mocked out, or at least for this branch, updated.

**Comment by sinzui** [comment]
$$merge$$

**Pull request merged**
