### PR TITLE
Backport deploy by revision

### PR DESCRIPTION
**Pull request by hmlanigan**
Adding the deploy by revision for charmhub changes to 2.9

Backporting the following PRs  
* #13165 
* #13183 
  * 39e13cba90785e93feb06dfa47e5dd6d7e19386b ended up as an empty change and was aborted, go fmt changes made inline.
* #13200 
  * 3736142840f90259a0347ecef155a9ff77a5f3c0 ended up as an empty change and aborted.
* #13206
  * b2cc0d9ee2b8a24aff4ee2ff49e9651b21dd2d9d not included. Not all facade changes made for compatibility in 2.9, see #13443, these lines still needed to run tests.
* #13226 
* #13295
* #13301 
* #13326 
  * 9602197faf34c47738abed4da694dbe9a68aa9f7 was not backported, charm/v9 vs charm/v8
  * 04d8a0487a6ddcfe2b69248ea7efc23714b3e644 contains the go.mod changes for the updated charm/v8 were made in a new commit

New commits, related to fixing tests due to differences in 2.9 and develop:
* c8e950a310db8f493eb6021b5874034c38514362
* df68fa8733e682003d902062afd271d2788a9c02
* 1aa125e196fcc7c78570c48515e3d6e4d5ef9591
* b683e0eab9d3125bd9126ef22fe429b5cb3c5866
* 7ed71041573aea61f3d03c8086ebb53651b18204
* bd95dc6675278d643df95c3735f6034beabcb40a
* 294bc9bc6988242682dd641654c979bb5b1f3e2d 
## QA steps

Any other deploy testing as well - focused on revisions and resource revisions.

QA steps from #13206 and #13226, related to resource revisions

```sh
(cd tests ; ./main.sh deploy)
(cd tests ; ./main.sh resources)
```

### CODE REVIEW

**Review by achilleasa — APPROVED** [review]
Changes LGTM. Running QA steps ATM...

**Comment by achilleasa** [comment]
I am getting a weird lxd-related error when running the tests (test-deploy-lxd-container: `Missing parent 'lxdbr0' for nic 'eth0'`). Probably not related to these changes but we should figure out why it fails before we land this.

**Comment by hmlanigan** [comment]
@achilleasa odd, I never saw that one.

**Comment by manadart** [comment]
I ran QA for this. Looks good.
```
====> Bootstrapping juju (2.9.18:lxd)
====> Bootstrapped juju (92s)
===> [ ✔ ] Success: deploy charm (46s)
===> [ ✔ ] Success: deploy specific series (15s)
===> [ ✔ ] Success: deploy lxd to container (179s)
===> [ ✔ ] Success: deploy lxd profile charm container (173s)
===> [ ✔ ] Success: deploy lxd to machine (54s)
===> [ ✔ ] Success: deploy lxd profile charm (40s)
===> [ ✔ ] Success: deploy local lxd profile charm (239s)
===> [ ✔ ] Success: deploy bundle (159s)
===> [ ✔ ] Success: deploy bundle overlay (109s)
===> [ ✔ ] Success: deploy exported bundle (29s)
===> [ ✔ ] Success: deploy trusted bundle (53s)
===> [ ✔ ] Success: deploy charmhub bundle (169s)
===> [ ✔ ] Success: deploy lxd profile bundle openstack (1011s)
===> [ ✔ ] Success: deploy lxd profile bundle (564s)
===> [ ✔ ] Success: deploy cmr bundle (247s)
===> [ ✔ ] Success: cmr bundles export overlay (29s)
==> TEST SKIPPED: deploy_centos - tests for AWS only
===> [ ✔ ] Success: deploy revision (16s)
===> [ ✔ ] Success: deploy revision resource (16s)
===> [ ✔ ] Success: deploy revision fail (5s)
===> [ ✔ ] Success: deploy revision upgrade (34s)
```

**Pull request merged**
