### PR TITLE
test: perf worker

### PR DESCRIPTION
**Pull request by SimonRichardson**
How hard can we actually hit dqlite from inside of juju. Let's find out!

---- 

The premise is simple, can we afford to run multiple read transactions with wild abandon?

Before this change a spike was done to test the premise, but from the outside of Juju, going via the CLI and the apiserver. The problem we hit pretty quickly was that we required a fmutex to access the local yaml files found in `~/.local/share/juju`. Hacking that out of the way allowed us to reach 800/tps (transactions per second). After doing the spike, the thought was to remove the overhead from the CLI, WebSockets, and API server/facades to get a true figure.

This proposal introduces a model worker. The model worker can acquire the service factory for that given model and then run several read-only queries. This then removes the potential of accidental writes into the database whilst testing this setup.

-----

The perf worker creates a new step worker every 30 seconds. The step worker will then run a series (currently 20 iterations), every second. This will then build up over time, currently no upper limit (this will likely change).

The step function will then call a series of calls against the controller and model database. 

To add more work and transactions, add more models.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing

## QA steps

Download the bundle and overlay https://gist.github.com/SimonRichardson/0283807cdc026c4ecfe557891958f5b6
Alternatively, deploy the COS stack to then monitor the controller.

```
$ juju bootstrap lxd test --build-agent --bootstrap-base=ubuntu@20.04
$ juju add-user prometheus
$ juju grant prometheus read controller
$ juju change-user-password prometheus
$ juju switch controller
$ juju deploy ./bundle.yaml --overlay ./overlay.yaml --map-machines=existing
 ```

## Links

**Jira card:** https://warthogs.atlassian.net/browse/JUJU-6625

### CODE REVIEW

**Comment by jnsgruk** [comment]
Interested in the results of this!

**Comment by SimonRichardson** [comment]
Test scenario:

  1. Deploy the controller (see QA steps)
  2. Add 20 models: `for i in {1..20}; do juju add-model "model-$i" && sleep 1; done`

Initial results:

screencapture-10-50-139-245-3000-d-cdwsdu6pjxxq8b-juju2-controllers-2024-09-03-14_50_12

Observations:

 1. We hit over 1.5k of read transactions.
 2. The number of retries is low compared to the initial spike (1 in 3 transactions succeeded), which alludes to the fact that there are not enough writes in this current performance scenario (which is fine for this exercise).

**Comment by SimonRichardson** [comment]
Test scenario:

 1. Remove the semaphore completely.
 2. Deploy the controller (see QA steps)
 3. Add 20 models: for i in {1..20}; do juju add-model "model-$i" && sleep 1; done

Initial results:

screencapture-10-50-139-62-3000-d-adww29ndq27eob-juju2-controllers-2024-09-04-15_34_23

Observations:

 1. We hit over 800 read transactions per second
 2. The load on the machine was higher than the first tests.
 3. The ramp-up time between is a lot faster, which is obvious because we don't have a semaphore throttling the transactions.

Thoughts:

 1. Run another test with more models, to see if we can push the throughput of transactions higher. We might be seeing, going slower to move faster...

**Comment by SimonRichardson** [comment]
I ran another test without the semaphore and wasn't able to push past 800 transactions per second. I'll explore if the semaphore should be tuned higher, or lower.

To get high numbers using sqlite, it is advised to only have a dedicated read connection. I'm unsure if that would translate to dqlite, but we could potentially spike a prototype to see if it's feasible.

**Comment by SimonRichardson** [comment]
See 3.6 results https://github.com/juju/juju/pull/18131#issuecomment-2371479671
 
Takeaway: It looks like mongo can hit a higher number of read queries, even if we take into account queries vs queries inside of a transaction. The latter is unlikely to have 6 queries per transaction (more likely 2-3 queries per transaction) to get to 8000+ queries per second.

I've got another round of testing to perform, which might give us the apples vs apples that we're looking for, but we might have to revisit the semaphore and retry solution to try and optimize it in the future.

**Comment by jameinel** [comment]
I worked with Simon to add actual metrics around "how many steps of the perf-worker" can run. And then we took the 3.6 version and compared it with the 4.0 version. We still need to dig in to really understand the details, but the initial results are a bit disheartening.
image

The first image is running both perf-worker-3.6 and perf-worker simultaneously, and setting them up to run 50 models each (50 models *10* step workers, is 500+ steps/second trying to run.)

perf-worker-3.6 got up to 10k / second, while perf-worker was pretty consistent around 1k/second.
The second image is first running perf-worker-3.6 and having it scale to 100 models, and then perf-worker and having it scale to 100 models. This time perf-worker-3.6 got to around 20k/s, while perf-worker again stayed close to 1k/s. At the same time, CPU load capped out for perf-worker around 300%. So some of this is just our internal semaphore throttling.

As another data point:
```
$ time juju models -c perf-36| wc -l
53

real    0m0.098s
user    0m0.048s
sys     0m0.068s
$ time juju models -c perf-40 | wc -l
54

real    0m14.606s
user    0m0.097s
sys     0m0.023s
```

So `juju models` slowed down quite a bit as the number of models increased. In the separate testing:
```
$ time juju models -c perf-40 | wc -l
103

real    1m9.098s
user    0m0.079s
sys     0m0.033s
```

This might just be poorly optimized queries, though, and not just about load. (it is easy for `juju models` to be at least linear with a bad factor, and trivially become quadratic if we haven't optimized it.)

**Comment by jameinel** [comment]
One very positive note. All of this was `juju bootstrap lxd; juju consume mk8s:prometheus; juju integrate -m controller controller prometheus` and those cross model relations worked across a 3.5 microk8s controller, a 3.6 test and a 4.0 test controller. There were some other issues to address (being able to label your data feeds), but the easy of getting grafana up, and getting it scraping your controllers was really good.

**Comment by SimonRichardson** [comment]
Screenshot from 2024-09-27 12-20-04

I ran the same setup, microk8s + cos-lite and 3.6 and 4.0 relating to that prometheus. Mongo stayed at 4000 req/s and dqlite was the low 300 req/s. I added more models and it just highlighted that mongo can perform more queries, whilst dqlite was hovering around the same amount. It's clear that the rate-limiting is just hurting us.

It's clear we can't run without the semaphore (performance dropped), we need to workout a better strategy for this. I'm unsure what.

**Comment by SimonRichardson** [comment]
I've experimented with creating a poor man's hash ring in a branch. 

Long story short; In the dbaccessor worker, I create 3 dqlite apps instead of one. Each dqlite app is created with its own transaction runner (each transaction runner has its own semaphore) and then depending on the hash of the namespace it's sent to the appropriate dqlite app. The controller namespace (global) is special as it is always at app 0. Each dqlite app is currently bound to an abstract domain socket (`@node-%d`) to make things a lot simpler.

The distribution of the namespace isn't perfect and it's a tendency to favor one index over the other (see below). We could potentially have a round-robin instead, which would give a fairer distribution. There is no consideration at all over scaling down the dqlite apps if a model goes away in the code, although I __do__ have ideas on how to do this.

```
namespace: "a04af513-ea0e-418a-8953-554e19b90a30", hash: 2146607202, index: 0
namespace: "f8d0aafe-bd6a-497a-8f98-714c93d060d7", hash: 2735222685, index: 0
namespace: "d4459721-aea3-42da-85f1-57e7e6b7083f", hash: 1944514803, index: 0
namespace: "77b9f43d-8a35-4add-8f4e-b6e4e422e6f1", hash: 3112230964, index: 1
namespace: "703cf2df-3c4d-414d-8533-d4663cffc7cb", hash: 931743233, index: 2
namespace: "b1625b7f-d93e-45f4-8df5-0f0f396dc273", hash: 1924279564, index: 1
namespace: "d4e51406-03ea-49f2-84b0-68cb0c6969ce", hash: 1975105366, index: 1
namespace: "407e4d07-3dc0-4d1f-8bb5-e523e93b1ca1", hash: 2777876998, index: 1
namespace: "995ffc68-4a01-4ab3-8ff4-04df003d300e", hash: 314819688, index: 0
namespace: "ccb8b4ca-fe24-4e8c-8923-4cb3786f25b5", hash: 3402146965, index: 1
namespace: "b2b789f7-f592-46b8-834d-38c34a1687e4", hash: 3388300066, index: 1
namespace: "9bf174b9-ce87-4516-8c06-ce2d02627f81", hash: 3670112825, index: 2
namespace: "87e51109-0c68-4592-8a74-795f231e77b8", hash: 2295687420, index: 0
namespace: "53fb30b7-5f32-4e06-8914-ceeb76d599ed", hash: 327607678, index: 1
namespace: "1393e58a-b872-4e90-8c02-606db9606468", hash: 3960529581, index: 0
namespace: "b74a01d6-f0e6-4252-8932-17594308ae0a", hash: 336590602, index: 1
namespace: "c0fc501e-062a-430c-8a00-91512d86b4a9", hash: 2142247282, index: 1
namespace: "71815fa4-1495-417b-82af-22953bb2c19e", hash: 1480114457, index: 2
namespace: "611422c6-2112-40ee-82d2-c6de01b58cc1", hash: 1377263489, index: 2
namespace: "2f93adfa-f616-459c-8051-ef88b72ad3e7", hash: 3778284257, index: 2
namespace: "ea952dbe-a72e-4535-8a38-78bb877ae05f", hash: 2429903874, index: 0
namespace: "3112b3ae-b580-4ecb-8918-7558373914e7", hash: 1486829634, index: 0
```

The great thing about this change was that all of the code changes were located in two places; the dbaccessor worker and the bootstrap dqlite code.

----

### Results:

Note: this wasn't testing 3.6 at the same time, although in the prior runs, the tests weren't taxing the system, so keep that in mind.

Screenshot from 2024-09-27 14-23-54

The number of dqlite applications was 3 and was hash indexed between the 3, with bias on index 1. The number of iterations rose above 1000, peaking at 1337.

#### Observations

We're not scaling linearly as that should put us in the 900 ballpark (300 req/s * 3 dqlite apps). I wonder if we're just not on the controller application, we scale much better. Reads vs writes is coming into play.

**Comment by SimonRichardson** [comment]
Further to the prior comment, I created 5 dqlite applications and we did not scale linearly. We top out at 1736 req/s. I then decided to a more models and the writes just tanked all the reads, which you can the iteration count just tanks.

Screenshot from 2024-09-27 15-33-43

**Comment by SimonRichardson** [comment]
Doubling the semaphore reduces the number of req/s to 859. This is with 3 dqlite apps running with 48 rate limit (weighted semaphore).

Screenshot from 2024-09-27 16-21-30

**Comment by SimonRichardson** [comment]
Cutting the semaphore to half doesn't reveal any difference between the req/s. The number ended up being 1326 req/s.

Screenshot from 2024-09-27 16-43-34

**Comment by SimonRichardson** [comment]
Setting the semaphore to 2, reveals that we can burst up to 2489 req/s.

Screenshot from 2024-09-27 17-18-05

### Observations

We see that we're connecting to dqlite a lot, so I believe setting the number of open connections to 1 (or a low number) should force us to reuse the connection and not spend time connecting to dqlite all the time.

**Comment by SimonRichardson** [comment]
Setting `SetMaxOpenConns` and `SetMaxIdleConns` to 2, to ensure pool reuse didn't do anything 2355 req/s.

Screenshot from 2024-09-27 17-39-03

Next attempt is to remove the semaphore and just cause the pool reuse.

**Comment by SimonRichardson** [comment]
Removing the semaphore and still with setting `SetMaxOpenConns` and `SetMaxIdleConns` to 2, peaks to 3353 req/s.

Screenshot from 2024-09-27 17-59-39

**Comment by jameinel** [comment]
I also tried removing the semaphore, going to db.SetMaxConnections(2), and ended up with a system that only hits 200% cpu, but is able to hit 3.6k simultaneous requests. 

image

**Comment by jameinel** [comment]
As a point, Simon asked "so how much can we throw at 3.6". So I scaled up to 200 models. Which at most runs 40k steps / second. I then took it a step further and went to 300 models, which should cap out at 60k steps/second.
At this point, I'm running at 80% cpu max, and not being thermal throttled, but only hitting a peak of 39k steps/second.
```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   2377 1000000   20   0 3165296   1.7g 102848 S  1162   5.3 275:35.97 /var/lib/juju/tools/machine-0/jujud machine --data-dir /var/lib/juju+
   2326 1000000   20   0 4971728 906080  53724 S 726.9   2.8 177:14.17 /snap/juju-db/178/bin/mongod --config /var/snap/juju-db/common/juju-+
```

So about 18 CPU cores fully engaged. (I have 12 E cores, 8 P cores, for a total of 28 threads.)

image

**Comment by SimonRichardson** [comment]
I did an experiment to see what happens if we move the controller to its own database (index 0), and everything is just a lot smoother—although nowhere as quick as Mongo. 

100 models. The system just isn't taxed (300% - I've got more cores than that) We're hitting the max throughput of dqlite. 

Screenshot from 2024-09-28 16-23-52

**Comment by SimonRichardson** [comment]
Nothing changed once I added more nodes, there is clearly a lock somewhere that is preventing the throughput to move forward. Either that's a flock, or lock somewhere. It's clearly processor bound, because adding more models didn't change anything, and yet @jameinel  single-threaded CPU performance is better than my CPU, which then gets a higher score.

The next step is to use parca, to analyse where the bottleneck is. That's a Monday job.

**Comment by SimonRichardson** [comment]
So parca didn't tell us anything we didn't already know from the pprof. What has helped is the opentelemetry, looking at the spans between the function requests has helped identify a problem. We're seeing a large time (>10ms), from executing the retryable transaction and calling `BEGIN`. A span at the top of the closure runs the transaction and the opentelemetry inside dqlite. Between those two spans is the `database/sql` driver, which includes the database pooling and the dqlite driver. The driver in dqlite is quite slim, so I'm speculating this is purely a pooling issue.

The semaphore was completely removed from the retryable transaction runner in favour of setting the max connection pool in the `database/sql` driver.

I've got an experiment to remove the controller queries from the run steps and use purely model queries. If it turns out that the number of steps suddenly rises, it would seem that it is indeed a problem with congestion with the controller database.

**Comment by SimonRichardson** [comment]
For the latest run;

 - I turned off open telemetry (it was sampling every trace)
 - I turned logging to INFO
 - Each database connection has `SetMaxIdleConns` and `SetMaxOpenConns` set to 10.
 - There are no database requests to the controller model in the perf-worker
 - Models are hashed across 10 dqlite apps. The controller model has its own dqlite app (11 in total).

The results speak for themselves: 9928 req/s

Screenshot from 2024-09-30 20-06-58

**Comment by SimonRichardson** [comment]
Last test:

- I turned off open telemetry (it was sampling every trace)
- I turned logging to INFO
- Each database connection has SetMaxIdleConns and SetMaxOpenConns set to 24 (to match the number of CPU cores).
- There are no database requests to the controller model in the perf-worker
- Models are hashed across 24  (to match the number of CPU cores) dqlite apps. The controller model has its own dqlite app (25 in total).
- Added 50 models, then 100...

The result: 19998 req/s

Screenshot from 2024-09-30 20-39-11

### Observations

 - Contention over the controller model just ends up being an accidental locking mechanism.
 - We can finally use all the CPU cores!!!
 - Sharding is the way to go!

**Comment by jameinel** [comment]
Simon realized that we were actually partially single-threaded because a lot of the actual steps were Controller steps, rather than model steps.
Restricting the steps to just some of the model steps actually allows us to scale if we enable sharding of model databases.
image

So the concrete values aren't comparable, because the actual steps are very different. But I scaled from 20,50,100,200,400 models, and we ended up at 65k ops/second. Which is equivalent to something like 350 models. (still 20 steps per model, but pulled from just 2 different possible steps that only touch the local model.)

It does clearly highlight that we need to watch out for incidental single-threading by depending over-much on the Controller model. And there is more to break apart this patch into actually usable things.
But it does mean that there isn't a fundamental reason dqlite can't scale with some sharding around it.
We might actually try to plan around not doing sharding at the Juju level, and see if we can get dqlite to do multiple raft queues instead.

The more important thing was that we actually scaled to 2200% cpu, which means that we aren't single threaded anymore.

**Comment by hpidcock** [comment]
> I've got an experiment to remove the controller queries from the run steps and use purely model queries. If it turns out that the number of steps suddenly rises, it would seem that it is indeed a problem with congestion with the controller database.

Oh nice. I wonder what we can do from a design/review/testing perspective to help limit the dependency on the controller db for model operations.

**Comment by sinanawad** [comment]
Noice! Impressive progress Simon.
Although it's still quite early in the game, when do you think you can start drafting a "whitepaper" document with validated recommendations from us on the performance/scaling specs for juju 4.0 and best practices (controllers vs. models ratio, optimizations, etc.)?

**Comment by SimonRichardson** [comment]
@sinanawad I'll get some of the quick wins from this draft PR into Juju, then I need to discuss with @manadart about issues that we have. To answer your question - soon.

**Comment by SimonRichardson** [comment]
I will mention that adding tail-sampling for open telemetry did reduce the CPU load. This will allow us to customize in the future how we would want to drop spans. https://github.com/juju/juju/pull/18134

**Comment by SimonRichardson** [comment]
I'm going to close this for now, we can always revisit it if and when required.

Some closing notes on additional reading I've done post-tests. All the notes I've been reading are about sqlite, and not about dqlite, so they might not apply to dqlite directly and would require further testing.

-----

### Sqlite settings

It may be possible to tweak the checkpointing to improve read operations at the cost of writes (again this is sqlite, not dqlite).

> Writers merely append new content to the end of the WAL file. Because writers do nothing that would interfere with the actions of readers, writers and readers can run at the same time. However, since there is only one WAL file, there can only be one writer at a time.

> A checkpoint can run concurrently with readers, however the checkpoint must stop when it reaches a page in the WAL that is past the end mark of any current reader. 

> Thus a long-running read transaction can prevent a checkpointer from making progress

 - https://sqlite.org/wal.html#concurrency

> Write transactions are very fast since they only involve writing the content once (...) and because the writes are all sequential.

> ...read performance deteriorates as the WAL file grows in size since each reader must check the WAL file for the content and the time needed to check the WAL file is proportional to the size of the WAL file.

> Hence, to maintain good read performance it is important to keep the WAL file size down by running checkpoints at regular intervals.

> The default strategy is to allow successive write transactions to grow the WAL until the WAL becomes about 1000 pages in size, then to run a checkpoint operation for each subsequent COMMIT until the WAL is reset to be smaller than 1000 pages. By default, the checkpoint will be run automatically by the same thread that does the COMMIT that pushes the WAL over its size limit. This has the effect of causing most COMMIT operations to be very fast but an occasional COMMIT (those that trigger a checkpoint) to be much slower.

> To maximize the read performance, one wants to keep the WAL as small as possible and hence run checkpoints frequently, perhaps as often as every COMMIT. 

 - https://sqlite.org/wal.html#performance_considerations

So in theory it might be possible to set the [`wal_autocheckpoint=1`](https://sqlite.org/pragma.html#pragma_wal_autocheckpoint) or some other low value (testing required) to get better read performance. The inverse is also true, setting it higher to improve write performance.

> To maximize write performance, one wants to amortize the cost of each checkpoint over as many writes as possible, meaning that one wants to run checkpoints infrequently and let the WAL grow as large as possible before each checkpoint.

----

This was also an interesting discussion about investigating [dqlite disk backend](https://github.com/canonical/dqlite/issues/368). 

I'm very much cherry-picking the conversation, so take it with a grain of salt, but it did lead me to re-read the WAL notes.

>  Not only checkpointing would block the main loop, but also any operation that involves reading a database page (which would need to be fetched from disk). So even simple SELECT statements could end up blocking the event loop. Since disk access performance can vary a lot depending on the system state at a given moment, the worst case scenario is that when a very long blocking disk I/O syscall returns and the even loop is unblocked, enough time might have elapsed that raft timers kick in, for example deposing the leader or converting a remote follower to a candidate (because it didn't receive anything) from the leader. Not only that, but during that time nothing else could be done (e.g. serving another SELECT) which would probably reduce the overall performance/throughput of the system.

 - https://github.com/canonical/dqlite/issues/368#issuecomment-1135809608

----

We might also want to see if tuning the snapshot parameters in dqlite changes anything. k8s-dqlite exposes them as a tuning configuration. There is an explanation [here](https://github.com/canonical/k8s-dqlite/pull/32#issuecomment-1375257825).

----

Things to think about. I can always do another round of tests in the future.

**Pull request closed without merging**
