### PR TITLE
chore: finer grained controller over docker registry and user in make

### PR DESCRIPTION
**Pull request by wallyworld**
When creating and pushing oci images for the juju agent, we could specify via DOCKER_USERNAME the full registry and user path to use.

This PR allows the registry and login user to be specified separately.
The default if unset remains the same.

This allows different repos to be used by changing DOCKER_REGISTRY but with the same login user name.

Simple to test, just run `make operator-image` and then `podman image list`.

To check the new settings:
```
export DOCKER_REGISTRY=ghcr.io
export DOCKER_USER=someuser
make push-release-operator-image
make seed-repository
```

### CODE REVIEW

**Comment by tlm** [comment]
Thanks @wallyworld but I am not satisfied the why has been addressed with this PR to justify. If anything it highlights that our language is possibly wrong.

When we talk about a docker_username we really are referring  to OCI_URL. It is only docker that puts any stock in the username component and meaning into that positional parameter.

I am not seeing the benefit by introducing this without a solid problem that this is solving.

**Comment by wallyworld** [comment]
> Thanks @wallyworld but I am not satisfied the why has been addressed with this PR to justify. If anything it highlights that our language is possibly wrong.
> 
> When we talk about a docker_username we really are referring to OCI_URL. It is only docker that puts any stock in the username component and meaning into that positional parameter.
> 
> I am not seeing the benefit by introducing this without a solid problem that this is solving.

As explained in the description, it allows the registry (eg ghcr.io or docker.io) and the logged in user name for that registry (eg mary) to be specified separately. This more easily enables testing with different registries. Yes, the DOCKER_USERNAME is misnamed but our entire build/ci pipeline depends on that and so that can't easily be changed now.

**Comment by tlm** [comment]
This is the change that is being proposed:

```
DOCKER_REGISTRY            ?= docker.io
DOCKER_USER                ?= jujusolutions
DOCKER_USERNAME            ?= ${DOCKER_REGISTRY}/${DOCKER_USER}
```

If I wanted to push to docker it would be:
`DOCKER_USER=tlm make push`

If I wanted to push to AWS in the same account in the same region on the same registry it would be:
`DOCKER_REGISTRY=123.dkr.ecr.us-east1.amazonaws.com DOCKER_USER=foo make push`

If I wanted to push to gcr it would be:
`DOCKER_REGISTRY=gcr.io/my-project` DOCKER_USER=foo make push`

If I wanted to push to GitHub it would be:
`DOCKER_REGISTRY=ghcr.io DOCKER_USER=foo make push`

This PR has put forward the proposition that we are gaining more fine grain control over the registry URL but that doesn't seem like the case to me. It seems like we are making more knobs that are harder to grok. While `DOCKER_USERNAME` is poorly name it is one value that can be set to anything and the make file will work.

Now with this change we are making the determination of what an OCI URL looks like when the spec makes no assumptions about this and each provider could and does do things wildly different as per above.

What is rocks going to look like?

The simplest and best change here if we wanted to drive better change in my opinion would the following:

```
DOCKER_USERNAME ?= docker.io/jujusolutions
OCI_URL ?= ${DOCKER_USERNAME}
```

We can then change the Makefile to use OCI_URL and maintain compatibility with CI. Easy additions to make swapping the OCI namespace around can be done through shell vars and expansion on invocation of make and don't have to be prescriptive in the Makefile.

The problem proposed in this PR still doesn't provide the pain point we are addressing. How often is this done and can you provide an example workflow that we are trying to fix here?

**Comment by wallyworld** [comment]
> This is the change that is being proposed:
> 
> ```
> DOCKER_REGISTRY            ?= docker.io
> DOCKER_USER                ?= jujusolutions
> DOCKER_USERNAME            ?= ${DOCKER_REGISTRY}/${DOCKER_USER}
> ```
> 
> If I wanted to push to docker it would be: `DOCKER_USER=tlm make push`
> 
> If I wanted to push to AWS in the same account in the same region on the same registry it would be: `DOCKER_REGISTRY=123.dkr.ecr.us-east1.amazonaws.com DOCKER_USER=foo make push`
> 
> If I wanted to push to gcr it would be: `DOCKER_REGISTRY=gcr.io/my-project` DOCKER_USER=foo make push`
> 
> If I wanted to push to GitHub it would be: `DOCKER_REGISTRY=ghcr.io DOCKER_USER=foo make push`
> 
> This PR has put forward the proposition that we are gaining more fine grain control over the registry URL but that doesn't seem like the case to me. It seems like we are making more knobs that are harder to grok. While `DOCKER_USERNAME` is poorly name it is one value that can be set to anything and the make file will work.
> 
> Now with this change we are making the determination of what an OCI URL looks like when the spec makes no assumptions about this and each provider could and does do things wildly different as per above.
> 
> What is rocks going to look like?
> 
> The simplest and best change here if we wanted to drive better change in my opinion would the following:
> 
> ```
> DOCKER_USERNAME ?= docker.io/jujusolutions
> OCI_URL ?= ${DOCKER_USERNAME}
> ```
> 
> We can then change the Makefile to use OCI_URL and maintain compatibility with CI. Easy additions to make swapping the OCI namespace around can be done through shell vars and expansion on invocation of make and don't have to be prescriptive in the Makefile.
> 
> The problem proposed in this PR still doesn't provide the pain point we are addressing. How often is this done and can you provide an example workflow that we are trying to fix here?

The change does not break the existing DOCKER_USERNAME configuration. It's opt in. If your existing scripts set DOCKER_USERNAME to something other than the default `docker.io/jujusolutions` nothing changes. This is a backwards compatible change that's totally optional to use.

Note - the existing github workflow scripts already do half of what this is proposing.
DOCKER_REGISTRY=10.152.183.69
docker build $BUILD_TEMP -t ${DOCKER_REGISTRY}/test-repo/jujud-operator:${SOURCE_JUJU_VERSION}

This change is just parameterising the base path as well.

I want to be able to do things like switch between `docker.io` and `ghcr.io` with the same path prefix, which for most cases also corresponds to the repo username. Having the registry and user separate is more ergonomic if you choose to opt in to use it that way - remember, the default doesn't change.

So I can 
export DOCKER_USER=myuser
in .bashrc (which also does docker login $DOCKER_USER etc)
and then
DOCKER_REGISTRY=ghcr.io make seed-repository
DOCKER_REGISTRY=docker.io make seed-repository

instead of
DOCKER_USERNAME=ghcr.io/myuser make seed-repository
DOCKER_USERNAME=docker.io/myuser make seed-repository

**Pull request closed without merging**
