### PR TITLE
If the Juju version has a tag (eg alpha or beta), then by default use testing stream to find tools

### PR DESCRIPTION
**Pull request by wallyworld**
Fixes: https://bugs.launchpad.net/bugs/1481500

We want to ship Juju 1.25 with wily in main.
We also want to release beta versions of Juju leading up to the wily release.
People should be able to deploy these beta Juju releases out of the box. This means that there should be no extra configuration necessary to bootstrap. However, beta tools are not published to released streams, only to devel. So we want to change Juju's tools search so that if the version asked for is a beta release, it looks automatically in a non release stream. ie "devel"

Tested live with AWS - an environment could be bootstrapped using beta tools with no additional config changes.

(Review request: http://reviews.vapour.ws/r/2340/)

### CODE REVIEW

**Comment by marcoceppi** [comment]
+1 on the logic for this, as it always bites me when I'm testing new versions. Not a code review, just supporting the feature

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$Merge$$

**Pull request merged**
