### PR TITLE
Revert pull request #2169 axw

### PR DESCRIPTION
**Pull request by bz2**
Fixes lp:1450919 as update to charm.v5 in dependencies.tsv dropped several
revisions, apparently from a bad split of the v6-unstable branch.

This reverts commit 1b667dd4779f64f625da5d0099ef2d4a608745e4, reversing
changes made to 542711150c0e017462aec9e1041d891a70740628.

(Review request: http://reviews.vapour.ws/r/1569/)

### CODE REVIEW

**Comment by bz2** [comment]
fixes-1450919

Go ahead and merge whenever.

**Comment by axw** [comment]
How about we fix charm.v5 instead.

**Comment by wallyworld** [comment]
charm.v5 dep fixed so no need for this revert

**Comment by bz2** [comment]
Because this could have landed while I was asleep, and 1.24 would now be unblocked. Instead, it's waiting on a change that could just as easily have been made at the same time as the unrevert.

**Pull request closed without merging**
