### PR TITLE
Generate docs (man page) as python 3

### PR DESCRIPTION
**Pull request by SimonRichardson**
## Description of change

Generating man page for juju uses python 2 via a hash bang. Python 2 is
deprecated, we instead should be using python 3.

The problem will come with older releases (xenial, et al), as how do we
use the right python version.

## QA steps

Run them and view the output.

#### Python 2

```sh
lxc launch ubuntu:16.04 test
lxc file push -p scripts/generate-docs.py /root
lxc file push -p scripts/jujuman.py /root
lxc file push -p ~/go/bin/juju /root/bin

lxc exec -t test -- bash

sudo apt install python-minimal

export PATH=/root/bin:$PATH

./generate-docs.py man
```

#### Python 3

I'm already running focal, so it becomes (it assumes that juju is in your $PATH):

```sh
./scripts/generate-docs.py man
```

### CODE REVIEW

**Comment by mitechie** [comment]
Right, my concern is can we make the code work in both pythons so that the script still works for older series?

**Comment by mitechie** [comment]
Or we'll have to update the build environments for older series to include a python3, but then we need to test on those older versions of python3

**Comment by SimonRichardson** [comment]
https://trello.com/c/66fpQAXb/2400-generate-docs-for-man-pages

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
