### PR TITLE
[JUJU-1095] Remove support for antiquated LXD versions

### PR DESCRIPTION
**Pull request by manadart**
As of Juju 3.0 we will no longer support series Trusty, or versions of LXD without the network API (< 2.3)

This patch removes said support, which includes very old versions of LXD that used the `lxd-bridge` service and `dpkg-reconfigure`.

Streamlining this provider will ease future LXD enhancements.

## QA steps

- Bootstrap to local LXD and deploy some units.
- Bootstrap to non-LXD cloud and deploy some units to container-in-machine.

## Documentation changes

I don't think we document LXD support specifically, but this should be indicated in major version release notes.

## Bug reference

N/A

### CODE REVIEW

**Comment by manadart** [comment]
!!build!!

**Review by hmlanigan — COMMENTED** [review]
QA: When I started containers on lxd machines, none got past pending.  They have network connectivity, but never download juju binaries.  cloud-init-out.log ends after creating ssh keys. machine 0 is running lxd 5.1 on focal

no issues with starting a container on an aws machine.

**Comment by manadart** [comment]
Perhaps I'm misremembering, or things have changed with LXD. Container-in-machine doesn't even work on 2.8.

**Comment by hmlanigan** [comment]
@manadart we have some lxd profile tests which use containers on the lxd machines in CI, so it has worked. I remember some issues with base machine and container machine combinations that weren't happy together.

**Review by hmlanigan — APPROVED** [review]

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
