### PR TITLE
WIP: implement targeting existing machines for ensure-availability

### PR DESCRIPTION
**Pull request by natefinch**
This change allows you to target machines that already exist in the environment with ensure-availability. Thus you can do `juju ensure-availability --to 1,2` and convert machines 1 and 2 to be state servers.  This works exactly like the existing --to, where it uses as many of the machines specified as it needs, and if it needs more machines, it'll create new ones.  e.g. if you have just one state server and do `juju ensure-availability -n 5 --to 1,2` then it'll convert 1 and 2 into state servers and start two new machines to fill in the other 2 machines it needs.

(Review request: http://reviews.vapour.ws/r/1299/)

### CODE REVIEW

**Comment by natefinch** [comment]
$$merge$$

**Comment by wwitzel3** [comment]
$$merge$$

**Comment by sinzui** [comment]
This looks like intermittent failure $$merge$$

**Comment by natefinch** [comment]
$$merge$$

**Comment by natefinch** [comment]
$$merge$$

**Pull request merged**
