### PR TITLE
2.7 remove vestigial code

### PR DESCRIPTION
**Pull request by jameinel**
## Description of change

While we were auditing the txn-revno stuff, we found a bit of vestigial code, so just clean it up, and update some parentheses so humans have an easier time understanding the code.

## QA steps

Nothing functional should change.

## Documentation changes

None.

## Bug reference

None.

### CODE REVIEW

**Comment by jameinel** [comment]
Windows lost connection after 20 minutes of trying to copy the source code
```
17:18:11 Copying juju-source-1560258746.tar.xz to d:\payloads\1560259089
17:18:11 + scp -l 40960 juju-source-1560258746.tar.xz 'cijujucharmscom-windows:d:\payloads\1560259089\'
17:18:11 Warning: Permanently added '35.171.35.205' (ECDSA) to the list of known hosts.
18:05:26 lost connection
18:05:26 + cleanup
18:05:26 + scp -l 40960 -T 'cijujucharmscom-windows:d:\payloads\1560259089\go-unitest.out' /var/lib/jenkins/workspace/unit-tests-win2012/go-
```

Why would SCP have hung for that long? The file can't be that big. (I'm guessing lost connection is actually 'test script was terminated after running too long'.) But something weirder is happening if scp is running for almost 1hr.

**Comment by jameinel** [comment]
$$merge$$

**Comment by achilleasa** [comment]
> Windows lost connection after ~50 minutes of trying to copy the source code
> 
> ```
> 17:18:11 Copying juju-source-1560258746.tar.xz to d:\payloads\1560259089
> 17:18:11 + scp -l 40960 juju-source-1560258746.tar.xz 'cijujucharmscom-windows:d:\payloads\1560259089\'
> 17:18:11 Warning: Permanently added '35.171.35.205' (ECDSA) to the list of known hosts.
> 18:05:26 lost connection
> 18:05:26 + cleanup
> 18:05:26 + scp -l 40960 -T 'cijujucharmscom-windows:d:\payloads\1560259089\go-unitest.out' /var/lib/jenkins/workspace/unit-tests-win2012/go-
> ```
> 
> Why would SCP have hung for that long? The file can't be that big. (I'm guessing lost connection is actually 'test script was terminated after running too long'.) But something weirder is happening if scp is running for almost 1hr.

We have been seeing this quite a lot last week. This seems to be randomly happening and is not fixed by rebooting either grumpig or the windows box. If you ssh into grumpig it looks like you can scp files to the windows box with no issue. @SimonRichardson has an interesting working theory for this and has merged https://github.com/CanonicalLtd/juju-qa-jenkins/pull/221 as a potential fix.

**Comment by jameinel** [comment]
$$merge$$

**Pull request merged**
