### PR TITLE
Update utils for SSH newline bugfix

### PR DESCRIPTION
**Pull request by Aflynn50**
The utils/ssh package allows for adding keys with a new line in the comment to the model config. The problem is, when they are retrieved, they are split by newline. This means invalid ssh keys get into the model config and cannot be removed since the ssh key passed for removal also gets validated and the comment (which is stored as an ssh key in the model config) is invalid.

Update utils to bring in [the fix](https://github.com/juju/utils/pull/336) that stops newline ssh keys from being added.

Allow invalid ssh keys to be deleted by writing out the key in full. (After a discussion with @jameinel it was decided this is an appropriate measure to allow removal of ssh keys added by the bug) 
## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing
- [x] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages

### Unit tests:
```
go test ./juju/apiserver/facades/client/keymanager/...
```
#### For adding invalid keys
Bootstrap and add invalid key
```
juju boostrap lxd
juju add-model default
juju  add-ssh-key "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAB36uxrTtfdEhfgN5d2P6dt2C3m64t3pBvkn54MFUrw line1
 key-label-after-newline"
```
Observe error

#### For deleting invalid keys

[juju db](https://discourse.charmhub.io/t/login-into-mongodb/309)
```
db.settings.find({"settings.name":"default"}).pretty()
# Copy authorizied keys string
db.settings.updateOne({ "settings.name": "default" }, { $set: { "settings.authorized-keys": "<copied autorised keys string>\ninvalid-key"}})
```
Exit mongo repl
```
juju ssh-keys
# Observe invalid key
juju remove-ssh-key invalid-key
juju ssh-keys
# Observe that is gone
```

## Links

**Launchpad bug:** https://bugs.launchpad.net/juju/+bug/2057686

**Jira card:** JUJU-5469

### CODE REVIEW

**Review by hmlanigan — CHANGES_REQUESTED** [review]
I bootstrapped 3.3.3 and added the bad key from the QA steps. I then upgraded the controller and model to the new code. However I fail to remove the ssh key:
```
$ juju upgrade-model
best version:
    3.3.4.1
started upgrade to 3.3.4.1
$ juju remove-ssh-key "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAB36uxrTtfdEhfgN5d2P6dt2C3m64t3pBvkn54MFUrw line1
 key-label-after-newline"
cannot remove key id "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAB36uxrTtfdEhfgN5d2P6dt2C3m64t3pBvkn54MFUrw line1\n key-label-after-newline": key not found: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAB36uxrTtfdEhfgN5d2P6dt2C3m64t3pBvkn54MFUrw line1
 key-label-after-newline
```

**Comment by hmlanigan** [comment]
```
$ juju ssh-keys
Keys used in model: admin/five
72:03:b2:d9:36:28:1f:24:1c:3f:2e:7c:f9:ed:ce:6c (heather.lanigan@canonical.com)
39:16:b1:bc:a1:e3:ec:9d:36:4d:06:73:37:91:9b:66
cf:25:2f:c0:ba:c5:30:63:89:e1:ca:d5:2d:1b:e3:91 (line1)
Invalid key: key-label-after-newline
```
`juju remove-ssh-key "key-label-after-newline"` does work. 
but
```$ juju remove-ssh-key "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAB36uxrTtfdEhfgN5d2P6dt2C3m64t3pBvkn54MFUrw line1"
cannot remove key id "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAB36uxrTtfdEhfgN5d2P6dt2C3m64t3pBvkn54MFUrw line1": key not found: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAB36uxrTtfdEhfgN5d2P6dt2C3m64t3pBvkn54MFUrw line1```

**Comment by Aflynn50** [comment]
> ```
> $ juju ssh-keys
> Keys used in model: admin/five
> 72:03:b2:d9:36:28:1f:24:1c:3f:2e:7c:f9:ed:ce:6c (heather.lanigan@canonical.com)
> 39:16:b1:bc:a1:e3:ec:9d:36:4d:06:73:37:91:9b:66
> cf:25:2f:c0:ba:c5:30:63:89:e1:ca:d5:2d:1b:e3:91 (line1)
> Invalid key: key-label-after-newline
> ```
> 
> `juju remove-ssh-key "key-label-after-newline"` does work. but
> 
> ```
> $ juju remove-ssh-key "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAB36uxrTtfdEhfgN5d2P6dt2C3m64t3pBvkn54MFUrw line1"
> cannot remove key id "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAB36uxrTtfdEhfgN5d2P6dt2C3m64t3pBvkn54MFUrw line1": key not found: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAB36uxrTtfdEhfgN5d2P6dt2C3m64t3pBvkn54MFUrw line1
> ```

Ah so that first one you would have to remove by just quoting the fingerprint or comment, since juju recognizes it as a valid ssh key.

This is how I implemented it so as not to change current behavior at all, but I could change it to also allow deleting valid keys by quoting them verbatim.

**Review by hmlanigan — APPROVED** [review]
Okay - I didn't understand that I couldn't do 
` juju remove-ssh-key "cf:25:2f:c0:ba:c5:30:63:89:e1:ca:d5:2d:1b:e3:91 (line1)"`

but had to do `juju remove-ssh-key line1` instead.

**Pull request merged**
