### PR TITLE
Relocate gateway module from network to core/network

### PR DESCRIPTION
**Pull request by manadart**
## Description of change

Progresses the phasing out of `network` in favour of `core/network` by relocating the gateway module.

## QA steps

Mechanical only; unit tests pass

### CODE REVIEW

**Comment by manadart** [comment]
[Relocate gateway to core/network](https://trello.com/c/HuQlzSPm/2755-relocate-gateway-to-core-network)

**Comment by manadart** [comment]
$$merge$$

**Comment by hpidcock** [comment]
$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Pull request merged**
