### PR TITLE
Juju 1061 add machine private key

### PR DESCRIPTION
**Pull request by juanmanuel-tirado**
During the manual provision Juju only considers the keys in folder `~/.ssh` and `~/.local/share/juju` to connect/configure the new machine. As required in the bug mentioned below, it would be good to extend the `add-machine` command to use a different private key to establish an ssh session with the new machine. Additionally, this PR extends the list of authorized keys to be set in the new machine by mentioning a public key stored in a file.

## Checklist
NA

## QA steps
For QA bootstrap a new controller on lxd, launch a new lxd machine, config the authorized ssh keys for the machine and try to add this new machine. This QA requires some manual checking...

```bash
# new controller
juju bootstrap lxd deleteme

# new machine
lxc launch ubuntu new-machine

# copy and paste the IP for the machine
lxc list new-machine

+-------------+---------+--------------------+------+-----------+-----------+
|    NAME     |  STATE  |        IPV4        | IPV6 |   TYPE    | SNAPSHOTS |
+-------------+---------+--------------------+------+-----------+-----------+
| new-machine | RUNNING | 10.73.25.18 (eth0) |      | CONTAINER | 0         |
+-------------+---------+--------------------+------+-----------+-----------+

# or if you feel jq-ish ;)
# lxc list new-machine --columns 4 -f json | jq '.[] | select(.name=="new-machine") | .state.network.eth0.addresses[0].address'

# create your pair of keys
mkdir -p /tmp/testkey
ssh-keygen -f /tmp/testkey/testkey

# add the public key to the list of authorized entries into the new machine
publickey=$(cat testkey.pub)
lxc file push testkey.pub new-machine/home/ubuntu/.ssh/authorized_keys

# check we can ssh with no password
ssh -i testkey ubuntu@10.73.25.18

# Test we cannot access using the standard method
juju add-machine ssh:ubuntu@10.73.25.18 --debug

# Test we can access with the private key
juju add-machine ssh:ubuntu@10.73.25.18 --private-key /tmp/testkey/testkey --public-key /tmp/testkey/testkey.pub --debug

# The new machine should be there!
juju list-machines

```

## Documentation changes

This usecase must be mentioned in the docs.

## Bug reference

[https://bugs.launchpad.net/juju/+bug/1971962](https://bugs.launchpad.net/juju/+bug/1971962)

### CODE REVIEW

**Comment by juanmanuel-tirado** [comment]
!!build!!

**Comment by juanmanuel-tirado** [comment]
!!build!!

**Review by cderici — APPROVED** [review]
I was able to reproduce the QA steps, and don't see any gotchas :+1:

**Comment by erik78se** [comment]
Hurray!

**Pull request merged**
