### PR TITLE
[JUJU-1415] Re-introduce xenial network test and re-write network-test charm

### PR DESCRIPTION
**Pull request by jack-w-shaw**
Re-write network-test charm and deploy source locally. This makes the tests more clear
and makes patching easier

Also re-introduce xenial

## Checklist

 - ~[ ] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change~
 - [x] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - ~[ ] Added or updated [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) related to packages changed~
 - [x] Comments answer the question of why design decisions were made

## QA steps

```sh
BOOTSTRAP_PROVIDER=localhost BOOTSTRAP_CLOUD=localhost ./main.sh network
BOOTSTRAP_PROVIDER=aws BOOTSTRAP_CLOUD=aws ./main.sh network
```

### CODE REVIEW

**Comment by tlm** [comment]
We are dropping support for xenial and also need to start testing Jammy as 2.9 is a long term release. Can we remove the old charm as well out of acceptance tests if this is our new one?

**Comment by jack-w-shaw** [comment]
I believe we still need to support Xenial on 2.9? But we can drop xenial and bionic on 3.0 when it comes to forward merging from what I understand.

I'm also pretty sure the old charm in accpetancetests is still in use for the platforms which haven't yet been migrated to the new style tests (oci, maas, etc.)

**Review by anvial — APPROVED** [review]
Test on AWS passes well.

There are problems with xenial deploy on LXD, but looks like it's not connected with the current PR

**Pull request merged**
