### PR TITLE
[JUJU-2745] Refactor keymanager

### PR DESCRIPTION
**Pull request by jack-w-shaw**
Refactor keymanager facade

Rewrite our unit test suite to use mocks instead of JujuConnSuite. This reduced execution time from approx 60s to 0.02s

Whilst we're here also fix some bugs, specifically
- Adding duplicate keys at the same time
- Adding/importing system keys

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- [x] Go unit tests, with comments saying what you're testing

## QA steps

```sh
go test github.com/juju/juju/apiserver/facades/client/keymanager

export KEY="ssh-rsa AA..."
juju add-ssh-key "$KEY" "$KEY" -> fail
juju add-ssh-key "$KEY juju-system-key" -> fail
```

### CODE REVIEW

**Review by nvinuesa — COMMENTED** [review]
LGTM, but it's better to wait for a more experienced member for approval

**Comment by juanmanuel-tirado** [comment]
Removing the connsuite is always good news!!

**Review by manadart — APPROVED** [review]
Needs one small change.

**Pull request merged**
