### PR TITLE
[JUJU-1083] Fix upgrade tests on 2.9

### PR DESCRIPTION
**Pull request by barrettj12**
After discussion with @wallyworld, we decided that it doesn't make sense for the Upgrade tests to run on latest/stable and latest/beta. We will now change these tests so that we try to upgrade from 2.8/stable (for 2.9).

Once this merges through to develop, I will change it there so that we try to upgrade from 2.9/stable.

### CODE REVIEW

**Comment by barrettj12** [comment]
After discussion with @wallyworld, we decided that it doesn't make sense for the Upgrade tests to run on latest/stable and latest/beta. I've now changed these tests so that:
- If the source code is v3.0+, we try to upgrade from latest/stable
- If the source code is v2.9, we try to upgrade from 2.8/stable.

**Comment by barrettj12** [comment]
Hmm, so Juju 2.8 doesn't have `wait-for`, which is causing some problems. Currently the tests install an old Juju, bootstrap and deploy an app, `wait-for` to check that the app is good, then try upgrading to the new version. Will have to rethink what we're doing here.

**Comment by manadart** [comment]
@barrettj12 We're unlikely to do another 2.8 point release, but I'd consider just back-porting the plugin. Could be as simple as dropping in the contents of _cmd/plugins/juju-wait-for_ from 2.9.

**Comment by barrettj12** [comment]
@wallyworld looks like the `--build-agent` flag is necessary for Upgrade (localhost) tests. With Juju 2.9.30-beta installed
```
juju upgrade-controller
```
will only upgrade the controller to 2.9.29, whereas
```
juju upgrade-controller --build-agent
```
upgrades it to 2.9.30.1. Unless you know a better way to force the upgrade to 2.9.30?

**Comment by barrettj12** [comment]
Apparently Juju 2.8 doesn't like this:
```
juju bootstrap microk8s c --config caas-image-repo='{"repository": "${DOCKER_REGISTRY}/test-repo", "serveraddress": "https://${DOCKER_REGISTRY}/"}'
```
It gives me an error
```
ERROR constructing controller config: caas-image-repo: expected string, got map[interface {}]interface {}(map[interface {}]interface {}{"repository":"10.152.183.69:5000/test-repo", "serveraddress":"https://10.152.183.69:5000/"})
```
How did we do this sort of thing in Juju 2.8?

**Comment by jack-w-shaw** [comment]
I ran into this issue when originally writing these tests. the `caas-image-repo` syntax is annoyingly fiddly, and actually changed subtly between 2.9.25 and 2.9.26 (mid way through development) 
https://github.com/juju/juju/pull/13772

You'll probably need to branch (until 3.0) here. 

However, it looks like it changed again some time between then and 2.8, since the string you're using in `90f` is what I used before 2.9.26. I'll investigate while you're asleep and see if I can find anything

**Comment by jack-w-shaw** [comment]
Here's your problem:
https://github.com/juju/juju/blob/0445a6e0b3b64d8b1931b2a27dcc1d17e6c03ce6/controller/config.go#L1000
Followed by:
https://github.com/juju/juju/blob/0445a6e0b3b64d8b1931b2a27dcc1d17e6c03ce6/core/resources/resources.go#L30-L36

It looks to me that the json format for `caas-image-repo` isn't supported in this version of juju. I can't remember exactly why I used the json version, but there's a chance it may be unnecessary in 2.8. Worth investigating

**Comment by barrettj12** [comment]
Yeah, looks like this new `validateCAASImageRepo` function was added in 2.9 to deal with the extra arguments:
https://github.com/juju/juju/blob/5f280267415dd16eb76b600f12368a723f3273af/controller/config.go#L1195-L1197

vs 2.8:
https://github.com/juju/juju/blob/7ebc09cacc4d2ad7146ef12155b66765cb14dbcb/controller/config.go#L999-L1001

I'll try just feeding it the `repository` value and ignore the `serveraddress` - see if it works.

**Comment by barrettj12** [comment]
Now I'm getting this error:
```
$ sudo microk8s refresh-certs
Please use the '--cert' flag to select the certificate you need refreshed.

Available certificate options:
'server.crt': refreshes the server certificate
'front-proxy-client.crt': refreshes the front proxy client certificate
'ca.crt': refreshes the root CA and all certificates created from it.
            Warning: refreshing the root CA requires nodes to leave and re-join the cluster
```
Which one(s) do we want to refresh?

**Comment by barrettj12** [comment]
Ah, this looks like a [change in microk8s 1.24](https://github.com/canonical/microk8s/pull/3029) which lets you refresh other certs. I'm guessing it's `ca.crt` that needs to be refreshed.

**Comment by barrettj12** [comment]
Whoops, didn't mean to delete this branch. I've redone this PR at #14052.

**Pull request closed without merging**
