### PR TITLE
Remove -core in comments, the windows registry key, tests

### PR DESCRIPTION
**Pull request by mitechie**
(Review request: http://reviews.vapour.ws/r/5607/)

### CODE REVIEW

**Comment by howbazaar** [comment]
Why is this targeting the develop branch and not master?

**Comment by mitechie** [comment]
This was created to help nick test out the new developer workflow that should have triggered a subset of the test suite once the PR was created and this would be landed against a staging branch once those 'representative tests' were successful.

**Comment by nskaggs** [comment]
$$build$$

**Comment by nskaggs** [comment]
$$build$$

**Comment by nskaggs** [comment]
$$build$$

**Comment by nskaggs** [comment]
$$build$$

**Comment by nskaggs** [comment]
$$build$$

**Comment by nskaggs** [comment]
$$build$$

**Comment by nskaggs** [comment]
$$build$$

**Comment by nskaggs** [comment]
$$build$$

**Pull request closed without merging**
