### PR TITLE
Update bundlechanges to bring in machine sorting.

### PR DESCRIPTION
**Pull request by howbazaar**
When there were many machines defined in a bundle, they would be processed alphabetically, so machine 10 was before machine 2. The new bundlechanges library fixes this.

As part of this fix, update all call sites for the SortStringsNaturally to use the new naturalsort repo.

## QA steps

Deploy a bundle, even --dry-run, that specifies more than 10 machines.

## Bug reference

https://bugs.launchpad.net/juju/+bug/1762309

### CODE REVIEW

**Comment by howbazaar** [comment]
@jameinel yeah, all the changes for the machine ordering is actually in the bundlechanges library, so the version bump there brings in the change.

**Comment by howbazaar** [comment]
!!build!!

**Comment by howbazaar** [comment]
!!build!!

**Comment by Veebers** [comment]
!!build!!

**Comment by howbazaar** [comment]
$$merge$$

**Pull request merged**
