### PR TITLE
Merge 3.2 into 3.3

### PR DESCRIPTION
**Pull request by barrettj12**
Merges the following patches:
- #16311
- #16310
- #16308
- #16306
- #16266
- #16292
- #16291
- #16286
- #16242
- #16284
- #16281
- #16273
- #16249

### Conflicts
- .github/workflows/microk8s-tests.yml
- .github/workflows/smoke.yml
- .github/workflows/upgrade.yml

### CODE REVIEW

**Comment by barrettj12** [comment]
Conflicts were just around versioning of `balchua/microk8s-actions`.

**Review by jack-w-shaw — APPROVED** [review]

**Review by nvinuesa — APPROVED** [review]
LGTM, thanks m8!

**Pull request merged**
