### PR TITLE
Merge 2.9 into develop

### PR DESCRIPTION
**Pull request by manadart**
Merge from 2.9 to bring forward:
- #13103 from manadart/2.9-lxd-spec-assignment
- #13105 from ycliuhw/fix/lp-1929904
- #13106 from SimonRichardson/update-http-dep
- #13100 from tlm/model-operator-29-upgrade
- #13102 from manadart/2.9-lxd-with-proxy
- #13099 from SimonRichardson/updating-packaging-dep
- #13096 from ycliuhw/lp-1927656
- #13101 from hpidcock/aws-encrypted-ebs
- #13073 from tlm/LP1930798-juju-2.9-k8s-upgrade-2
- #13078 from hmlanigan/sidecar-charm-via-bundle
- #13098 from achilleasa/2.9-logsink-error-if-persisting-logs-to-db-fails
- #13091 from wallyworld/use-aws-sdk-v2
- #13095 from jujubot/increment-to-2.9.7

Conflicts:
- caas/kubernetes/provider/export_test.go
- cmd/juju/application/deployer/bundlehandler.go
- cmd/juju/application/deployer/deployer.go
- core/bundle/changes/handlers.go
- core/charm/computedseries.go
- go.mod
- go.sum
- scripts/win-installer/setup.iss
- snap/snapcraft.yaml
- version/version.go

### CODE REVIEW

**Comment by manadart** [comment]
[Merge 2.9 into develop](https://trello.com/c/JHq2rxCc/3749-merge-29-into-develop)

**Comment by achilleasa** [comment]
@manadart there is some weird issue with the mocks which trips up the linter (and probably some of the tests).

**Comment by hpidcock** [comment]
!!build!!

**Comment by hpidcock** [comment]
!!build!!

**Comment by hpidcock** [comment]
$$merge$$

**Review by hpidcock — APPROVED** [review]

**Comment by hpidcock** [comment]
$$merge$$

**Pull request merged**
