### PR TITLE
fix(makefile): fix makefile link

### PR DESCRIPTION
**Pull request by jack-w-shaw**
Fix Makefile link to point to link version package variables correctly.

We recently moved the github.com/juju/juju/version package to github.com/juju/juju/core/version.

However, our Makefile overrides some variables in this package ("build" in particular) using the -X flag.

However, when we moved the version package the Makefile was not updated, leading to our build system failing to inject build metadata (such as build number).

This then leads to failures in our CI, as the build number was left behind.

Fix this by:
- Pointing the Makefile to the correct package.
- Improving docstrings for the variables we overwrite.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
- ~[ ] Go unit tests, with comments saying what you're testing~
- ~[ ] [Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- ~[ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

```
$ JUJU_BUILD_NUMBER=666 make install
$ jujud --version
4.0-beta4.666-ubuntu-amd64
```

### CODE REVIEW

**Review by Aflynn50 — APPROVED** [review]
LGTM, good job finding this, looks like a fiend of a thing to debug.

**Comment by jack-w-shaw** [comment]
> LGTM, good job finding this, looks like a fiend of a thing to debug.

Don't get me started!

**Review by SimonRichardson — APPROVED** [review]

**Pull request merged**
