### PR TITLE
cert: use unique serial number for server certificates

### PR DESCRIPTION
**Pull request by rogpeppe**
Browsers complain if you don't.

(Review request: http://reviews.vapour.ws/r/5538/)

### CODE REVIEW

**Comment by rogpeppe** [comment]
:shipit:

**Comment by rogpeppe** [comment]
$$merge$$

**Comment by rogpeppe** [comment]
$$merge$$

**Comment by bz2** [comment]
The inital run failed due to a mistake in the job when looking for the tarball, which has now been fixed:
```[Errno 2] No such file or directory: 'ci/juju-core_2.0-beta17.tar.gz'```

The latest one failed on feature tests not being able to connect to the api:
```[LOG] 0:00.351 ERROR juju.worker.dependency "api-caller" manifold worker returned unexpected error: cannot open api: unable to connect to API: websocket.Dial wss://localhost:48632/model/deadbeef-0bad-400d-8000-4b1d0d06f00d/api: dial tcp 127.0.0.1:48632: getsockopt: connection refused```

**Comment by rogpeppe** [comment]
$$merge$$

**Comment by rogpeppe** [comment]
$$merge$$

**Comment by rogpeppe** [comment]
$$merge$$

**Pull request merged**
