### PR TITLE
change controller model name from admin to controller

### PR DESCRIPTION
**Pull request by natefinch**
review here: http://reviews.vapour.ws/r/4854/

### CODE REVIEW

**Comment by natefinch** [comment]
$$merge$$

**Comment by cherylj** [comment]
Please don't land this just yet.  We're still getting feedback on this requested change.

**Comment by natefinch** [comment]
I've fixed the tests so this is now ready to land when/if it is appropriate to do so.

**Comment by natefinch** [comment]
$$merge$$

**Comment by sinzui** [comment]
$$merge$$ __JFDI__

**Comment by sinzui** [comment]
$$merge$$ __JFDI__

**Comment by sinzui** [comment]
$$merge$$ __JFDI__

**Comment by sinzui** [comment]
$$merge$$ __JFDI__

**Pull request merged**
