### PR TITLE
Lxd master merge

### PR DESCRIPTION
**Pull request by tych0**
(Review request: http://reviews.vapour.ws/r/3756/)

### CODE REVIEW

**Comment by ericsnowcurrently** [comment]
$$merge$$

**Comment by cherylj** [comment]
$$fixes-1542336$$

**Comment by tych0** [comment]
Ok, I believe I've fixed that error as part of this branch, so perhaps it might work this time? :)

**Comment by cherylj** [comment]
$$fixes-1542336$$

**Comment by cherylj** [comment]
$$fixes-1542336$$

**Comment by tych0** [comment]
$$merge$$

**Comment by cherylj** [comment]
$$merge$$

**Comment by tych0** [comment]
$$merge$$

**Comment by tych0** [comment]
$$merge$$

**Comment by tych0** [comment]
At some point I should probably install a go1.2 compiler...

**Comment by tych0** [comment]
$$merge$$

**Comment by tych0** [comment]
$$merge$$

**Pull request merged**
