### PR TITLE
Feature/add pod asddresses2bind addresses

### PR DESCRIPTION
**Pull request by ycliuhw**
## Description of change

Make `network-get` returns container addresses in binding addresses for `CaaS`;

## QA steps

- deploy mediawiki and mariadb, then relate them;

```bash
$ juju deploy cs:~juju/mariadb-k8s-0 
$ juju deploy cs:~juju/mediawiki-k8s-3
$ juju relate mediawiki-k8s:db mariadb-k8s:server
```

- run `network-get`;

```bash
$ juju run --unit mediawiki-k8s/0 --timeout=30s "network-get db" --operator=false
bind-addresses:
- macaddress: ""
  interfacename: ""
  addresses:
  - hostname: ""
    address: 10.1.26.40
    cidr: ""
egress-subnets:
- 10.152.183.7/32
ingress-addresses:
- 10.152.183.7

$ juju run --unit mariadb-k8s/0 --timeout=30s "network-get server" --operator=false
bind-addresses:
- macaddress: ""
  interfacename: ""
  addresses:
  - hostname: ""
    address: 10.1.26.39
    cidr: ""
egress-subnets:
- 10.152.183.236/32
ingress-addresses:
- 10.152.183.236
```

## Documentation changes

No

## Bug reference

No

### CODE REVIEW

**Comment by ycliuhw** [comment]
[add pod address to bind-addresses in network-get](https://trello.com/c/AaaC0mev/931-add-pod-address-to-bind-addresses-in-network-get)

**Comment by ycliuhw** [comment]
$$merge$$

**Comment by manadart** [comment]
Can we rebase before merging if we have commits like "Fix tests"?

**Comment by ycliuhw** [comment]
$$merge$$

**Pull request merged**
