### PR TITLE
New merge from 2.9 from 15196 timeline

### PR DESCRIPTION
**Pull request by hmlanigan**
Merge from 2.9 into 3.0

- Merge pull request #15196 from hmlanigan/fix-refresh-resource-no-charm-rev-change
- Merge pull request #15201 from toabctl/develop-aws-new-regions
- Merge pull request #15220 from manadart/2.9-revert-omit-match

2 new commits were necessary to update tests due to differences in 2.9 and 3.0 branches
- a32ea36
- f83b1cf9

Merge conflicts were all in files related to #15196

### CODE REVIEW

**Comment by cderici** [comment]
Just stopped by to say great work on the description! I'm gonna save it for my future merge PRs :)

**Review by manadart — COMMENTED** [review]
Looks good as far as my part goes.

**Review by manadart — APPROVED** [review]

**Pull request merged**
