### PR TITLE
Merge 2.9

### PR DESCRIPTION
**Pull request by wallyworld**
Merge 2.9

#12735 Silences proxy log messages from klog
#12742 Fixes broken kubeconfig loading tests
#12754 Record hostname when machine agent starts
#12755 Fix broken centos proxy tests part2
#12756 Update github.com/juju/charm/v7 to include v2 block
#12757 Disable tests/run.sh for released bundle test and dump logs
#12739 Scaffold upgrade series logic 
#12753 Disregard refcount for blobstore cleanup
#12758 No panic missing bundle app body
#12759  Fix errant relative timeout for migration minion reports
#12760  Include hostname in multi-watcher machine deltas
#12750 Refactor series support to that juju itself can set its own supported series

```
# Conflicts:
#       apiserver/allfacades.go
#       apiserver/facades/agent/machine/machiner.go
#       apiserver/facades/client/client/client.go
#       apiserver/facades/schema.json
#       caas/kubernetes/provider/cloud.go
#       cloudconfig/userdatacfg_unix.go
#       cmd/juju/commands/bootstrap_test.go
#       state/migration_internal_test.go
```

## QA steps

See PRs

### CODE REVIEW

**Comment by wallyworld** [comment]
!!build!!

**Review by tlm — APPROVED** [review]
lgtm

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
