### PR TITLE
Structured metadata: delete metadata for image

### PR DESCRIPTION
**Pull request by anastasiamac**
This proposal adds ability to delete stored image metadata.

### CODE REVIEW

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by cherylj** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
$$merge$$

**Pull request merged**
