### PR TITLE
Colorize meter status.

### PR DESCRIPTION
**Pull request by cmars**
QA steps: Deploy a charm that has meter status. In a terminal that supports colors, observe meter status in color.

### CODE REVIEW

**Comment by cmars** [comment]
!!build!! again?

**Comment by cmars** [comment]
!!build!!

**Comment by nskaggs** [comment]
@cmars , seems the bot is failing to get code from git. Looking at it.

**Comment by nskaggs** [comment]
!!fixed-the-bot!!

**Comment by cmars** [comment]
!!build!!

**Comment by cmars** [comment]
!!build!! now with test fixed

**Comment by cmars** [comment]
!!build!! again, mgo flakiness

**Comment by cmars** [comment]
!!build!!

**Comment by cmars** [comment]
!!build!!

**Comment by cmars** [comment]
!!build!!

**Comment by cmars** [comment]
$$merge$$

**Pull request merged**
