### PR TITLE
Support for multi-doc bundles and overlays

### PR DESCRIPTION
**Pull request by achilleasa**
## Description of change

This PR consists of two parts:

On the server-side, the bundle export code has been updated to use the new
"split-overlay" functionality introduced by the charms.v6 package. When
exporting a bundle that contains offers (currently, the only overlay-specific
block that we support), the export code will generate a multi-document yaml
output where the first document contains the base overlay a.k.a. what you
would normally get if you didn't enable the `bundle-cmr` flag and an **overlay**
part with the overlay-specific bits.

The choice of the multi-doc format was made for the following reasons:

- It allows us to run `juju export-bundle > bundle.yaml` without the need to
  manually split the output into a base and overlay part (which must be emitted
  somewhere else than the stdout).
- We don't need to modify the python client.
- It is transparent to older juju versions as parsing stops after the first
  document. Which is fine as you would need a newer juju cli anyway to leverage
  the new support for offers/saas blocks in bundles.

On the client-side, the deploy (and bundle diff) code has been updated to use
the multi-doc aware BundleDataSource mechanism and overlay application logic
that is now provided by charms.v6.

To this end, the local bundle deployer has been changed to work with the charms
package _directly_ instead of going through the `charmrepo.v3` package. However,
the remote bundle fetching code that does use `charmrepo.v3` poses a problem. I
have tried to create a `charmrepo.v5` as a converge point for v3, v4 and my
changes but importing that package back into juju breaks the codebase in several
places due to the inconsistent use of macaroon-bakery.v2/v2-unstable (which have
also diverged in incompatible ways). As a result, and observing that we don't
(at this point at least) care about supporting multi-doc remotely-fetched
bundles, we decided to re-use the existing implementation (GetBundle) but wrap the
result in a BundleDataSource-compatible container.

Since the overlay merging logic is now handled by the charms package in a
forward-compatible way (changes to the bundle-related structs are automatically
picked up by the overlay merging code via reflection instead of lots of if
statements), it is a great opportunity to get rid of quite a bit of code from
the juju client ;-)

Finally, this PR fixes a bug in the deploy code! Turns out that the pre/post
deploy checks were executed before the final bundle was composed. So we could
actually be skipping checks for applications added via overlays. This has also
been addressed as part of this PR.

## QA steps

```console
$ export JUJU_DEV_FEATURE_FLAGS=bundle-cmr
$ juju bootstrap lxd test --no-gui

# Deploy a bundle with an offer
$ juju add-user bar
$ juju deploy ./testcharms/charm-repo/bundle/apache2-with-offers
Resolving charm: cs:apache2-26
Executing changes:
- upload charm cs:apache2-26 for series bionic
- deploy application apache2 on bionic using cs:apache2-26
- create offer my-offer using apache2:apache-website,website-cache
- grant user admin admin access to offer my-offer
- grant user bar consume access to offer my-offer
- create offer my-other-offer using apache2:apache-website
Deploy of bundle completed.

# Verify that export-bundle generates a multi-doc bundle
$ juju export-bundle
series: bionic
applications:
  apache2:
    charm: cs:apache2-26
--- # overlay.yaml
applications:
  apache2:
    offers:
      my-offer:
        endpoints:
        - apache-website
        - website-cache
        acl:
          admin: admin
          bar: consume
      my-other-offer:
        endpoints:
        - apache-website
        acl:
          admin: admin

# Deploy another bundle with overlays
$ juju add-model test1

$ less testcharms/charm-repo/bundle/multi-doc-overlays/bundle.yaml
series: trusty
applications:
  apache2:
    charm: cs:apache2-26
    num_units: 1
--- # overlay 1
applications:
  apache2:
    offers:
      my-offer:
        endpoints:
        - apache-website
        acl:
          admin: admin
--- # overlay 2
applications:
  wordpress:
    charm: cs:trusty/wordpress-5
    num_units: 1

$ echo -n 'my-include' > example.txt
$ cat > overlay.yaml << EOT
applications:
  wordpress:
    annotations:
      raw: include-file://example.txt
      enc: include-base64://example.txt
EOT

$ juju deploy ./testcharms/charm-repo/bundle/multi-doc-overlays --overlay overlay.yaml
Resolving charm: cs:apache2-26
Resolving charm: cs:trusty/wordpress-5
Executing changes:
- upload charm cs:apache2-26 for series trusty
- deploy application apache2 on trusty using cs:apache2-26
- upload charm cs:trusty/wordpress-5 for series trusty
- deploy application wordpress on trusty using cs:trusty/wordpress-5
- set annotations for wordpress
- create offer my-offer using apache2:apache-website
- grant user admin admin access to offer my-offer
- add unit apache2/0 to new machine 0
- add unit wordpress/0 to new machine 1
Deploy of bundle completed.

$ juju export-bundle
series: trusty
applications:
  apache2:
    charm: cs:apache2-26
    num_units: 1
    to:
    - "0"
  wordpress:
    charm: cs:trusty/wordpress-5
    num_units: 1
    to:
    - "1"
    annotations:
      enc: bXktaW5jbHVkZQ==
      raw: my-include
machines:
  "0": {}
  "1": {}
--- # overlay.yaml
applications:
  apache2:
    offers:
      my-offer:
        endpoints:
        - apache-website
        acl:
          admin: admin
```

You will also need to run some `juju diff-bundle` tests too.

## Documentation changes

We probably need to update our docs to explain the concept around multi-doc bundles.

### CODE REVIEW

**Comment by achilleasa** [comment]
!!build!! 

(failed due to loginSuite.TestOtherModel)

**Comment by achilleasa** [comment]
!!build!!

(more unrelated test failures)

**Comment by achilleasa** [comment]
!!build!!

(even more unrelated test failues; tests pass locally)

**Comment by achilleasa** [comment]
!!build!!

**Comment by achilleasa** [comment]
!!build!!

(intermittent fail for statusUnitTestSuite.TestMigrationInProgress)

**Comment by achilleasa** [comment]
!!build!!

(windows box tests timed out)

**Comment by achilleasa** [comment]
!!build!!

(intermittent fail for statusUnitTestSuite.TestMigrationInProgress)

**Comment by achilleasa** [comment]
I just identified a bug in the overlay-split logic. I will fix that and update the PR.

**Comment by achilleasa** [comment]
!!build!!

The identified bug has been squashed so the PR is ready for review.

**Comment by achilleasa** [comment]
!!build!!

(unrelated test fail: loginSuite.TestOtherModel)

**Comment by achilleasa** [comment]
!!build!!

(unrelated test fail: loginSuite.TestOtherModel)

**Comment by achilleasa** [comment]
!!build!!

(DNS failures)

**Comment by achilleasa** [comment]
!!build!!

(lookup for archive.ubuntu.com fails)

**Comment by mitechie** [comment]
QA works ok. Did a few different deploy/offering setups with and without acls and seems to be working as intended. Thanks!

**Comment by achilleasa** [comment]
@mitechie Can you also please try to deploy something (non offer-related) and use an overlay to override bits that correspond to some common use cases for overlays? I ran a few tests on my own but it would be great to double-check just in case I missed something. Keep in mind though that with these changes you should be able to change more things with an overlay (including the trust flag)

**Comment by achilleasa** [comment]
$$merge$$

**Comment by achilleasa** [comment]
$$merge$$

(transient fail: statusUnitTestSuite.TestMigrationInProgress)

**Pull request merged**
