### PR TITLE
Simple Non-Functional Tweaks

### PR DESCRIPTION
**Pull request by manadart**
## Description of change

- Fixes a comment typo in `add-cloud` help text.
- Removes interface and test implementation no longer used following https://github.com/juju/juju/pull/10886

## QA steps

No functional changes; tests pass

## Documentation changes

None.

## Bug reference

https://bugs.launchpad.net/juju/+bug/1851801

### CODE REVIEW

**Comment by manadart** [comment]
[Comment Fix and Small Cleanup](https://trello.com/c/r9DzAzeO/1982-comment-fix-and-small-cleanup)

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Comment by mitechie** [comment]
hmmm $$merge$$

**Pull request merged**
