### PR TITLE
Merge up 3.6 to main

### PR DESCRIPTION
**Pull request by Aflynn50**
Merge up from 3.6 to main.

The conflicts were:
- `cmd/modelcmd/package_test.go` - This was resolved by by putting -typed in front of the mockgen commands
-  `state/machine_test.go` - The test `TestLifeJobManageModelWithControllerCharm` was removed
-  `state/cleanup.go` - This was resolved by passing the object store to the build command by piping it through.

The merge up includes:
- #17780 from Aflynn50
  - #17776 from Aflynn50
    - #17772 from Aflynn50
    - #17700 from Aflynn50
    - #17756 from nvinuesa

### CODE REVIEW

**Comment by nvinuesa** [comment]
There might be a glitch here, I don't see any changes to `state/machine_test.go`. We should have this change 
```
// Force remove of controller machines will first clean up units and
	// after that it will pass the machine life to Dying.
	c.Assert(m2.Life(), gc.Equals, state.
```
on `TestLifeJobManageModelWithControllerCharm()`.

Is it because the test was removed on main?

**Comment by Aflynn50** [comment]
> There might be a glitch here, I don't see any changes to `state/machine_test.go`. We should have this change
> 
> ```
> // Force remove of controller machines will first clean up units and
> 	// after that it will pass the machine life to Dying.
> 	c.Assert(m2.Life(), gc.Equals, state.
> ```
> 
> on `TestLifeJobManageModelWithControllerCharm()`.
> 
> Is it because the test was removed on main?

Yea, it was, I've just realised I didn't put that in the conflicts. Should that test be reinstated and modified?

**Review by nvinuesa — APPROVED** [review]
Thanks

**Pull request merged**
