### PR TITLE
Meter status manifold and worker.

### PR DESCRIPTION
**Pull request by tasdomas**
The meter status manifold will be used to control workers that run the meter-status-changed hook.

This branch currently depends on http://reviews.vapour.ws/r/2756/ 

(Review request: http://reviews.vapour.ws/r/2796/)

### CODE REVIEW

**Comment by tasdomas** [comment]
$$merge$$

**Comment by cmars** [comment]
$$merge$$

**Comment by cmars** [comment]
$$sigh$$

**Comment by cmars** [comment]
$$tarball-this$$

**Comment by cmars** [comment]
@tasdomas, this is an actual compile error -- usually the "tarball failed" message indicates a temporary issue with the buildbot, but this looks like an actual package import problem. From latest Jenkins log: 
```
worker/meterstatus/manifold.go:16:2: cannot find package "gopkg.in/juju/charm.v5/hooks" in any of:
	/usr/lib/go/src/pkg/gopkg.in/juju/charm.v5/hooks (from $GOROOT)
	/var/lib/jenkins/workspace/github-merge-juju/tmp.n5baTdsxew/RELEASE/src/gopkg.in/juju/charm.v5/hooks (from $GOPATH)
```

**Comment by cmars** [comment]
@tasdomas looks like master is using `gopkg.in/juju/charm.v6-unstable` now. You probably had charm.v5 in your development environment $GOPATH (I did).

**Comment by tasdomas** [comment]
$$try again$$

**Comment by tasdomas** [comment]
$$merge$$

**Comment by tasdomas** [comment]
$$merge$$

**Pull request merged**
