### PR TITLE
Fixed duplicated relations in tabular status.

### PR DESCRIPTION
**Pull request by perrito666**
Fix https://bugs.launchpad.net/juju-core/+bug/1559329

(Review request: http://reviews.vapour.ws/r/4235/)

### CODE REVIEW

**Comment by perrito666** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by perrito666** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$__JFDI__$$

**Pull request merged**
