### PR TITLE
Emit errors for invalid credential names

### PR DESCRIPTION
**Pull request by achilleasa**
## Description of change

Juju currently allows users to add credentials whose name contains spaces even though they are not valid according to the `juju/names.v2` package. This causes a `juju bootstrap` to panic when passing an invalid credential name.

This PR attempts to fix this issue by:
- ensuring that we always validate cloud credentials in all code paths that construct cloud credential tags (names.NewCloudCredentialTag expects a valid ID or it panics)
- preventing users from entering invalid cloud credential names (interactively or via file) when running `juju add-credential`.

NOTE: even if a user with an older juju version _did_ manage to create an invalid credential they could not bootstrap the controller anyway due to the panic. Consequently, these changes are mostly UX improvements and should not break anything for existing users.

## QA steps
```console
# NOTE: I have added a new (lxd) cloud for my tests; it seems like the changes block
# deploy bootstrap attempts on localhost with a "credential not found" message. YMMV
#
# Add a credential whose name contains spaces (e.g "with spaces") using 
# an OLDER juju version (or checkout 80fc578 from this branch)
$ juju add-credential lxd-with-cache
Enter credential name: with spaces

Auth Types
  certificate
  interactive

Select auth type [interactive]: interactive

Enter trust-password:

Loaded client cert/key from "/home/.../.local/share/juju/lxd"
Credential "with spaces" added locally for cloud "lxd-with-cache".

# Boostrap using the invalid credential; we should get an ERROR instead of a panic
$ juju bootstrap lxd-with-cache lxd-test --credential "cred with spaces"
...
ERROR cloud credential ID "lxd-with-cache/admin/cred with spaces" not valid
ERROR failed to bootstrap model: subprocess encountered error code 1

# Now switch to the HEAD of this branch and attempt to add a similar credential either via interactive mode or via a yaml file. You should get an error in both cases.
```

## Bug reference
https://bugs.launchpad.net/juju/+bug/1702538
https://bugs.launchpad.net/juju/+bug/1816826

### CODE REVIEW

**Comment by achilleasa** [comment]
!!build!!

**Comment by achilleasa** [comment]
!!build!!

**Comment by mitechie** [comment]
The error is nice but it doesn't fit the normal format of other errors. I've attached a screenshot to demonstrate. Any chance we can bring them in line with each other?

Thanks!

invalid-creds

**Comment by mitechie** [comment]
QA using a credential file ok (minus the bug filed here: https://bugs.launchpad.net/juju/+bug/1817122)

    % juju add-credential aws -f creds.yaml
    ERROR "personal with spaces" is not a valid credential name

**Comment by achilleasa** [comment]
@mitechie Updated the interactive prompt. It looks like this now: 
image

**Comment by achilleasa** [comment]
$$merge$$

**Pull request merged**
