### PR TITLE
Merge in the 2.7.4 release changes.

### PR DESCRIPTION
**Pull request by howbazaar**
This PR brings in the changes from the 2.7.4 release into the previously mainline 2.7 branch.

Particularly this branch merges in the 2.7 changes rather than rebasing in order to keep the original commit hashes.

### CODE REVIEW

**Comment by howbazaar** [comment]
$$merge$$

**Comment by howbazaar** [comment]
$$merge$$ intermittent caas test failure

**Comment by howbazaar** [comment]
```
----------------------------------------------------------------------
FAIL: caasoperator_test.go:243: WorkerSuite.TestWorkerDownloadsCharm

[LOG] 0:00.001 INFO juju.charm charm is not versioned, charm path "/home/ubuntu/go/src/github.com/juju/juju/testcharms/charm-repo/kubernetes/gitlab"
[LOG] 0:00.002 DEBUG juju.worker.caasoperator starting caas operator juju-run listener on &{unix /tmp/check-2872823298019106274/30/test.listener <nil>}
[LOG] 0:00.002 DEBUG juju.worker.uniter juju-run listener running
[LOG] 0:00.002 INFO juju.worker.uniter.charm downloading cs:gitlab-1 from API server
[LOG] 0:00.272 DEBUG juju.worker.uniter.charm preparing to deploy charm "cs:gitlab-1"
[LOG] 0:01.960 DEBUG juju.worker.uniter.charm deploying charm "cs:gitlab-1"
[LOG] 0:09.887 DEBUG juju.worker.uniter.charm finishing deploy of charm "cs:gitlab-1"
caasoperator_test.go:258:
    c.Fatal("timed out sending application change")
... Error: timed out sending application change

[LOG] 0:10.004 DEBUG juju.worker.uniter juju-run listener stopping
[LOG] 0:10.004 DEBUG juju.worker.uniter juju-run listener stopped
[LOG] 0:15.494 INFO juju.worker.caasoperator operator "gitlab" started

----------------------------------------------------------------------
FAIL: caasoperator_test.go:382: WorkerSuite.TestWorkerSetsStatus

[LOG] 0:00.632 INFO juju.charm charm is not versioned, charm path "/home/ubuntu/go/src/github.com/juju/juju/testcharms/charm-repo/kubernetes/gitlab"
[LOG] 0:00.634 DEBUG juju.worker.caasoperator starting caas operator juju-run listener on &{unix /tmp/check-2872823298019106274/34/test.listener <nil>}
[LOG] 0:00.634 DEBUG juju.worker.uniter juju-run listener running
[LOG] 0:00.634 INFO juju.worker.uniter.charm downloading cs:gitlab-1 from API server
[LOG] 0:03.940 DEBUG juju.worker.uniter.charm preparing to deploy charm "cs:gitlab-1"
[LOG] 0:09.672 DEBUG juju.worker.uniter.charm deploying charm "cs:gitlab-1"
caasoperator_test.go:392:
    s.client.CheckCallNames(c, "Charm", "SetStatus", "SetVersion", "WatchUnits", "WatchContainerStart", "SetStatus", "Watch")
/home/ubuntu/go/src/github.com/juju/juju/vendor/github.com/juju/testing/stub.go:248:
    return c.Check(funcNames, jc.DeepEquals, expected)
... obtained []string = []string{"Charm", "SetStatus"}
... expected []string = []string{"Charm", "SetStatus", "SetVersion", "WatchUnits", "WatchContainerStart", "SetStatus", "Watch"}
... mismatch at top level: length mismatch, 2 vs 7; obtained []string{"Charm", "SetStatus"}; expected []string{"Charm", "SetStatus", "SetVersion", "WatchUnits", "WatchContainerStart", "SetStatus", "Watch"}

[LOG] 0:10.623 DEBUG juju.worker.uniter juju-run listener stopping
[LOG] 0:10.623 DEBUG juju.worker.uniter juju-run listener stopped
[LOG] 0:17.781 DEBUG juju.worker.uniter.charm finishing deploy of charm "cs:gitlab-1"
caasoperator_test.go:394:
    ...
/home/ubuntu/go/src/github.com/juju/juju/vendor/gopkg.in/juju/worker.v1/workertest/check.go:58:
    c.Errorf("timed out waiting for worker to stop")
... Error: timed out waiting for worker to stop

caasoperator_test.go:394:
    ...
/home/ubuntu/go/src/github.com/juju/juju/vendor/gopkg.in/juju/worker.v1/workertest/check.go:83:
    c.Check(err, jc.ErrorIsNil)
... value *errors.Err = &errors.unformatter{message:"workertest: worker not stopping", cause:error(nil), previous:error(nil), file:"github.com/juju/juju/vendor/gopkg.in/juju/worker.v1/workertest/check.go", line:59} ()
... error stack:
	github.com/juju/juju/vendor/gopkg.in/juju/worker.v1/workertest/check.go:59: workertest: worker not stopping
```

**Comment by jameinel** [comment]
$$merge$$

**Comment by jameinel** [comment]
Last failure was a Raftflag intermittent failure:
```
flag_test.go:131:
    // When the raft node toggles between leader/follower,
    // then the worker will exit with ErrRefresh.
    err := workertest.CheckKilled(c, s.worker)
/home/ubuntu/go/src/github.com/juju/juju/vendor/gopkg.in/juju/worker.v1/workertest/check.go:58:
    c.Errorf("timed out waiting for worker to stop")
... Error: timed out waiting for worker to stop
```

**Pull request merged**
