### PR TITLE
Fixes spelling error in bootstrap cred finalizer.

### PR DESCRIPTION
**Pull request by tlm**
Spelling mistake in the boostrap credential finalizer interface was causing instance profile bootstrapping to not work properly.

## Checklist

 - [x] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change
 - [x] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - [x] Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed
 - [x] Comments answer the question of why design decisions were made

## QA steps

Not required.

## Documentation changes

N/A

## Bug reference

N/A

### CODE REVIEW

**Review by wallyworld — APPROVED** [review]

**Comment by tlm** [comment]
$$merge$$

**Comment by tlm** [comment]
Work for JUJU-120

**Comment by tlm** [comment]
$$merge$$

**Review by hpidcock — APPROVED** [review]

**Comment by tlm** [comment]
$$merge$$

**Pull request merged**
