### PR TITLE
Pass the 'ldflags' that avoid debugger symbols.

### PR DESCRIPTION
**Pull request by jameinel**
## Description of change

This makes the jujud binary much smaller, and doesn't impact (panic) stack traces. I don't know yet whether this would affect juju-introspection results.

## QA steps

```
$ make install
$ juju bootstrap lxd
```

## Documentation changes

None.

## Bug reference

[lp:1764339](https://bugs.launchpad.net/juju/+bug/1764339)

### CODE REVIEW

**Comment by jameinel** [comment]
For now I'm not changing "--build-agent", on the premise that if you're calling "--build-agent" you might want debugging symbols in the target. We can certainly discuss changing that internally.

**Comment by jameinel** [comment]
[1764339 Strip agent binaries](https://trello.com/c/OXyf656L/164-1764339-strip-agent-binaries)

**Comment by jameinel** [comment]
!!build!!

**Comment by jameinel** [comment]
!!build!!

**Comment by jameinel** [comment]
!!build!!

**Comment by jameinel** [comment]
Last build failure was known intermittent test: https://bugs.launchpad.net/bugs/1764594

**Comment by nskaggs** [comment]
$$merge$$

**Pull request merged**
