### PR TITLE
[JUJU-552] Use go 1.17 and regenerate mocks

### PR DESCRIPTION
**Pull request by wallyworld**
Update the go version to be 1.17 and regenerate the mocks.

The only files of interest are `go.mod` plus the github actions. All the others are generated.
There were also some minor tweaks due to CA cert error message changes and a change in httpserver behaviour.

## QA steps

juju bootstrap

### CODE REVIEW

**Review by benhoyt — APPROVED** [review]
Conditionally approving -- let's just fix the test issues (mostly TLS/certificate things by the looks).

**Comment by wallyworld** [comment]
> Conditionally approving -- let's just fix the test issues (mostly TLS/certificate things by the looks).

Yup, https://github.com/juju/juju/pull/13690/commits/cae25931d48a090b8c471d4776e7f639c9fd5b81 fixes the issues. Only a few tweaks were needed.

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
