### PR TITLE
lxd provider: use right bind address for LXD

### PR DESCRIPTION
**Pull request by tych0**
Prevents:

ERROR cannot find network interface "lxcbr0": route ip+net: no such network interface
ERROR invalid config: route ip+net: no such network interface

when the user doesn't have a lxcbr0 (i.e. doesn't have lxc1 installed).

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

(Review request: http://reviews.vapour.ws/r/4446/)

### CODE REVIEW

**Comment by reedobrien** [comment]
LGTM. Two tests fail in the container/lxd suite, but those pass in #5000 so will pass once that is merged.

**Comment by jameinel** [comment]
$$merge$$

**Comment by tych0** [comment]
yay go 1.2! I just added a stub like we have elsewhere.

**Comment by tych0** [comment]
$$merge$$

**Pull request merged**
