### PR TITLE
Added default value for no_proxy

### PR DESCRIPTION
**Pull request by perrito666**
## Description of change

no_proxy configuration now has localhost values as a
default so users can eliminate them if they so require.
localhost hostname was added.

## QA steps

Bootstrap a cotnroller, and deploy a machine.
In the machine env NO_PROXY and no_proxy should contain the following values:
 * localhost
 * 127.0.0.1
 * ::1
 * the ip of the machine

Also, running `juju model-config` should yield
`no-proxy                    default  127.0.0.1,localhost,::1
`
## Bug reference

https://bugs.launchpad.net/juju/+bug/1637370

### CODE REVIEW

**Comment by vmorris** [comment]
Thanks!

**Comment by reedobrien** [comment]
QA checks out.

**Comment by reedobrien** [comment]
QA checks out, tests pass.

**Comment by anastasiamac** [comment]
I think you might want to re-target it against develop :D

**Comment by reedobrien** [comment]
I think @anastasiamac is right. I didn't even notice since there wasn't a massive diff:|

**Comment by perrito666** [comment]
Good catch @anastasiamac that was a missclick

**Comment by perrito666** [comment]
$$merge$$

**Comment by perrito666** [comment]
$$merge$$

**Pull request merged**
