### PR TITLE
Improve missing argument error by listing valid 'upgrade-series' commands.

### PR DESCRIPTION
**Pull request by ExternalReality**

### CODE REVIEW

**Comment by ExternalReality** [comment]
[Improve error message when missing the prepare/complete arguments to upgrade-series](https://trello.com/c/bhcnEaaY/473-improve-error-message-when-missing-the-prepare-complete-arguments-to-upgrade-series)

**Comment by ExternalReality** [comment]
[Improve error message when missing the prepare/complete arguments to upgrade-series](https://trello.com/c/bhcnEaaY/473-improve-error-message-when-missing-the-prepare-complete-arguments-to-upgrade-series)

**Comment by ExternalReality** [comment]
[Improve error message when missing the prepare/complete arguments to upgrade-series](https://trello.com/c/bhcnEaaY/473-improve-error-message-when-missing-the-prepare-complete-arguments-to-upgrade-series)

**Comment by mitechie** [comment]
LGTM QA ok 

thanks for the update

**Comment by ExternalReality** [comment]
$$MERGE$$

**Pull request merged**
