### PR TITLE
WIP: Image metadata worker.

### PR DESCRIPTION
**Pull request by anastasiamac**
Periodically updates image metadata stored in state based on published images.

(Review request: http://reviews.vapour.ws/r/2526/)

### CODE REVIEW

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
