### PR TITLE
[JUJU-1781] Merge develop onto decoupled apiclient

### PR DESCRIPTION
**Pull request by cderici**
Get the latest from develop onto the decoupled-apiclient to have the CI tests in https://github.com/juju/juju/pull/15135 pass.

Solves some conflicts in the test files (using charmstore, series->base, etc).

### CODE REVIEW

**Comment by cderici** [comment]
@SimonRichardson I'm getting a bunch of dqlite errors here including the copyright job in static-analysis (which does pass for me locally), any ideas?

**Review by hmlanigan — APPROVED** [review]
LGTM

**Pull request merged**
