### PR TITLE
Moved extendDisk method to use vm.disk.change

### PR DESCRIPTION
**Pull request by phvalguima**
## Please provide the following details to expedite Pull Request review:

----

## Description of change

This change is a partial fix for LP #1847245.
It searches for the root disk of the VM and runs vm.Reconfigure method from govmomi rather than methods.ExtendVirtualDisk_Task to extend it.

This is a partial fix because GRUB fails to find root device after extend-disk process.

## QA steps

Deploy node with root-disk constraint set to a different value than VM template.
Run govc to recover VMs' disk size and compare with requested value.

## Documentation changes

None

## Bug reference

https://bugs.launchpad.net/juju/+bug/1847245

### CODE REVIEW

**Comment by phvalguima** [comment]
WIP: improve logs and resolve VMs not finding root disk

**Comment by timClicks** [comment]
@phvalguima Thanks for helping us with this issue! It's really great to receive contributions from other teams.

**Comment by mitechie** [comment]
!!build!!

**Comment by babbageclunk** [comment]
This is doing essentially the same thing as using ExtendVirtualDisk but in a fiddlier way (since the Reconfigure method is more flexible). Now that the extend code can wait for the task rather than polling the disk size I don't think we need this change, hopefully you agree @phvalguima? (The grub error turned out to be a red herring - the VMs were being created with only 4Mb ram rather than the intended 4Gb, which was preventing them from booting.)

**Pull request closed without merging**
