### PR TITLE
Merge 2.9 into develop

### PR DESCRIPTION
**Pull request by manadart**
Merge from 2.9 to bring forward:
- #14131 from ycliuhw/fix/lp-1977488
- #14143 from hmlanigan/unused-interface
- #14127 from hmlanigan/remove-rackspace-cloud-registion
- #14136 from wallyworld/fix-race-failure
- #14134 from jameinel/2.9-build-info-metrics
- #14135 from hpidcock/extend-k8s-grace
- #14137 from benhoyt/delete-unused-init-controller
- #14138 from wallyworld/fix-storage-export
- #14120 from jack-w-shaw/JUJU-1177_rewrite_unit_tests
- #14126 from jack-w-shaw/JUJU-1190_drop_acceptance_test_block
- #14128 from wallyworld/azure-deploy-race
- #14125 from jnsgruk/2.9
- #14122 from manadart/2.9-upgrade-test-race
- #14119 from wallyworld/inst-cfg-controller
- #14124 from tlm/lp-1976434-aks-storage
- #14113 from manadart/2.9-multiwatcher-race
- #14115 from tlm/lp-1976620-lxd-filename-expanding
- #14129 from tlm/juju-3.0-k8s-storage-refactor
- #14164 [JUJU-1328] Set snapcraft version to 6.x
- #14155 Validate the input better to avoid confusion
- #14163 [JUJU-1326] Allow series upgrade state to be set by the agent to the same status
- #14142 [JUJU-1273] Check and branch on cloud type when remove-cloud
- #14171 Generate modern ssh host keys for jammy support
- #14167 Add debug log for when the unit series-upgrade status is unchanged
- #14170 [JUJU-1288] Update azure provider to use new Azure SDK
- #14110 [JUJU-1231] Disallow do-release-upgrade for ubuntu controller;

Conflicts:
- apiserver/facades/client/application/package_test.go
- caas/kubernetes/provider/application/application.go
- caas/kubernetes/provider/bootstrap.go
- caas/kubernetes/provider/cloud.go
- caas/kubernetes/provider/cloud_test.go
- caas/kubernetes/provider/metadata.go
- cloudconfig/podcfg/image.go
- cloudconfig/podcfg/podcfg.go
- provider/azure/environ.go
- provider/maas/environ.go
- provider/rackspace/environ.go

[JUJU-1328]: https://warthogs.atlassian.net/browse/JUJU-1328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[JUJU-1326]: https://warthogs.atlassian.net/browse/JUJU-1326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by barrettj12** [comment]
I had several CI patches yesterday that should fix the failing GitHub Actions:
- #14150
- #14156
- #14158

Is it possible to add these to the merge?

**Review by ycliuhw — APPROVED** [review]
My changes are correctly picked.
Thanks for making this merge.

**Comment by manadart** [comment]
@wallyworld I can't work out what's wrong with azure failing the environ tests here. Any help?

**Comment by wallyworld** [comment]
> @wallyworld I can't work out what's wrong with azure failing the environ tests here. Any help?

I merged the latest 2.9 commits and fixed the Azure provider issues and resolved conflicts. So now this PR will merge the latest 2.9 as at the time of writing.
Please take a look at https://github.com/juju/juju/pull/14154/commits/40418f79c301672aae311481b0023f423d408f87 which is the commit I pushed to make sure everything looks ok.

**Comment by wallyworld** [comment]
@manadart 2 remaining test failures:
- TestEnableHAAddsControllerCharm
- TestEnableHAAddsControllerCharmToPromoted

due to this check
```
		if args.machineID != "" && !strings.HasPrefix(*a.doc.CharmURL, "juju-") {
			return "", nil, errors.NotSupportedf("non-empty machineID")
		}
```

Juju 3 has a controller charm which is added by default to the controller model. Need to look into what's happening here.

**Comment by hpidcock** [comment]
> @manadart 2 remaining test failures:
> 
> * TestEnableHAAddsControllerCharm
> * TestEnableHAAddsControllerCharmToPromoted
> 
> due to this check
> 
> ```
> 		if args.machineID != "" && !strings.HasPrefix(*a.doc.CharmURL, "juju-") {
> 			return "", nil, errors.NotSupportedf("non-empty machineID")
> 		}
> ```
> 
> Juju 3 has a controller charm which is added by default to the controller model. Need to look into what's happening here.

This should be fixed by my commit

**Pull request merged**
