### PR TITLE
2.8 into develop

### PR DESCRIPTION
**Pull request by jameinel**
### Checklist

 - [ ] Checked if it requires a [pylibjuju](https://github.com/juju/python-libjuju) change?
 - [ ] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR?
 - [ ] Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed?
 - [ ] Do comments answer the question of why design decisions were made?

----

## Description of change

This is merging 2.8 into develop, including:
 * Merge pull request #11985 from mhilton/008-multiwatcher-application-offers
 * Merge pull request #11980 from jameinel/2.8-log-stderr-warning-1893993
 * Merge pull request #11977 from tlm/bug-juju-app-label
 * Merge pull request #11978 from wallyworld/juju-machine-operations
 * Merge pull request #11975 from benhoyt/bug-1888409

## QA steps

See individual PRs.

## Documentation changes

See individual PRs.

## Bug reference
 * https://bugs.launchpad.net/juju/+bug/1893993
 * https://bugs.launchpad.net/juju/+bug/1892285
 * https://bugs.launchpad.net/juju/+bug/1888409

### CODE REVIEW

**Comment by jameinel** [comment]
Since I resolved some changes between 2.8 and develop around CAAS and labels, just make sure I chose the route that we *want* to be going.

**Review by tlm — APPROVED** [review]
lgtm

**Comment by jameinel** [comment]
!!build!!

**Comment by jameinel** [comment]
$$merge$$

**Pull request merged**
