### PR TITLE
Run make dep by default

### PR DESCRIPTION
**Pull request by wallyworld**
## Description of change

make target dep is now run by default

## QA steps

make dep

### CODE REVIEW

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
@wallyworld,

I don't think you merge will work as even check-merge fails with:
	(1) failed to clean up git repository at /workspace/pkg/dep/sources/https---github.com-juju-gojsonpointer - dirty? corrupted? status output: 
warning: unable to access '/home/ubuntu/.config/git/ignore': Permission denied

	(2) failed to list versions for ssh://git@github.com/juju/gojsonpointer: Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
: exit status 128
	(3) failed to list versions for git://github.com/juju/gojsonpointer: fatal: unable to connect to github.com:
github.com[0: 192.30.253.113]: errno=Connection timed out
github.com[1: 192.30.253.112]: errno=Connection timed out

: exit status 128
	(4) failed to list versions for http://github.com/juju/gojsonpointer: fatal: unable to access 'http://github.com/juju/gojsonpointer/': Could not resolve host: github.com
: exit status 128 

as per http://ci.jujucharms.com/job/github-check-merge-juju/2872/console

**Comment by wallyworld** [comment]
$$merge$$

**Comment by Veebers** [comment]
!!build!!

**Comment by Veebers** [comment]
!!build!!

**Comment by Veebers** [comment]
!!build!!

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
#veebers-test##

**Comment by Veebers** [comment]
#veebers-test##

**Comment by Veebers** [comment]
#veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by Veebers** [comment]
##veebers-test##

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
