### PR TITLE
Fixed incorrect test setup and assert in TestIsMeteredTrueRequired.

### PR DESCRIPTION
**Pull request by cmars**

### CODE REVIEW

**Comment by cmars** [comment]
!!build!!

**Comment by cmars** [comment]
@nskaggs PTAL, this fixes the unit test issue we saw this morning.

Can we get the buildbot to test this?

**Comment by nskaggs** [comment]
!!build!!

**Comment by nskaggs** [comment]
cmars add to whitelist

**Comment by cmars** [comment]
!!;_;!!

**Comment by cmars** [comment]
!!build!!

**Comment by cmars** [comment]
!!build!!

**Comment by cmars** [comment]
$$merge$$

**Comment by cmars** [comment]
$$merge$$

**Pull request merged**
