### PR TITLE
[JUJU-1301] Rewrote to bash-based nw-add-credentials-aws

### PR DESCRIPTION
**Pull request by anvial**
This PR adds a credential suite with the add-remove credential test.

## Checklist

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made

## QA steps

```sh
cd tests/
./main.sh -v -p aws credential
```

### CODE REVIEW

**Comment by jack-w-shaw** [comment]
I would suggest you set JUJU_DATA to your temp test dir to ensure adding/removing credentials is done in a clean environment

**Review by manadart — APPROVED** [review]
Works well now.

**Pull request merged**
