### PR TITLE
Fixes bug #1386425: juju authorised-keys import only imports last key

### PR DESCRIPTION
**Pull request by johnsca**
Fixes [bug #1386425](https://bugs.launchpad.net/juju-core/+bug/1386425) to import all keys for a given key id.

NB: New to go, so constructive criticism for making things more idiomatic, efficient, etc. appreciated.

(Review request: http://reviews.vapour.ws/r/694/)

### CODE REVIEW

**Comment by wwitzel3** [comment]
$$merge$$

**Comment by wwitzel3** [comment]
$$merge$$

**Comment by wwitzel3** [comment]
$$merge$$

**Comment by wwitzel3** [comment]
$$merge$$

**Comment by wwitzel3** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Pull request merged**
