### PR TITLE
Remove the fanconfigurer worker

### PR DESCRIPTION
**Pull request by nvinuesa**
In the context of dropping the fan networking support on 4.0+, this patch removes the fanconfigurer worker, which applied the fan configuration using `fanctl`, which is part of the ubuntu-fan package and no longer installed after the patch https://github.com/juju/juju/pull/17410 lands.

All api endpoints regarding fanconfigurer have also been removed.

## Checklist

- [X] Code style: imports ordered, good names, simple structure, etc
- [X] Comments saying why design decisions were made
- [X] Go unit tests, with comments saying what you're testing
- [ ] ~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~
- [ ] ~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

Bootstrap on aws and deploy:

```
juju bootstrap aws c
juju add-model m
juju deploy ubuntu --to lxd
```
and make sure there are no errors on the logs.

Also, 3.6->4.0 migration should not be broken:
```
juju_36 bootstrap aws 36
juju_36 add-model m
juju_36 deploy ubuntu --to lxd
# install this patch at this point
juju bootstrap aws c40
juju switch c36:admin/m
juju migrate c40
```
Check the logs and the status after migration, the model should have been correctly migrated.
## Links

**Jira card:** JUJU-6048

### CODE REVIEW

**Review by SimonRichardson — COMMENTED** [review]
Model migrate on ec2 from 3.6 to 4.0 and see if there are any problems.

**Comment by nvinuesa** [comment]
@SimonRichardson 
> Model migrate on ec2 from 3.6 to 4.0 and see if there are any problems.

I have an upcoming PR which removes `FanInfo` from `SubnetInfo` and this will be part of that QA. Is it OK with you if we QA this then? There should be no impact from the fanconfigurer worker.

**Comment by SimonRichardson** [comment]
You removed some API facades, hence the ask.

**Comment by manadart** [comment]
What I suspect will happen is that machiner worker will not come up, because the fan configurer worker (on old, migrating agents) will throw an error for the missing facade and it will not satisfy dependents.

Propose the same patch without the facade removal. Then we can merge it straight away and think about a strategy following.

**Comment by nvinuesa** [comment]
@manadart @SimonRichardson I have brought back the facade to avoid new errors on migration.

**Review by manadart — COMMENTED** [review]
You need to sort out your QA steps. Those listed do not verify the patch.
If I attempt to deploy into a container-in-machine, I see logs with:
```
machine-0: 10:29:33 INFO juju.worker.lxdprovisioner found machine pending provisioning id:0/lxd/0, details:0/lxd/0
machine-0: 10:29:33 WARNING juju.worker.lxdprovisioner machine 0/lxd/0 failed to start: unable to setup network: host machine "0" has no available FAN devices in space(s) "alpha"
machine-0: 10:29:33 WARNING juju.worker.lxdprovisioner failed to start machine 0/lxd/0 (unable to setup network: host machine "0" has no available FAN devices in space(s) "alpha"), retrying in 10s (10 more attempts)
machine-0: 10:29:43 WARNING juju.worker.lxdprovisioner machine 0/lxd/0 failed to start: unable to setup network: host machine "0" has no available FAN devices in space(s) "alpha"
machine-0: 10:29:43 WARNING juju.worker.lxdprovisioner failed to start machine 0/lxd/0 (unable to setup network: host machine "0" has no available FAN devices in space(s) "alpha"), retrying in 10s (9 more attempts)
machine-0: 10:29:53 WARNING juju.worker.lxdprovisioner machine 0/lxd/0 failed to start: unable to setup network: host machine "0" has no available FAN devices in space(s) "alpha"
machine-0: 10:29:53 WARNING juju.worker.lxdprovisioner failed to start machine 0/lxd/0 (unable to setup network: host machine "0" has no available FAN devices in space(s) "alpha"), retrying in 10s (8 more attempts)
machine-0: 10:30:03 WARNING juju.worker.lxdprovisioner machine 0/lxd/0 failed to start: unable to setup network: host machine "0" has no available FAN devices in space(s) "alpha"
machine-0: 10:30:03 WARNING juju.worker.lxdprovisioner failed to start machine 0/lxd/0 (unable to setup network: host machine "0" has no available FAN devices in space(s) "alpha"), retrying in 10s (7 more attempts)
machine-0: 10:30:13 WARNING juju.worker.lxdprovisioner machine 0/lxd/0 failed to start: unable to setup network: host machine "0" has no available FAN devices in space(s) "alpha"
machine-0: 10:30:13 WARNING juju.worker.lxdprovisioner failed to start machine 0/lxd/0 (unable to setup network: host machine "0" has no available FAN devices in space(s) "alpha"), retrying in 10s (6 more attempts)
machine-0: 10:30:23 WARNING juju.worker.lxdprovisioner machine 0/lxd/0 failed to start: unable to setup network: host machine "0" has no available FAN devices in space(s) "alpha"
machine-0: 10:30:23 WARNING juju.worker.lxdprovisioner failed to start machine 0/lxd/0 (unable to setup network: host machine "0" has no available FAN devices in space(s) "alpha"), retrying in 10s (5 more attempts)
...
```

**Comment by nvinuesa** [comment]
@manadart Indeed I had forgotten the `--to lxd` in the deploy step of the QA. The error you were seeing is because I hadn't rebased on top of main which included my previous patch (now we can never have lxd as container networking method). I tried the QA steps after rebasing and there are no issues.

**Review by manadart — APPROVED** [review]
Please update the PR description with upgrade steps.
Include in those, migrating a model from 3.6 to 4.0 with this patch.

We will need to work out an approach on 3.6 for models using the Fan. Such models will need to be prevented from migration to 4.0.

**Pull request merged**
