### PR TITLE
Merge 2.9

### PR DESCRIPTION
**Pull request by wallyworld**
Merge 2.9 plus do a fix for action related acceptance tests to cater for new run behaviour.

#12574 [Charmhub] - Allow resolution for bundles.
#12579 Fix typo in action Enqueue() api
#12582 Fix list operation args
#12583 Add offset/limit handling to list-operations api

## QA steps

See PRs

### CODE REVIEW

**Comment by wallyworld** [comment]
[fix actions related acceptance tests on develop](https://trello.com/c/gDvgWMrD/1369-fix-actions-related-acceptance-tests-on-develop)

**Comment by SimonRichardson** [comment]
$$merge$$

We're aware of the macos issue, we're starting to investigate why acquiring a lock takes more than 5 minutes.

**Comment by SimonRichardson** [comment]
$$merge$$

**Review by SimonRichardson — APPROVED** [review]

**Comment by SimonRichardson** [comment]
$$merge$$

Somebody did not have their caffeine today!

**Pull request merged**
