### PR TITLE
[JUJU-1291] Upgrade golint to 1.4.6

### PR DESCRIPTION
**Pull request by juanmanuel-tirado**
Upgrade golint version to 1.4.6

## Checklist

 - [ ] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change
 - [ ] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - [ ] Added or updated [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) related to packages changed
 - [ ] Comments answer the question of why design decisions were made

## QA steps

NA

## Documentation changes

NA

## Bug reference

NA

### CODE REVIEW

**Review by manadart — APPROVED** [review]

**Comment by juanmanuel-tirado** [comment]
/merge

It looks like a testing timeout retry.

**Comment by hpidcock** [comment]
This should have been backported to juju 2.9

**Pull request merged**
