### PR TITLE
Add manual deploy tests for AWS

### PR DESCRIPTION
**Pull request by SimonRichardson**
### Checklist

 - [x] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR?

----

## Description of change

This tests the manual deployment of a HA `percona-cluster` and ensures 
that it has deployed to the correct machine.

This uses the same `manual_deploy` test as LXD so that we can verify that
the high level juju commands are identical between the substrates.

---

Unfortunately the process of bringing up an aws instance with the right
ingress and egress rules are somewhat convoluted but required to show
that manual provisioning is possible.

---

I've tried to ensure that we clean up the VPC as much as possible, but
we may, in the end, require to reuse the VPC that we already have, which
maybe be better off?

## QA steps

You need to ensure that you've correctly setup the AWS CLI and that you
have a **default** region that probably isn't `us-east-1`.

Ensure you have a valid Juju.

```sh
BOOTSTRAP_PROVIDER=aws ./main.sh -v manual
```

Let it run, it takes time.

### CODE REVIEW

**Comment by SimonRichardson** [comment]
https://trello.com/c/b2hF2fKd/2501-manual-aws-deploy-test

**Comment by hmlanigan** [comment]
Looks like we'll need to update jenkins to install petname appropriately.

**Comment by hmlanigan** [comment]
Okay, the last commit fixed the issue where the test didn't run.  However I did have to manually answer yes, see line 8.

https://pastebin.canonical.com/p/KNz2Bs7h6t/

What are the ERRORs at the bottom of the pastebin, though they didn't lead to failure.  Clean up appears to have been good.

**Comment by manadart** [comment]
Yeah, required intervention:
```bash
==> Checking for dependencies
==> TEST BEGIN: test_manual (tmp.MjR)
==> Checking for dependencies
===> [   ] Running: deploy manual awsThe authenticity of host 'ec2-52-49-72-168.eu-west-1.compute.amazonaws.com (52.49.72.168)' can't be established.
ECDSA key fingerprint is SHA256:FZGXQ0zvG+VvYBf9wTmH4rkkFh8UgBiyzOBUs67Zc6I.
Are you sure you want to continue connecting (yes/no)? yes
+ cat /home/joseph/go/src/github.com/juju/juju/tests/tmp.MjR/test_manual.log

==> Checking for dependencies
+ add_clean_func run_cleanup_deploy_manual_aws
```
But instances were correctly cleaned up and multiple runs use the same VPC.

**Comment by SimonRichardson** [comment]
@manadart @hmlanigan I've fixed the issue where it expects you to interact with it now.

**Comment by manadart** [comment]
Tried a couple times with failures. Instances appear to get set up correctly, but bootstrap fails thusly:
```
13:26:27 INFO  juju.environs.manual.sshprovisioner sshprovisioner.go:43 initialising "ec2-3-249-24-210.eu-west-1.compute.amazonaws.com", user "ubuntu"
13:26:27 DEBUG juju.utils.ssh ssh.go:305 using OpenSSH ssh client
13:26:28 DEBUG juju.utils.ssh ssh.go:305 using OpenSSH ssh client
13:26:28 ERROR juju.provider.manual provider.go:37 initializing ubuntu user: subprocess encountered error code 255 (Received disconnect from 3.249.24.210 port 22:2: Too many authentication failures
Disconnected from 3.249.24.210 port 22)
ERROR subprocess encountered error code 255 (Received disconnect from 3.249.24.210 port 22:2: Too many authentication failures
Disconnected from 3.249.24.210 port 22)
13:26:28 DEBUG cmd supercommand.go:519 error stack:
subprocess encountered error code 255 (Received disconnect from 3.249.24.210 port 22:2: Too many authentication failures
Disconnected from 3.249.24.210 port 22)
/build/juju/parts/juju/go/src/github.com/juju/juju/environs/bootstrap/prepare.go:133:
/build/juju/parts/juju/go/src/github.com/juju/juju/cmd/juju/commands/bootstrap.go:735:
```

**Comment by SimonRichardson** [comment]
@macgreagoir what's your ssh/config does it have a wildcard host? If so can you remove and bounce the ssh daemon?

**Comment by hmlanigan** [comment]
QA with latest code works for me.

**Comment by SimonRichardson** [comment]
$$merge$$

**Pull request merged**
