### PR TITLE
Fortress worker

### PR DESCRIPTION
**Pull request by fwereade**
Previously discussed in some detail at http://reviews.vapour.ws/r/2597/ -- now proposed against master.

(Review request: http://reviews.vapour.ws/r/2627/)

### CODE REVIEW

**Comment by fwereade** [comment]
$$merge$$

**Comment by fwereade** [comment]
$$merge$$

**Comment by fwereade** [comment]
$$merge$$

**Comment by sinzui** [comment]
$$merge$$ The previous job was aborted because AWS failed to provide an instance.

**Comment by fwereade** [comment]
$$merge$$

**Comment by fwereade** [comment]
hmm, not sure why the last one wasn't picked up... $$merge$$

**Comment by bz2** [comment]
Build failed: aws was unhappy.

**Comment by bz2** [comment]
$$merge$$

**Comment by fwereade** [comment]
$$merge$$

**Pull request merged**
