### PR TITLE
[JUJU-1558] Validate local bundle

### PR DESCRIPTION
**Pull request by hmlanigan**
Check the response for parsing a local bundle for any UnmarshalErrors. If they exist, print and fail the deploy unless --force is used. Not done for repository bundles, who knows what havoc that might wreak.

Developer friendly structure data is available with `--logging-config "juju.charm=TRACE" --show-log`

## QA steps

Deploy local charms, repository charms and bundles, no changes to be found.

```sh
# Deploy the following bundle without force
name: slurm
description: A suite of codified operations to asssemble, install, deploy, and operate Slurm.
website: https://omnivector-solutions.github.io/osd-documentation/master/
docs: https://omnivector-solutions.github.io/osd-documentation/master/
source: https://github.com/omnivector-solutions/slurm-bundles/
issues: https://github.com/omnivector-solutions/slurm-charms/issues

series: focal

applications:
  slurmctld:
    charm: slurmctld
    num_units: 1
    contstraints: instance-type=c5a.large root-disk=20G

$ juju deploy ./bundle-min.yaml --dry-run
ERROR cannot deploy bundle: unmarshal document 0: yaml: unmarshal errors:
  line 1: field name not found in bundle
  line 3: field website not found in bundle
  line 4: field docs not found in bundle
  line 5: field source not found in bundle
  line 6: field issues not found in bundle
  line 14: field contstraints not found in applications
$ juju deploy ./bundle-min.yaml --dry-run --force
Located charm "slurmctld" in charm-hub, channel stable
Changes to deploy bundle:
- upload charm slurmctld from charm-hub for series focal with architecture=amd64
- deploy application slurmctld from charm-hub on focal
- add unit slurmctld/0 to new machine 0
```

## Bug reference

https://bugs.launchpad.net/juju/+bug/1983386

### CODE REVIEW

**Review by cderici — APPROVED** [review]
Aside from the CI tests this LGTM (not sure what's going on with the ci). QA steps worked as expected too.

**Comment by hmlanigan** [comment]
rebased and updated go.mod/sum with charm v 8.0.2

**Pull request merged**
