### PR TITLE
Don't automatically add env life assertions to txns

### PR DESCRIPTION
**Pull request by mjs**
The multiEnvRunner will no longer automatically add assertions on environment life to transactions as this create a serious performance bottleneck. Instead, the env is asserted to be alive in specific key areas (mainly where a txn may result in provisioning of resources).

Fixes LP #1474195

(Review request: http://reviews.vapour.ws/r/2180/)

### CODE REVIEW

**Comment by wallyworld** [comment]
$$merge$$

**Comment by wallyworld** [comment]
$$merge$$

**Comment by mjs** [comment]
$$merge$$

**Comment by mjs** [comment]
$$merge$$

**Pull request merged**
