### PR TITLE
docs: add badges to README

### PR DESCRIPTION
**Pull request by jnsgruk**
The snapcraft badge will ensure the Juju entry is populated correctly on releases.juju.is.

## Checklist

- [ ] ~~Code style: imports ordered, good names, simple structure, etc~~
- [ ] ~~Comments saying why design decisions were made~~
- [ ] ~~Go unit tests, with comments saying what you're testing~~
- [ ] ~~[Integration tests](https://github.com/juju/juju/tree/main/tests), with comments saying what you're testing~~
- [ ] ~~[doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~~

## QA steps

N/A

### CODE REVIEW

**Review by tmihoc — APPROVED** [review]
Nice, thanks!

**Comment by tlm** [comment]
@jnsgruk do we want to wash this through all of our branches? Currently the default branch we show on GitHub is 3.4. This change will only be visible on 4.0 and up at the moment.

**Comment by jnsgruk** [comment]
> @jnsgruk do we want to wash this through all of our branches? Currently the default branch we show on GitHub is 3.4. This change will only be visible on 4.0 and up at the moment.

Good point, lemme retarget at 3.4

**Pull request closed without merging**
