### PR TITLE
Increment juju to 1.25.10

### PR DESCRIPTION
**Pull request by sinzui**

### CODE REVIEW

**Comment by sinzui** [comment]
$$merge$$

**Comment by howbazaar** [comment]
$$merge$$

**Comment by howbazaar** [comment]
$$try-again$$

**Comment by howbazaar** [comment]
$$merge$$

**Comment by anastasiamac** [comment]
we had to manually stop previous attempt to land as it took more than 2hrs and appeared just spinning. trying again...
$$merge$$

**Comment by howbazaar** [comment]
The bot thinks it has already accepted it.

Deleting last accepted message.

**Comment by howbazaar** [comment]
$$gah$$

**Comment by howbazaar** [comment]
$$pos$$

**Comment by howbazaar** [comment]
$$how-freaking-hard-is-this$$

**Pull request closed without merging**
