### PR TITLE
[JUJU-3326] implement charm config for DeployFromRepository

### PR DESCRIPTION
**Pull request by hmlanigan**
Config for DeployFromRepository should now work as expected. In the client, the key/value pair config is combined with the config provided via file. Trust is an application config, but remains separate rather than special handling.

There should be no change in how config is used from the user point of view. Both key/value pairs and a config yaml file can be provided. Key/value pairs take priory over the config from a file. Values can also be provided via file using the `@` symbol.

I have to work out the application name logic so there are some contortions right now.
## QA steps

Please try various method to provide config - try to break the config logic.

```sh
$ JUJU_DEV_FEATURE_FLAGS=server-side-charm-deploy juju bootstrap localhost test
$ juju add-model five

$ cat > config.yaml << EOT
testme:
  skill: 7
  status: test status message
EOT

$ JUJU_DEV_FEATURE_FLAGS=server-side-charm-deploy juju deploy juju-qa-test testme --config status=override --config ./config.yaml --trust
application.DeployInfo{
    ...
}

$ juju config testme
application: testme
application-config:
  trust:
    ...
    value: true
charm: juju-qa-test
settings:
...
  skill:
    ...
    value: 7
  status:
    ...
    value: override
...
```

### CODE REVIEW

**Review by nvinuesa — APPROVED** [review]
LGTM, for the QA, I see a difference to what you posted (in my case `value: true` for `trust`):
```yaml
❯ juju config testme
application: testme
application-config:
  trust:
    default: false
    description: Does this application have access to trusted credentials
    source: user
    type: bool
    value: true
```

**Comment by hmlanigan** [comment]
unrelated failure `FAIL: stream_test.go:423: streamSuite.TestOneChangeIsBlockedByFile`

/merge

**Comment by hmlanigan** [comment]
same unrelated error was hit

**Pull request merged**
