### PR TITLE
Fix LXD init in Equinix provider

### PR DESCRIPTION
**Pull request by cprivitere**
Right now when juju, using the Equinix Metal provider, tries to start a container, the lxd service never start due to failing to auto init. This was due to the juju-fixups.sh script not fully executing due to needing jq installed on the box and it not being in the image by default. This fixes that as well as enables DHCP from the fan network that juju automatically configures so that containers can DHCP and obtain an IP address. 

Changes:
- Add jq which is needed by juju-fixups.sh
- Add iptables rule for DHCP from fan network.

## Checklist

*If an item is not applicable, use `~strikethrough~`.*

- [x] Code style: imports ordered, good names, simple structure, etc
- [x] Comments saying why design decisions were made
~- [ ] Go unit tests, with comments saying what you're testing~
~- [ ] [Integration tests](https://github.com/juju/juju/tree/develop/tests), with comments saying what you're testing~
~- [ ] [doc.go](https://discourse.charmhub.io/t/readme-in-packages/451) added or updated in changed packages~

## QA steps

*Commands to run to verify that the change works.*

```sh
juju add-credential equinix
#add credential
juju bootstrap equinix/da equinix
juju deploy etcd --to lxd
#validate that the container starts and gets an IP address, etcd in particular will want some additional cert stuff set up, but you can ignore that for this test.
```

### CODE REVIEW

**Comment by cprivitere** [comment]
@manadart Just wanted to ping you here too, we're rebased to the 3.0 branch now.

**Review by manadart — APPROVED** [review]
Looks fine. QA works. Will merge when we've got the [CLA signed](https://github.com/juju/juju/blob/develop/CONTRIBUTING.md#contributor-licence-agreement)

**Comment by juanmanuel-tirado** [comment]
@cprivitere could you please sign the [CLA](https://ubuntu.com/legal/contributors) so we can land this into the next release?

**Comment by cprivitere** [comment]
Sure thing. I figured Equinix had an org level CLA, sorry about that. I've signed as an individual.

**Comment by cprivitere** [comment]
I note it's still failing even though I amended my commit to not use the noreply address. I'm not sure what else i can do.

**Review by hpidcock — APPROVED** [review]

**Pull request merged**
