### PR TITLE
[2.8] fix race in start hook after reboot test

### PR DESCRIPTION
**Pull request by achilleasa**
This PR backports the fixes from #12250 and #12254 to 2.8.

## QA steps

```sh
cd tests
./main.sh -v hooks
```

### CODE REVIEW

**Comment by achilleasa** [comment]
!!build!! (GH failed to compute merge?!?)

**Review by SimonRichardson — APPROVED** [review]
Q&A went well

**Comment by achilleasa** [comment]
!!build!! (transient:  flag_test.go:94: WorkerSuite.TestErrRefresh)

**Comment by achilleasa** [comment]
$$merge$$

**Pull request merged**
