### PR TITLE
Resume tests execution on macos

### PR DESCRIPTION
**Pull request by markelog**
There was four types of issues for running tests on macos.

## Makefile

On macos syntax of the command `mktemp` is a bit different, it doesn't have
the `--tmpdir` argument on macos it just creates a directory `--tmpdir` in
the source path and bunch of other temporary directories. This complecates the
development and confuses the tests.

> makefile: remove deadspace
> makefile: make creation of temp dir cross os

## Plugin Tests

Plugin code checks every path on the `$PATH` list in order to
find addtional plugins. In tests it reduces the amount of paths
by temporary editing the `$PATH` list leaving  only temp dir and `/bin` folder.
Assuming that the bash commands used inside the tests are present on the target
system. Like `touch` for example, but in newer macos systems, some of the
commands are present inside `/usr/bin` path

> tests: carefully edit `$PATH` variable in tests, so it would be cross OS

## CI Configuration

There was minor issues with macos preparation instructions. Like putting
mongo on incorrect path `/user/...` instead of `/usr/...` and assuming that
GitHub runners are doesn't have mongodb installed.

> ci: correct macos preparation instructions

`go test` Parallization Issues

There is several tests that used mongodb concurrently,
at least "cmd/application" and "juju/commands". Presumably operationg on the
same set of data and/or their structure. It makes the tests execution a little
bit slower on macos environment. Have not invisitigated why this doesn't happen
on ubuntu. Perhaps amount of CPUs already limited or because Go differently
works with parallization on Linux machines

> ci: limit amount of available CPUs to one for macos setup

## Checklist

 - [ ] Requires a [pylibjuju](https://github.com/juju/python-libjuju) change
 - [ ] Added [integration tests](https://github.com/juju/juju/tree/develop/tests) for the PR
 - [ ] Added or updated [doc.go](https://discourse.jujucharms.com/t/readme-in-packages/451) related to packages changed
 - [x] Comments answer the question of why design decisions were made

--

### CODE REVIEW

**Review by SimonRichardson — APPROVED** [review]

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
@markelog can we move back to `-v` instead of `-vv`. Juju is massively chatty and it's causing a slow down in the output actions.

**Comment by markelog** [comment]
@SimonRichardson done!

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by SimonRichardson** [comment]
!!build!!

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by manadart** [comment]
We got an intermittent failure on the merge, but before we try again, can you squash these commits? It'll be nicer as one.

**Comment by markelog** [comment]
> We got an intermittent failure on the merge, but before we try again, can you squash these commits? It'll be nicer as one.

Done! Don't have the rights to see the jenkins run though :/, so not sure what is going on there

**Comment by SimonRichardson** [comment]
$$merge$$

**Comment by manadart** [comment]
$$merge$$

**Comment by manadart** [comment]
!!build!!

**Comment by manadart** [comment]
Try this one more time.
$$merge$$

**Comment by manadart** [comment]
While we get to the bottom of the merge bot issues, I've cherry picked the commit on to a new patch:
https://github.com/juju/juju/pull/12572

**Pull request closed without merging**
