### PR TITLE
Use clock.Clock in metricsender.

### PR DESCRIPTION
**Pull request by tasdomas**
Addresses LP:#1558657

### CODE REVIEW

**Comment by cmars** [comment]
LGTM

**Comment by tasdomas** [comment]
$$merge$$

**Comment by cmars** [comment]
Looks like a compile error:
```
+ make check
# github.com/juju/juju/apiserver/metricsender_test
apiserver/metricsender/metricsender_test.go:46: undefined: "github.com/juju/juju/testing".NewClock
apiserver/metricsender/metricsender_test.go:129: not enough arguments in call to metricsender.SendMetrics
apiserver/metricsender/sender_test.go:54: undefined: "github.com/juju/juju/testing".NewClock
# github.com/juju/juju/apiserver/metricsmanager_test
apiserver/metricsmanager/metricsmanager_test.go:42: undefined: "github.com/juju/juju/testing".NewClock
apiserver/metricsmanager/metricsmanager_test.go:67: undefined: "github.com/juju/juju/testing".NewClock
make: *** [check] Error 2
```

**Comment by tasdomas** [comment]
$$merge$$

**Comment by tasdomas** [comment]
$$merge$$

**Pull request merged**
