### PR TITLE
Allow the httpserver dualport to close early.

### PR DESCRIPTION
**Pull request by jameinel**
## Description of change

This is a small cleanup for the http dualPort code. If the http server was shutting down, the old code wouldn't notice until timeout was reached. This didn't actually block anything (as far as I can tell) because the dualListener was opened from a Hub message, which didn't block the other worker from shutting down. So all this really does is cleanup a goroutine a bit earlier.

Still, since I noticed it, I figured it was worth landing. The test doesn't actually fail if you don't exit early, because we can't wait for the openAPIPort to return, because it is triggered from the Hub subscription. Though I think the setup of the test is still relevant (you shouldn't fail if requested to shut down before the timeout occurs.)

## QA steps

New Unit test. You can see how it is triggered if you do 'go test -check.vv' where you can see that it notices right away that shutdown was requested.

## Documentation changes

None.

## Bug reference

None.

### CODE REVIEW

**Comment by jameinel** [comment]
I'm targeting 2.7, but I want to wait to land this until 2.7.0 is final.

**Comment by howbazaar** [comment]
$$merge$$

**Comment by jameinel** [comment]
$$merge$$

**Comment by jameinel** [comment]
$$merge$$

**Pull request merged**
