### PR TITLE
tmp fix: patch microk8s coredns

### PR DESCRIPTION
**Pull request by ycliuhw**
## Description of change

patch coredns config for microk8s CI tests;

## QA steps

None

## Documentation changes

None

## Bug reference

None

### CODE REVIEW

**Comment by ycliuhw** [comment]
!!build!!

**Comment by ycliuhw** [comment]
!!build!!

**Comment by ycliuhw** [comment]
$$merge$$

**Comment by ycliuhw** [comment]
[enable bootstrap to microk8s](https://trello.com/c/EWM90oRh/115-enable-bootstrap-to-microk8s)

**Comment by ycliuhw** [comment]
!!build!!

**Comment by wallyworld** [comment]
!!build!!

**Comment by ycliuhw** [comment]
!!build!!

**Comment by ycliuhw** [comment]
$$merge$$

**Pull request merged**
